- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
Replaces `display: none` with a set of styles used to hide something visually while keeping it accessible to assistive technology.
This was pulled up in the accessibility audit retesting, here's what was said:
> The back to home link has now been combined into a single element. However the ‘Back to home’ text within the <a> is hidden via display:none; and only visible on hover or focus. This means a screen reader user navigating via read mode will not hear a name for the link (the URL is announced as the link’s name).
When the back to home text is hidden, do not use display:none; - instead use the clipping method utilised to hide text for screen reader users.
> fix: Use visually hidden instead of display:none for breadcrumb link name

- site/src/pages/component-health.scss
Unfortunately noticed too late that the icons are sitting above the sticky header when scrolling
Adding a `z-index` helped:
> chore: Fixing icons overlapping sticky header on health page

- .github/workflows/stale.yml
- As brought up in standup today, our issues are closing too fast. It was set to:
1. After 2 months of no activity -> tag as stale
2. Then 14 days with no activity -> close
Now it'll be
1. After 4 months of no activity -> tag as stale
2. Then 1 month of no activity -> close
> fix: bump stale issues tagging and close

- draft-packages/form/KaizenDraft/Form/CheckboxField/styles.scss
- draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.tsx
- draft-packages/form/KaizenDraft/Form/Primitives/Radio/Radio.tsx
- draft-packages/form/KaizenDraft/Form/RadioField/styles.scss
- draft-packages/form/KaizenDraft/Form/RadioGroup/__snapshots__/RadioGroup.spec.tsx.snap
- draft-packages/select/KaizenDraft/Select/Select.tsx
There were a couple of things around on Radios and Checkboxes to work around some issues we ran into on Capture where they weren't working properly for touch devices. This recently broke again because the divs were changed to spans and these rules no longer applied.
After a bit of investigation - the checkboxes and radios weren't working properly because of FastClick (which is about to be removed from all our repos), so these can just be removed now.
> chore: Remove FastClick support on Checkbox and Radio

- packages/tabs/src/Tab.tsx
This isn't actually supported by ReachUI tabs (which we are shimming over). Tabs.onChange can be used instead.
> fix: Remove Tab.onClick prop

- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/InformationModal.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/InformationModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/RoadblockModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/RoadblockModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/matchMedia.mock
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModalSection.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModalSection.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalBody.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx
- draft-packages/modal/docs/InputEditModal.stories.tsx
- draft-packages/modal/package.json
- packages/design-tokens/docs/StoryBoard.stories.tsx
Update generic modal components and update Input-edit modal to match latest design.
Created new Input Edit Modal story which is controllable.
Notes:
- Ignore previous modal stories! Review only the Input Edit modal sub category in modal [here](https://dev.cultureamp.design/nat/generic-and-input-modal-update/storybook/?path=/story/components-modal-input-edit-modal--input-edit-modals) 
- Created custom breakpoint for smaller mobile phones to be used for the Heading styling as Responsive Typography is still under construction. Will need to come back once Responsive Typography is complete to remove custom styles.
closes #1469
> fix: Update Input Edit Modal to use new styles and created new StoryBook

- storybook/gtm-addon/register.ts
Change the import of `isEmpty` to a default import. 
TOL - Typescript should have warned me about this. 
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the …
> chore: Change lodash.isEmpty to a default import

- draft-packages/menu/KaizenDraft/Menu/components/MenuList.tsx
There's an interesting history in the usage of imports in `uuid`. 
- Have …
> fix: Change import for uuid

- draft-packages/menu/KaizenDraft/Menu/components/MenuList.tsx
This PR updates the import of uuid to be a named import. 
Verified as a canary release: https://github.com/cultureamp/kaizen-design-system/pull/2315
kaizen/draft-menu@4.1.9-canary.32 …
> fix: Change uuid to use named import

- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss
- draft-packages/modal/docs/ConfirmationModal.stories.tsx
- packages/design-tokens/docs/StoryBoard.stories.tsx
- Update Confirmation Modal to match latest design
- Create Confirmation Modal Story **with** controls
- Update scss files to use design tokens (previously using deprecated component library helpers)
Notes when reviewing:
- Please ignore previous modal stories and only review the Confirmation Modal sub category modal here
- To view the variants use the StoryBook controls (e.g isProminent and type)
closes #1469
> fix: Update ConfirmationModal to new styles and variants

- .buildkite/pipeline.yaml
Each of our Buildkite steps should have a defined timeout in case it goes into an endless cycle, never exits, and never releases the build agent.
We have seen occasions where builds were going on for days (!).
> chore: Set timeout for each Buildkite step to 15min

- packages/design-tokens/package.json
Rolling forward a patch version for ci. 
- Have Storybook stories been …
> fix: Roll forward for ci

- draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx
- draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
- draft-packages/illustration/docs/IllustrationSpot.stories.tsx
- Add objective spot illustration
- Objective spot illustration needs to be added as part of this ticket (https://trello.com/c/JWjtRIYn/104-improve-ux-for-onboarding-flow) …
> feat: Add objective spot illustration to Spot.tsx and stories

- draft-packages/menu/KaizenDraft/Menu/components/MenuList.tsx
Moves the uuid generation for this component out of the component itself to avoid it being regenerated on every rerender.
> fix: Move uuid generation out of component to avoid new id on each render

- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.elm
- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/ElmConfirmationModal.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/ElmInputEditModal.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.elm
- draft-packages/modal/KaizenDraft/Modal/Primitives/ElmGenericModal.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ElmModalBody.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ElmModalFooter.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ElmModalHeader.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.elm
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalBody.elm
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.elm
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalHeader.elm
Reset Modal styles to be used for Elm Modals only.
To fix visual breaking issues on Elm modals.
We do not intend to uplift the Elm modals at this stage.
> feat: revert previous modal styles to be used for Elm modals

- .buildkite/pipeline.yaml
- Bumping our timeout on the release pipeline due to it needing more time when multiple packages are updated
- https://cultureamp.slack.com/archives/C016N8Y1E10/p1638931924106500 …
> fix: bump release timeout to allow for longer builds when multiple packages are changed

- draft-packages/modal/KaizenDraft/Modal/Presets/ContextModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/RoadblockModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModalSection.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalHeader.tsx
Fix undefined being rendered as a class on the GenericModal. Removed the .padded styles from classname() as it was no longer required as a style for the generic modal.
Undefined was being added as a class on the GenericModal which wraps ModalHeader, ModalBody and ModalFooter.
> fix: remove previous padded styling on GenericModal

- draft-packages/illustration/KaizenDraft/Illustration/style.module.scss
- Add support for aspect-ratio CSS in Safari 14 and IE11 
- initial PR with feature here: https://github.com/cultureamp/kaizen-design-system/pull/2322
Here's the fallback working (just removed the support so it was forced on)
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/ …
> fix: add fallback for aspect ratio styles in safari 14

- draft-packages/form/KaizenDraft/Form/SearchField/SearchField.tsx
BREAKING CHANGE: 🧨  Fixed SearchField to have a required ID prop to avoid any undefined errors. Also removes the weird suffix that we stuck onto the ID.
✅  Closes: #2329
Adjusts the ID prop of `SearchField` to be required.
We're assuming that people are passing down IDs into this component, but it's not required. This gives us some weird mark-up with undefined IDs if they aren't passed through.
> fix: 🐛 Update ID prop on SearchField to be required and update name.

- packages/design-tokens/docs/DocsComponents.tsx
- packages/design-tokens/docs/pages/getting-started.stories.mdx
- storybook/main.ts
🍐 with @mcwinter07 
While trying to fix #2100 we noticed that the Design Tokens pages in Storybook had gone completely missing which was due to a recent change in the Storybook config.
Once this was solved we managed to fix the problem that these pages weren't loading properly by changing the `LinkTo` import... 🤷 
Here it is all working again:
Fixes #2100
> docs: Fix Storybook Design Tokens pages not loading [KDS-73]

- draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx
- draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
Update Team Spot component to use team-1.svg after updating in previous ([PR](https://github.com/cultureamp/kaizen-design-system-assets/commit/d07859ecae132a6a37a0bd75ebf7bbb0b13aef3b))
Broke the Team component in production as it was no longer linking to the correct asset Url.
> fix: Update Team component image url to use team-1

- draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.scss
- draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx
- draft-packages/tooltip/docs/Tooltip.stories.tsx
Adds new `mood` prop which allows different variants of the tooltip.
UI kit parity for different mood variants
[KDS-70](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-70)
> feat: new Tooltip mood variants

- draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.scss
- draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx
- draft-packages/tooltip/docs/Tooltip.stories.tsx
- Add left and right placement variant. 
- Allow the popper to 'flip' depending on the space within the viewport -> see Scroll story example.
- Match the UI kit.
> feat: tooltip placement for scroll and left/right

- draft-packages/avatar/KaizenDraft/Avatar/styles.module.scss
- explicitly set `border-bottom: none` for initials on the Avatar component, since in `performance-ui` global Materialize styling will set `border-bottom: 1px dotted` for all `abbr` tags.
- `border-bottom: 1px dotted` will cause all Avatar components used in `performance-ui` (which render initials) to have appear like so:
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, …
> fix: explicitly set border-bottom: none on Avatar component

- draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss
- draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
- draft-packages/guidance-block/docs/GuidanceBlock.stories.tsx
- Changes allow the guidance block to follow [Tile](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=1929%3A33867) design responsive behaviour based on the size of the guidance block instead of the screen size. 
- Utilizes `ResizeObserver` to add necessary css class names to allow us to modify the layout. 
- Additional RTL support to finesse spacings
- Improve button styling on mobile making them fullwidth per [Tile](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=1929%3A33867) designs
- Ensure text does not occupy widths less than `320px`
- Allow the secondary button to dismiss and hide the Guidance block
- Add `smallScreenTextAlignment` prop to left align text on mobile layout (center by default)
- …
> feat: Guidance block container query

- draft-packages/form/KaizenDraft/Form/RadioGroup/RadioGroup.spec.tsx
- draft-packages/form/KaizenDraft/Form/RadioGroup/RadioGroup.tsx
- draft-packages/form/KaizenDraft/Form/RadioGroup/__snapshots__/RadioGroup.spec.tsx.snap
- draft-packages/form/docs/RadioGroup.stories.tsx
To allow screen readers to connect the radio group to the label so it can be read out (also general accessibility).
https://github.com/cultureamp/kaizen-design-system/issues/2409
This was originally discovered when trying to use RadioGroup to mark up a radio group in performance-ui. This change fixes the accessibility of the component, but it is still not able to be used in perform-ui. This is because the component enforces the use of the Label component that does not match what the perform product uses:
I raised a possible solution to allow the consumer to override the Label element by supplying a render function for it where a consumer could render custom UI with the appropriate ID, but that was deemed too flexible.
- Does there need to be right-to-left (RTL) options for localization …
> feat: improve RadioGroup accessibility

- draft-packages/form/CHANGELOG.md
- draft-packages/form/package.json
- draft-packages/hierarchical-select/CHANGELOG.md
- draft-packages/hierarchical-select/package.json
- draft-packages/modal/CHANGELOG.md
- draft-packages/modal/package.json
- draft-packages/popover/KaizenDraft/Popover/AppearanceAnim.scss
- draft-packages/popover/KaizenDraft/Popover/AppearanceAnim.tsx
- draft-packages/popover/KaizenDraft/Popover/Popover.tsx
- draft-packages/popover/KaizenDraft/Popover/README.mdx
- draft-packages/popover/KaizenDraft/Popover/classMappers.ts
- draft-packages/popover/KaizenDraft/Popover/styles.scss
- draft-packages/popover/KaizenDraft/Popover/types.ts
- draft-packages/popover/docs/Popover.stories.tsx
- draft-packages/popover/package.json
- draft-packages/select/CHANGELOG.md
- draft-packages/select/package.json
- draft-packages/table/CHANGELOG.md
- draft-packages/table/package.json
- draft-packages/title-block-zen/CHANGELOG.md
- draft-packages/title-block-zen/package.json
- packages/brand-moment/CHANGELOG.md
- packages/brand-moment/package.json
- packages/component-library/icons/close.icon.svg
- Update Popover to include left and right Placement variant. 
- Allow for flip and fallback placements
- Update stories to show off clickable and hoverable story - Due to the makeup of this component being different to Tooltip, I decide to rather than re-invent the wheel but to illustration on the Kaizen Story of how you would use this component and make it clickable or hoverable.
- Include a 'Sticker sheet' story.
- After the work on Tooltips we decided Popover was lacking variants and functionality.
- We have updated both the component but the UI Kit
> feat: Add variants and update stories for Popover

- draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.scss
Update calc() to use `calc(#{$kz-some-var})` syntax. 
Causing error on other builds.
> fix: calc function syntax error

- .github/workflows/chromatic.yaml
The Chromatic baselines were not being updated when a branch was merged to master as there was an early exit in the steps. This change allows all master branches to update snapshots and autoaccepts them as the new baseline.
> ci: Run Chromatic action on the master branch to auto accept baselines

- js-audit-allow-list.json
- package.json
- packages/stylelint-plugin/package.json
- yarn.lock
Address https://nvd.nist.gov/vuln/detail/CVE-2022-0235
To fix failing audit step in our builds
- Upgrade `node-fetch` to `^2.6.7` where we have it as a direct dependency
- Move `node-fetch` from `dependencies` to `devDependencies`
- Upgrade `danger` to `^10.9.0` (they upgraded `node-fetch`)
- Add `node-fetch` CVE-2022-0235 to audit allow list
> chore: address node-fetch vulnerability CVE-2022-0235

- site/src/docs-components/animation/AnimationExample.tsx
- site/src/docs-components/animation/TransitionDrop.tsx
I noticed that selecting a different animation preset on our [Animation Guidelines](https://cultureamp.design/guidelines/animation/) would make the page jump to the very top and I had to scroll all the way back again :(
Turns out each option in the dropdown is using the deprecated `MenuItem` component, which is essential an `A` tag with `href="#"` by default - hence it jumping to the top.
I amended to `onClick` function passed to `MenuItem` with a good ol' `e.preventDefault()` and now it doesn't jump anymore but you can immediately see the change in animation :)
[See in action here on the branch build for the Kaizen site](https://dev.cultureamp.design/kds-190-fix-kaizen-site-scrolling-issue-on-animation-guidelines/guidelines/animation/)
> chore: Kaizen Site scrolls to top of page when selecting different animation preset on animation guidelines [KDS-190]

- js-audit-allow-list.json
Add `node-sass` and `engine.io` to js audit allow list.
Our builds fail the vulnerability check.
```
VULNERABILITY WARNINGS (not allow-listed)
--
  | The following vulnerability warnings were raised, and must be resolved to satisfy this build step:
  |  
  | !! [moderate]  node-sass: "Upgrade to version 7.0.0 or later" (CVE-2020-24025). Dependency chain: site>node-sass
  | !! [high]  engine.io: "Upgrade to version 4.0.0 or later" (CVE-2020-36048). Dependency chain: site>gatsby>socket.io>engine.io
  | !! [moderate]  node-sass: "Upgrade to version 7.0.0 or later" (CVE-2020-24025). Dependency chain: node-sass
```
- Add `node-sass` to allow list
- Add `engine.io` to allow list when sub dependency of `gatsby`
This is not the ideal solution, but due to an upgrade requiring a significant …
> chore: add node-sass and engine.io to audit allow list

- draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx
- draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
- draft-packages/illustration/docs/IllustrationScene.stories.tsx
Add the final illustrations that had to be created for specific use-case.
In order to remove the following...As at the time of my prior updates there was no illustration to be replaced with.
- illustrations/scene/performance-company-settings.svg
- illustrations/scene/getting-started.svg
- illustrations/scene/survey-overview-closed.svg
> feat: add final scene illustrations

- draft-packages/avatar/docs/avatarData.json
- draft-packages/illustration/docs/IllustrationSpot.stories.tsx
- draft-packages/popover/docs/Popover.stories.tsx
- draft-packages/tooltip/docs/Tooltip.stories.tsx
Fix/mitigate Chromatic false positives.
|Avatar - Initials long (large)|Cause|
|---|---|
|<img width="405" alt="image" src="https://user-images.githubusercontent.com/25891850/153308983-7da84f19-802e-4565-a5f6-6f7c89f08306.png">|`react-textfit` deviates between 10px and 11px for the snapshots|
|Spot Illustration - Animated|Cause|
|---|---|
|<img width="142" alt="image" src="https://user-images.githubusercontent.com/25891850/153309114-f35a726d-7c7f-45ef-b965-fc990efe14ba.png">|Snapshot is taken during different times of the animation|
|Tooltip (Also happens to Popover)|Cause|
|---|---|
|<img width="130" alt="image" src="https://user-images.githubusercontent.com/25891850/153309164-a6d71e62-e00a-492a-92ac-00be738b2c9f.png">|`react-popper` position calculation deviates|
False positives have …
> chore: fix chromatic false positives

- draft-packages/avatar/docs/avatarData.json
- draft-packages/popover/docs/Popover.stories.tsx
- draft-packages/tooltip/docs/Tooltip.stories.tsx
Attempt 2 at fixing Chromatic false positives.
Apparently it just wasn't good enough last time.
Last attempt: #2507 
- Change the accuracy threshold for Tooltip and Popover to the least accurate
- If this fails again, I reckon we'll just need to ignore the stories
- Change the `fullName` value for Avatar long initials again and hope they don't deviate this time
> chore(chromatic): fix chromatic false positives (again)

- .eslintrc.js
- draft-packages/button/docs/deprecated.Button.stories.tsx
- draft-packages/form/KaizenDraft/Form/Primitives/InputSearch/InputSearch.tsx
- draft-packages/hero-card/docs/HeroCard.stories.tsx
- draft-packages/illustration/KaizenDraft/Illustration/Players/LottiePlayer.tsx
- draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx
- draft-packages/menu/KaizenDraft/Menu/StatelessMenu.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx
- draft-packages/popover/docs/Popover.stories.tsx
- draft-packages/split-button/KaizenDraft/SplitButton/DropdownMenu.tsx
- draft-packages/table/KaizenDraft/Table/Table.tsx
- draft-packages/tabs/KaizenDraft/Tabs/Tabs.tsx
- draft-packages/title-block-zen/docs/TitleBlockZen.stories.tsx
- draft-packages/tooltip/docs/Tooltip.stories.tsx
- package.json
- packages/brand-moment/docs/BrandMoment.stories.tsx
- packages/button/docs/Button.stories.tsx
- packages/component-library/components/Dropdown/DropdownMenu.tsx
- packages/component-library/components/MenuList/MenuItem.tsx
- packages/design-tokens/docs/DocsComponents.tsx
- site/src/components/Footer.scss
- site/src/components/Footer.tsx
- site/src/components/NavigationBar/components/Link.tsx
- site/src/components/StorybookDemo.tsx
- site/src/components/markdownComponents.tsx
- site/src/docs-components/animation/Drop.scss
- site/src/docs-components/animation/Drop.tsx
- site/src/docs-components/icons/IconTile.tsx
- yarn.lock
Installs [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) and remediates/ignores any issues after implementing the recommended set of rules.
Helps to catch some common a11y anti-patterns. The main ones I came across while remediating the issues that surfaced here were:
* onClick being put onto non-interactive elements (div)
* Images with no/obsolete alt text
* Links being used where it should be a button
> feat: Install eslint-plugin-jsx-a11y

- draft-packages/button/KaizenDraft/Button/Button.tsx
- draft-packages/button/KaizenDraft/Button/IconButton.tsx
Adding a doc-block to provide substantive feedback for consumers using the Button and IconButton from the draft-packages. 
A version bump caused by updated packages in another commit re-released this on NPM. This has been deprecated again but we are now adding a doc-block to add additional feedback for consumers in the case of this happening again.
> chore: add doc-block deprecate warning to button

- packages/date-picker/src/DatePicker/DatePicker.tsx
- Build is failing because the Date Picker stories aren't exporting the props
https://buildkite.com/culture-amp/kaizen-design-system/builds/27992#35c59b30-9b21-43cd-95bf-e2c4107d880c …
> fix: export date picker props to fix build

- packages/date-picker/src/DatePicker/DatePicker.scss
- Fix issue where the background was transparent on popup and not the highest element
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in …
> fix: give calendar popup a z-index and background-color

- draft-packages/page-layout/KaizenDraft/Skirt/Skirt.tsx
- draft-packages/page-layout/package.json
Remove a dependency on itself from `draft-page-layout`
Closes https://github.com/cultureamp/kaizen-design-system/issues/2370
> fix: Remove circular dependency from draft-page-layout

- storybook/components/StoryWrapper/StoryWrapper.scss
- storybook/components/StoryWrapper/StoryWrapper.tsx
Add a mt and mb boolean prop to allow a marginTop or marginBottom to be added.
For cases where there are multiple storyWrappers stacked.
> feat: allow for margin top and bottom

- packages/component-library/icons/end.icon.svg
- packages/component-library/icons/start.icon.svg
Adds 2 new icons for pagination: `start` and `end`
> feat: Add new start and end icons

- CONTRIBUTING.md
- package.json
- yarn.lock
Set up [`commitizen`](https://github.com/commitizen/cz-cli).
Conventional commits can sometimes be confusing (eg. is my doc fix really a fix?). Commitizen will help provide you prompts with descriptions to help you through it, and then format your commit for you based on your input :)
https://user-images.githubusercontent.com/25891850/155635289-705c7ad3-7819-492b-b93f-922d39201d2c.mp4
1. `yarn install` (to ensure you have the changes)
2. `git add` some changes
3. `yarn commit` (or `yarn cz` if you prefer; the former is a script alias)
4. Profit!
As a first pass, I want it to be available, but still optional for people to use.
Apparently you can make it hook into `git commit`, but there’s some extra steps, and I don’t want to stop people who are comfortable with just plain writing their …
> chore: add commitizen

- packages/component-library/icons/end.icon.svg
- packages/component-library/icons/start.icon.svg
Update 2 new icons for pagination: `start` and `end`. 
Needed to be black fill to be able to inherit colours.
> feat: Update new start and end icons

- packages/progress-bar/src/ProgressBar.scss
The TS part of this component is referencing an `isAnimating` className that doesn't exist.
> fix: Restore ProgressBar isAnimating styling

- draft-packages/form/KaizenDraft/Form/CheckboxGroup/README.mdx
- draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/styles.scss
- draft-packages/select/KaizenDraft/Select/README.mdx
- site/docs/components/date-picker.mdx
- site/docs/components/pagination.mdx
- site/docs/guidelines/infinite-scroll.mdx
- site/docs/guidelines/pagination-infinite-scroll.mdx
Component health movements:
* CheckboxGroup to latestDesign: true
* Select to allVariants: false (missing cautionary and others)
* Datepicker to allVariants, responsive, and documented: true
Rather than updating health to false for a few components, I updated `FieldMessage` cautionary styling to `yellow-100`. Closes https://github.com/cultureamp/kaizen-design-system/issues/2596
Moved infinite scroll to guidelines and removed component health data for it (we don't see this as a component that needs to be built in Kaizen).
> docs: Component Health Update Mar 11

- draft-packages/card/KaizenDraft/Card/Card.tsx
classNameAndIHaveSpokenToDST property was incorrectly resolved in `classNames` as `classNameAndIHaveSpokenToDST` instead of the value because it was passed as an object (aka `{ classNameAndIHaveSpokenToDST: true }`
The custom styles were ignored so it resulted in broken UIs in murmur after updating the package to the latest version
https://cultureamp.atlassian.net/browse/MO-109
> fix: draft-card classNameAndIHaveSpokenToDST prop

- docs/basic-component.md
- docs/package-structure.md
- draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.tsx
- draft-packages/collapsible/KaizenDraft/Collapsible/__snapshots__/Collapsible.spec.tsx.snap
- draft-packages/collapsible/KaizenDraft/Collapsible/index.ts
- draft-packages/collapsible/package.json
- packages/component-base/index.ts
- packages/component-base/package.json
- packages/component-base/src/types.ts
- packages/component-base/tsconfig.dist.json
Add `component-base` package and new generic type `OverrideClassName` which removes `className` and adds `classNameOverride`.
Update `Collapsible` to extend HTML attributes with className override.
New `component-base` package will house any generic helpers and types.
Update made to `Collapsible` to ensure the new package does what we want it to.
- Add `component-base` package
- Omitted the `peerDependencies` of `react` and `design-tokens` until they are needed
- Update `Collapsible` to extend HTML attributes with className override
- Update code guidelines to reflect new component base
> feat: add `component-base` package and extend Collapsible with HTML attributes and className override

- draft-packages/select/KaizenDraft/Select/Select.tsx
- draft-packages/select/docs/Select.stories.tsx
Adds optional `description` prop to the `<Select/>` component, and stories to demonstrate
With description:
With description + error message:
> feat: Add description prop to Select

- draft-packages/collapsible/package.json
Move `@kaizen/component-base` to deps instead of devDeps for `Collapsible`.
The `.d.ts` still needs to know what the type `OverrideClassName` looks like.
> fix(deps): move `@kaizen/component-base` to deps instead of devDeps

- draft-packages/avatar/KaizenDraft/Avatar/Avatar.tsx
- draft-packages/avatar/KaizenDraft/Avatar/AvatarGroup.tsx
- draft-packages/avatar/KaizenDraft/Avatar/index.ts
- draft-packages/avatar/docs/AvatarGroup.stories.tsx
- draft-packages/avatar/index.ts
- draft-packages/avatar/package.json
- draft-packages/badge/KaizenDraft/Badge/Badge.tsx
- draft-packages/badge/KaizenDraft/Badge/index.ts
- draft-packages/badge/docs/Badge.stories.tsx
- draft-packages/badge/index.ts
- draft-packages/badge/package.json
- packages/brand-moment/package.json
- packages/brand-moment/src/BrandMoment.tsx
- packages/brand/package.json
- packages/brand/src/Brand/Brand.tsx
- packages/component-library/components/Box/Box.tsx
- packages/component-library/package.json
- yarn.lock
Part 1
Updates following components to extend HTML attributes with `classNameOverride`:
- Avatar
- AvatarGroup
- Badge
- Box
- Brand
- BrandMoment
To prevent us being roadblocks for our consumers
> feat: update components to extend HTML attributes with classNameOverride (part 1)

- draft-packages/page-layout/KaizenDraft/Content/Content.tsx
- draft-packages/page-layout/KaizenDraft/Content/index.ts
- draft-packages/page-layout/KaizenDraft/Skirt/Skirt.tsx
- draft-packages/page-layout/KaizenDraft/Skirt/SkirtCard.tsx
- draft-packages/page-layout/index.ts
- draft-packages/page-layout/package.json
- draft-packages/popover/KaizenDraft/Popover/Popover.tsx
- draft-packages/popover/package.json
- packages/pagination/package.json
- packages/pagination/src/Pagination.tsx
- packages/progress-bar/package.json
- packages/progress-bar/src/ProgressBar.tsx
Part 3
Updates following components to extend HTML attributes with `classNameOverride`:
- PageLayout
- Container
- Content
- Skirt
- SkirtCard
- Pagination
- Popover
- ProgressBar
To prevent us being roadblocks for our consumers
> feat: update components to extend HTML attributes with classNameOverride (part 3)

- draft-packages/split-button/KaizenDraft/SplitButton/SplitButton.spec.tsx
- draft-packages/split-button/KaizenDraft/SplitButton/SplitButton.tsx
- draft-packages/split-button/KaizenDraft/SplitButton/index.ts
- draft-packages/split-button/package.json
- draft-packages/tile/KaizenDraft/Tile/InformationTile.tsx
- draft-packages/tile/KaizenDraft/Tile/MultiActionTile.tsx
- draft-packages/tile/KaizenDraft/Tile/TileGrid.tsx
- draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx
- draft-packages/tile/KaizenDraft/Tile/index.ts
- draft-packages/tile/index.ts
- draft-packages/tile/package.json
- draft-packages/well/Well.tsx
- draft-packages/well/index.ts
- draft-packages/well/package.json
- packages/typography/package.json
- packages/typography/src/Heading/Heading.tsx
- packages/typography/src/Paragraph/Paragraph.tsx
Part 4
Updates following components to extend HTML attributes with `classNameOverride`:
- SplitButton
- Tile
- InformationTile
- MultiActionTile
- TileGrid
- Typography (just updated these to use `OverrideClassName`)
- Heading
- Paragraph
- Well
To prevent us being roadblocks for our consumers
> feat: update components to extend HTML attributes with classNameOverride (part 4)

- draft-packages/split-button/docs/SplitButton.stories.tsx
- Use storyWrapper to create stickersheet stories
note: the disabled variant is broken and there is not reversed variant
> docs: update split button stories to use storywrapper

- draft-packages/collapsible/docs/Collapsible.stories.tsx
- draft-packages/filter-menu-button/docs/FilterMenuButton.stories.tsx
- draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.tsx
- draft-packages/form/KaizenDraft/Form/Primitives/InputRange/InputRange.tsx
- draft-packages/form/KaizenDraft/Form/Slider/Slider.tsx
- draft-packages/form/docs/Slider.stories.tsx
- draft-packages/form/package.json
- draft-packages/likert-scale-legacy/KaizenDraft/LikertScaleLegacy/LikertScaleLegacy.tsx
- draft-packages/likert-scale-legacy/package.json
- draft-packages/loading-spinner/docs/deprecated.LoadingSpinner.stories.tsx
- draft-packages/menu/docs/Menu.stories.tsx
- draft-packages/modal/docs/ConfirmationModal.stories.tsx
- draft-packages/modal/docs/ContextModal.stories.tsx
- draft-packages/modal/docs/InputEditModal.stories.tsx
- draft-packages/page-layout/docs/PageLayout.stories.tsx
- draft-packages/table/docs/Table.stories.tsx
- draft-packages/tile/docs/Tile.stories.tsx
- packages/a11y/docs/SkipLink.stories.tsx
- packages/brand-moment/docs/BrandMoment.stories.tsx
- packages/brand-moment/src/BrandMoment.spec.tsx
- packages/component-library/stories/Box.stories.tsx
- packages/design-tokens/docs/DocsComponents.tsx
- packages/loading-spinner/docs/LoadingSpinner.stories.tsx
- packages/tabs/docs/Tabs.stories.tsx
I managed to miss a whole bunch in https://github.com/cultureamp/kaizen-design-system/pull/2616
Moves the remaining internal `Paragraph` imports from `component-library` to `typography`
> refactor(deps): Update all internal usages of Paragraph to typography package

- draft-packages/illustration/KaizenDraft/Illustration/BrandMomentCaptureIntro.tsx
- draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx
- draft-packages/illustration/docs/IllustrationScene.stories.tsx
Change animated illustration scenes to not animate in Chromatic.
[New Chromatic snapshots](https://www.chromatic.com/build?appId=60a1e4a102f0cb003b5d19d6&number=339)
Refactored stories file to use templates and adjust the controls to be more relevant (it's not perfect as there's a bit of manual overriding required since animated/non-animated use different props, so having them share a file is a little conflicting by nature).
Animated scene illustrations were not showing up in the Chromatic snapshots (eg. [here](https://www.chromatic.com/component?buildNumber=316&historyLengthAtIndex=44&distanceToMoveBack=-13&appId=60a1e4a102f0cb003b5d19d6&name=Components%2FIllustration%2FScene&specName=Brand+Moments&componentInspectorKey=6227e05c07cc90003a2f97dd-1200-snapshot-true)).
- Add display name to …
> refactor: change animated illustration scenes to not animate in Chromatic

- packages/design-tokens/less/typography.less
- packages/design-tokens/sass/typography.scss
- packages/design-tokens/src/themes/heart.ts
- packages/design-tokens/tokens/typography.json
- There was a minor update to the heading 3 line height in the Heart design tokens. The updated to the design token is required to reach parity with the design system
- It was decided that this constitutes such a minor change it is a fix
- `typography-heading-3-line-height` has been changed from 1.5rem to 1.875 to reflect the the change from 24px to 30px
> fix: update heading 3 line height to match figma token update

- draft-packages/hero-card/KaizenDraft/HeroCard/HeroCard.tsx
- draft-packages/hero-card/KaizenDraft/HeroCard/README.mdx
- draft-packages/hero-card/docs/HeroCard.stories.tsx
- site/src/pages/component-health.tsx
- site/src/templates/componentPage.tsx
As per UI Kit, `HeroCard` is to be superseded by `Tile` when it is rebuilt.
- Soft deprecate `HeroCard`
- Update site component health and page to accept `deprecated` frontmatter
> refactor(herocard): soft deprecate HeroCard and remove from health metrics

- draft-packages/card/package.json
- draft-packages/divider/package.json
- draft-packages/empty-state/package.json
- draft-packages/hero-card/package.json
- draft-packages/loading-placeholder/package.json
- packages/brand-moment/package.json
- packages/component-library/package.json
- packages/loading-spinner/package.json
- packages/rich-text-editor/package.json
- See card https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-360
- When `component-base` is a dev dependency only, it can cause TypeScript issues
- Moved `@kaizen/component-library` to `dependencies` in `package.json` where it wasn't yet
> fix: Component-Base to become dependency not dev only [KDS-360]

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
Removes pointer events from the psuedo element created for the RTE focus ring.
This element is getting in the way of selecting text.
> fix: Set pointer-events to none on RTE focus ring

- packages/rich-text-editor/package.json
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
- packages/rich-text-editor/src/RichTextEditor/inputrules.ts
- packages/rich-text-editor/src/RichTextEditor/keymap.ts
- yarn.lock
Adds 'inputrules' to the RichTextEditor, including:
* Smart quotes
* Two hyphens into an emdash
* Three full stops into an ellipsis
Because these things are expected from rich text editors, and sets us up for adding list functionality.
> feat: Add inputrules to RTE

- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
- Fixes [KDS-240](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-240)
- Issue: The underline the Title Block breadcrumb link sometimes has the wrong color:
A bit of a CSS mindtwister here:
Turns out there is a global `a:hover { color: blue; }` CSS rule which overrides the color set in the class for the `a` tag wrapping the breadcrumb link (because the class didn't have an explicit `.className:hover` providing greater specificity). This then leads to the color mixup because of how the DOM is nested and `text-decoration: underline` uses `currentColor` by default for the underline's color:
```
<a href="#"> 
<span> 
<span> 
Back to report
</span>
</span>
</a>
```
See this[ Codepen for a demo](https://codepen.io/christian314159/pen/gOooMod)
I simply …
> fix: Breadcrumb link in Title Block to use correct underline color [KDS-240]

- draft-packages/title-block-zen/package.json
- Lerna complaining that tag already exists
Manually setting it to 6.0.15 hoping it'll tag it correctly now
> fix: Set TitleBlock to 6.0.15 to fix deploy issues

- draft-packages/split-button/KaizenDraft/SplitButton/Dropdown.tsx
- draft-packages/split-button/KaizenDraft/SplitButton/DropdownMenu.tsx
- draft-packages/split-button/KaizenDraft/SplitButton/SplitButton.tsx
- draft-packages/split-button/docs/SplitButton.stories.tsx
Will be refactoring `SplitButton` as a blessed package.
Deprecate draft `SplitButton` and subcomponents.
- Merge in #2654 (best to merge these on the same day)
- https://cultureamp.atlassian.net/wiki/spaces/DesignSystem/pages/2769650898/Deprecation+warnings+-+how+to+guide
> refactor(splitbutton): deprecate draft SplitButton

- packages/rich-text-editor/docs/RichTextEditor.stories.tsx
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
Adds a `rows` prop to `RichTextEditor`, which will set a min-height on the editable area, in units of body paragraph line height. Pretty much the same as we've done on `TextAreaField`, but this component has autogrow enabled all the time. 
The default value has been set to 3, in line with `TextAreaField` and roughly matching the UI Kit.
Gives users a good way to set a min height on the text area.
> feat: Add rows prop to RichTextEditor for setting min-height

- draft-packages/form/docs/CheckboxGroup.stories.tsx
I noticed that the ["interactive" story](https://cultureamp.design/storybook/?path=/story/components-form-checkbox-group--interactive-kaizen-site-demo) for `CheckboxGroup` wasn't actually that interactive, it could only be toggled from `mixed` to `off`, but not `on`.
- removed the `actions` config option that caught the event callbacks that would set the state
- refactored the story helper component from a class to a functional component
> chore(docs): Made interactive CheckboxGroup story actually interactive [KDS-378]

- packages/split-button/docs/SplitButton.stories.tsx
False positive in Chromatic for SplitButton caused by the dropdown contents
Add data attribute to ignore dropdown contents from Chromatic.
Added to a wrapper because `MenuList` currently cannot take className nor data attributes (otherwise, ideally I would have instead of making the wrapper).
> docs(splitbutton): ignore dropdown contents in chromatic

- package.json
Looking at whether [this dependency update](https://github.com/cultureamp/kaizen-design-system/pull/2455) was required, and found that `loader-utils` was [introduced for elm](https://github.com/cultureamp/kaizen-design-system/commit/aed5a3869badb8d69ecd4ad4c69968c06412405a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R130).
Remove `loader-utils` (yes there's no `yarn.lock` update apparently)
> chore(deps): remove loader-utils

- packages/design-tokens/package.json
- yarn.lock
Questioning whether we should continue upgrading `react-intersection-observer` (https://github.com/cultureamp/kaizen-design-system/pull/2697) or just remove it since it appears to never be used.
Remove `react-intersection-observer`
> chore(deps): remove react-intersection-observer from design-tokens

- packages/button/Button/components/GenericButton.module.scss
- packages/button/Button/components/GenericButton.tsx
- packages/button/Button/styles.scss
Button focus styles broken as the pagination style border-radius was over riding it.
- Remove the styling that is overriding all focus-visible border-radius styles. 
- Add the pagination border-radius styles under the %caCircleButton class styles.
- Remove %caCircleButtonFocus as it's no longer needed
> fix: button focus styling

- draft-packages/page-layout/KaizenDraft/useResizeObserver.spec.tsx
- jest.config.js
- package.json
- packages/notification/src/components/GenericNotification.spec.tsx
- yarn.lock
Resolve https://github.com/cultureamp/kaizen-design-system/pull/2472 and https://github.com/cultureamp/kaizen-design-system/pull/2698 (this wants v28, but `jest` and `ts-jest` must match so I've gone with v27 since `ts-jest` doesn't have v28 yet).
- Update `jest` and `ts-jest` to v27
- Set jest `testEnvironment` to `jsdom` (default was changed to `node` in version update)
- Fix broken tests (GenericNotification and useResizeObserver)
> chore(deps): update jest and ts-jest to v27

- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.scss
- draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.tsx
- draft-packages/modal/KaizenDraft/Modal/index.ts
- draft-packages/modal/docs/ConfirmationModal.stories.tsx
- draft-packages/modal/docs/ContextModal.stories.tsx
- draft-packages/modal/docs/InputEditModal.stories.tsx
Support ticket: https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-427
`ModalAccessibleDescription` is embedded within `ConfirmationModal`, and was adding extra unnecessary space.
- Remove padding from `ModalAccessibleDescription`
- Fix modal stories to show code snippets
> feat(draft-modal): remove padding from ModalAccessibleDescription

- packages/design-tokens/src/lib/makeCssVariableTheme.ts
- packages/design-tokens/tsconfig.dist.json
- tsconfig.json
We had an incident on unified-home recently and that was caused by a piece of code accessing item in an array via index like this `items[0]` but not checking whether that can be undefined before using it. Because of that, we are enabling [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) for TS so that it warns us of this potential issue ([trello ticket](https://trello.com/c/lj3dwRpy/341-add-nouncheckedindexedaccess-true-to-tsconfigts-and-fix-ts-errors)). While we enabling that config, we got this error from `design-tokens` so we created this PR to address it. This TS config is helpful and recommended to avoid potential issue
Another way to fix it could be to exclude `src` from the published package but would still recommend to switch this option …
> fix: Enable noUncheckedIndexedAccess for design tokens and fix TS errors

- draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.tsx
We can't have a div inside a span, for accessibility reasons
- Change inner div to span
- Refactor a render method for less code-duplication
> fix: Kds 267 checkbox adds a div into span when clicked

- draft-packages/modal/package.json
- yarn.lock
Pin the `headlessui/react` package to <=1.5 while we wait for this issue to be fixed in headlessui.
Also updates headlessui/react from 1.4 to 1.5 as a side effect.
`headlessui/react` v1.6 has a bug causing the modal backdrop to not be removed, which means user can't interact with the page at all after closing a modal.
https://github.com/tailwindlabs/headlessui/issues/1417
> chore(deps): Pin headlessui/react to <1.5 until bug is fixed

- draft-packages/form/KaizenDraft/Form/CheckboxGroup/styles.scss
- draft-packages/form/KaizenDraft/Form/Primitives/Input/styles.scss
- draft-packages/form/KaizenDraft/Form/Primitives/InputSearch/styles.scss
- draft-packages/form/KaizenDraft/Form/RadioField/styles.scss
- draft-packages/form/KaizenDraft/Form/RadioGroup/styles.scss
- draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss
- draft-packages/hero-card/KaizenDraft/HeroCard/HeroCard.scss
- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.scss
- draft-packages/tag/KaizenDraft/Tag/Tag.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
- legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss
- packages/component-library/components/Dropdown/Dropdown.module.scss
- packages/component-library/components/MenuList/Menu.module.scss
- packages/component-library/components/Spacing/Base.module.scss
- packages/component-library/styles/type.scss
- packages/deprecated-component-library-helpers/styles/type.scss
- site/src/components/NavigationBar/NavigationBar.module.scss
- site/src/components/NavigationBar/_styles.scss
- site/src/components/NavigationBar/components/Link.module.scss
- site/src/components/OffCanvas/OffCanvas.module.scss
- site/src/components/OffCanvas/components/Header.module.scss
- site/src/components/PageHeader.scss
There is a lot of noise when building the site.
Reduce as much dart-sass warnings as possible.
We could not fix the `strip-unit` function because it's not doing a recommended calculation. Also could not ignore it, so it's still there.
> refactor: fix dart-sass division errors

- packages/deprecated-component-library-helpers/styles/type.scss
The to unitless pixels function was throwing a sass dart warning and prevents us from upgrading to the next major version. The intention of this PR is to clean up the last of the console warning for Kaizen relating to scss.
- refactoring the styles to no longer use unitless pixels function and just hardcode the values instead.
> refactor: remove to-unitless-pixels function to clean up sass err

- renovate.json5
Stops renovate from creating PRs trying to update these things.
We've got some older versions of React things in order to have our build steps testing against React 16 and 17.
> chore: Add pinned react packages to renovate config

- draft-packages/modal/package.json
Moves a `react-dom` dependency from a direct dep to a peer dep in the modal package.
This can cause consuming repos to include a separate version of react-dom just for this, bloating bundle size. We can expect our FE repos to have this already, and it can be any of these listed versions.
> chore(deps): Move react-dom from direct to peer dependency in modal

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
Uses the property name `content` instead of `contentObject` when creating editor state from the `value` prop.
This was broken, when passing an existing `value`, the editor wasn't showing the content.
> fix: Supply correct property name for prepopulating RTE

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
This doesn't currently work in perf-ui
Use interpolation for RTE height calculation
> fix: Use interpolation for RTE height calculation

- draft-packages/avatar/docs/AvatarGroup.stories.tsx
- draft-packages/avatar/package.json
Lerna and NPM versions are out of sync
manually bumps the version of draft avatar to 2.6.0
> fix: manually bump draft-avatar to 2.6.0 to correct failed lerna publish to npm

- draft-packages/avatar/package.json
- draft-packages/menu/package.json
- draft-packages/tooltip/package.json
- packages/rich-text-editor/package.json
Lerna is out of sync with npm packages
sync up lerna versions with npm by manually updating each package
> chore: force version bump of out of sync packages

- .github/workflows/chromatic.yaml
- yarn.lock
Update GH action to trigger Chromatic build when label `run chromatic` is added.
Also added the missing `yarn.lock` changes.
Provides a manual trigger in PRs for Chromatic so we don't need to wait for an approval to see if we broke anything.
> ci(chromatic): update GH action to trigger Chromatic build on label add

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yaml
- .buildkite/scripts/publish.sh
- .github/workflows/add_branch_preview_link_to_pr.yml
- site/gatsby-config.js
See: #2735
This lays the groundwork for the split of the Gatsby site and ensures that branch previews are still available for storybook.
- removes the site deploy from this repo (moved to [cultureamp/kaizen-site](https://github.com/cultureamp/kaizen-site))
- writes storybook to the root of the branch deploy in dev (i.e. to `dev.cultureamp.design/my-branch/`)
- updates branch previews comments to reflect change to storybook deploys
> ci: Publish storybook site only in dev

- .buildkite/pipeline.yaml
We temporarily decouple the release and link step to allow the site to publish testing new ci flow. This revert our pipeline workflow back to it original state.
- adds `wait` back to pipeline yml
- remove `depends_upon` and `key` in the build and publish step
> ci: add wait step back into pipeline to link build with release

- draft-packages/form/KaizenDraft/Form/CheckboxGroup/styles.scss
- draft-packages/form/KaizenDraft/Form/Primitives/Input/styles.scss
- draft-packages/form/KaizenDraft/Form/Primitives/InputSearch/styles.scss
- draft-packages/form/KaizenDraft/Form/RadioField/styles.scss
- draft-packages/form/KaizenDraft/Form/RadioGroup/styles.scss
- draft-packages/hero-card/KaizenDraft/HeroCard/HeroCard.scss
- draft-packages/tag/KaizenDraft/Tag/Tag.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
- legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss
- packages/component-library/components/Dropdown/Dropdown.module.scss
- packages/component-library/components/MenuList/Menu.module.scss
- packages/component-library/components/Spacing/Base.module.scss
- packages/component-library/styles/type.scss
- packages/deprecated-component-library-helpers/styles/type.scss
- site/src/components/NavigationBar/NavigationBar.module.scss
- site/src/components/NavigationBar/_styles.scss
- site/src/components/NavigationBar/components/Link.module.scss
- site/src/components/OffCanvas/OffCanvas.module.scss
- site/src/components/OffCanvas/components/Header.module.scss
Not having interpolated values has caused issues with the compiled scss when product teams try to
upgrade to the latest version.
wraps calc inner values with scss string interpolation
This fix related to the work done in [this commit](https://github.com/cultureamp/kaizen-design-system/commit/7ce2973289ab3f66db96d5d26b6d951c0bcf55dc)
> fix: wrap scss calc variables with interpolated values

- packages/component-library/package.json
Remove unused `@kaizen/button` dep from `component-library`.
This is unused and is causing a circular dependency.
> chore(deps): Remove button dep from component-library

- packages/button/src/Button/DirectionalLink.tsx
- packages/button/src/Button/PaginationLink.tsx
PaginationLink and DirectionalLink join in on having storyboard links.
> chore: storyboard links for pagination components

- packages/date-picker/docs/DatePicker.stories.tsx
- packages/date-picker/docs/DateRangePicker.stories.tsx
- packages/date-picker/index.ts
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/DatePicker/DateRangePicker.spec.tsx
- packages/date-picker/src/DatePicker/components/Calendar/Calendar.spec.tsx
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.spec.tsx
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.tsx
- packages/date-picker/src/DatePicker/enums.ts
- packages/date-picker/src/DatePicker/index.ts
- packages/date-picker/src/utils/isInvalidDate.spec.ts
- Handle validation for whether the date is valid and not disabled. 
- Still allow the consumer to override the `status` and the `validationMessage`.
- Add `onValidate` callback function as a prop of DatePicker. 
- `onValidate` provides an `validationResponse` object back to the consumer.
- Update stories to include an error state example on the sticker sheet
- Add a Validation story that provides an example of how to add additional validation on top the `isValid` and `isDisabled`.
- Add extra doc comments to props.
- Remove deprecated Input Props
**An Example of Validation with the validationResponse printed out**
> feat: Add validation to DatePicker

- packages/rich-text-editor/src/RichTextEditor/components/ToggleIconButton/ToggleIconButton.tsx
The Kaizen RTE loses focus when clicking on the toolbar button.
[JIRA CARD](https://cultureamp.atlassian.net/browse/COMP-147)
https://user-images.githubusercontent.com/48308300/171392000-8a236b72-38b2-4a6d-8cda-95eef5534e8f.mov
- Added the `onMouseDown` event on `ToggleIconButton` to prevent the editor from losing focus.
https://github.com/ProseMirror/prosemirror/issues/555#issuecomment-278723624
https://user-images.githubusercontent.com/48308300/171392449-8d6dd406-9a05-4c05-8a31-28a626ac8c93.mov
> fix: focus should remain in editor when clicking toolbar buttons

- .github/workflows/add_branch_preview_link_to_pr.yml
Fix PR branch preview link to check for the correct string.
New comments were being added as opposed to updating the existing one.
> ci: fix branch preview comment to update existing

- .github/workflows/add_branch_preview_link_to_pr.yml
- .github/workflows/chromatic.yaml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/danger.yml
Upgrade:
- `github/codeql-action` to v2
- `actions/checkout` to v3
As recommended by @ckychris
> ci: upgrade github/codeql-action to v2 and actions/checkout to v3

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
On Firefox there is a bug that removes white-space between text nodes. This is a known [issue](https://github.com/ProseMirror/prosemirror/issues/651) with prosemirror as the editor requires `white-space: pre-wrap` in the editable area. It is recommended that if you are not importing prosemirrors default css file you declare this to ensure the package can interpret white-space correctly in edit mode.
- adds `white-space: pre-wrap` to rich text editor styles.
> fix: add white space fix to resolve spacing bug on firefox

- draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx
The try..catch won't catch async errors unless the function is actually async.
We're getting a lot of errors in the logs when media is disabled
> fix: Catch the video element error

- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.scss
- See issue here: https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-523
- Modal backdrop would snap to full opacity at the end of the fade-in animation; a window resize would fix it
- Changing the Modal package all the way back to v6.x didn't help, showed same problem, so likely no code regression
- Investigation showed that it is somehow correlated with the latest Blink engine 102.x; MS Edge 95 was fine, once updated to 102 demonstrated the bug; Firefox & Safari also did not exhibit the issue
- After some exploration it showed that changing the animation duration from `rapid` to the default of `slow` removes the issue
- The difference in animation speed is noticeable (to me at least)
> fix: Fixed issue of modal background going full opacity in Chrome 102 by changing animation speed  [KDS-523]

- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.scss
- See issue here: https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-523
- Modal backdrop would snap to full opacity at the end of the fade-in animation; a window resize would fix it
- Changing the Modal package all the way back to v6.x didn't help, showed same problem, so likely no code regression
- Investigation showed that it is somehow correlated with the latest Blink engine 102.x; MS Edge 95 was fine, once updated to 102 demonstrated the bug; Firefox & Safari also did not exhibit the issue
- After some exploration it showed that changing the animation duration from `rapid` (200ms) to just something slightly off (201ms) made it work; fwiw 300ms also didn't work 🤷
> fix: Fixed issue of modal background going full opacity in Chrome 102 by changing animation speed [KDS-523]

- .buildkite/dockerfiles/release.Dockerfile
release step was breaking on buildkite - [see thread](https://cultureamp.slack.com/archives/C016N8Y1E10/p1654656512683039)
- Removes config Alpine config
- Adds node image stretch
> ci: update docker release image to node lts stretch

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
Rte editor state causing clipping while hovering [JIRA](https://cultureamp.atlassian.net/browse/COMP-156)
BEFORE:
AFTER:
Adding border radius and removing border radius when toolbar is present
> fix(rte): rte hover state causing clipping

- draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/ContextModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/RoadblockModal.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx
I need to focus on the RTE after the link modal closes, but I can't do it on submit because the animation still needs to happen first. Our modal puts focus back on the button that opened the modal, but in this case that button has disappeared, and we really want it back in the editor.
I only need this for the Input/Edit Modal, but I figure I may as well expose it on all of our modals while I'm here for future cases.
Adds a new prop to all our modal components called `onAfterLeave`, and passes this callback into the prop of the same name on `Transition` (headlessui component) via `GenericModal'.
> feat: Expose onAfterLeave on all modal components

- draft-packages/tile/KaizenDraft/Tile/components/Action.spec.tsx
- draft-packages/tile/KaizenDraft/Tile/components/Action.tsx
- packages/button/src/Button/components/GenericButton.tsx
In unified-home, we are using `MultiActionTile` for the displaced tiles at the bottom of the page. We are working on [this ticket](https://trello.com/c/nhIwDNmf/427-displaced-tiles-dont-have-analytics) to add missing analytics to track user clicking on these tiles. It turns out that inside `MultiActionTile`, it is using `Action` and it is not passing through `onClick` when `href` is there. Due to that, the `onClick` we pass to `MultiActionTile` would not be called to track user clicks since we are passing through `href` as well.
For more info/discussion, there is slack thread [here](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1654743194761219)
Allow passing both href and onClick to Button from Action component
> fix: Allow passing both href and onClick to Button from Action component

- packages/rich-text-editor/docs/RichTextEditor.stories.tsx
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
Using a discriminated union ideally, to make sure consumers are using one of the two. For more details [https://cultureamp.atlassian.net/browse/COMP-161](url)
Added new property `labelledBy` to use it as `aria-labelledby` for Rich Text Editor.
In RTE, label will be created only if `labelledBy` is not passed.
> feat: Allow aria-labelledby as an alternative to labelText on RTE

- js-audit-allow-list.json
- package.json
- yarn.lock
Address vulnerability warnings and update js audit allow list.
- Upgraded Storybook packages to ^6.5.9
- Reviewed and updated js audit allow list
- Removed `axios` resolution
- Added comment for why we have a resolution for `@types/react`
We're vulnerable :(
We still have quite a long list of warnings (which are in the allow list) which are caused by:
- `lerna` 
- we couldn't upgrade it simply, and since we're looking to change to `changesets` later, no point investing too much time into it
- `commitizen` 
- the package itself seems to have updated its dependencies automatically, but there hasn't been a release done. Since it's a dev tool, not too fussed
- `@storybook/*` 
- the main vulnerability seems to be `ansi-regex` in `node-logger`, which is quite embedded.
- `trim-newlines` is a …
> chore(deps): address vulnerabilities

- packages/date-picker/docs/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/DatePicker/DateRangePicker.spec.tsx
- packages/date-picker/src/DatePicker/components/Calendar/Calendar.spec.tsx
- packages/date-picker/src/DatePicker/components/Calendar/Calendar.tsx
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.scss
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.spec.tsx
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.tsx
- packages/date-picker/src/DatePicker/components/DateInput/utils/getDescription.spec.tsx
- packages/date-picker/src/DatePicker/components/DateInput/utils/getDescription.tsx
- packages/date-picker/src/utils/formatDateAsText.spec.ts
- packages/date-picker/src/utils/formatDateAsText.ts
- packages/date-picker/src/utils/setFocusInCalendar.ts
Fixes [card](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-480)
- Add onClick to input to open the calendar dialog.
- Remain focus within the input if the input is clicked.
UI:
- Returns focus to input when a date is selected through the calendar and:
-  it was opened via input click
-  it was opened via input keydown down arrow
- Returns focus to the calendar button when a date is selected through the calendar and:
- it was opened via calendar button click
- it was opened via calendar button keydown enter
- Closes the calendar when user is within the input and a date is selected and keydown on Tab.
Technical:
- Add `onClick` to input to open calendar dialog
- Created a check for when the focus should go to the calendar once opened or remain …
> feat: open calendar on click and focus on input

- .github/workflows/chromatic.yaml
- lerna.json
- package.json
- storybook/main.ts
- tsconfig.json
Delete the legacy-packages folder and any config related to it.
There are no packages remaining in the `legacy-packages` folder, so this can be removed
> chore: Remove legacy-packages folder

- draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.spec.tsx
- draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx
- packages/brand-moment/src/__snapshots__/BrandMoment.spec.tsx.snap
- yarn.lock
- See: [KDS-564](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-564)
- Scene illustrations get tab focus (at least in Firefox), probably because they're `video` elements
- Added `tabindex="-1"` to the `video` tag
- Refactor: Removed some duplication in the current component
> fix: Remove tab on scene illustrations [KDS-564]

- packages/date-picker/docs/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/DatePicker/components/Calendar/Calendar.tsx
- packages/date-picker/src/utils/setFocusInCalendar.ts
Calendar could not open when an invalid date was initially set.
- Check for invalid date which is type of Date but check as a string for both `selected` and `defautMonth`
> fix: update calendar to check for Invalid Date type Date

- draft-packages/likert-scale-legacy/KaizenDraft/LikertScaleLegacy/LikertScaleLegacy.tsx
- packages/notification/src/ToastNotificationsList.tsx
- when upgrading performance-ui to @cultureamp/frontend-build v2, we discovered style modules referenced using require were not being applied
- see this slack thread for more context: https://cultureamp.slack.com/archives/C016N8Y1E10/p1656464394609989
- the suggested solution from FE foundations was to update kaizen packages to use import instead of require
- it looks like this change was made for a bunch of packages a while ago, but these couple components got missed: https://github.com/cultureamp/kaizen-design-system/pull/782
- no functional change, using `import` should result in the same behaviour
> fix: Update styles to use import instead of require

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
The default lists in the rte did not have any nested styles.
- adds recurring nested list styles for `ul` and `ol` tags up to a dept of 6
- I also used this PR to update the focus ring to match design since this is a very small scss change we wanted to fix
| Prev lists | Updated lists |
|---|---|
| ![old_list_styles](https://user-images.githubusercontent.com/36558508/175846893-1497f536-8cbf-4bd3-a5a9-59150bd9a096.png) | ![new_list_styles](https://user-images.githubusercontent.com/36558508/175846909-6f3c960e-bd71-46dc-b3b3-5641f1a9df44.png) | 
| Prev border | Updated border |
|---|---|
|  ![old_focus](https://user-images.githubusercontent.com/36558508/175847211-c768f71f-e856-4e65-bc8a-d1cc37802aa3.png)   |   ![new_focus](https://user-images.githubusercontent.com/36558508/175847196-a6ca6468- …
> refactor: update RTE nested list styles

- draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.tsx
- draft-packages/empty-state/KaizenDraft/EmptyState/responsive.scss
- draft-packages/empty-state/KaizenDraft/EmptyState/styles.scss
- draft-packages/empty-state/package.json
Empty state was relying on deprecated-component-library-helpers and using kz- typography styles,
which was importing old sizes, weights and line-heights. This has been removed and the Paragraph and
Heading components have used to align to the UI toolkit
- replaces divs with `Paragraph` and `Heading` components
- replaces deprecates typographic styles with design tokens
- aligns sizes and responsiveness to ui toolkit
> refactor: remove deprecated styles and helpers from EmptyState

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/utils/setFocusInCalendar.spec.tsx
[KDS-584](https://cultureamp.atlassian.net/browse/KDS-584?atlOrigin=eyJpIjoiYzE2NTIwODc4OWI5NDliNzk1N2IyNWZkNzZhOTM4ZmIiLCJwIjoiaiJ9)
There’s some minor niceties we can use to make our tests more reflect the intended behaviour.
- Use `getByRole` instead of using `selector` argument, or traversing DOM element’s parent
- Skip some assertions that have been done in previous tests
- Use `toBeVisible` instead of `toBeInTheDocument`, which makes sure the element is in the document _and_ the accessibility tree.
- Use tabbing instead of focusing on specific elements.
@HeartSquared changes:
- Remove unnecessary usages of `async`
- Clean up tests to use consistent patterns
- Add tests for `setFocusInCalendar`
> test: improve DatePicker tests

- draft-packages/select/KaizenDraft/Select/Select.tsx
- draft-packages/select/KaizenDraft/Select/styles.react.scss
Secondary placeholder was missing padding and reversed styles.
- Add padding to placeholder
- Add reversed colour to placeholder and label when reversed.
> feat: update secondary select styles

- packages/rich-text-editor/docs/EditableRichTextContent.stories.tsx
- packages/rich-text-editor/docs/RichTextContent.stories.tsx
- packages/rich-text-editor/docs/RichTextEditor.stories.tsx
- packages/rich-text-editor/docs/ToggleIconButton.stories.tsx
- packages/rich-text-editor/docs/Toolbar.stories.tsx
- packages/rich-text-editor/docs/dummyContent.json
- packages/rich-text-editor/index.ts
- packages/rich-text-editor/package.json
- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.scss
- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.tsx
- packages/rich-text-editor/src/EditableRichTextContent/index.ts
- packages/rich-text-editor/src/RichTextContent/RichTextContent.scss
- packages/rich-text-editor/src/RichTextContent/RichTextContent.tsx
- packages/rich-text-editor/src/RichTextContent/index.ts
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.spec.tsx
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
- packages/rich-text-editor/src/RichTextEditor/controlmap.ts
- packages/rich-text-editor/src/RichTextEditor/index.ts
- packages/rich-text-editor/src/RichTextEditor/schema.ts
- packages/rich-text-editor/src/_mixins.scss
- packages/rich-text-editor/src/constants.ts
- packages/rich-text-editor/src/types.ts
- storybook/constants.ts
- yarn.lock
Creates two new components in the `@kaizen/rich-text-editor` package.
**`RichTextContent`**
Renders content created from the `RichTextEditor`. Creates a schema that includes all of our possible features/controls.
**`EditableRichTextContent`**
Renders the content with some styling and accessibility built in. Adds hover and focus styling, and a visually hidden button.
Smaller changes:
* Created some demo rich text data for our stories
* Moved `Toolbar` and `ToggleIconButton` into a `Subcomponents` subfolder on Storybook
* Moved all of the common styling rules for our content (things like typography and list styling) into a single mixin that is applied to both the editor and content.
* Created a constant array with our possible control names, to make it easy to generate a schema with …
> feat: Create RichTextContent and EditableRichTextContent components

- packages/rich-text-editor/package.json
- yarn.lock
- latest version updates link validation
- updates `@cultureamp/rich-text-toolkit` v1.8 to v1.9
> chore: upgrade toolkit to latest version

- packages/rich-text-editor/src/RichTextContent/RichTextContent.tsx
To resolve a broken build, [see thread](https://cultureamp.slack.com/archives/C02NUQ27G56/p1658287850617659) for the full context.
- export RichTextContentProps interface from RichTextContent component
> fix: export RichTextContentProps to fix compiler breaking

- draft-packages/tag/KaizenDraft/Tag/Tag.scss
- draft-packages/tag/KaizenDraft/Tag/Tag.tsx
- draft-packages/tag/package.json
To remove dependency on old deprecate library helpers - [see ticket ](https://cultureamp.atlassian.net/browse/KDS-570) and [original discovery](https://cultureamp.atlassian.net/browse/KDS-548)
- replaces style dependent on `deprecated-component-library-helpers` with design tokens and modern CSS
- remove redundant @types/classname from package.json dependency
> refactor: remove deprecated styles from Tag component

- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
Fixes an issue where a long, unbroken string will overflow the editor. This fix makes it wrap to a new line.
> fix(rte): fix bug where long strings overflow editor

- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.tsx
links withint the RTE Content wrapper do not currently bubble up so could not be used in its non editable state.
- Add a click handler for the onClick event to allow anchor links to be clicked
> fix: add click handler to editor wrapper to bubble events

- packages/rich-text-editor/src/RichTextEditor/components/ToolbarSection/ToolbarSection.scss
There is an overlap of the buttons on smaller screens. Since this will still be wrapping within each Section each individual button won't be bump each other but will break across multiple lines (see video for reference). After time boxing an alternative solution to remove section wrapper and try to use a divider or lastItem class between the sections, I opted to push this change up first to deal with the bug. The alternatives solutions will likely take more (though worthwhile investigating in the future).
https://user-images.githubusercontent.com/36558508/180934363-c9dcee07-53c0-4243-adac-21f6d58a40a4.mp4
- this adds a simple flex wrap on the sections
There is currently an additional section wrapper that is being created in the controlMap but I will address this in a different PR
> refactor: add flex wrap to toolbar section

- draft-packages/select/KaizenDraft/Select/Select.module.scss
- draft-packages/select/package.json
part of the work to remove all deprecated-component-library-helpers dependence on kz and ca scss variables
- replaces ca & kz typography variables with design tokens
> refactor: replace deprecated component lib helpers and old border styles

- js-audit-allow-list.json
- package.json
- yarn.lock
- Update commitizen
- adds resolution for commitizen as cz-conventional-changelog still has a dependency on 4.2.4
- Update js audit allow list
Vulnerabilities should be addressed often. Although @christian314159 will be checking on whether Snyk will replace the need to check these.
> chore: address vulnerabilities

- draft-packages/likert-scale-legacy/KaizenDraft/LikertScaleLegacy/LikertScaleLegacy.spec.tsx
- draft-packages/likert-scale-legacy/KaizenDraft/LikertScaleLegacy/LikertScaleLegacy.tsx
- draft-packages/likert-scale-legacy/docs/LikertScaleLegacy.stories.tsx
- draft-packages/likert-scale-legacy/package.json
- add new dependency @kaizen/draft-form
BREAKING CHANGE: replace props validationError & validationErrorId with validationMessage & status
The motivation for this change is to allow the LikertScale to produce an error message when input is not valid.
The LikertScale will now produce an error message when is passed a validationMessage and set to a status of "error"
> feat(likert-scale-legacy): add validation message support

- packages/a11y/package.json
- packages/a11y/src/VisuallyHidden/VisuallyHidden.tsx
This aligns to our pattern of extending classNameOverride for handling additional classes in our component. This would be used for target purposes within CSS and was created off the back of the comments in [this PR](https://github.com/cultureamp/kaizen-design-system/pull/2882/files#r931765082)
- extends classNameOverride prop on VisuallyHidden component
> feat: add classNameOverride to hidden wrapper

- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.module.scss
- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.tsx
There is a double focus ring on the editable rich text content for keyboard navigation when tabing to inner anchor tags in the rte content.
- useses the  visually hidden classNameOverride to target the sibling element for focus
https://user-images.githubusercontent.com/36558508/181419532-1413da79-86e4-4c2c-820c-2f9a892408b3.mp4
> refactor: add override and change target of css focus

- packages/component-library/icons/maximize.icon.svg
- packages/component-library/icons/minimize.icon.svg
There’s a need by designer Aru in team Apollo for a Maximize icon, as currently there is only a Minimize icon.  This will be used to expand and contract a data table they’re working on, with the impetus to go fullscreen if the user needs.
- adds max and minimize icons
> feat: add maximize and minimize icons to comp lib

- packages/date-picker/docs/Calendar.stories.tsx
- packages/date-picker/docs/DatePicker.stories.tsx
- packages/date-picker/src/_primitives/Calendar/Calendar.module.scss
When "today" is disabled in the Calendar, the disabled styles (grey font) were not coming through; although they did when the date was focused.
|OLD|NEW|
|---|---|
|![image](https://user-images.githubusercontent.com/25891850/182273936-425b507a-5d9f-47fc-86a2-b242d0bd8be2.png)|<img width="292" alt="image" src="https://user-images.githubusercontent.com/25891850/182275005-f267735e-23ef-49e5-a269-cb54b3ab1115.png">|
Removed the `:not(.outside)` selectors which don't appear to do anything except make things overspecific.
> fix(date-picker): remove unnecessary :not(.outside) selectors in Calendar styles

- packages/date-picker/docs/DatePicker.stories.tsx
Removes the spread props for the validation story because the controls have been removed.
Accidentally broke the story when updating DatePicker stories.
> docs(date-picker): fix validation story

- packages/date-picker/src/utils/setFocusInCalendar.spec.tsx
- packages/date-picker/src/utils/setFocusInCalendar.ts
Add focus fallback to the first day of the displayed month.
To cater for cases such as "the default month is set to a different month than the current month, and there is no selected day". Fallback to focusing on the first of the month.
> feat(date-picker): add fallback date to focus on for calendar

- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.spec.tsx
- draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx
- draft-packages/modal/docs/InputEditModal.stories.tsx
In `InputEditModal` modal - we currently have 3 buttons.
1) A primary button to Submit action.
2) A secondary button that is attached to Dismiss action.
3) A close button that is attached to Dismiss action.
We in Polaris have a product need to separate these 3 buttons with 3 distinct actions. 
* When two props `onSecondaryAction` and `secondaryLabel` are supplied, secondary action feature is available in the secondary button.
* Otherwise, the modal works as usual.
* Gearing towards minimal change and only `minor` version upgrade.
* So, not touching other prop names.
* I'd like to avoid major package upgrade.
* Have done design review with designer in #community_amplify_1on1
> feat: Add secondary action prop

- packages/date-picker/docs/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
Validate input when the user presses the Enter key.
Updated the Validation story to use a `<form>`.
Pressing Enter submits the form (if it exists), but we did not trigger the validation when it happens, which lead to an inaccurate error message (lagging one step behind).
> feat(date-picker): validate input on pressing Enter key

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DateRangePicker/DateRangePicker.spec.tsx
[KDS-698](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-698)
Discovered we had jest `overlapping act calls` errors in https://github.com/cultureamp/kaizen-design-system/runs/7717010748?check_suite_focus=true when looking at other errors.
Made DatePicker tests async where needed
> test(date-picker): fix Date(Range)Picker tests with overlapping act calls

- packages/date-picker/docs/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
- Improve developer experience
- Allow `status`, `validationMessage`, and `onValidate` to be optional and use inbuilt validation.
> feat(date-picker): render inbuilt validation when props not set

- draft-packages/avatar/docs/Avatar.stories.tsx
- I always use this sticker sheet during the Kaizen onboarding and keep stumbling on the typos
> chore: Fixed typos in Avatar sticker sheet headings

- draft-packages/form/KaizenDraft/Form/RadioGroup/RadioGroup.module.scss
https://cultureamp.atlassian.net/browse/KDS-716
The `label` inside a `RadioGroup` is given a width of 400px, which could cause problems on small screens and increased font-size.
As suggested by @christian314159 using a `max-width` instead of `width` is the best solution to prevent any scenarios that do require the width
> fix: use max-width on label

- packages/select/src/FilterMultiSelect/components/SelectionControlButton/SelectionControlButton.scss
Adds padding to control buttons, as per [the figma designs](https://www.figma.com/file/hANEprZKom5Br1IBXhE8mr/%F0%9F%9A%A7-UI-Kit%3A-Beta-Components?node-id=24636%3A129157)
> fix(multi-filter-select): add padding to control buttons

- packages/select/src/FilterMultiSelect/components/Trigger/TriggerButtonBase/TriggerButtonBase.scss
- packages/select/src/FilterMultiSelect/components/Trigger/TriggerButtonBase/TriggerButtonBase.tsx
- packages/select/src/FilterMultiSelect/components/Trigger/_mixins.scss
On the FilterMultiSelect's trigger button, changes spacing between children and the chevron from 12px to $spacing-xs
Spacing was previously 12px, which is a larger value than the figma design
> fix(filter-multi-select): use spacing-xs between children and chevron

- packages/select/docs/FilterBarExample/DemographicValueSelect.tsx
- packages/select/docs/FilterMultiSelect.stories.tsx
- packages/select/src/FilterMultiSelect/provider/SelectionProvider/SelectionProvider.spec.tsx
A bug was raised that when having multiple filter category selected, removing the first category will clear the second one as well.
The proposed solution:
- remove the internal state within the [DemographicValueSelect.tsx](https://github.com/cultureamp/kaizen-design-system/compare/ll/fix-filter-multi-select-stories?expand=1#diff-fb7011fd06c523f4db5afb33622454f35bbb27efdd224b70c16c68b94f9a800d) 
- allow its value to be controlled externally
https://user-images.githubusercontent.com/8596435/184593993-f5d23529-06d2-455b-9312-f3dad54b8fef.mov
> fix: FilterMultiSelect stories - FilterBar 

- packages/rich-text-editor/package.json
- packages/rich-text-editor/src/RichTextEditor/controlmap.ts
- yarn.lock
To highlight the list buttons in the toolbar when it is active in the RTE component
[COMP-262](https://cultureamp.atlassian.net/browse/COMP-262)
- Update dependency version for `rich-text-toolkit`
- Use `listIsActive` method from `rich-text-toolkit` to highlight list buttons
- Bullet list
- Numbered list
> feat: Use `listIsActive` to highlight list buttons when active

- packages/split-button/docs/SplitButton.stories.tsx
The split button's menu causes flaky chromatic tests when the position is a few pixels off.
- Wrap the chromatic rows in a chromatic ignore
> fix: Splitbutton flaky test on chromatic

- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.spec.tsx
- packages/date-picker/src/DatePicker/components/DateInput/DateInput.tsx
- packages/date-picker/src/utils/isRefObject.ts
- To refactor Date Input to use forward Ref
- use forwardRef within DateInput
- pass buttonRef and InputRef as a ref Object to DateInput
> refactor(date-picker): update DateInput to use forwardRef

- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.module.scss
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.spec.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.tsx
We want to render `Link` components from our routing library for tabs.
Similar to the GenericButton `component` prop, we've added a custom render prop to the  TitleBlock.NavigationTab. Most props are forwarded through the render prop, however, className is calculated by the internals and then forwarded through.
We removed the inner div of the navigation tab link. This allowed the classNames to be passed as one string to the resulting custom component. All styles of the div could be safely moved to the anchor tag.
Unlike the GenericButton, the NavigationTab was not a forwardRef component. We did not add that functionality here, but it may be useful to add in the future.
> feat: Add custom component render prop to navigation tab of title block

- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.tsx
The `Component` prop was changed to `renderTab` but was not
updated in this prop definition. Also, we do still pass down the
variant, so do not omit it from the props.
> fix: Update CustomNavigationTabProps

- packages/select/src/FilterMultiSelect/components/SelectionControlButton/ClearButton/ClearButton.spec.tsx
- packages/select/src/FilterMultiSelect/components/SelectionControlButton/ClearButton/ClearButton.tsx
- packages/select/src/FilterMultiSelect/components/SelectionControlButton/SelectAllButton/SelectAllButton.spec.tsx
- packages/select/src/FilterMultiSelect/components/SelectionControlButton/SelectAllButton/SelectAllButton.tsx
"Select all" and "Clear" buttons are currently scoped to affect all options, instead of just those that are filtered.
Scopes "Select all" and "Clear" button click behaviour to affect only filtered options.
- When options have been filtered, "Select all" will
- Select all filtered options
- Not select unselected, un-filtered options
- Not clear selected un-filtered options
- When options have been filtered, "Clear will
- Deselect all filtered options
- Not deselect selected unfiltered options
> fix: KDS-737 Only apply 'select all' and 'clear' to filtered items when using the search

- packages/select/package.json
- packages/select/src/FilterMultiSelect/components/MultiSelectOption/MultiSelectOption.spec.tsx
- packages/select/src/FilterMultiSelect/components/MultiSelectOption/MultiSelectOption.tsx
- packages/select/src/FilterMultiSelect/components/SearchInput/SearchInput.spec.tsx
- packages/select/src/FilterMultiSelect/components/SearchInput/SearchInput.tsx
- packages/select/src/FilterMultiSelect/provider/SelectionProvider/SelectionProvider.spec.tsx
Slack ticket - KDS-760
In order to use the FilterMultiSelect in older version of React, `useId` has been swapped out for `uuid` as the former is only available in version 18.
> fix(component): use uuid package instead of useId for compatibility with older React versions

- packages/component-library/components/Icon/Icon.module.scss
- packages/component-library/components/Icon/styles.scss
This class rule is unused, and may lead to confusion around whether or not a prop should be available to turn the Icon into a block layout. It is expected that this should be achieved through classNameOverride instead, so removing this should make that less confusing.
Removes an unused css rule that applies `display: block` to the Icon component.
If importing this variable in your own repo, please replace all instances of `%caIconBlockLayout` with your own `display: block` css rule.
> fix: Remove unused %caIconBlockLayout scss var

- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/SecondaryActions.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/Toolbar.tsx
- Toolbar subcomponent in TitleBlock has a hardcoded `data-automation-id` which makes it hard to distinctively target each usage of it on a page
- See Slack convo: https://cultureamp.slack.com/archives/C0189KBPM4Y/p1662354117952409
- Made `automationId` an optional prop and then passed in an ID for each usage
* Uses the original `title-block-main-actions-toolbar` for the main actions
* And `title-block-secondary-actions-toolbar` for the secondary actions
This is a breaking change because some of our tests might rely on the previous IDs in a way that will break after upgrading to this version.
> fix: Set distinct automation-ids for each usage of TitleBlock Toolbar

- draft-packages/select/KaizenDraft/Select/Select.module.scss
Removes blue background unless focused, and fixes font styling
Implementation is out of sync with the UI kit - screenshots [here](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-396&text=select)
- Removes blue-100 background for selected item (unless focused. This is to differentiate between what is focused, and what is selected)
- Adds bold font weight, and color blue-500 to selected item, to distinguish from non-selected items
> fix(select): fix selected option styling

- packages/design-tokens/src/ThemeManager.ts
In order to let nextjs app set default styles on server-side. We have to set defaultTheme at html component before this fix.
This is an easy fix that, in the nextjs app, we can specify the component with id `kaizen-root` as a root element and it can render default styles on the server side.
> fix: be able to specify root element applying theme

- draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx
Some older (unsupported) browsers did not have a promise as the result of the `.play` function so they are spamming the error logs. Although we don't support those browsers, we do need to add the guard against it as they are spamming our error logs.
Have wrapped the `.play` in a try..catch and also check that the result of `.play` returns a callable `.catch` before adding the catch.
> fix: Extra catch around illustration video player

- draft-packages/form/KaizenDraft/Form/RadioField/RadioField.tsx
Removes children prop from RadioField
BREAKING CHANGE: children can no longer be passed to RadioField
`children` prop is currently available on the `RadioField` component, despite not being used. This may lead to confusion on behalf of consumers.
Removes `children` prop from `RadioField` component
> fix(radio-field): remove children prop from RadioField

- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.spec.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
- draft-packages/title-block-zen/docs/TitleBlockZen.stories.tsx
Renames the `renderTab` prop to just `render` on Title Block's `NavigationTab` component.
Also adds a prop description to the `render` prop from the last PR 'cause I forgot.
To create a consistent name for this prop, rather than having something unique each time.
This should technically be a breaking change, but we just added this prop a couple weeks ago and no one is using it yet so I'm looking to get away without a breaking change :)
> chore(title-block-zen): Rename renderTab prop to render

- packages/design-tokens/less/typography.less
- packages/design-tokens/sass/typography.scss
- packages/design-tokens/src/themes/heart.ts
- packages/design-tokens/tokens/typography.json
Updates the typography-paragraph-intro-lede-letter-spacing var from -0.5px to 0px
The current value (-0.5px) is not up to date with the UI-Kit
> fix(design-tokens/heart): update intro-lede letter spacing

- draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.module.scss
- draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.spec.tsx
- draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.tsx
- draft-packages/collapsible/package.json
Rather than the whole Collapsible header being a `button` element, turn the chevron that sits in the header into an `IconButton` which will act as the toggle button for keyboard & screen reader users. Then add add an `onClick` to the header div as an additional layer so that mouse users can still click the header to open and close. 
Two reasons:
1: There are times where we want the header to contain other actions, e.g.
In these cases, we're forced to have _buttons inside buttons_, which is invalid HTML and causes many issues.
2: Elements inside of buttons have their semantics stripped and simplified down to a string. If you were to put an `h3` into this heading (and it's wrapped in a button), the document will no longer see the `h3` as an `h3`.
> feat(Collapsible): Use an IconButton for header toggle (a11y improvement)

- .buildkite/pipeline.yaml
build failed ci posts are no longer being post to slack - this should update this to our channel
- updates slack notification channel to wol_kaizen
> ci: update pipeline slack channel notification

- draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.spec.tsx
- draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx
- draft-packages/form/KaizenDraft/Form/TextField/TextField.spec.tsx
- draft-packages/form/KaizenDraft/Form/TextField/TextField.tsx
When using a validation message, the text input field would receive this violation: "ARIA attribute element ID does not exist on the page" . You can see in storybook, the `aria-describedby` on the input field is looking for `kaizen-demo-text-field-field-validation-message` but the ID of the validation message is `kaizen-demo-text-field-field-message`
Correct ID used for validation text so `aria-describedby` works as intended
> fix: correct ID on validation message used for describedBy on text field

- .gitignore
- packages/rich-text-editor/package.json
- packages/rich-text-editor/src/RichTextContent/RichTextContent.tsx
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
- packages/rich-text-editor/src/RichTextEditor/controlmap.ts
- packages/rich-text-editor/src/RichTextEditor/inputrules.ts
- packages/rich-text-editor/src/RichTextEditor/keymap.ts
- packages/rich-text-editor/src/RichTextEditor/schema.ts
- yarn.lock
- Misalignment between prosemirror dependencies (specifically prosemirror-model and prosemirror-state) in the Toolkit and RTE was causing the component to break on render
- As these repo are not connected by the same dependancy bot there is no guarantee that these issue would not regularly arise
- This was surfaced on a lock file [maintenance PR](https://github.com/cultureamp/kaizen-design-system/pull/2868/files), which caused a cascade of issues
- Update import statements
- Fixes type errors
- remove prose-mirror dependencies
- This will rely on this [PR](https://github.com/cultureamp/rich-text-toolkit/actions/runs/3080111238/jobs/4977082827) to be merged in
> refactor: upgrade RTE Toolkit to 2.0.0 and update ProseMirror imports

- .buildkite/pipeline.yaml
- Playwright currently runs on our `master` builds, but it's pretty useless then because it only runs after things have been released - and it already ran before the merge
- added branch filtering rule to the Playwright step in our Buildkite config
> chore: Skipping playwright tests on master branch

- .github/workflows/chromatic.yaml
Enable Turbosnap for Kaizen.
Should update subset:
- Appears to take all the changes from your branch and does a normal `push` check
Should update all:
- Imported directly into the components
- Does not have `.module.scss`
Should not update:
Skipped:
- If you run any of the below triggers, then it will update all snapshots as the commits have changed and Turbosnap doesn't know what to compare to
Triggers (will apply above rules; does not have a specific rule itself):
Configure Turbosnap to reduce the number of snapshots registered in Chromatic to save costs (as they charge per snapshot).
Looks like `FilterMultiSelect` stylesheets are all using `.scss` as opposed to `.module.scss`. This needs to be fixed to be able to benefit from our Turbosnap config (also not to conflict with upcoming …
> ci(chromatic): update chromatic GH action to use turbosnap

- draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx
I was looking into adding a new Spot illustration and noticed that the file was ~1300 lines long and consisted of a lot of repetition as almost all components were identical but for the `url` they used.
The length of the file, plus the noise from the repetition, made it really hard to get an overview of what's going on and how/where to add new illustrations.
I created a simple factory function that creates the illustration component using a given `url`.
Unfortunately, Prettier would still wrap these much simpler statements due to its 80 char max default, which made it still quite "noisy" to look at IMO. Thus Ito add a `// prettier-ignore` to each line (group statements are not supported :( ), which isn't the best - but still better than the alternative, I think.
So previously an …
> refactor: Added factory function for spot illus so they fit on one line

- draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx
- draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
- draft-packages/illustration/docs/IllustrationSpot.stories.tsx
We have a new illustration for "Calendar Sync".
The SVG has already been added to our assets repo, so all that needed to be done here was adding the new component.
> feat: Added new “Calendar Sync” spot illustration

- draft-packages/form/KaizenDraft/Form/Primitives/Label/Label.module.scss
- draft-packages/form/KaizenDraft/Form/Primitives/ToggleSwitch/ToggleSwitch.module.scss
[KDS-640](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-640)
The UI Kit components for the [Checkbox Field](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=14462%3A196) use different spacing between the checkbox and the label than what is shown in [Storybook](https://dev.cultureamp.design/develop/filter-select/?path=/story/components-form-checkbox-field--interactive-kaizen-site-demo).
> fix(draft-form): Label margin should be 6px and not 10px

- packages/notification/package.json
Manually bump the notification package to 1.0.0
Breaking changes on sub v1 versions (0.x.x) don't trigger a major version release, it has to be manually updated to v1 before that happens (something I didn't realise when I made this package starting at 0.0.0)
> chore: Release @kaizen/notification v1

- draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.spec.tsx
- draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.tsx
- draft-packages/empty-state/docs/EmptyState.stories.tsx
**Use heading tag and add `headingVarient` prop in EmptyState component**
Currently the "Empty State" component heading renders as a `<div>`, but is styled as `heading-3` which doesn't follow best a11y semantic practices (and has created a violation on the survey configure questions edit page - [here is ticket](https://cultureamp.atlassian.net/browse/KD-1721))  
1. Use `headingVarient` to control heading level
2. Use `tag="div"` when no `headingVarient` provided
3. Add optional `headingVarient` prop so that correct heading can be applied for the page (in cases where no preceding `<h2>`)
4. use `heading-3` styling by default when no `headingVarient` provided
> Note: an alternative to this PR could be adding `role="heading"` to the div, but seemed best to make a heading a heading
> feat: heading tag for EmptyState component

- package.json
We've been expeirencing issue with mismatched bundle hashes in our storybook and whats been built and deployed to our S3 buckets on dev branches. This is a potential solution outline in this [thread](https://github.com/storybookjs/storybook/issues/13261).
- adds  `--no-manager-cache` flag to `storybook:build` script.
> ci: add --no-manager-cache flag to storybook:build

- playwright.dev.config.ts
Playwright would spin up a new web server or fail if current webserver for local host was already running (6006). This should speed up testing locally on dev
- Adds the `reuseExistingServer` prop
- increase timeout for local dev to ensure there are no timeout test issues on older machines
> refactor: add reuseExisting server flag

- packages/select/src/FilterMultiSelect/components/ListBox/ListBox.tsx
disabledItems currently returns an array that includes filtered-out items as `undefined`. This causes `disabledItems.length` to return unexpected results, causing confusion for the consumer.
Strips `disabledItems` of all undefined values, leaving only items that are filtered in.
> fix(filter-multi-select): strip items of undefined values

- packages/design-tokens/package.json
`design-tokens@10.0.3` has exported types in different locations, `package.json` has not been updated.
Updated `package.json` to contain no types key, limiting one file pattern. Instead, allow typescript to find types file automatically.
https://cultureamp.slack.com/archives/C02NUQ27G56/p1664939298139269
> fix: remove incorrect design tokens type location

- .github/workflows/ci.yml
Adds a new step to our build to run `yarn check --integrity`.
Currently you can push a `package.json` change without running yarn install and get it all the way to master. This will stop that from happening.
> ci: Add step to check yarn integrity

- packages/pagination/src/Pagination.module.scss
https://cultureamp.slack.com/archives/C0189KBPM4Y/p1637035693120500
Based on the linked design feedback and currently what's in figma, we have changed the colour of the ellipses in `truncateIndicatorWrapper`.
Updates the color of ellipses to distinguish them from clickable pagination links.
> fix(pagination): Update ellipse color to purple 800, 70%

- packages/split-button/src/SplitButton/components/BaseButton/BaseButton.module.scss
When importing the new SplitButton component into murmur the CSS was failing to compile. 
We identified that the use of `font` was the cause of the issue. Instead, we are using the longwinded way of applying CSS fonts.
This fix allows murmur to import the package within the CSS failing to compile.
Jira Ticket: https://cultureamp.atlassian.net/browse/KDS-902
> fix(splitbutton): fixing font css for murmur

- draft-packages/form/KaizenDraft/Form/Primitives/InputSearch/InputSearch.tsx
- When user selects the clear button the focus does not return to the input
https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-611
- Add a ref to input and force focus back onto the input when the onClear has been called.
> fix(searchfield): update onClear to return focus to input

- packages/select/docs/FilterBarExample/DemographicValueSelect.tsx
- packages/select/docs/FilterMultiSelect.stories.tsx
- packages/select/src/FilterMultiSelect/components/MenuLayout/MenuLoadingSkeleton/MenuLoadingSkeleton.tsx
BREAKING CHANGE: FilterMultiSelect's loadingSkeleton prop no-longer accepts a variable with JSX. It must be a React Functional Component.
Changes MenuLoadingSkeleton to be a component, and make FilterMultiSelect's loadingSkeleton prop expect a component
For consistency with the way components are passed as props in other parts of the code base.
> fix(filter-multi-select): update MenuLoadingSkeleton to be a component

- packages/date-picker/src/TimeField/TimeField.module.scss
The `TimeField` input had a transparent background, causing issues when it renders on non-white backgroundds
Change the background of the input from `transparent` to white.
> style(timefield): swap transparent input background to white

- draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx
Some of our users are using older versions of safari which do not have the `addEventListener` method on `matchMedia`.
There is a deprecated `addListener` function, but I'm following what was established in `useMediaQueries` and stopping the effect from running, rather than supporting old browsers.
> fix: Ensure legacy safari and legacy edge users don't call missing methods

- draft-packages/menu/KaizenDraft/Menu/Menu.spec.tsx
- draft-packages/menu/KaizenDraft/Menu/Menu.tsx
- draft-packages/menu/KaizenDraft/Menu/StatelessMenu.tsx
The button within the Menu component was using the onClick to toggle open/closed the menu list. When a consumer of the component was setting their own onClick on the Menu button, it was being overridden and not actioned.
Refer to [KDS-963](https://cultureamp.atlassian.net/browse/KDS-963)
This change combines the onClick set by the consumer with the functionality of the Menu, enabling both onClick events to be actioned.
No visual changes have been made.
> fix(component): accept consumers onClick event for button within Menu

- package.json
- yarn.lock
Jest types needs to be re-upgraded.
Jest types from v27 -> v29
> chore(deps): upgrade jest types to v29

- draft-packages/select/KaizenDraft/Select/Select.module.scss
- draft-packages/select/KaizenDraft/Select/Select.tsx
- draft-packages/select/docs/Select.stories.tsx
- Allow the indicators to be selectable when the dropdown is open
- add z-index to indicators containers
> feat: allow indicators container to be clickable above select

- renovate.json5
We aren't moving to 18, so I added it to the ignore list.
#3087
We also don't use gatsby anymore.
Renovate ignore deps are updated
> chore(deps): remove gatsby dep from renovate ignore + add node to renovate ignore

- packages/select/docs/FilterMultiSelect.stories.tsx
- packages/select/src/FilterMultiSelect/components/SearchInput/SearchInput.tsx
- Add the ability to pass the isLoading state to the searchInput
- Add isLoading prop to `SearchInput` which uses the Kaizen `InputSearch` which has the loading spinner inbuilt
- Update the story to pull out the `isRefetching` boolean from `useInfiniteQuery` and pass to the `SearchInput`
- Check that the searchState is not `"" `and `isRefetching` to avoid displaying the loading spinner when the search is empty initially
> feat: add isLoading to SearchInput and story

- draft-packages/table/KaizenDraft/Table/Table.module.scss
- draft-packages/table/docs/Table.stories.tsx
Add background colour hover state to TableCard when a href or onClick prop is active.
[KDS-996](https://cultureamp.atlassian.net/browse/KDS-996)
The reports components project has a couple of instances in which a table row has a link with hover state. The screenshot attached shows the expected behaviour, a gray-100 background colour on hover.
> feat: On hover add a gray-100 background colour to TableCard with href or onClick.

- packages/select/src/FilterMultiSelect/components/ListBox/ListBox.module.scss
- packages/select/src/FilterMultiSelect/components/LoadMoreButton/LoadMoreButton.module.scss
- packages/select/src/FilterMultiSelect/components/SearchInput/SearchInput.module.scss
Adjusts some padding and margins inside the filter multi-select dropdown
More specifically:
* Adds the missing padding bottom to the listbox container
* Removes the margin bottom from the search field container (this was adding too much margin and not matching UI Kit)
* Removes the padding bottom from the "Load more" button for async multi-select (this is now covered by the listbox padding bottom mentioned above).
Fixes this issue where there's no padding at the bottom of the listbox
Also fixes this issue where a scroll bar will appear when selecting an item
> fix(FilterMultiSelect): Improve list box spacing

- packages/design-tokens/docs/pages/examples/themeManager.ts
This is something that had been causing a ts error when compiling with `yarn tsc` if you had a compiled /dist folder of the design-tokens. 
- updated the docs component example for themeManager to import for @kaizen/design-system instead of using local paths
> docs: update themeManager import to resolve tsc error

- draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.module.scss
Add z-index to Input pseudo states.
Separated this into its own PR so it can be released as a patch instead of a minor version.
While implementing FilterDRP with overlapping inputs, found that the underlying Input component needs some z-index applied to the pseudo states.
|WITHOUT|WITH|
|---|---|
|![image](https://user-images.githubusercontent.com/25891850/204933336-35514a49-7a48-450d-b573-f785b462b74d.png)|![image](https://user-images.githubusercontent.com/25891850/204933282-80b3a7b6-64d7-4276-b2ce-4156df5effef.png)|
> fix(input): add z-index to input pseudo styles

- draft-packages/select/KaizenDraft/Select/Select.module.scss
- When trying to click the "x" to remove one of the tags from the legacy multi-select, it does not remove it but opens the dropdown instead
- It does however work fine using the keyboard
https://user-images.githubusercontent.com/763385/205181669-3fc6513c-95c7-4849-89c9-ac89a385a003.mov
- I noticed that when trying to look at the `Tags` using the DevTools, it wouldn't select them, but the wrapping `div` they're in instead; I couldn't figure out exactly why, but somehow the rendering order is off, so I added a `z-index` to the `Tags` to get them to be rendered on the top level, which now allows the "x" remove button to be clicked
https://user-images.githubusercontent.com/763385/205181938-dfd59ef3-d65c-4165-838a-aa763f5b4b27.mov
> fix: Resolving clearing issue of legacy multi-select [KDS-1030]

- package.json
- yarn.lock
This isn't being used, and looking at [this PR where it was removed from our fops tooling](https://github.com/cultureamp/frontend-ops/pull/1138), it's not something that works for us.
> chore(deps): Remove unused typescript-plugin-css-modules dep

- package.json
- yarn.lock
Not being used, and TSLint has been deprecated since 2019
> chore(deps): Remove unused @typescript-eslint/eslint-plugin-tslint dep

- packages/select/docs/FilterBarExample/DemographicValueSelect.tsx
- packages/select/docs/FilterMultiSelect.stories.tsx
- packages/select/src/FilterMultiSelect/FilterMultiSelect.tsx
- packages/select/src/FilterMultiSelect/components/ListBox/ListBox.module.scss
- packages/select/src/FilterMultiSelect/components/ListBox/ListBox.tsx
- packages/select/src/FilterMultiSelect/components/NoResults/NoResults.module.scss
- packages/select/src/FilterMultiSelect/components/NoResults/NoResults.tsx
- packages/select/src/FilterMultiSelect/components/NoResults/index.ts
Creates a new `FilterMultiSelect.NoResults` component for showing a "No results found for [search term]" message inside the dropdown.
So that users get a confirmation that there's no results, rather than just getting an empty list and wondering if it's broken, or still loading, etc.
> feat: Add component for 'No results found' message

- draft-packages/collapsible/docs/SingleCollapsible.stories.tsx
This comes up every now and then. People want to put extra actions into the Collapsible heading. We have a story showing how to do a custom header with Collapsible, but it just has an Icon. I've adjusted that to have IconButtons showing how to do actions, most notably using `event.stopPropagation()` to avoid the additional action triggering the collapse behaviour.
> chore(docs): Adjust Collapsible custom header example to have IconButtons

- draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
- draft-packages/guidance-block/docs/GuidanceBlock.stories.tsx
- draft-packages/guidance-block/package.json
- yarn.lock
Team Home has a requirement to add an Early Access tag above the GuidanceBlock heading. Currently GuidanceBlock only allows for title and description text field. This limits our ability to add necessary markup to achieve the product vision.
By adding `content` prop for custom markup, consumers are able to better match design requirements to custom markup.
> feat(GuidanceBlock): Add content prop to allow for custom markup

- packages/date-picker/docs/Calendars.stories.tsx
- packages/date-picker/src/_subcomponents/Calendar/Calendar.module.scss
Remove disabled focus ring stories for Calendars.
Remove Calendar disabled focus ring styles.
[KDS-1062](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1062)
An update in `react-day-picker` changed the UX for disabled days to not be focusable via the keyboard. This was a feature to make it easier for users to not be stuck on disabled days without knowing where the next available day is.
- https://github.com/gpbl/react-day-picker/pull/1519
- https://github.com/gpbl/react-day-picker/issues/1449#issuecomment-1149942033
~~Keeping the styles around in the case the UX decision is reverted.~~
[KDS-1062]: https://cultureamp.atlassian.net/browse/KDS-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(date-picker): remove Calendar disabled focus ring styles

- packages/date-picker/docs/FilterDateRangePicker.stories.tsx
- packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.tsx
Expose `description` prop for FilterDRP.
[KDS-1100](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1100)
Allow consumers to add a custom description.
[KDS-1100]: https://cultureamp.atlassian.net/browse/KDS-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(date-picker): allow custom description for FilterDRP

- renovate.json5
Test fail for `stylelint-plugin` when upgrading stylelint to v14, https://github.com/cultureamp/kaizen-design-system/pull/3204
Seems our codemods aren't suited for v14
Lock our stylelint version to v13
> fix(deps): ignore stylelint upgrade

- packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.tsx
Component filterdaterangepicker `onRemove` prop function is not getting triggered as the internal wiring for the function is not in place
[Fix onRemove bug](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1674170621930549?thread_ts=1674105839.497259&cid=C0189KBPM4Y)
Wire function correctly
> fix(date-picker): fix function wiring to onRemove

- draft-packages/form/docs/Slider.stories.tsx
Elliot raised this a while back but the input in the controls was break the component when attempting to input new text.
- update story args type to allow for text input (in place of the ReactNode) to allow consumers to use the control input
> fix: update Slider story argTypes to allow text input

- draft-packages/form/docs/Slider.stories.tsx
- packages/component-library/components/Spacing/Base.module.scss
- packages/component-library/components/Spacing/util.ts
The value output for the 1.25 prop for the box component has incorrectly been rendering this as the `"0-point-25"` rem value.
- corrects the utili on ln18 to `"1-point-25"`
- remove dependence on the deprecated component lib helper for ca-grid
- cleans up and adds calc value on the sass calculations
> fix: update 1.25 padding prop to correct rem value

- packages/date-picker/docs/Calendars.stories.tsx
- packages/date-picker/src/_subcomponents/Calendar/Calendar.module.scss
bug: Global Selector not compilable by NextJS project
https://cultureamp.atlassian.net/browse/KDS-1160
~~fix: Change Global selector to be "accepted" by NextJS projects~~
Delete the global class and find another way to make the story work
> fix(date-picker): remove Calendar global class for dayToday

- packages/select/src/FilterMultiSelect/provider/SelectionProvider/SelectionProvider.spec.tsx
- packages/select/src/FilterMultiSelect/provider/SelectionProvider/SelectionProvider.tsx
- The filter remained within the options when open and closed but the SearchInput gets reset when unmounted.
https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-960
This JIra card number 2 on the list
- Match the normal filterMultiSelect UX and reset the filter when opened/first rendered
> feat: reset filter when open

- packages/select/src/FilterMultiSelect/components/ListBox/ListBox.module.scss
The listbox max-height had been updated when doing the Select rebuild
Match the Select ListBox styles
NEW:
OLD:
> feat: update max-height of filterSelect listbox

- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/index.ts
- draft-packages/title-block-zen/docs/TitleBlockZen.stories.module.scss
- draft-packages/title-block-zen/docs/TitleBlockZen.stories.tsx
to title block zen
Our team has a design to have a status Pill (Tag) in the section title area of the title block component.
See [discussion here](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1669611247289339).
This PR adds a render prop, that, if provided, renders the provided component in the space where the section title is normally rendered.  All relevant section title props are provided through the callback (`sectionTitle`, `sectionDescription`, and the `data-*` attributes).
This implementation was a tougher decision than I thought.  Initially, I was just going to change the `sectionTitle` prop type from a `string` to `ReactNode`.  The issue I came across was, if the `{sectionTitle}` section is rendered in a heading, which has style and accessibility implications.  
If we split …
> feat: add renderSectionTitle render prop

- docs/Systems/Tailwind/WorkingWithTailwind.stories.mdx
Makes more sense to order these sections by "degrees of modifying" in the "Working with Tailwind" readme.
- Moves "Altering Kaizen components" above "Creating bespoke components"
- Adds an index at the top
> docs(tailwind): reorder working with tailwind sections

- draft-packages/modal/KaizenDraft/Modal/Presets/ContextModal.module.scss
fix: add box-sizing:content-box to modal to prevent incorrect sizing in environments that use a border-box default
Murmur has a style rule of
`*, :before, :after { box-sizing: border-box; }` which breaks the modal's width calculations as it assumes a default of content-box.
I've added a default of content-box to the element with the width calculations.
> fix: add box-sizing:content-box to modal to prevent incorrect sizing in environments that use a border-box default

- draft-packages/form/KaizenDraft/Form/CheckboxGroup/CheckboxGroup.module.scss
- draft-packages/form/KaizenDraft/Form/RadioGroup/RadioGroup.module.scss
BREAKING CHANGE: Layouts that rely on a `max-width: 400px` checkbox or radio groups may be affected
The radio group has a css rule that all labels have a max-width of `400`.  Something like:
```
.radio-group {
label {
max-width: 400px;
}
}
```
This number seems arbitrary and we have needed to add special css overrides in our app in order to have full width radio buttons.
This change removes the max-width css rule.
We don't have any issues with the checkbox group, but I noticed that has a `width: 400px` css rule for the label.  I'm happy to remove that as part of this PR.
> feat: remove max-width in form groups

- packages/select/src/FilterMultiSelect/components/Trigger/RemovableFilterTrigger/RemovableFilterTrigger.tsx
Update component tooltip to match others filters tooltips as per:
https://github.com/cultureamp/kaizen-design-system/blob/main/packages/date-picker/src/FilterDateRangePicker/components/Trigger/RemovableFilterTriggerButton/RemovableFilterTriggerButton.tsx#L38
Ticket: https://cultureamp.atlassian.net/browse/KZN-962
Update tooltip interpolation
> fix(filtermultiselect): trigger button tooltip consistency

- packages/tailwind/src/kz-spacing.ts
6px is a spacing value that comes up a lot in designs.
Adds a 6px spacing token to the Tailwind package.
> feat(tailwind): Add spacing token for 6px/.375 rem

- packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.spec.tsx
The "resets the input values if cleared from the outside" test for the Filter DRP is throwing a timeout in CI. The test itself is functioning as expected but due to its asynchronous interaction with a complex component, it sometimes breaks in CI.
If this is a recurring issue In the future we may want to either revisit our CI to see if a larger agent will more reliably run this test or explore alternatives such as playwright.
- increases jest timeout to 10000
> fix: increase timeout for filter DRP long test

- packages/select/src/Select/Select.spec.tsx
- packages/select/src/Select/Select.tsx
- Only force focus when the `defaultOpen` is set
- useEffect was created as a solution to force the focus back to the button when defaultOpen was set
- Update useEffect within Select to only force focus after close when `defaultOpen` is true
> feat: Update the useEffect only trigger when defaultOpen

- packages/button/src/Button/components/GenericButton.spec.tsx
- packages/button/src/Button/components/GenericButton.tsx
When using the `component` prop of a button, we allow the user to render a custom component via render props. When we do so, we do not generate `customProps` that the link or regular button allow for.
Generate the customProps for the custom button, and pass them through to the custom Component function.
> fix: custom button now forwards custom props

- storybook/manager-head.html
Because we don't need it.
Removes a `<link>` to a stylesheet in manager-head.html that doesn't exist any more.
> fix(storybook css escape hatch): remove outdated css import

- packages/date-picker/docs/controls/validationControls.ts
- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.spec.tsx
- packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.tsx
- packages/date-picker/src/FilterDateRangePicker/components/DateRangeInputField/DateRangeInputField.tsx
- packages/date-picker/src/FilterDateRangePicker/hooks/useEndDateValidation.spec.tsx
- packages/date-picker/src/FilterDateRangePicker/hooks/useEndDateValidation.ts
- packages/date-picker/src/FilterDateRangePicker/hooks/useRangeDateValidation.spec.tsx
- packages/date-picker/src/FilterDateRangePicker/hooks/useRangeDateValidation.ts
- packages/date-picker/src/FilterDateRangePicker/hooks/useStartDateValidation.spec.tsx
- packages/date-picker/src/FilterDateRangePicker/hooks/useStartDateValidation.ts
- packages/date-picker/src/FilterDateRangePicker/types.ts
- packages/date-picker/src/FilterDateRangePicker/utils/getDateValidationHandler.spec.ts
- packages/date-picker/src/FilterDateRangePicker/utils/getDateValidationHandler.ts
- packages/date-picker/src/FilterDateRangePicker/utils/getNodeText.spec.tsx
- packages/date-picker/src/FilterDateRangePicker/utils/getNodeText.ts
- packages/date-picker/src/FilterDateRangePicker/utils/validateEndDateBeforeStartDate.spec.ts
- packages/date-picker/src/FilterDateRangePicker/utils/validateEndDateBeforeStartDate.ts
- packages/date-picker/src/hooks/useDateInputHandlers.spec.tsx
- packages/date-picker/src/hooks/useDateInputHandlers.ts
- packages/date-picker/src/types.ts
- packages/date-picker/src/utils/validateDate.spec.ts
- packages/date-picker/src/utils/validateDate.ts
Add inbuilt validation for FilterDateRangePicker.
Uses existing `validateDate` util.
Adds additional validation for checking whether End Date is before Start Date.
[KZN-397](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/491?modal=detail&selectedIssue=KZN-397)
[KZN-397]: https://cultureamp.atlassian.net/browse/KZN-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(filter-drp): add inbuilt validation

- packages/rich-text-editor/docs/EditableRichTextContent.stories.tsx
- packages/rich-text-editor/docs/RichTextEditor.stories.tsx
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.module.scss
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.spec.tsx
- packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
- packages/rich-text-editor/src/_mixins.scss
The object current returned on the RTE's `onChange` handler doesn't have all properties needed by some ProseMirror modules to content to/from other formats. Currently, the Performance team is using a different text editor, and saving the format as markdown. As a short term goal, we want to replace this editor with Kaizen's RTE and use a parser to convert to/from markdown, so that no BE and database changes are needed.
**Tasks**:
https://cultureamp.atlassian.net/browse/TX-48
**Solution preview**
https://cultureamp.atlassian.net/wiki/spaces/TV/pages/3066855433/Solution+preview+Use+Kaizen+Rich+Text+Editor+in+Performance
**Discussion:**
https://cultureamp.atlassian.net/browse/KZN-1068
**THIS IS A BREAKING CHANGE.** Instead of returning a content array, we are now returning the whole …
> feat: KZN-1068 - Expose rte internal state

- docs/Systems/Tailwind/UtilityClassReferences/Borders/BorderWidth.stories.tsx
- packages/tailwind/src/tailwind-presets.ts
We've decided that the clarity of adding w- to borderWidth isn't worth the busy utility classes. For example, border-b-w-default isn't as nice as border-b-default.
BREAKING CHANGE: Any border width utilities will need to be renamed without the `w-`. These include the following prefixes, where `?` represents a pixel-based spacing token.
`border-w-?`  -> `border-?`
`border-x-w-?` -> `border-x-?`
`border-y-w-?` -> `border-y-?`
`border-t-w-?` -> `border-t-?`
`border-b-w-?` -> `border-b-?`
`border-r-w-?` -> `border-r-?`
`border-l-w-?` -> `border-l-?`
Adding `w-` (to represent 'width') is redundant, considering that these only get applied to borderWidth anyway. The unnecessary clarity isn't worth the extra utility-class-bulk.
- Removes `w-` from borderWidth utilities.
- Adds an info card …
> fix(tailwind): remove w- from borderWidth utilities

- lerna.json
To be safe, we are ignoring the components package to test changesets
> chore: ignore components dir for testing

- .github/workflows/chromatic.yaml
- .github/workflows/ci.yml
The gh-actions bot that creates changeset PR's cannot trigger other gh actions, this change has the gh actions ignore the changeset PR
> chore: GH actions ignore changset PR's

- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.spec.tsx
- packages/rich-text-editor/src/EditableRichTextContent/EditableRichTextContent.tsx
- This PR is created to allow passing html attributes to `RichTextContent` component inside the `EditableRichTextContent`.
- This is required for adding id attribute to content div in `EditableRichTextContent`, with this we can use that id for accessible purposes. 
- Without this change if I just pass id to `EditableRichTextContent` and use that id for `aria-labelledby` it will read the button label as well when using voice over.
https://cultureamp.atlassian.net/browse/COMP-664
- Added a separate prop for passing the html attributes to `RichTextContent` inside `EditableRichTextContent`.
- This change does not effect any existing functionality.
> feat: Pass HTMLAttributes to content in EditableRichTextContent

- packages/component-library/icons/comment-bank.icon.svg
- packages/component-library/stories/Icons.ts
There’s a need by designer from team Compass for a comment-bank icon which is available in Figma but missing in the codebase. This will be used in the 1-on-1 tab in Dossier, refer [here](https://www.figma.com/file/CLx78YeFD7uauDot08bTgs/Amplify-%2F-1-1-save-to-dossier?node-id=15-36574&t=sarxE0xql99rdp5b-0) for more details: https://www.figma.com/file/CLx78YeFD7uauDot08bTgs/Amplify-%2F-1-1-save-to-dossier?node-id=15-36574&t=sarxE0xql99rdp5b-0
- Add a new comment-bank icon which is available in Figma but missing in the codebase
> feat: Add comment-bank icon

- packages/button/docs/Button.stories.tsx
- storybook/components/DocsContainer/ComponentDocsTemplate/subcomponents/Links/Links.tsx
- storybook/components/DocsContainer/ComponentDocsTemplate/subcomponents/Title/Title.tsx
Design guidelines is an important part of the docs, we want to make them more discoverable for anyone browsing our components.
- Added an extra link type to the header of docs
- Updated the styles and logic for rendering links
- Removed awkward space below heading
> add new design guideline links + styling

- .github/workflows/chromatic.yaml
We want chromatic to automatically run again when a branch is updated with code from `main`.
Removal of branch restriction on push event so that the job will detect pushes on all branches.
> Run chromatic when a PR is updated with changes from main

- locales/en.json
We have hard coded strings in FilterDRP that need to be translated. This source file will be picked up by translate bot to generate PRs with translated versions of the English source file.
Adds an English source file with three messages for the FilterDRP.
> feat: Add locales folder with English source file

- packages/button/docs/Button.stickersheet.stories.tsx
- packages/button/docs/Button.stories.tsx
- plop-templates/basic-component/docs/{{pascalCase componentName}}.stickersheet.stories.tsx.hbs
- Move stickersheets from category `Stickersheets` to `Components` and update plop template to reflect the change
- Also removed `Button Group` from the `Button` alternatives (this was accidentally merged in from testing)
Since we deploy only Docs to our site, Stickersheets (as long as they remain in their own file without the `autodocs` tag) can live under the `Components/{{ componentName }}` structure during dev :)
> docs: update stickersheets to live under Components category

- .buildkite/scripts/release.sh
- package.json
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
We want to publish the git tags of our released packages to allow people to find the code via our github repo page
Add `git push --follow-tags` to the ci:publish script, according to [instructions](https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#git-tags)
> update ci:publish script to include push of tags

- packages/components/src/FilterDateRangePicker/_docs/FilterDateRangePicker.stickersheet.stories.tsx
Update FilterDateRangePicker sticker sheet examples to use dates in the past.
"Today" has a different style, so the snapshots will change every day if the date is within the shown calendars.
> docs(filter-drp): update stickersheets to all have dates in the past

- package.json
- yarn.lock
Reverts cultureamp/kaizen-design-system#3366
`ttypescript` in `@kaizen/components` is not compatible with v5.
> Revert "chore(deps): update dependency typescript to v5"

- .changeset/metal-cameras-fly.md
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
The UI doesn't update if the if a selectedDay prop is returned after the component is rendered. This is a problem if data is returned async / from the server after render - as was the case for SR.
- Add selectedDay to the useEffect hook to ensure that this will trigger a rerender of the input if the selectedDay changes
- Add test coverage for this scenario
go to the Kaizen storybook (not this branch) and update the `selectedDay` control in the Datepicker story
> Date picker selectedDay fix

- .changeset/thin-trains-dress.md
- draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.spec.tsx
- draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.tsx
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
In the SR rebuild repo, the FieldMessage (as part of the date-picker) component was throwing ts error for `noUncheckedIndexedAccess`. To unblock this we're removing the capitalize function from the FieldMessage since it passes the status prop directly to the icon title (used for aria-label), which provides little value to screen readers.
- remove capitalize function
- pass status directly to the Icon title
> remove capitalize function and pass status directly to title

- .changeset/odd-cats-eat.md
- draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.spec.tsx
- draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
Needed to be able to override the h3 in Guidance block for Performance-UI to fix accessibility issues
https://cultureamp.atlassian.net/jira/software/c/projects/HOME/boards/387?modal=detail&selectedIssue=HOME-439
Added title tag to Guidanceblock to be able to override from a h3
> allow users to override the title tag in guidanceblock

- .changeset/sixty-ants-mix.md
- draft-packages/collapsible/KaizenDraft/ExpertAdviceCollapsible/ExpertAdviceCollapsible.spec.tsx
- draft-packages/collapsible/KaizenDraft/ExpertAdviceCollapsible/ExpertAdviceCollapsible.tsx
In a11y audit in develop, the following issue is raised:
Decorative image is not hidden from assistive technologies
The collective intelligence icon on an accordion is a decorative image, and is not hidden from assistive technologies. The icon has alt="Collective intelligence" applied.
Mark up the decorative icon with an empty alt attribute to hide them from screen reader users. This needs to be done using alt="" (empty string).
> fix: ensure alt is empty string to hide from screen reader

- .changeset/thin-countries-travel.md
- packages/component-library/styles/animations/_settings.scss
Certain animations require motion-ui's default settings which haven't been added
Copied over motion-ui's settings: https://github.com/foundation/motion-ui/blob/cd1070ec5024b1a36dced76c88717cf8d7a8b99c/src/_settings.scss#LL49C1-L62C12
> KDS-1447-add-missing-motion-ui-settings

- .changeset/nice-taxis-sell.md
- packages/select/docs/MenuLoadingSkeleton.stories.tsx
- packages/select/src/FilterMultiSelect/components/MenuLayout/MenuLoadingSkeleton/MenuLoadingSkeleton.tsx
We are requiring the loading state here in
https://cultureamp.atlassian.net/browse/COSE-1367
and noticed that is can't currently be animated.
This was a simple need of passing the prop in
Add the isAnimated prop to animate the loading skeleton
> Add isAnimated prop to MenuLoadingSkeleton

- .changeset/friendly-planets-design.md
- packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss
- Current Select doesn't set background color unless hovered or focused; when placed on non-white background this could potentially be an issue (e.g. color contrast)
- Set BG to white for non-reversed variant
- Doesn't address any problems of label or description not meeting color contrast guidelines (as there is no background to be set)
> fix(Select): Set background color to white by default [KDS-1449]

- .changeset/yellow-clocks-jam.md
- packages/rich-text-editor/src/RichTextEditor/components/Toolbar/Toolbar.tsx
Using multiple RTE and testing with storybook a11y detected non-unique ids on the toolbar buttons.
https://cultureamp.atlassian.net/browse/KDS-1450
- Removed ids from toolbar buttons
> fix: multiple RTE usage a11y issues

- draft-packages/popover/KaizenDraft/Popover/Popover.module.scss
- draft-packages/table/KaizenDraft/Table/Table.module.scss
- packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss
Got further build errors with the select component. 
- Changed all rgb functions with 4 args into rgba (Sylelint cannot enforce this correctly)
- Changed all alpha values to numbers only (Sylelint cannot enforce this correctly)
> fix: rgb functions allow 3 arguments only

- .changeset/six-poets-learn.md
- draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.tsx
- draft-packages/collapsible/KaizenDraft/ExpertAdviceCollapsible/ExpertAdviceCollapsible.spec.tsx
This toggle button for Collapsible's has a built in label of "Toggle section".
The problem with this is that when a screen reader user scans the page's buttons, these don't have the context that would help them.
Use the Collapsible title as a better accessible label for toggling the collapsible, rather than a generic built in "Toggle section" string.
> Use Collapsible title as toggle button accessible label

- .changeset/wicked-points-retire.md
- .stylelintrc.json
- draft-packages/popover/KaizenDraft/Popover/Popover.module.scss
- draft-packages/table/KaizenDraft/Table/Table.module.scss
- packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss
This PR converts the rgba percentage value to an opacity value.
Fixes [KDS-1457](https://cultureamp.atlassian.net/browse/KDS-1457).
The rgba percentage value was not valid and caused the browser to convert the RGBA value to HEX.
Before
After
[KDS-1457]: https://cultureamp.atlassian.net/browse/KDS-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: convert rgba percentage value to opacity value

- .changeset/lemon-cobras-unite.md
- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/utils/parseDateAsTextOrNumeral.spec.ts
- packages/date-picker/src/utils/parseDateAsTextOrNumeral.ts
- When entering or picking a (valid) date, the date picker would still mark it as invalid
- This was introduced when we fixed the ability to change/set the current day after render
- Error happens because it tries to parse a "text" date (eg. "1 May 2023") as a "numeral" date (eg. "01/05/2023")
- Hence the logic now tries both approaches to parse the string into a valid date
*Important:* This is just a quick patch to make things work again. This bug highlights the need for a bigger refactor (for many of our form/filter components) to properly accept a "default (starting) value" and also be able to be reset from the outside again.
> fix(DatePicker): Fixes regression in DatePicker validation

- .changeset/stupid-rules-love.md
- draft-packages/avatar/package.json
- draft-packages/collapsible/package.json
- draft-packages/filter-menu-button/package.json
- draft-packages/form/package.json
- draft-packages/guidance-block/package.json
- draft-packages/illustration/package.json
- draft-packages/likert-scale-legacy/package.json
- draft-packages/menu/package.json
- draft-packages/modal/package.json
- draft-packages/popover/package.json
- draft-packages/select/package.json
- draft-packages/table/package.json
- draft-packages/tabs/package.json
- draft-packages/tag/package.json
- draft-packages/tile/package.json
- draft-packages/title-block-zen/package.json
- draft-packages/tooltip/package.json
- package.json
- packages/brand-moment/package.json
- packages/button/package.json
- packages/date-picker/package.json
- packages/notification/package.json
- packages/pagination/package.json
- packages/progress-bar/package.json
- packages/rich-text-editor/package.json
- packages/select/package.json
- packages/split-button/package.json
Consumers still seeing issues with `rgb` and token values going missing.
Bumped components which haven't been updated to use the latest patches for rgab to latest
> Update all components relying on component-library to latest

- .changeset/shiny-elephants-hang.md
- draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.module.scss
Recent updates to kaizen illustration has modified the markup adding a figure tag. This means that the targeting rules in EmptyState no longer apply causing the illustration to be too big.
Thread: https://cultureamp.slack.com/archives/C0189KBPM4Y/p1685336384933739
Update styling selector in EmptyState to take into account changes in illustration markup.
> fix(EmptyState): Apply illustration sizing rules

- packages/components/src/FilterButton/_docs/filter-buttons.mdx
- packages/components/src/KaizenProvider/_docs/KaizenProvider.mdx
- packages/components/src/Workflow/_docs/Workflow.mdx
- storybook/components/DocsContainer/ComponentDocsTemplate/subcomponents/Installation/Installation.tsx
- storybook/components/DocsContainer/ComponentDocsTemplate/subcomponents/Links/Links.tsx
- storybook/components/Installation/Installation.tsx
- storybook/components/Installation/index.ts
- storybook/components/ResourceLinks/ResourceLinks.module.scss
- storybook/components/ResourceLinks/ResourceLinks.tsx
- storybook/components/ResourceLinks/index.ts
- storybook/components/index.ts
Parts of the Storybook docs template such as Installation and Resource Links should be reusable between pages, but the components were tied to context for autodocs, so we were duplicating the code within MDX docs.
- Abstract the visuals for Installation and Resource Links to be able to use them within MDX, and update the template to use these components.
- Update the MDX files with the duplicate code to use the components.
> docs(storybook): add reusable SB docs components for mdx

- package.json
This was breaking the build of our storybook.
Prebuild was failing, cause it looked into node_modules found the compiled component-library. Normally it would work it’s way into the source directory, but was compiled to the wrong folder
https://cultureamp.slack.com/archives/C02NUQ27G56/p1685593697359189
- removes component-library as a root dependency
> Remove component library from the root package json

- .buildkite/pipeline.yaml
Sometimes publishing doesn't work and we need a way for humans to force a release without making a new version
Base the conditional that triggers a release on the branch name rather than the branch author.
> update release conditional

- .changeset/modern-icons-hammer.md
This is a PR to patch KAIO to trigger a re-release.
This was made necessary following us merging in a [release](https://github.com/cultureamp/kaizen-design-system/commit/16d22011b46befbb8f18aa42caeb824b2c3d77af) that failed its build, which caused versioning to [fail](https://buildkite.com/culture-amp/kaizen-design-system) on buildkite.
The root cause of this was the `component-library` package dependency in our root folders, which caused the prebuild to fail as the compiled component-library was found in our node_modules instead of within the source directory.
-  no changes
> add changeset to trigger re-release

- .changeset/wild-llamas-swim.md
- draft-packages/select/KaizenDraft/Select/Select.tsx
- draft-packages/select/package.json
Draft select's label was not linked to the react selects input field as there was no `id` and  `aria-labelledby`. 
This PR adds a `ID` to the label, and links this to the input field / select field using `aria-labelledby`
> Draft select: link label with select

- packages/components/src/FilterDatePicker/_docs/FilterDatePicker.stickersheet.stories.tsx
DatePicker's current date shifts every day, causing chromatic to take a new snapshot 
Place the default month in the past, so that the date never changes.
> set default month to the past in filterdatepicker stories to prevent chromatic changes

- .changeset/eleven-pears-pull.md
- packages/notification/src/_styles.scss
Potential fix for: https://github.com/cultureamp/kaizen-discourse/issues/92
The change allows the InlineNotification to be placed side by side with other elements, without taking up an excessive amount of space. Seeing as `width: auto` has the desired behaviour of fillling the available space created by the parent, there doesn't seem any advantage or reason to have `width: 100%` instead of `width: auto`.
There are no changes to existing stories in Chromatic, showing that this does not change the current behaviour (other than 2 changes in the date picker that look like flakes)
_note: for some reason I couldn't reopen https://github.com/cultureamp/kaizen-design-system/pull/3724, so I created this new PR._
> InlineNotification: change to `width: auto`

- .changeset/cold-ties-guess.md
- packages/button/docs/Button.stories.tsx
In the Kaizen Storybook, the button text reads "Sumbit". It should be "Submit".
This PR fixes the Submit typo.
> patch: Submit typo

- .changeset/chilled-baboons-compare.md
- draft-packages/tabs/KaizenDraft/Tabs/Tabs.tsx
- draft-packages/tabs/KaizenDraft/Tabs/__snapshots__/Tabs.spec.tsx.snap
Conveys the 'active' state that we see with styling to screen reader users.
Add `aria-current=page` to the active tab in draft-tabs
> draft-tabs: Add aria-current=page to active tab

- .github/workflows/chromatic.yaml
Drafts generally are very work in progress and shouldn't need to be verified until it's ready for review.
Add a condition to chromatic to ignore draft pull reuests.
> stop chromatic on draft pull requests

- .github/workflows/ci.yml
I think the yarn install for changesets check needs extra permissions, hard to tell if this will fix the issue until it hits `main`.
Edit: Seems PR's are fine without this now...? Only merge if it becomes a problem again soon...
> Add auth token to github packages

- .changeset/fuzzy-melons-try.md
- draft-packages/table/KaizenDraft/Table/Table.tsx
Expose the portalSelector prop for the Tooltip component being used within the TableHeaderRow. Enables consumers to override the location of the tooltip rendered for edge cases where the tooltip can be cut off due to conflicting styles
> feat: expose portalSelector for TableHeaderRow

- .changeset/nervous-dodos-battle.md
- draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.module.scss
Fixes https://github.com/cultureamp/kaizen-discourse/issues/76
Uses `visibility: hidden` on Title Block's MobileActions so that the contents are hidden from screen readers, and unavailable in the keyboard tab order while the menu is closed.
The reason I didn't use `display: none` instead is because there's an animation with this. When using `display: none`, the closing animation breaks. Using `visibility` meant that I could hide the contents of the menu at the same time as the animation finishes.
> Title block: stop title block mobile actions from receiving keyboard focus when menu is closed

- .changeset/brown-horses-cheat.md
- packages/components/src/FilterBar/FilterBar.module.scss
- packages/components/src/FilterBar/FilterBar.spec.tsx
- packages/components/src/FilterBar/FilterBar.tsx
- packages/components/src/FilterBar/_docs/FilterBar.mdx
- packages/components/src/FilterBar/context/FilterBarContext.tsx
- packages/components/src/FilterBar/context/reducer/filterBarStateReducer.spec.ts
- packages/components/src/FilterBar/context/reducer/filterBarStateReducer.ts
- packages/components/src/FilterBar/subcomponents/ClearAllButton/ClearAllButton.module.scss
- packages/components/src/FilterBar/subcomponents/ClearAllButton/ClearAllButton.tsx
- packages/components/src/FilterBar/subcomponents/ClearAllButton/index.ts
Add a Clear All button to the FilterBar.
All selected values are cleared, and any active removable filters are made inactive and moved into the Add Filters menu.
[KDS-1471](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1471)
[KDS-1471]: https://cultureamp.atlassian.net/browse/KDS-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(filter-bar): add Clear All button

- .changeset/smart-ties-happen.md
- packages/components/src/FilterBar/FilterBar.spec.tsx
- packages/components/src/FilterBar/context/FilterBarContext.tsx
- packages/components/src/FilterBar/context/reducer/filterBarStateReducer.spec.ts
- packages/components/src/FilterBar/context/reducer/filterBarStateReducer.ts
[KDS-1552](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1552)
Calling a dispatch action within a loop will re-render only once all executed :)
https://react.dev/learn/queueing-a-series-of-state-updates
Thanks @gyfchong 
Refactor FilterBar to loop through singular dispatch actions instead of having a separate batch action for the same result.
[KDS-1552]: https://cultureamp.atlassian.net/browse/KDS-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(filter-bar): replace batch dispatch actions with loop of singular

- .changeset/eight-socks-fly.md
- packages/components/future/package.json
The dist reference paths did not align to the outputs and we could not import components from the future folder.
```
{
"main": "../dist/__future__/index.js",
"module": "../dist/esm/__future__/index.js",
"types": "../dist/__future__/index.d.ts"
}
```
This is a small fix to update the paths to the `future.js` file in the esm and cjs folders, and the types pulled from `esm/dts/__future__`
- updates `@kaizen/components` future package.json
> update the future release /dist reference path in package.json

- .changeset/late-lobsters-know.md
- packages/components/package.json
- packages/components/rollup.config.mjs
- yarn.lock
Fixes an issue where `process is undefined` gets thrown whenever any KAIO component is used in non-next-template projects.
Makes node builtins external.
> test, no externals at all

- .changeset/five-spoons-hear.md
- packages/components/src/KaizenProvider/KaizenProvider.tsx
- packages/components/src/KaizenProvider/OptionalIntlProvider/OptionalIntlProvider.tsx
- packages/components/src/KaizenProvider/_docs/internationalization-in-kaizen.mdx
Puts the OptionalIntlProvider back in KaizenProvider
> Revert "Remove optional intl provider and update docs"

- .changeset/spicy-scissors-allow.md
- draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.tsx
- draft-packages/form/KaizenDraft/Form/TextField/TextField.spec.tsx
- draft-packages/form/docs/TextField.stories.tsx
InputType prop was always superseding the type prop because it was passed in with a default value, ie:
```
...
type = "text",
inputType = "text",
...
<Input
{...otherProps}
type={inputType || type}
/>
```
This would mean that no matter what `type` passed in, the `inputType` would remain the same.
- remove default value from `inputType` prop so it can be undefined
- This means `type` can be passed without defaulting to the `inputType` value
- Add test coverage to ensure TextField components have the correct type
- Update stories to use `type` instead of `inputType`
> add fix for inputType issue in TextField

- .buildkite/dockerfiles/publish.Dockerfile
- .buildkite/dockerfiles/release.Dockerfile
Issue was release to a dependency of awscli - cython in pYyaml. This PR aims to lock the version of cython temporarily till a fix is released
updates build and release script on recommendation in this [thread](https://github.com/aws/aws-cli/issues/8036#issuecomment-1638544754) - specifically [this comment](https://github.com/aws/aws-cli/issues/8036#issuecomment-1638679410) relating to support to Alpine users (us)
> update docker build files

- .stylelintrc.json
- packages/select/package.json
update stylelint rc following prettier v3 update
- adds rule to allow no space after : in scss variables on multi-line declarations
> update stylelint rc following prettier v3 update

- .changeset/metal-beers-reflect.md
- packages/components/src/FilterDatePicker/FilterDatePicker.playwright.spec.tsx
- packages/components/src/FilterDatePicker/FilterDatePicker.spec.tsx
- packages/components/src/FilterDatePicker/_docs/FilterDatePicker.stories.tsx
- packages/components/src/FilterDatePicker/hooks/useDateInputHandlers.spec.ts
- packages/components/src/FilterDatePicker/hooks/useDateInputHandlers.ts
- packages/components/src/FilterDatePicker/subcomponents/FilterDatePickerField/FilterDatePickerField.spec.tsx
- packages/components/src/FilterDatePicker/subcomponents/FilterDatePickerField/FilterDatePickerField.tsx
- packages/components/src/FilterDatePicker/subcomponents/FilterDatePickerField/filterDatePickerFieldReducer.tsx
- packages/components/src/FilterDateRangePicker/subcomponents/FilterDateRangePickerField/FilterDateRangePickerField.tsx
- packages/date-picker/src/hooks/useDateInputHandlers.spec.ts
- packages/date-picker/src/hooks/useDateInputHandlers.ts
[KDS-1621](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1621)
Team Pathfinder reported that the popover closed when attempting to navigate months after having selected a value.
After investigation, it was actually found to be due to the blur event of the input when a valid date exists.
- Fix the logic so that the popover only closes when submitting a value.
- Add more tests
- Move `useDateInputHandlers` from `@kaizen/date-picker` to KAIO as the only usages of it are within KAIO (to prevent needing a release for date-picker for this fix)
[KDS-1621]: https://cultureamp.atlassian.net/browse/KDS-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(filter-date-picker): only close popover when submitting value

- .changeset/gold-rings-remember.md
- packages/components/src/FilterSelect/FilterSelect.module.scss
- packages/components/src/FilterSelect/_docs/FilterSelect.mdx
- packages/components/src/FilterSelect/_docs/FilterSelect.stickersheet.stories.tsx
[KDS-1635](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1635)
The popover width has been set to an arbitrary value of 224px. No one really knows why.
Update it to be more flexible as per https://www.figma.com/file/hANEprZKom5Br1IBXhE8mr/%F0%9F%A7%AA-Kaizen-Labs?type=design&node-id=28873-184759&mode=design&t=tLDLiMNpxcYRO1wI-0
- Update FilterSelect to have width range 196px-400px (rem equivalent)
- Add extra examples to stickersheet
- Expose stickersheet in docs (rewriting would take too long, so this is the quicker option)
[KDS-1635]: https://cultureamp.atlassian.net/browse/KDS-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(filter-select): change the popover width to be more flexible

- .changeset/shaggy-carrots-rest.md
- packages/components/src/FilterMultiSelect/subcomponents/Trigger/RemovableFilterTrigger/RemovableFilterTrigger.tsx
- packages/select/src/FilterMultiSelect/components/Trigger/RemovableFilterTrigger/RemovableFilterTrigger.tsx
[KDS-1658](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1658)
Applying `classNameOverride` only applied to the trigger button as opposed to the button as a whole.
Move `classNameOverride` to container of removable button for FilterMultiSelect (kaizen/select and KAIO)
[KDS-1658]: https://cultureamp.atlassian.net/browse/KDS-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(filter-ms): move classNameOverride to removable button container

- .github/workflows/check-files.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Allow the whole team to do releases.
Update required CI workflows to run but skip all steps on the release branch.
> ci: run and skip workflows on release branch automerge

- .github/workflows/changeset.yaml
We need to manually push tags for our published packages.
> add push tags

- .github/workflows/test-stories.yaml
Weird edge case where if your chromatic ci step has previously built and passed all tests, and you close/re-open your branch, it will skip the publishing of chromatic (since nothing has changed) causing the subsequent test steps to fail
Remove the "reopened" type of pull request event
> Skip running chromatic flow again on reopen of PR

- .github/workflows/canary-release.yml
Since the switch to changeset we have not had a release strategy for canary's and relied on yalc to test new release features in consuming repos. This PR aims to adopt the [Front Ops canary release workflow
](https://github.com/cultureamp/frontend-ops/blob/master/.github/workflows/release.yml) tailored to our environments.
- adds a canary release workflow
> add canary release workflow

- .github/actions/playwright/action.yml
- .github/workflows/test-stories.yaml
Sometimes the Playwright install step lags for many minutes, which causes the storybook tests to timeout (eg. https://github.com/cultureamp/kaizen-design-system/actions/runs/5745672429/job/15574123956?pr=3948)
Cache the Playwright binary to try and stabilise the workflows.
The speed seems to be slower given the need to search through cache first, but perhaps it's more stable?
|With cache|Without cache|
|---|---|
|![image](https://github.com/cultureamp/kaizen-design-system/assets/25891850/509d6443-3b49-47c9-bc1a-7ef59a491168)|![image](https://github.com/cultureamp/kaizen-design-system/assets/25891850/31f03ee6-cf11-4496-8ffa-f4e3511a3a32)|
> ci: set up cache for playwright

- .github/workflows/canary-release.yml
Some minor tweaks to the canary workflow just to clean up the build logs, prefix the release with `canary` and push the tags 
- updates canary-release.yml
> add canary prefix, push tags and clean up steps

- .changeset/eighty-monkeys-beam.md
- draft-packages/table/KaizenDraft/Table/Table.spec.tsx
- draft-packages/table/KaizenDraft/Table/Table.tsx
All of our examples of how to compose a Table with our components (and all of the usages that exist out there now) do something like this (noting the placement of `TableHeaderRow`):
Which creates mark up like this
```
<div role="table">
<div role="rowgroup">
<div role="rowheader">
<div role="columnheader" />
<div role="columnheader" />
<div role="columnheader" />
</div>
</div>
</div>
```
If you look at [documentation for role=rowheader](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowheader_role), this is not how the role is meant to be used. It's basically a `<th scope="row">`, whereas it's being used as a `<tr>`. 
The way `TableHeaderRow` is being used, the correct role is just "row". There doesn't appear to be such a thing as a `<tr>` that's header specific.
* …
> Fix incorrect usage of role=rowheader in TableHeaderRow

- .changeset/chilled-beans-retire.md
- packages/components/src/FilterBar/FilterBar.spec.tsx
- packages/components/src/FilterBar/_docs/FilterBar.mdx
- packages/components/src/FilterBar/_docs/FilterBar.stories.tsx
- packages/components/src/FilterBar/context/FilterBarContext.tsx
- packages/components/src/FilterBar/context/reducer/filterBarStateReducer.spec.ts
- packages/components/src/FilterBar/context/reducer/filterBarStateReducer.ts
- packages/components/src/FilterBar/context/reducer/setupFilterBarState.spec.tsx
- packages/components/src/FilterBar/context/reducer/setupFilterBarState.ts
- packages/components/src/FilterBar/context/reducer/updateSingleFilter.spec.ts
- packages/components/src/FilterBar/context/reducer/updateValues.spec.ts
- packages/components/src/FilterBar/context/reducer/updateValues.ts
- packages/components/src/FilterBar/context/types.ts
- packages/components/src/FilterBar/context/utils/checkShouldUpdateValues.spec.ts
- packages/components/src/FilterBar/context/utils/checkShouldUpdateValues.ts
- packages/components/src/FilterBar/context/utils/getInactiveFilters.spec.ts
- packages/components/src/FilterBar/context/utils/getIsUsableWhenArgs.spec.ts
- packages/components/src/FilterBar/context/utils/getIsUsableWhenArgs.ts
- packages/components/src/FilterBar/context/utils/updateDependentFilters.spec.ts
- packages/components/src/FilterBar/context/utils/updateDependentFilters.ts
- packages/components/src/FilterBar/subcomponents/FilterBarDatePicker/FilterBarDatePicker.tsx
- packages/components/src/FilterBar/subcomponents/FilterBarDateRangePicker/FilterBarDateRangePicker.tsx
- packages/components/src/FilterBar/subcomponents/FilterBarMultiSelect/FilterBarMultiSelect.tsx
- packages/components/src/FilterBar/subcomponents/FilterBarSelect/FilterBarSelect.tsx
[KDS-1474](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1474)
Pathfinder have a use case where they want to open a DateRangePicker when they select a custom value from a Select.
- Prevent infinite loop when calling `toggleOpenFilter` from selecting a value.
- Deprecate `toggleOpenFilter`, and replace with `setFilterOpenState` for clearer function intent.
- Add context util `openFilter` for consumers to be able to open a filter through an event from another filter.
[KDS-1474]: https://cultureamp.atlassian.net/browse/KDS-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(filter-bar): allow consumer to open a filter from another filter's action

- .github/workflows/changeset.yaml
Github Actions have been trying to push tags despite not needing to
Only push the git tags if there's been a publish
> ci(release): added condition to check if publish is true before pushing tags

- .changeset/dull-donuts-promise.md
- .changeset/nine-jobs-rush.md
- .github/workflows/changeset.yaml
So that we only get notified when changesets starts to publish.
Using the outputs of changesets action we detect if there's a changeset, if there isn't then we can assume that this is the publishing action, and if the published status is`true`, then we are successful.
> Fix-published-flag

- .changeset/big-tools-sneeze.md
- packages/components/package.json
- yarn.lock
performance-review-cycles-ui's build was failing after upgrading to @cultureamp/i18n-react-intl 2.0, because of a version mismatch between that direct dependency and the version 1.7.0 used by @kaizen/components.
Slack discussion:
https://cultureamp.slack.com/archives/C05D8BD1CB1/p1694578905096639?thread_ts=1694494680.865279&cid=C05D8BD1CB1
In order to allow consuming projects to bring their own version of @cultureamp/i18n-react-intl, this moves the package to peerDependencies, and adds it to devDependencies for use while working on this package locally.
> Move @cultureamp/i18n-react-intl to peerDeps

- .changeset/afraid-knives-approve.md
- packages/components/package.json
Fixes this same issue detailed here: https://github.com/ng-select/ng-select/issues/1717
Kaizen CSS was being tree-shaken by Webpack as it is part of a package marked with no side effects and our styles are imported via JS yet not directly used. This fix adds our styles to the side effects parameter to prevent webpack from shaking it out.
> KDS-1868 add styles.css to sideeffects

- .changeset/cool-spies-mix.md
- packages/components/assets/svgs/icons/close.icon.svg
- packages/components/src/Icon/CloseIcon.tsx
- packages/components/src/Icon/_docs/Icon.stickersheet.stories.tsx
- packages/components/svgoUtils.js
`CloseIcon` does not inherit colour.
- Update stickersheet for Icon to show colour inheritance
- Update icon script to also replace Purple 800 hex (as UI Kit stores them as such - easier moving forward)
- Regenerate `CloseIcon`
- Note: There are some other icons which are broken, but will fix them separately as they have other issues (eg. doesn't exist in UI Kit or has a complex svg)
> fix: update CloseIcon to be able to inherit color

- .changeset/wise-rivers-begin.md
- packages/components/src/ErrorPage/hooks/useErrorMessages.ts
This PR fixes a typo on the Kaizen 404 Error Page.
Fixes the typo "fing" instead of "find".
> fix(ErrorPage): 404 fing typo

- .changeset/old-kangaroos-wonder.md
- packages/components/src/TitleBlockZen/index.ts
This PR adds the TitleBlock types file to index so that barreling will work for types.
With this change, TitleBlockProps will now be accessible.
[KDS-1968](https://cultureamp.atlassian.net/browse/KDS-1968).
[KDS-1968]: https://cultureamp.atlassian.net/browse/KDS-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add the TitleBlock types file to index

- .changeset/long-wombats-provide.md
- packages/components/src/__future__/Select/Select.spec.tsx
- packages/components/src/__future__/Select/Select.tsx
From the code comment I wrote:
react-aria/useSelect wants to prefix the combobox's accessible name with the value of the select.
We use role=combobox, meaning screen readers will read the value.
So we're modifying the `aria-labelledby` property to remove the value element id.
Issue: https://github.com/adobe/react-spectrum/issues/4091
> Remove value prefix on Select combobox accessible name

- .buildkite/pipeline.yaml
This aims to stop all buildkite builds and publishing if a merge to the main brain does not have a release tag
- adds a conditional in the Buildkite steps to check for the existance of a tag and that it is in release format, ie: `blah@12.3.4`
- Theoretically this means that it should fail on the initial step, which should early exit of the pipeline
- This also mean we don't have to supply any more information since all releases should have tags (hopefully!)
> Add conditional check for release tag in Buildkite pipeline

- .buildkite/pipeline.yaml
Reverting this because it was breaking the pipeline and I'm exploring an alternative method using github labels
- reverts pipeline.yml to original state
> Revert Buildkite pipeline changes

- .buildkite/scripts/check-build-for-publish.sh
Testing if updating the pipeline yml will reflect in buildkite
- adds basic shell script to check for labels
> ci(buildkite): update shell script

- .buildkite/pipeline.yaml
- .buildkite/scripts/check-build-for-publish.sh
- docker-compose.yml
While the step may still not continue, this update is to handle when jq is unable to find the label property
- adds try catch and handle failed exit conditions with feedback
> Update bk shell script to catch and handle errors

- .buildkite/pipeline.yaml
- .buildkite/scripts/check-build-for-publish.sh
- docker-compose.yml
Need some way to allow for the BK script to exit gracefully since a lot of failed builds would mess out our stability metrics.
- allows for soft fail on the label check
- add test step to validation using an env var to skip steps
> Allow a soft fail on the bk shell script

- .changeset/honest-weeks-sniff.md
- packages/components/src/Select/Select.module.scss
- packages/components/src/Select/_docs/Select.stickersheet.stories.tsx
- packages/components/src/Select/_docs/Select.stories.tsx
Team Athena is using the Select component in Anytime Feedback. We are running the storybook tests and are addressing all accessibility issues that are raised. The Select had a placeholder opacity of 0.5 (whereas other placeholders were 0.7 in Kaizen) and this was failing the minimum contrast rule.
We've not been able to override this using react-select properties as it's overridden by these styles from what I can see.
1. Change placeholder opacity from 0.5 to 0.7
2. Remove override of a11y test as it should now pass the rule
> Increase opacity on placeholder in Select

- .changeset/honest-ties-admire.md
- packages/components/src/RichTextEditor/RichTextEditor/RichTextEditor.spec.tsx
- packages/components/src/RichTextEditor/RichTextEditor/RichTextEditor.tsx
The `aria-describedby` was being put on the container div instead of the textbox element, meaning screen readers will not have the descriptions announced.
Port of this fix on legacy: https://github.com/cultureamp/kaizen-legacy/pull/55
> fix(RTE): Move aria-describedby to textbox element

- .changeset/beige-cups-hug.md
- packages/components/src/MultiSelect/subcomponents/Popover/Popover.module.scss
Having this styling on `:focus` means we get this happening:
https://github.com/cultureamp/kaizen-design-system/assets/1811583/cb748bbb-1f07-4547-9808-b82c88dc7f75
Switching to `:focus-visible`, we still lose focus on the checkbox on mouse down for some reason (happens on our regular CheckboxField as well) but at least it's no longer as obviously janky.
Focus rings are ideally only set on `:focus-visible` as well anyway.
> fix(MultiSelect Popover): Use :focus-visible instead of :focus for focus ring

- .changeset/stupid-apples-sneeze.md
- packages/components/src/Illustration/subcomponents/VideoPlayer/VideoPlayer.spec.tsx
- packages/components/src/Illustration/subcomponents/VideoPlayer/VideoPlayer.tsx
- packages/components/src/Illustration/subcomponents/VideoPlayer/__snapshots__/VideoPlayer.spec.tsx.snap
When using the Illustration component either directly or through another component (BrandMoment for instance), you will receive a hydration warning in the console:
Without this fix, every consumer that uses a component with VideoPlayer in it needs to dynamically import it into their Next.js app and disable prerendering for it.
This PR moves the source element logic into a `useEffect` so we can ensure that it only runs once on the client - thus keeping the server HTML and initial client render consistent.
I encountered an issue with updating the inline snapshots as that feature is no longer compatible with prettier 3.0. I have converted these to external snapshots after [confirming with the DS team.](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1702857404345209)
Tested it fixed the …
> Fix SSR hydration warning when using Illustration

- .changeset/silly-snails-drive.md
- packages/components/src/Tabs/subcomponents/TabList.tsx
`TabList` was accepting a `classNameOverride` prop but it wasn't actually doing anything.
> Fix TabList classNameOverride usage

- .changeset/pink-donkeys-crash.md
- packages/components/src/TitleBlockZen/_docs/TitleBlockZen.stories.tsx
- packages/components/src/TitleBlockZen/subcomponents/MainActions.tsx
- packages/components/src/TitleBlockZen/subcomponents/MobileActions.spec.tsx
- packages/components/src/TitleBlockZen/subcomponents/MobileActions.tsx
- packages/components/src/TitleBlockZen/subcomponents/TitleBlockMenuItem.tsx
- packages/components/src/TitleBlockZen/types.ts
- packages/components/src/TitleBlockZen/utils.ts
Bit of a confusing mess here in typical TitleBlockZen fashion:
We had 2x `TitleBlockMenuItemProps` type definitions being exported, one which had an old and required `action` prop.
I've consolidated those into one (living in types.ts) and cleaned up any remnants of the old `action` prop in stories.
> Clean up remnants of TitleBlock's action prop on menu items

- .buildkite/dockerfiles/publish.Dockerfile
Alpine was updated in a dep refresh and subsequently broke the build.
We then tried updating python: https://github.com/cultureamp/kaizen-design-system/pull/4421
and then removing things from the pip install: https://github.com/cultureamp/kaizen-design-system/pull/4423 
but they still failed, so we're reverting everything here.
> Revert alpine update

- .changeset/ten-cycles-approve.md
- packages/components/src/ToggleSwitch/ToggleSwitch/ToggleSwitch.tsx
Bug identified where ToggleSwitch CheckIcon stayed visible regardless of true/false state of toggle - due to missing className.
Addressed this to keep ToggleSwitch behaviour inline with preKAIO component.
Added className to component - checkIcon now appears when ToggleSwitch set to true, fades when ToggleSwitch set to false.
> fix: add className to checkIcon

- .changeset/blue-seals-argue.md
- packages/components/src/TimeField/TimeField.module.scss
- packages/components/src/TimeField/TimeField.tsx
There is currently an issue with aria-describedby and FieldMessage, this PR add a conditional to only add the "aria-describedby" if there is a `FieldMessage`
Also updated Label for consistency
> Timefield label and accessibility fix

- .github/workflows/test-stories.yaml
- package.json
Branch preview uses Chromatic, but we were not providing Docs in the build, therefore we only see stories.
Separate the build for SB tests (stories only) and Chromatic (stories + docs).
> ci: separate SB build for chromatic

- .changeset/fluffy-spies-thank.md
- packages/components/src/Modal/GenericModal/GenericModal.tsx
There is a bug when modal is unmounted (e.g. navigation, parent unmounted) after onConfirm, the unscrollable style remains which stops user from scrolling unless refresh.
Include the clean up code in onAfterLeave to a useEffect's return block.
Before
https://github.com/cultureamp/kaizen-design-system/assets/8596435/4741bc9b-a7f4-44d2-94fa-32609ba72e70
After
https://github.com/cultureamp/kaizen-design-system/assets/8596435/3c398b56-d210-4696-bc38-9fc727140ba6
> fix: unscrollable style remains when modal is unmounted

- .changeset/few-seas-notice.md
- packages/components/locales/en.json
- packages/components/src/SplitButton/subcomponents/DropdownButton/DropdownButton.spec.tsx
- packages/components/src/SplitButton/subcomponents/DropdownButton/DropdownButton.tsx
The label "Open menu" doesn't do a good job of describing this button because:
- It doesn't give you any indication of what the menu holds or is for
- It remains as "_Open_ menu" even when the action would be to close the menu.
The `aria-haspopup` and `aria-expanded` attributes already cover communicating that this is a menu and whether it's open or not.
Change the aria-label on the dropdown button on SplitButton from "Open menu" to "More actions"
Also adds internationalisation while I was here.
> Improve SplitButton dropdown accessible label

- .changeset/nasty-zoos-roll.md
- package.json
- packages/components/src/Illustration/subcomponents/VideoPlayer/VideoPlayer.tsx
- pnpm-lock.yaml
- The helper to check for WebM relied on `window`, which was not available during the Next SRR cycle
- wraps the helper in a useEffect
> Update VideoPlayer component to be SSR friendly

- README.md
The previously-linked docs are obsolete.
Our new team members in Serbia are looking at possibly using some parts of Kaizen in their initial reskinning efforts. The setup instructions for GitHub Package Registry have been an initial stumbling block, as they reference outdated information from the node-packages repo.
Link to our current Confluence docs for setting up GitHub Package Registry.
> Update link to docs for GitHub Package Registry setup

- .changeset/odd-roses-punch.md
- packages/components/package.json
- packages/components/rollup.config.mjs
- pnpm-lock.yaml
As of release `1.42.3` the SplitButton styles have cause visual regression in consuming repos. This appears to have been caused by the recent update to the Rollup config, whereby the compile CSS is causing the BaseButton styles to override the DropdownButton. It appears that this may have been caused by the removal of rollup plugin`plugin-node-resolve`, which impact where in the cascade the styles are declared.
**@kaizen/components v1.42.3**
The `BaseButton` styles will supersede the `DropdownButton`
**@kaizen/components v1.42.1**
The `DropdownButton` styles will supersede the `BaseButton`
- Adds the resolve config back into rollup with a comment explaining why it is there... for now
[See thread](https://cultureamp.slack.com/archives/C02NUQ27G56/p1713157055178419)
> fix(SplitButton): Add node resolve back into the rollup config

- .changeset/ninety-gifts-run.md
- packages/components/src/TitleBlockZen/TitleBlockZen.module.scss
- packages/components/src/TitleBlockZen/_docs/TitleBlockZen.stories.tsx
The breadcrumbs was using the browser default `outline` property for focus styles.
This creates a contrast issue in Safari as the default outline is dark blue.
The focus ring will now high the back breadcrumb anchor on focus.
Note that this is slightly different to the hover state that underlines the text.  Give the text is a span and not actually focus-able I chose not to include a that style - see example below
- adds focus ring to breadcrumbs anchor and story coverage
> Fix TitleBlockZen breadcrumbs focus styles

- .changeset/rude-toes-tap.md
- packages/components/src/TitleBlockZen/subcomponents/NavigationTabs.module.scss
The active `NavigationTab` was obscured on Windows High Contrast Mode (WHCM). This makes it hard for the end user to determine the relationship with the active Tab.
- Use `forced-colors` media query to replace the background color in the tabs pseudo `after` element with a transparent border. This will now render on a user's page if high contrast mode is active.
While the focus state showed the active tab was obscured.
Behavior now matches the current tab experience but with the user's preferred color scheme in WHCM
> Fix TitleBlockZen active tab state on High Contrast

- .changeset/stupid-teachers-admire.md
- packages/components/src/Radio/Radio/Radio.module.scss
High contrast mode removes the selected state background color.
Adds a `forced-color` media query to fall back to a transparent border for the selected Icon that will render as a full circle
This screenshot is from a Windows machine.
> Fix Windows high contrast Radio select state issue

- .changeset/rotten-weeks-push.md
- packages/components/src/LikertScaleLegacy/LikertScaleLegacy.module.scss
- packages/components/src/LikertScaleLegacy/LikertScaleLegacy.tsx
- packages/components/src/LikertScaleLegacy/_docs/LikertScaleLegacy.stickersheet.stories.tsx
- packages/components/src/LikertScaleLegacy/types.ts
- storybook/components/StickerSheet/types.ts
We have some big customers threating to churn based them being unhappy with the red color used in the traditional LikertScale. 
This is an extension on the LikertScale so that we can render it in a blue version. 
The red/classical version is still the default one. *The change is backward compatible.*
> Create a blue variant for the Likert Scale

- .changeset/short-bears-train.md
- packages/components/src/Modal/ConfirmationModal/ConfirmationModal.tsx
- packages/components/src/Modal/ContextModal/ContextModal.tsx
- packages/components/src/Modal/GenericModal/GenericModal.tsx
- packages/components/src/Modal/GenericModal/_docs/GenericModal.spec.stories.tsx
- packages/components/src/Modal/InputEditModal/InputEditModal.tsx
- packages/components/src/Modal/InputEditModal/_docs/InputEditModal.mdx
- packages/components/src/Modal/InputEditModal/_docs/InputEditModal.stories.tsx
- packages/components/src/RichTextEditor/utils/plugins/LinkManager/components/LinkModal/LinkModal.tsx
This update to the modals is a more holistic way of addressing the issue raised by Will regarding the RTE's Link modal (see thread [here](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1713422268454219))
https://github.com/cultureamp/kaizen-design-system/assets/36558508/ebd5d18d-559f-4935-96bb-60bf5669b9c1
Initially, to resolve this we were going to intercept the onKeyDown event for a `paste` and shift focus to the input. This was more a monkey patch that a long term solution. Instead we opted to provide an `onAfterEnter` callback that is triggered when the Modal is opened.
The default behaviour that we have baked into our modals is to focus on the accessible title. This is to ensure that screen reader users have context to where there focus has been shifted. This guard rail still …
> Add onAfterEnter callback to Modals 

- .changeset/angry-ants-know.md
- packages/components/src/Button/IconButton/IconButton.tsx
In conversations-ui, we are using `Menu` `MenuItem` and `IconButton` for our meatball. This meatball allows user to switch to edit mode and once user have either decided to cancel or submit the edit, we want to return their focus back to the IconButton of the Menu
To enable the above, we are exposing the ref of IconButton so that we can focus on it
> Expose ref for IconButton

- .changeset/new-adults-rescue.md
- .changeset/tame-geckos-exercise.md
- packages/components/src/RichTextEditor/RichTextEditor/RichTextEditor.tsx
While reviewing a11y on RTE, I noticed a duplicate id issue, It was also difficult to target the RTE without being able to control the id, so I have added an optional id props to override the generated Id inside the RTE component, this will allow to use `describedBy` or `labelledBy` on components that are related to the RTE
- Fixed duplicate Id on RTE
- Added optional id prop
Before :
After :
> fix(RTE): duplicate id, added optional id

- .changeset/curvy-boxes-clap.md
- packages/components/tsconfig.json
- tsconfig.json
We made some changes to our tsconfig attempting to resolve TS errors including the `jest.setup`. This resulted in our distributed types being bundle incorrectly.
- update tsconfig to pull types from @testing-library/jest-dom instead of including our local `jest.setup` file
> Fix tsconfig types to resolve broken types build

- .buildkite/scripts/build-storybook.sh
- .changeset/late-dragons-switch.md
- .changeset/swift-stingrays-travel.md
- package.json
- packages/components/package.json
- packages/design-tokens/package.json
- packages/hosted-assets/package.json
- packages/package-bundler/CHANGELOG.md
- packages/package-bundler/package.json
- packages/package-bundler/src/presets/shared-ui/bin/postBuild.ts
- packages/tailwind/package.json
- turbo.json
We accidentally published a 2.0 instead of 1.0 for `package-bundler` and the publish script failed to bundle all the code, making `package-bundler` and  the latest `KAIO` unusable.
- Revert and publish `package-bunlder` to `1.0.0`
- Remove all `prepublishOnly` scripts
- Change the publishing process to use `build` instead
> Fix bundling and package version

- .changeset/flat-eyes-wash.md
- packages/components/src/EmptyState/EmptyState.tsx
Illustrations in Empty States have alt text at the moment, when `isAnimated` is false. It uses the string of the `mood` prop. e.g. `positive` or `action`.
We want these blank because they're decorative
> fix(EmptyState): Blank out alt text for illustrations in EmptyState

- .changeset/long-cheetahs-serve.md
- packages/components/src/Filter/FilterBar/subcomponents/FilterBarMultiSelect/FilterBarMultiSelect.tsx
[KZN-2441](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2441)
Perf have a requirement for overriding the shape of selected values where they wish to access the label in the parent `FilterBar` level prior to loading their full list of async options.
Update the props for `FilterBarMultiSelect` to allow the consumer to override default behaviour
- No functionality change as the spread props is already working - just addressing the TS error
[KZN-2441]: https://cultureamp.atlassian.net/browse/KZN-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FilterBarMultiSelect): allow consumer to override more props

- renovate.json5
Peer dependencies have been receiving renovate version bumps, even when we list the version as `>= {version}`.
As discussed with @gyfchong, our peer dep versions should be deliberate and allow for a broader range of compatible versions, and only bumped when it becomes incompatible.
Disable renovate for peer dependencies.
> ci(renovate): disable for peerDeps

- .changeset/heavy-humans-provide.md
- packages/components/locales/en.json
- packages/components/src/Filter/FilterMultiSelect/subcomponents/SearchInput/SearchInput.tsx
- packages/components/src/Input/InputSearch/InputSearch.tsx
[KZN-2449](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2449)
Support request. Customer noticed some strings in FilterMultiSelect were not translated.
Translate embedded text in:
- `FilterMultiSelect.SearchInput`
- `InputSearch`
[KZN-2449]: https://cultureamp.atlassian.net/browse/KZN-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: translate embedded text within FMS SearchInput

- .changeset/forty-games-battle.md
- packages/components/src/TitleBlockZen/TitleBlockZen.module.scss
- packages/components/src/TitleBlockZen/TitleBlockZen.tsx
- packages/components/src/TitleBlockZen/_docs/TitleBlockZen.stories.tsx
Update `TitleBlockZen`'s title font to match the composable header.
Match the font family of the composable header.
After discussion with Dave, removed breadcrumb breakpoint title font scaling given:
- We don't know the actual use case it was solving
- The change of font changes the width of the text - therefore may already be solving initial reason for it
- The breakpoint being at 1644 means most users never actually see the proper visual hierarchy, which isn't ideal
> feat(TitleBlockZen): update title font to match composable header

- .changeset/plenty-buses-fail.md
- packages/components/styles/foundation/_fonts.css
We were missing a declaration for our the font-face to support Tiempos at a font weight of 500.
Kaizen font faces are stored in the `kaizen-design-system-assets` repo under fonts.
- @HeartSquared and I caught up with Jess and confirmed that we currently only want to support Tiempos 500 and 800 font weights.
- If any more need to be added we will need to declare them in the `_fonts.css` in the `kaizen-design-system` repo 
- add Tiempos `tiempos-headline-medium` to kaizen support font weights
>  Update tiempos font face

- .changeset/sixty-rockets-nail.md
- packages/components/src/__future__/Workflow/subcomponents/Header/Header.tsx
As part of our accessibility review, we need to fix the Culture Amp logo https://cultureamp.atlassian.net/wiki/spaces/PA/pages/3684237362/Perform+create+cycle+v2+accessibility+review#%3Across_mark%3A-Images-have-alt-text-or-are-hidden-from-assistive-tech
- renamed "Cultureamp" to "Culture Amp"
> fix(workflow future): CA logo a11y

- .buildkite/scripts/publish.sh
Fixing an git command not found error in a script that publishes kaizen design website
> fix: git command not found

- .changeset/perfect-cougars-sip.md
- package.json
- packages/components/src/Calendar/CalendarRange/CalendarRange.tsx
- packages/components/src/Calendar/CalendarSingle/CalendarSingle.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/DatePicker/_docs/DatePicker.mdx
- packages/components/src/DatePicker/_docs/controls/datePickerLocaleControls.ts
- packages/components/src/DatePicker/_docs/getLocale.stickersheet.stories.tsx
- packages/components/src/DatePicker/utils/getLocale.spec.ts
- packages/components/src/DatePicker/utils/getLocale.ts
- packages/components/src/DateRangePicker/DateRangePicker.tsx
- packages/components/src/Filter/FilterDatePicker/_docs/FilterDatePicker.stickersheet.stories.tsx
[KZN-2486](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2486)
Extension of support request which added `fr-CA`
- Add all supported locales to `DatePicker`, `FilterDatePicker`, `FilterDateRangePicker`
- Update default locale object from `en-AU` to `en-GB`
- They are visually the same, but `en-AU` is not in [our list of locales](https://github.com/cultureamp/unified-home/blob/master/packages/i18n-react-intl/src/constants.ts#L62)
- Update `Calendar`s to infer starting weekday based on provided locale
[KZN-2486]: https://cultureamp.atlassian.net/browse/KZN-2486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add all supported locales to date components

- .changeset/selfish-ears-lick.md
- packages/components/src/Menu/subcomponents/MenuDropdown/MenuDropdown.tsx
Fixes an issue where there's multiple menus on a page, when closing a menu, the focus goes to a different menu button
React focus lock is getting confused about which trigger button to return focus to. It happens when focus is on one menu button when another one is opened, as shown in the video below.
https://github.com/user-attachments/assets/d48a68b7-9b39-4327-a08e-808d7043e89e
Override React focus lock's default focus return, hard coding to always return to the menu's trigger button.
> fix(Menu): Ensure focus returns to correct menu button on close

- .changeset/heavy-geese-live.md
- packages/components/src/Filter/FilterBar/_docs/FilterBar.stories.tsx
- packages/components/src/Filter/FilterBar/context/FilterBarContext.tsx
- packages/components/src/Filter/FilterBar/context/reducer/filterBarStateReducer.ts
- packages/components/src/Filter/FilterBar/context/utils/createFiltersHash.ts
Full context on issue can be found here: https://cultureamp.slack.com/archives/C0189KBPM4Y/p1720760726579179
Added a `update_filter_labels` action to the FilterBar reducer to fix the above
> FilterBar - update filter labels if they change

- .changeset/lazy-crabs-pay.md
- packages/components/src/Menu/_docs/MenuContentExample.tsx
- packages/components/src/Menu/subcomponents/MenuItem/MenuItem.tsx
No reason to block this, it's needed in some cases where you want to do something before navigating, like tracking. Best to still keep the element as a link in the DOM in this case.
Currently, `onClick` is not being passed through in the case that MenuItem has an `href` and renders a link
> fix(Menu): Pass onClick through even when rendered as a link

- .changeset/red-walls-add.md
- packages/components/src/__actions__/Menu/v3/MenuItem.module.scss
- packages/components/src/__actions__/Menu/v3/_docs/Menu.docs.stories.tsx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.stories.tsx
https://cultureamp.atlassian.net/browse/KZN-2531
Remove `outline` and add border colour for menu item focus.
Bonus: Use sentence case in story examples to follow our guidelines
> fix(Menu): Hide outline and use border for focus ring

- .changeset/bright-frogs-smile.md
- packages/components/src/Modal/GenericModal/GenericModal.module.scss
- packages/components/src/Modal/GenericModal/subcomponents/ModalAccessibleLabel/ModalAccessibleLabel.module.scss
Adjusting the focus styling when first opening a modal with a keyboard, to wrap the modal container instead of the title
Before:
After:
Looks nicer
> fix(Modal): Remove focus ring on title when focus-visible

- .changeset/heavy-teachers-occur.md
- packages/components/src/Icon/subcomponents/SVG/SVG.tsx
I accidentally merge this in with the Button v3 when I was exploring how to handle icons and RTL. I appear to have removed half of the logic so this is a redundant boolean prop that does nothing
- removes redundant prop
> remove flipOnRtl prop on SVG pirimitive

- .changeset/silver-shirts-decide.md
- packages/components/src/Avatar/Avatar.spec.tsx
- packages/components/src/Avatar/Avatar.tsx
It's fairly common to put an avatar next to someone's name. In these cases, we want the alt text to be blank, otherwise it ends up doubling up the same information.
E.g. this common usage in a MultiCombobox:
The only way that this can currently be achieved would be to blank out the `fullName` prop, but then you'd miss out on the initials feature.
Add an `alt` prop to the `Avatar` component so that consumers can have control of it separate from `fullName`.
> feat(Avatar): allow control over alt text

- .changeset/red-trees-bow.md
- packages/components/src/MultiSelect/MultiSelect.tsx
- packages/components/src/MultiSelect/subcomponents/Popover/Popover.tsx
- packages/components/src/__future__/Select/Select.spec.tsx
- packages/components/src/__future__/Select/Select.tsx
Future Select uses the MultiSelect's Popover component, which has role=dialog built in.
Select shouldn't have this, so I've moved the role=dialog stuff to the MultiSelect implementation of Popover only.
Had to adjust tests a bit because a few of them were written to expect the dialog element and in a specific place. Deleted one because it wouldn't be possible to test without a test id and wasn't super valuable.
> fix(Future Select): Remove role=dialog from listbox container

- .changeset/rude-lamps-brake.md
- packages/components/src/RichTextEditor/RichTextContent/RichTextContent.tsx
Don't need this attribute at all for this case where we're just displaying content.
Seems to be playing a role in a strange bug in the platform:
https://cultureamp.slack.com/archives/C02NUQ27G56/p1725336851040669
Remove the `contenteditable` attribute from the prosemirror container
> fix(RichTextContent): remove contenteditable attribute

- .changeset/chilly-weeks-judge.md
- packages/components/src/MultiSelect/subcomponents/Popover/Popover.module.scss
We've had two instances of people needing to add z-index to the select portal, because it's not always possible to put the portal in a place that will place it over the top of everything while also not having the page shift in position on open.
100000 matches the z-index that react-aria uses for its Popover, if/when we move to using that.
Add `z-index: 100000` to the Select/MultiSelect Popover
> fix(Select/MultiSelect): Add z-index 100000 to popover

- .changeset/long-impalas-repeat.md
- packages/design-tokens/package.json
- pnpm-lock.yaml
[KZN-2699](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2699)
Move `color-string` back to dependencies.
[KZN-2699]: https://cultureamp.atlassian.net/browse/KZN-2699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): move color-string back from devDeps to deps

- .changeset/twelve-pugs-whisper.md
- packages/components/src/Filter/FilterSelect/FilterSelect.spec.tsx
- packages/components/src/__future__/Select/Select.spec.tsx
- packages/components/src/__future__/Select/Select.tsx
- packages/components/src/__future__/Select/subcomponents/ListBox/ListBox.module.scss
- packages/components/src/__future__/Select/subcomponents/ListBox/ListBox.tsx
I was attempting to remove the page jump when the select is opened and found these focus management things that aren't needed and in some cases cause incorrect behaviour (e.g. pressing up arrow on the trigger was focusing the first item, should be the final item).
This has shown to cause no page jump in our storybook
Before:
https://github.com/user-attachments/assets/4cd87900-6ce9-4670-bdd1-385c772a7bf5
After:
https://github.com/user-attachments/assets/4796c5ac-f011-41e2-bd3d-28cdadb95e51
But when testing in one of our UIs via pnpm link, it was still jumping so I'm not confident that this has fixed that.
Either way, definitely still worth pushing this through.
- The main change: remove the autoFocus in the `useListBox` hook causing it to always focus the first item in the list
- This is …
> fix(Future Select): remove redundant focus management

- .changeset/eleven-taxis-cross.md
- package.json
- packages/package-bundler/package.json
- pnpm-lock.yaml
As part of https://cultureamp.atlassian.net/browse/FEF-1571 I am trying to clean up some of the dependencies in next-template, including resolving some peerDependency warnings.
One of those required `@cultureamp/package-bundler` to support `postcss-preset-env` v10 as well as v9. 
The release notes are here: https://github.com/csstools/postcss-plugins/wiki/PostCSS-Preset-Env-10
TLDR the breaking changes are:
- some subtle nesting changes that won't effect us in sass files
- dropping Node 16/17 support (which we dropped long ago)
So v10 is a perfectly fine version to allow with the bundler.
- allow v10 of postcss-preset-env
- also add some PNPM config to silence complaints from `react-textfit` and `@reach/*` about react versions (clearly the thing we need them for works with React 18, even …
> Tweak peer dependencies

- .changeset/popular-cherries-sparkle.md
- packages/components/src/__layout__/Workflow/v2/subcomponents/Footer/components/ProgressStepper/ProgressStepper.module.scss
- packages/components/src/__layout__/Workflow/v2/subcomponents/Footer/components/ProgressStepper/ProgressStepper.tsx
- packages/components/src/__layout__/Workflow/v3/subcomponents/Footer/components/ProgressStepper/ProgressStepper.module.css
- packages/components/src/__layout__/Workflow/v3/subcomponents/Footer/components/ProgressStepper/ProgressStepper.tsx
I've remove the Text component from the Progress stepper as a fix to the CSS layer issue that Baptise was experiencing with the Workflow v3. I think this is a relatively safe move since the stepper is more a visual artifact than text and just needed the a few tokens.
- replace Text usage with tokens
> ProgressStepper spacing margin fix 

- .changeset/late-icons-know.md
- packages/components/src/GuidanceBlock/GuidanceBlock.tsx
To facilitate accessibility patches where a team already has this component implemented
Allow aria props on GuidanceBlock actions
> Allow aria props on GuidanceBlock

- .changeset/silver-cougars-explain.md
- packages/components/src/Notification/InlineNotification/InlineNotification.tsx
Consistency with other components, somewhat common for people to want to pass something like `id`
Allow native div props on `InlineNotification`
> feat: Allow native div props on InlineNotification

- .changeset/popular-moons-sip.md
- packages/components/src/utils/useMediaQueries.tsx
Fixes a bug where the events wouldn't run if you jump straight from small viewport to large, or vice versa
Rather than just adding an event listener for the medium viewport, add one for small and large.
Putting this just on medium was an attempt to keep this as performant as possible, but unfortunately meant that the updates never trigger when bypassing the medium size.
> fix(useMediaQueries): Add event listeners to small and large instead of medium

- .changeset/gorgeous-cameras-repeat.md
- packages/components/src/ToggleSwitch/ToggleSwitch/ToggleSwitch.tsx
We override the ToggleSwitch `onToggle` prop with a `ChangeEvent`, but since we are not removing the default event from the HTMLInputElement as we extend it, typescript thinks the event expects either a `ChangeEvent` type or a `ToggleEvent` type.
Omit the `onToggle` event from the `ToggleSwitchProps`.
> fix: Remove ToggleSwitch default onToggle prop type

- .changeset/giant-ghosts-sniff.md
- packages/components/src/Brand/Brand.tsx
- packages/components/src/Workflow/subcomponents/Header/components/Branding/Branding.module.css
[KZN-2755](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2755)
Styles do not apply properly to Brand as the classes get added to the `picture` element (where they disappear) instead of `img`.
Need this to work to be able to proceed with Icon codemod (where `CaMonogramIcon` changes to use `Brand`).
Move `classNameOverride` and `style` to `img` element.
[KZN-2755]: https://cultureamp.atlassian.net/browse/KZN-2755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Brand): move styling props to img instead of picture

- .changeset/nasty-toys-raise.md
- packages/components/src/__future__/Select/_docs/Select.stories.tsx
- packages/components/src/__future__/Select/subcomponents/Option/Option.tsx
[KZN-2764](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2764)
~~Selecting an option that sits above other elements (eg. radios) propagates the events.
React Aria does not allow us access to `stopPropagation`.~~
On touch devices, there is an appearance of event propagation.
Testing with @mcwinter07 shows that it is closer to a visual race condition, where the closing of the select happens so fast that the device thinks it is also clicking on the area after it is closed.
~~Disable the RAC events that allow propagation, and re-simulate the selection manually.~~
Set a timeout for touch events to slow down the processing of events.
[KZN-2764]: https://cultureamp.atlassian.net/browse/KZN-2764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> fix(future/Select): stop propagation on touch devices

- .changeset/strange-scissors-peel.md
- packages/components/package.json
[KZN-2766](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2766)
Teams with a CJS set up have been seeing TypeScript errors as our explicit `"type": "module"` tells their TypeScript we are ESM, despite us actually building with both CJS/ESM compatibility.
Remove `"type": "module"`
[KZN-2766]: https://cultureamp.atlassian.net/browse/KZN-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(kaio): remove type module in package.json

- .changeset/twelve-goats-greet.md
- packages/components/src/Filter/FilterSelect/FilterSelect.tsx
This PR addresses the a11y issues that Kayd raised with the Filter Select - this was split from the PR that had to be reverted.
- remaps the id to draw the accessible label from the trigger
> Filter select aria label fix

- .changeset/many-plums-jam.md
- packages/components/src/Filter/FilterBar/FilterBar.spec.tsx
- packages/components/src/Filter/FilterBar/context/FilterBarContext.tsx
- packages/components/src/Filter/FilterBar/context/reducer/filterBarStateReducer.ts
- packages/components/src/Filter/FilterBar/context/reducer/setupFilterBarState.ts
- packages/components/src/Filter/FilterBar/context/types.ts
- packages/components/src/Filter/FilterBar/subcomponents/AddFiltersMenu/AddFiltersMenu.tsx
- packages/components/src/Filter/FilterBar/subcomponents/FilterBarButton/FilterBarButton.tsx
- packages/components/src/Filter/FilterBar/subcomponents/FilterBarMultiSelect/FilterBarMultiSelect.tsx
- packages/components/src/Filter/FilterMultiSelect/FilterMultiSelect.tsx
- packages/components/src/Filter/FilterMultiSelect/context/MenuTriggerProvider/MenuTriggerProvider.tsx
Avoid losing focus for a11y purposes
* Move focus to the filter button when adding a filter
* Move focus to 'Add filter' button when removing a filter
> FilterBar: manage focus on add/remove filters

- .changeset/chilly-starfishes-marry.md
- .changeset/three-students-peel.md
- package.json
- packages/components/package.json
- packages/package-bundler/package.json
- pnpm-lock.yaml
- turbo.json
Package bundler will fail to build as TypeScript paths cannot be resolved when updating to 5.6.
See https://github.com/LeDDGroup/typescript-transform-paths/issues/266
Lock `typescript` version and update peerDeps versions to reflect compatibility.
> chore(peerDeps): update version compatibilty for typescript

- .changeset/afraid-schools-cover.md
- .stylelintrc-css.mjs
- packages/components/src/__future__/Icon/Icon.module.css
- packages/components/src/__future__/Icon/Icon.tsx
Reported by Viet, in dev farms the CDN styles somehow override KAIO as opposed to KAIO taking precedence (does not happen in Storybook nor local dev).
Remove the usage of the CDN global style, and copy the default styles across into a custom class instead.
Note: We accept the risk that if Google changes the font name, all our icons will cease to work. We assume this is extremely unlikely to happen.
> fix(future/Icon): copy CDN styles to internal styles

- .changeset/kind-feet-kick.md
- package.json
- packages/package-bundler/package.json
- pnpm-lock.yaml
Dep update.
`typescript` peerDep version loosened as this fix no longer restricts it.
- Update `typescript-transform-paths` to `^3.5.2`
- Loosen `typescript` peerDep as this version fixes it
> chore(deps): update typescript-transform-paths to ^3.5.2

- .changeset/large-spies-play.md
- .changeset/violet-elephants-lick.md
- package.json
- packages/package-bundler/package.json
- pnpm-lock.yaml
Reverts cultureamp/kaizen-design-system#5243
The build errors don't happen, but the plugin doesn't work anymore :')
> Revert "chore(deps): update typescript-transform-paths to ^3.5.2"

- .changeset/fifty-snails-hunt.md
- packages/components/src/Pagination/Pagination.tsx
- packages/components/src/Pagination/subcomponents/PaginationLink/PaginationLink.module.scss
- packages/components/src/Pagination/subcomponents/TruncateIndicator/TruncateIndicator.module.css
Got some things wrong in https://github.com/cultureamp/kaizen-design-system/pull/5269
- Increase spacing between pagination buttons
- Only show boundary pages on large viewports and up
> Pagination responsive adjustments

- .changeset/nervous-gorillas-teach.md
- packages/components/src/Filter/FilterBar/FilterBar.module.css
- packages/components/src/Filter/FilterBar/FilterBar.tsx
Missed this in https://github.com/cultureamp/kaizen-design-system/pull/5238
Remove this container property that's not being used (still causing the issue mentioned in ☝️)
> Remove container CSS from FilterBar wrapper

- .changeset/shaggy-plants-rescue.md
- packages/components/src/__actions__/Menu/v3/MenuItem.module.css
- packages/components/src/__actions__/Menu/v3/_docs/Menu.docs.stories.tsx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.spec.stories.tsx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.stories.tsx
Currently, MenuItems show this border on hover:
We only want that to show on focus-visible (keyboard focus). Originally I thought this was a limitation with React Aria.
React Aria says that an item has 'focus' when it is hovered for this component. So the normalize/default focus outline was kicking in on hover/focus. I've explicitly removed that, and used `[data-focus-visible]` to add the border.
Bonus: now that browsers support outline border radius, use outline instead of border (using transparent borders causes issues with Windows High Contrast mode)
> fix(Menu v3): Only show MenuItem border/outline on focus-visible

- .changeset/two-bugs-march.md
- packages/components/locales/en.json
- packages/components/src/Tile/InformationTile/_docs/InformationTile.mdx
- packages/components/src/Tile/InformationTile/_docs/InformationTile.stories.tsx
- packages/components/src/Tile/subcomponents/GenericTile/GenericTile.spec.stories.tsx
- packages/components/src/Tile/subcomponents/GenericTile/GenericTile.tsx
Provide users with a way to have contextual accessible labels for the Information Button.
https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-2730
Adds a prop to the GenericTile component to allow control of the Information button's label.
> Kzn 2730/update info button label

- .changeset/giant-maps-enjoy.md
- packages/components/src/TextArea/TextArea.tsx
- packages/components/src/TextArea/_docs/TextArea.stickersheet.stories.tsx
https://cultureamp.slack.com/archives/C0189KBPM4Y/p1733288289604299
There's an internal version of the TextArea value held to support the autogrow feature. It was being used to feed into the TextArea in the case that value isn't provided, but that's not actually needed.
> fix(TextArea): Only use internal value for autogrow data property

- .changeset/afraid-dolls-visit.md
- packages/components/src/Tile/TileGrid/TileGrid.module.scss
- packages/components/src/Tile/TileGrid/TileGrid.tsx
- packages/components/src/Tile/TileGrid/_docs/TileGrid.stickersheet.stories.tsx
- packages/components/src/Tile/TileGrid/_docs/TileGrid.stories.tsx
Marking up TileGrid items in a list so that screen readers can report on how many tiles are in a list, so that context about the TileGrid is more accessible.
https://cultureamp.atlassian.net/browse/KZN-2865
Converted TileGrid to contain its children in an unordered list and wrapped each tile in a list item when passed as props to the TileGrid.
> Mark up Tiles in TileGrid as List

- .changeset/thin-actors-knock.md
- packages/components/src/__future__/Tabs/_docs/Tabs.spec.stories.tsx
- packages/components/src/__future__/Tabs/_docs/Tabs.stickersheet.stories.tsx
- packages/components/src/__future__/Tabs/_docs/Tabs.stories.tsx
- packages/components/src/__future__/Tabs/constants.ts
- packages/components/src/__future__/Tabs/subcomponents/Tab/Tab.tsx
- packages/components/src/__future__/Tabs/subcomponents/TabList/TabList.module.css
- packages/components/src/__future__/Tabs/subcomponents/TabList/TabList.tsx
- packages/components/src/__utilities__/isRTL/index.ts
- packages/components/src/__utilities__/isRTL/isRTL.spec.tsx
- packages/components/src/__utilities__/isRTL/isRTL.ts
Add carousel to Future Tabs when tabs start overflowing the width of the viewport
https://github.com/user-attachments/assets/a98a1d97-b6ef-428d-ac53-9e87ad3ebffc
Nicer than having heaps of tabs wrap to a new line
> Tabs (future): add carousel functionality when tabs overflow container

- .changeset/lemon-kings-push.md
- packages/components/src/__future__/Tabs/subcomponents/Tab/Tab.module.css
Hovering over the Future Tabs turns your cursor into the text input variant instead of the default. This has been changed to be consistent with the current Tab component. 
https://cultureamp.atlassian.net/browse/KZN-2916
Set the cursor to default on hover when tab is disabled and not disabled.
> 1:1 Future Tags hover state incorrect

- .changeset/tiny-poets-beg.md
- packages/components/src/__actions__/Menu/v3/MenuHeader.tsx
- packages/components/src/__actions__/Menu/v3/MenuPopover.tsx
- packages/components/src/__actions__/Menu/v3/MenuSection.tsx
- packages/components/src/__actions__/Menu/v3/MenuTrigger.tsx
- packages/components/src/__actions__/Menu/v3/_docs/ApiSpecification.mdx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.docs.stories.tsx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.mdx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.spec.stories.tsx
- packages/components/src/__actions__/Menu/v3/_docs/Menu.stories.tsx
- packages/components/src/__actions__/Menu/v3/index.ts
Avoid consumers having to pull directly from RAC.
If anything changes, e.g. they deprecate the `Section` component as they've just done. It's a single update instead of needing to update every usage.
Same applies if we wanted to adjust anything on our end.
Create the following wrappers around RAC components for use in the Menu component:
* MenuPopover (RAC Popover)
* MenuSection (RAC MenuSection)
* MenuHeader (RAC Header)
> Menu: Create MenuPopover, MenuSection and MenuHeader wrappers over RAC

- .changeset/beige-mugs-sort.md
- packages/components/src/Notification/subcomponents/GenericNotification/GenericNotification.module.scss
Inline notification icon color (blue-400) is lighter than else where
https://cultureamp.atlassian.net/browse/KZN-2923
Changed color to blue-500
> Update inline notification icon color

- .github/workflows/chromatic-pr.yaml
We are transitioning to module.css files, Chromatic must be updated to detect changes in these files
Added module.css files to Chromatic's externals
> Update Chromatic Externals

- .changeset/kind-spies-refuse.md
- packages/components/src/LinkButton/LinkButton.tsx
Failed file resolution reported in in the release [thread](https://cultureamp.slack.com/archives/CETLTFG9G/p1734656795682039) by Viet and Brendan [here](https://github.com/cultureamp/calibrations-ui/actions/runs/12527289914/job/34940725042?pr=679).
This is due to the import of the shared button styles using the `~` alias import instead of a relative import, which does not get compiled correctly.
Update import of the Button stylesheet to use a relative path.
> fix LinkButton stylesheet import path

- .changeset/brave-keys-check.md
- packages/components/src/Content/Content.module.scss
Reverts https://github.com/cultureamp/kaizen-design-system/pull/5444 due to unforeseen side effects where the content width got smaller.
> Revert margin to padding change on Content

- .changeset/moody-terms-drum.md
- packages/components/src/Content/Content.module.scss
Adjust width on small viewports to take horizontal margin into account as this could cause the margin to flow outside the viewport when components with `nowrap` applied cause the 100% width to be greater than it's parent.
Added `calc()` to content when in small viewports to minus off the horizontal margin applied.
Initially I converted this to CSS module, but reverted that due [vars and calcs not working in media queries](https://bholmes.dev/blog/alternative-to-css-variable-media-queries/). I decided to keep this change small and will follow up with CSS module conversion after.
> Content: Adjust width on small viewports

- .changeset/unlucky-shrimps-relate.md
- packages/components/package.json
This is a follow-up from my earlier work here: https://github.com/cultureamp/kaizen-design-system/pull/5492
I had missed that consumers are also importing the built out CSS. I think ideally we don't want to expose the `./dist` directory, but in order to avoid a breaking change, I figured it would be best to keep the same path for now.
I've tested this via a Canary and the problem looks to be resolved.
> feat: export dist styles from kaio

- .changeset/giant-monkeys-turn.md
- packages/components/package.json
A follow-up to https://github.com/cultureamp/kaizen-design-system/pull/5499. We'll get there eventually!
While it's not encouraged, some of our packages & apps are importing the `dist/styles.css` file from a `.css` file. In these cases, we need to set the `style` condition for that to resolve properly.
I've tested a canary and it looks sweet. 🚀
> feat: set style condition in exports so styles can be imported from a CSS file.

- .changeset/slow-students-hear.md
- packages/components/src/ToggleSwitch/ToggleSwitch/ToggleSwitch.module.scss
- packages/components/src/ToggleSwitch/ToggleSwitchField/ToggleSwitchField.tsx
Bug fix for `ToggleSwitchField` component
https://cultureamp.atlassian.net/browse/KZN-2988
- removes colour change on disabled hover state for `ToggleSwitchField`
- updates the cursor to be consistently `default` and not a mix of `default` and `text` over the `ToggleSwitch`
- applies disabled state opacity to `ToggleSwitch` 
Video of hover state before:
https://www.loom.com/share/79edbb648b6f4d1dbb8353f374830784?sid=01bd2fb2-1834-479f-b8c8-556a04b02511
Video of hover state after: 
https://www.loom.com/share/4d0ee52c50b94589895f57fd56c46250?sid=72a576b4-7dfa-441e-bb3e-01dcfead71bc
Before:
After:
> removes disabled hover state for ToggleSwitchField

- .changeset/thin-planets-cheat.md
- packages/components/src/Select/Select.tsx
Drill down `isDisabled` prop to react-select
Verified in local storybook, compared to [live one where isDisabled isn't working](https://cultureamp.design/?path=/docs/components-select--docs)
> fix: drill down isDisabled prop for Select

- .changeset/silent-chefs-return.md
- packages/components/package.json
v3 utilities need to be exported in packge.json like the rest of the modules
If we don't set the exports then esm envs don't know where to find the correct module.
> feat: add exports for v3 utilities

- .changeset/tiny-elephants-kick.md
- packages/components/src/__rc__/Tabs/subcomponents/Tab/Tab.module.css
- packages/components/src/__rc__/Tabs/subcomponents/TabList/TabList.module.css
https://cultureamp.atlassian.net/browse/KZN-2922
Updates colours to reflect design changes to Tabs inline with the button 
- overflow buttons background colour and icons 
- focus and hover background colour of Tabs
- border colour change
> Tabs state colours to reflect designs

- .changeset/friendly-mangos-deny.md
- packages/components/src/Filter/FilterButton/index.ts
To more easily enable teams to more to construct a tier 3 implementation of the FilterButton to meet new designs ([See thread](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1738730513616289) for additional context on the support request).
While we have recommended they attempt to use the new Button API in its place with tailwind to align to the original styles of the FitlerButton, this does not seem like it will work with their current API.
We have caveat-ed this update stating that any changes to Filters and its primitives like FilterButtonBase (ie: with the Pickers rebuild initiative), will likely lead to a larger migration effort for the team.
- adds `FilterButtonBase` primitive to exports from the component
> update Filter exports to include the FilterButtonBase primitive

- .changeset/poor-suns-fly.md
- packages/components/src/RichTextEditor/utils/commands/index.ts
Appears to be causing build failures for teams
> Revert: Export RTE mockRangeForBoundingRect

- .changeset/wet-planets-sniff.md
- packages/components/src/TitleBlockZen/TitleBlockZen.module.scss
To fix a stacking context issue the title sitting over the top of any popover that may intersect with it.
https://cultureamp.atlassian.net/browse/KZN-2956
There was a few places that a z-index was applied that is no longer needed, one being a comment on the page switcher which is no longer located in the title area when active.
I reduced the z-index in the `%navigationTabEdgeShadow` extend block as it's still needed to ensure the shadow apears over the navigation it just doesn't need to be any higher than `1` for it too work correctly.
> Fixes popovers being underneath title

- .changeset/clever-crews-relax.md
- packages/components/src/Modal/ConfirmationModal/ConfirmationModal.tsx
- packages/components/src/Modal/ContextModal/ContextModal.tsx
- packages/components/src/Modal/GenericModal/GenericModal.tsx
- packages/components/src/Modal/InputEditModal/InputEditModal.tsx
`className` for our modal components was overriding our built in styles (our pattern on this is to extend rather than override)
It was also being passed in at a lower level than the top, meaning you can't access everything in the tree.
This is technically a breaking change, I'll be reaching out to the one team currently using this prop.
> Adjust Modal className implementations to insert at the top level

- .changeset/stupid-jars-sip.md
- packages/components/src/Modal/ConfirmationModal/ConfirmationModal.module.scss
- packages/components/src/Modal/ContextModal/ContextModal.module.scss
- packages/components/src/Modal/GenericModal/GenericModal.module.scss
- packages/components/src/Modal/GenericModal/subcomponents/ModalAccessibleLabel/ModalAccessibleLabel.module.scss
- packages/components/src/Modal/GenericModal/subcomponents/ModalFooter/ModalFooter.module.scss
- packages/components/src/Modal/GenericModal/subcomponents/ModalHeader/ModalHeader.module.scss
- packages/components/src/Modal/InputEditModal/InputEditModal.module.scss
- packages/components/src/Modal/InputEditModal/InputEditModal.tsx
Updates all hardcoded directional properties and values to logical properties and values for RTL support.
Also removes `localeDirection` prop from `InputEditModal` which only has legacy usages in murmur, so should've been gotten rid of in the move to KAIO.
> Modal: Update directional CSS to logical properties/values for RTL support

- .github/workflows/check-files.yml
- .github/workflows/chromatic-pr.yaml
Avoids running the changeset check and chromatic when the PR isn't going into main.
This is mainly for the renovate PRs, so that they can go straight through to the rollup branch without requiring our intervention.
> Avoid changesets-exists and chromatic jobs when PR isn't going into main

- renovate.json5
Following https://github.com/cultureamp/kaizen-design-system/pull/5570, remove this setting so that Renovate PRs are no longer created as drafts and hopefully go through to the rollup branch without intervention
> Renovate: don't create as draft

- .github/workflows/check-files.yml
No need for such a hard block here. We have the changeset bot on PRs to remind us in case we've forgotten.
> Remove check for changeset

- .changeset/tall-chicken-grow.md
- packages/components/src/__next__/Select/Select.tsx
Found in a recent accessibility review: next/Select doesn't have the description and validation message linked via `aria-describedby`
> next/Select: link description and validation msg to combobox description

- .changeset/vast-gifts-know.md
- packages/components/src/TimeField/TimeField.tsx
- packages/components/src/TimeField/subcomponents/TimeSegment/TimeSegment.module.scss
- packages/components/src/TimeField/subcomponents/TimeSegment/TimeSegment.tsx
A recent dep update of the `@react-stately/datepicker` package caused some extra padding in the component
Before:
After:
On further investigation, there were some new invisible 'segment' characters added to ensure correct RTL behaviour:
Currently, every segment has padding added by us.
Avoid adding padding to these new invisible character segments.
> TimeField: fix spacing after dep update

- .changeset/smart-falcons-look.md
- packages/components/src/Checkbox/Checkbox/Checkbox.module.scss
- packages/components/src/ClearButton/ClearButton.module.scss
- packages/components/src/Input/Input/Input.module.scss
- packages/components/src/Input/Input/Input.tsx
- packages/components/src/Input/InputSearch/InputSearch.module.scss
- packages/components/src/Input/InputSearch/InputSearch.tsx
- packages/components/src/Link/Link.module.css
- packages/components/src/Modal/GenericModal/GenericModal.module.scss
- packages/components/src/Notification/subcomponents/GenericNotification/GenericNotification.module.scss
- packages/components/src/Radio/Radio/Radio.module.scss
- packages/components/src/__next__/Button/Button.module.css
- packages/components/src/__next__/Icon/_docs/Icon.docs.module.css
- packages/components/src/__next__/Select/subcomponents/Option/Option.module.scss
- packages/components/src/__next__/Select/subcomponents/SelectToggle/SelectToggle.module.scss
- packages/components/src/__next__/Tag/RemovableTag/subcomponents/RemoveButton.module.scss
- packages/components/styles/utils/_form-variables.scss
These pseudo element focus rings were implemented because `outline` didn't support rounded borders until more recently. Now that our supported browsers support this, we can adjust these to use outlines which is much more simple and less potential for issues.
This isn't comprehensive, I've left a bunch for components that are going away in the 2.0 release, or things that I don't want to touch (TitleBlock, Table)
> Use outline instead of pseudo elements for focus rings

- packages/components/src/__next__/Tag/Tag/_docs/Tag.stories.tsx
https://cultureamp.slack.com/archives/C05D8V4GALX/p1743656786238939
The `icon` prop for Tag (next) has a type of `React.ReactElement`. By default, Storybook will make the control value an object, but clicking "Set object" in the preview panel will break the component.
This PR adds `argTypes` to the Tag stories to provide some example options that the user can choose to preview icons in the Tag preview. It does it in the same way that it's done in Button (next)
> fix: add argTypes to Tag (next) for the icon prop

- .changeset/forty-women-wink.md
- README.md
- packages/components/package.json
In our vitest CI jobs we were getting a [bunch of warnings](https://github.com/cultureamp/kaizen-design-system/actions/runs/14325027474/job/40148863590?pr=5625#step:4:62) about types needing to come first in our exports object.
Reordered exports to have types come first.
> fix(components): reorder package.json export fields to prioritize types

- .changeset/lemon-rooms-laugh.md
- docs/pages/client-side-routing.mdx
next-services@4.6.0 now includes react-aria-components `RouterProvider` as part of the defaultPresets so `Link` & `LinkButton` will just work™️
Updated client-side routing docs, this also changes the docs to show that using the RAC re-export is the preferred method.
https://cultureamp.atlassian.net/browse/KZN-3239
> docs(client-side-routing): update documentation with next-services routing info

- .changeset/late-terms-hide.md
- package.json
In order to upgrade to react 19 we need to suppress some peerdep warnings for specific packages as they no longer maintained.
The 5 packages so far that need to have peerDep versions changed/ignored are:
* @reach/tab - no longer maintained
* react-focus-on - has an [outstanding issue](https://github.com/theKashey/react-focus-on/issues/98) to allow 19 as a peerDep
* react-textfit - no longer maintained
* react-popper - archived, floating-ui is the path forward
* @popper/core - same as above
Will create some tech health cards if they don't exist already to address and track these issues.
> chore: Ignore peerDep warnings for older packages

- .changeset/funny-rivers-camp.md
- packages/components/package.json
- pnpm-lock.yaml
postinstall ts-patch is not running in CI.
Installed ts-patch in components and run it before build
> fix: use ts-patch before building components

- .changeset/metal-papers-take.md
- packages/components/styles/utils/AIMoment.module.css
Jay reported an issue with the floating gradient borders not appearing in the latest release.
This appeared to be due to the z-index of the not being able to layer correctly off the `relative` parent. The interim fix was to add a `z-[0]` to the `classNameOveride`. This PR will mean they don't have to set this value.
- adds `z-index: 0` to `aiMoment` class 
Since this was an issue locally, I tested a canary (`0.0.0-canary-fix-zindex-ai-moment-20250502014154`) in the local dev for `ai-ui` and can confirm the z-index no longer is required in`classNameOveride`
> fix(AIMoment): add z index 0 on base aiMoment class

- package.json
- packages/tailwind/package.json
- pnpm-lock.yaml
To support react 19 
There seems to hard dependency on react and react-dom in the top level package.json that may be left over from pre KAIO days. From my testing there seems to be no real use for it to be there.
> fix: remove root-level React dependencies 

- .changeset/twelve-wombats-write.md
- packages/components/src/RichTextEditor/_mixins.scss
Kaizen will soon be loaded into a `components` layer in consuming apps using Tailwind 4 (see cultureamp/performance-review-cycles-ui#3392).
Once this happens, the `white-space: pre-wrap` style on the `RichTextContent` component would be overridden by the un-layered styles injected into the page by ProseMirror/TipTap at runtime.
To resolve the above issue, this adds `!important` to the `white-space: pre-wrap` style on the `RichTextContent` component.
> Force white-space: pre-wrap on RichTextContent

- packages/components/package.json
- packages/components/src/Calendar/CalendarRange/CalendarRange.module.scss
- packages/components/src/Calendar/CalendarRange/CalendarRange.tsx
- packages/components/src/Calendar/CalendarSingle/CalendarSingle.tsx
- packages/components/src/Calendar/CalendarSingle/_docs/CalendarSingle.stickersheet.stories.tsx
- packages/components/src/Calendar/LegacyCalendarRange/LegacyCalendarRange.module.scss
- packages/components/src/Calendar/LegacyCalendarRange/LegacyCalendarRange.tsx
- packages/components/src/Calendar/baseCalendarClassNames.module.scss
- packages/components/src/Calendar/baseCalendarClassNames.ts
- packages/components/src/Calendar/utils/isSelectingDayInCalendar.spec.tsx
- packages/components/src/Calendar/utils/setFocusInCalendar.spec.tsx
- packages/components/src/Calendar/utils/setFocusInCalendar.ts
- packages/components/src/DatePicker/DatePicker.spec.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/Filter/FilterBar/subcomponents/FilterBarDatePicker/FilterBarDatePicker.spec.tsx
- packages/components/src/Filter/FilterBar/subcomponents/FilterBarDateRangePicker/FilterBarDateRangePicker.spec.tsx
- packages/components/src/Filter/FilterDatePicker/FilterDatePicker.spec.tsx
- packages/components/src/Filter/FilterDatePicker/subcomponents/FilterDatePickerField/FilterDatePickerField.spec.tsx
- packages/components/src/Filter/FilterDateRangePicker/_docs/FilterDateRangePicker.stories.tsx
- packages/components/src/Filter/FilterDateRangePicker/subcomponents/FilterDateRangePickerField/FilterDateRangePickerField.spec.tsx
- pnpm-lock.yaml
Update react-day-picker to version 9.6.7 and update all dependent components to work with the new API. Changes include:
To support react 19 we need to update react-day-picker to v9
- Refactor component props to use the updated type definitions
- Update component rendering to match the new API requirements
- Modify CSS modules to accommodate new class naming conventions
- Adjust navigation components to use the new Chevron component API
- Add new styles for proper range highlighting and hidden requirements
react-day-picker changed quite a lot between major versions and how it applies class names to the table cell and button based on the type it is, so had to adjust some styles to target button children in some instances.
Behaviour between v8 and v9 in respect to how it handles clicking the …
> feat(components): upgrade react-day-picker from 8.10.1 to 9.6.7

- packages/components/src/__next__/Tooltip/_docs/Tooltip.spec.stories.tsx
Tooltip next tests have still been failing intermittently even after updating the Tooltip next tests and having them pass locally, as well as on the [PR](https://github.com/cultureamp/kaizen-design-system/pull/5791). 
The tests seem to be failing when the browser loses focus. I've added a click event to each of the tests as a workaround to refocusing the canvas - allowing the tests to pass. As the Tooltip next tests are run as one test, updating the test runner preVisit to refocus the page wouldn't work.
> [KZN-3168] Tooltip keyboard interaction test

- .changeset/warm-insects-show.md
- packages/components/src/__next__/Select/Select.tsx
RAC types update for `onSelectionChange` has broken teams implementations 
Updating the `Select` next's `onSelectionChange` prop so that it now only takes a `Key` again instead of `Key | null`
> [KZN-3362] replace RAC onSelectionChange

- .changeset/deep-owls-sink.md
- packages/components/src/__next__/Select/Select.tsx
- packages/components/src/__next__/Select/subcomponents/Overlay/Overlay.tsx
- packages/components/src/__next__/Select/subcomponents/SelectPopoverContents/SelectPopoverContents.tsx
Fixes: https://cultureamp.atlassian.net/browse/KZN-3349
When a user interacts with the Select scrollbar, or the padding of the popover the dropdown closes -> it should stay open
https://github.com/user-attachments/assets/63930d2c-ee11-4734-a036-c0b8dc543f6a
Issue was reported in January by Coles
I've updated the `Overlay` component which handles closing the dropdown giving it the ref of the parent `Popover` component. Now the overlay won't close the dropdown if the popover is clicked, which includes the padding space and the scrollbar. 
https://github.com/user-attachments/assets/a4c6bc43-a86d-4fc0-8f11-c011a92fde09
> [KKZ-3349] Select next overlay bug - dropdown closes when clicking on scrollbar

- docs/pages/upcoming-releases.mdx
- packages/components/src/__next__/Button/_docs/Button--migration-guide.mdx
- packages/components/src/__next__/Icon/_docs/Icon--migration-guide.mdx
- packages/components/src/__next__/Tabs/_docs/Tabs--migration-guide.mdx
- packages/components/src/__next__/Tooltip/_docs/Tooltip--migration-guide.mdx
KAIO consumers are uplifting their repos to be KAIO v2 compatible, but we currently don't provide a migration guidance for next/Tooltip. This creates friction to our goal of teams being KAIO v2 ready by 1 Sep 2025.
Jira ticket: [KZN-3037](https://cultureamp.atlassian.net/browse/KZN-3037)
- Added a Tooltip migration guide
- Linked new Tooltip migration guide to the KAIO v2 migration page
- Updated existing Button, Icon and Tabs migration guides, as follows:
- Standardise title case
- Define audience (KAIO v1 consumers getting ready for KAIO v2) - some repos (e.g. Murmur) are still heavily using legacy packages and might feasibly need to migrate through multiple KAIO versions at once
[KZN-3037]: https://cultureamp.atlassian.net/browse/KZN-3037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> docs: Add migration guide for tooltip

- .changeset/fine-berries-repeat.md
- packages/components/styles/utils/AIMoment.module.css
The z-index added to the AIMoment clas was a fix to ensure that animated border rendered correctly in implementations across the platform.
This was unintentionally removed when merging the the CSS layers PR so I'm re-adding this.
- re-add z-index to AIMoment class
> fix(AIMoment): re-add missing z-index from stylesheet

- .buildkite/pipeline.yaml
This PR removes the LinearB Cycle Time plugin from the pipeline. It required that we remove this as we are shutting down our account with LinearB shortly.
This change should not affect the functionality of the pipeline, but it will remove the dependency on the LinearB Cycle Time plugin.
Please merge this PR as soon as possible to avoid any issues with the pipeline.
> chore: remove LinearB Cycle Time plugin

- .changeset/angry-animals-behave.md
- .changeset/clean-buses-serve.md
- .changeset/kind-carrots-battle.md
- .changeset/lucky-carrots-approve.md
- packages/components/src/LikertScaleLegacy/LikertScaleLegacy.spec.tsx
- packages/components/src/LikertScaleLegacy/LikertScaleLegacy.tsx
- packages/components/src/LikertScaleLegacy/_docs/LikertScaleLegacy.mdx
- packages/components/src/LikertScaleLegacy/_docs/LikertScaleLegacy.stories.tsx
- packages/components/src/Menu/subcomponents/StatelessMenu/StatelessMenu.tsx
- packages/components/src/__next__/Select/Select.tsx
- packages/components/src/__next__/Select/_docs/Select.mdx
- packages/components/src/__next__/Select/_docs/Select.stories.tsx
Backports accessibility fixes for pre-1.79.0 as migration to the latest release with CSS layers is proving to be difficult in murmur.
- Cherry picks accessibility fixes for Menu, Select/next and LikertScale
Merging this into 1.78.xx *should* create a patch version release.
> fix(a11y): Backport a11y fixes for 1.78.x

- .changeset/empty-grapes-try.md
- .changeset/fifty-snails-do.md
- packages/components/src/__next__/Button/_docs/Button--api-specification.mdx
- packages/components/src/__next__/Button/_docs/Button.docs.stories.tsx
- packages/components/src/__next__/Menu/_docs/Menu--api-specification.mdx
- packages/components/src/__next__/Menu/_docs/Menu.stories.tsx
Split Button is being deprecated so we need a path forward for existing usage
Added stories and API spec docs to both Menu and Button sections
> feat: add Split Button Replacement story and docs to Button & Menu

- .changeset/empty-spies-wear.md
- packages/components/src/Avatar/Avatar.spec.tsx
- packages/components/src/Avatar/Avatar.tsx
When the avatarSrc does not exist, an `img` is still getting rendered. There is no problem visually, but it isn't ideal to have a broken img in the DOM.
https://cultureamp.slack.com/archives/C0189KBPM4Y/p1752472765353019
This change means `avatarState` of `error` will not render an `img` element. Only the initials will render
> Avatar component will only render the image when it loads successfully

- .changeset/tricky-radios-clap.md
- packages/components/src/Notification/GlobalNotification/_docs/GlobalNotification.stickersheet.stories.tsx
- packages/components/src/Notification/InlineNotification/_docs/InlineNotification.stickersheet.stories.tsx
- packages/components/src/Notification/ToastNotification/_docs/ToastNotification.stickersheet.stories.tsx
- packages/components/src/Notification/subcomponents/GenericNotification/_mixins.scss
Passing the `Link` component into any of our notifications was breaking the styling and giving the link 2 underlines. 
Updating the styling to fix the implementation when using the `Link` component without breaking the older implementations that use a link`<a href="/" >` 
`Link` component passed
`<a href="/" >` passed
> [KZN-3487] styling Link component in notifications

- packages/components/src/TitleBlock/TitleBlock.tsx
v2 readiness
TitleBlock is not deprecated this comment was left over from the rename PR, only  saw it due to my editor complaining  in the canary implementation test.
> fix: remove @deprecated comment from TitleBlock

- .changeset/polite-years-swim.md
- packages/components/src/Illustration/Spot/Spot.tsx
- packages/components/src/Illustration/Spot/_docs/Spot.stickersheet.stories.tsx
Add 3 new illustrations for the new effectiveness templates
> adding three new spot illustrations for effectiveness templates

- packages/components/libs/react-aria/package.json
- packages/components/package.json
- packages/components/rollup.config.mjs
- packages/components/src/__react-aria-components__/index.ts
- packages/components/src/__react-aria__/index.ts
- packages/components/v3/react-aria-components/package.json
- packages/components/v3/react-aria/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Top reduce the risk of compatibility issues with shared libraries that have not upgraded to KAIO V2 (ie: next-services, goals-shared-ui) we should still export `react-aria` and `react-aria-components` from the V3 endpoint as well as the libs.
This will allow us to remove this as a minor release in the future and will not make the upgrade those packages as a hard dependency for v2.
- re-adds endpoint for v3 with only react-aria and react-aria components exported
- small fix to the types path for the libs export of react-aria
> re-add v3 RA library exports to v2

- docs/pages/v2-migration-guide.mdx
v2 readiness
Add link to v1 docs in v2 migration guide
> docs: v1 docs link

- .changeset/config.json
- .github/workflows/changeset.yaml
- .github/workflows/check-files.yml
- .github/workflows/lint.yml
- .github/workflows/test-stories.yaml
- .github/workflows/test-unit.yml
Update these workflows so backported fixes can be released from the kaio-v1 feature branch - see more on the guide [here](https://cultureamp.atlassian.net/wiki/spaces/DesignSystem/pages/5277254482/4.3+Backporting+fixes#Step-3.-Update-the-Github-Actions)
- update base branch for changeset on feature branch
- update github workflows to add `kaio-v1` on relevant actions
> chore(ci): update kaio-v1 workflow config for backporting

- packages/components/locales/en.json
- packages/components/src/__alpha__/SingleSelect/_docs/SingleSelect.spec.stories.tsx
- packages/components/src/__alpha__/SingleSelect/context/SingleSelectContext.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/ComboBox.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/ComboBoxTrigger/ComboBoxTrigger.module.css
- packages/components/src/__alpha__/SingleSelect/subcomponents/ComboBoxTrigger/ComboBoxTrigger.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/Popover/Popover.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/Select.tsx
- packages/components/src/__alpha__/SingleSelect/types.ts
Added a `ClearButton` to the combobox - which clears the selected state of the input
The button is only seen once an item has been selected
Clicking the button will clear the selection
The `ClearButton` is accessible via keyboard and can be tabbed to. Once the button is interacted with focus is moved back to the input
Item Selected
ClearButton focused
> [KZN-3439] Clear selected item button

- packages/components/src/__alpha__/SingleSelect/subcomponents/ComboBox.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/ComboBoxTrigger/ComboBoxTrigger.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/Popover/Popover.tsx
- packages/components/src/__alpha__/SingleSelect/subcomponents/Popover/utils/usePopoverPositioning.ts
- packages/components/src/__alpha__/SingleSelect/subcomponents/Popover/utils/usePositioningStyles.ts
- packages/components/src/__alpha__/SingleSelect/types.ts
Recent work done to refactor the alpha `SingleSelect` to manage state instead of using components caused 2 regressions in the popover component. 
1. The popover itself was rendering before all the items loaded - causing the list to render on the bottom even in situations where it would be cutoff.
2. Combobox was not rendering correctly: because the inputRef was being passed to the popover instead of the triggerWrapper 
This PR fixes both of these regressions. Calling the updatePosition once the popover has rendered, and passing the correct wrapper ref to the popover for the combobox
> [KZN-3416] Fix popover regressions

- .changeset/spicy-carpets-laugh.md
- packages/components/src/Notification/InlineNotification/InlineNotification.tsx
https://cultureamp.slack.com/archives/C0189KBPM4Y/p1758088320927829
A bug was raised around `InlineNotification` and the `hideCloseIcon` not working as intended. When `hideCloseIcon="true"` was passed the icon was still shown
Replaced the `??` nullish coalescing operator with the `||` logical or operator, so that the `hideCloseIcon` would be passed correctly. The `persistent` prop was being passed with a default of false, meaning that with the `??` operator the `hideCloseIcon` would never be passed. 
Before
After
> [KZN-3556] Inline notification: hideCloseIcon 
