cultureamp/kaizen-design-system

lerna.json, site/package.json
Because lerna was getting its packages from yarn workspaces, we were pushing tags for all updates to the site. This was creating a lot of noise in the git history and the releases page.
By separating lerna packages and workspaces, we can exclude the site from being versioned.
=> ci: Stop versioning/tagging private packages

site/src/components/MainNav.tsx, site/src/templates/componentPage.tsx, site/src/templates/guidelinePage.tsx, site/src/templates/util.ts
We're already sorting the GraphQL data for the nav items on the Guidelines page; this PR does the same for Components (slightly different as they don't need to be in separate sections in the sidebar).
=> docs: Order Components nav items with Overview at top

packages/binary-assets/README.md, packages/binary-assets/lib/index.ts, packages/binary-assets/package.json
Release the `@cultureamp/kaizen-binary-assets` package, using it's current S3 assets URL.
(This will be updated to a cloudfront for http2 support, but the S3 URLs will remain available for backwards-compatibility.)
=> chore: Add binary-assets package

lerna.json
Something since the first package release has broken the release pipeline (lerna is unable to authenticate with the npm registry), and this seems like the most likely candidate.
This change was introduced in #55 but was not necessary for the purpose of that PR.
=> ci: Switch lerna npm client back to yarn

packages/binary-assets/package.json
This is suspected to be causing authentication problems in the release pipeline.
=> chore: Stop overriding registry in the binary-assets package

lerna.json
Markdown changes had previously been ignored by lerna, but this was causing issues with the changelog when docs were updated in packages.
Updates to tests and stories would encounter the same issues.
This change makes it so that the release step will now depend on the conventional commit alone to determine appropriate bumps, and group all previous unreleased changes in the next package release.
=> ci: Make all changes eligible for versioning and release

site/src/docs-components/Do.tsx, site/src/docs-components/Dont.tsx, site/src/docs-components/DosAndDonts.scss, site/src/docs-components/DosAndDonts.tsx, site/src/docs-components/WhenUse.scss, site/src/docs-components/WhenUse.tsx, yarn.lock
This PR allows docs contributors to add dos + don'ts components like this:
Note that MDX doesn't seem to allow named imports like `import { Do, Dont, DosAndDonts }`.
=> docs: Create dos and don'ts components

packages/component-library/package.json
Types which are referenced in our published typescript declarations should also be published as direct dependencies.
Fixes compiler errors for missing types (e.g. lodash) in consuming projects with strict compiler settings.
=> fix: Include types referenced in declarations

packages/component-library/draft/Kaizen/Select/styles.elm.scss
=> fix: fix visibility of Elm Select's selected item text

CODEOWNERS
Props to @zioroboco for the suggestion 👍 
This essentially adds us as an owner for any new packages in this repo. It will need to be updated once draft components are split out of the Design System.
=> chore: update codeowners to ping the DST for any new packages

packages/component-library/draft/Kaizen/Select/styles.elm.scss
Reverts cultureamp/kaizen-design-system#86
=> fix: revert select content alignment in ie11 off (#86)

packages/component-library/draft/Kaizen/Table/styles.scss, packages/component-library/stories/Table.stories.tsx
Storybook:
https://dev.cultureamp.design/lijuenc/fix-table-animations/storybook-static/?path=/story/table--expanded-popout
This PR fixes some unexpected shifting layout and text when expanding and collapsing table rows.
This problem was also not obvious in the storybook because the examples were just static. There was no way to toggle the expanding and collapsing of rows so I only came across this issue in real use. To fix that, I've also updated the stories to make them interactive.
Before (notice that the text shifts to the right, then back to the left):
After:
=> fix: Fix shifting text when expanding and collapsing table rows

.buildkite/pipeline.yaml
Storybook builds were a bit slow! This PR requests large agents for this step, knocking about a minute off the build time under ideal conditions.
=> ci: Increase agent size for storybook build

packages/component-library/draft/Kaizen/Tag/Tag.elm, packages/component-library/draft/Kaizen/Tag/Tag.scss, packages/component-library/draft/Kaizen/Tag/Tag.tsx
The root element of the Tag component is currently `display: flex` when it should be `display: inline-block`.
This resulted in an issue where the Tag would stretch to fill the width of its container.
=> fix: Fix Tag not constraining its width to its content

packages/component-library/draft/Kaizen/Modal/presets/InputEditModal.tsx
Creating optional prop, `submitDisabled`, which can disable the submit button on an editModal.
The prop is passed through to the `modalFooter`, which accepts a `disabled` prop for each type of button.
Naturally, the default value is false.
=> feat: passing optional prop to disable submit button on edit modal

packages/design-tokens/package.json
Changes files from lib->sass
I also removed `directories` as it's not something that's supported now. 
https://docs.npmjs.com/files/package.json#directories
=> fix: Design token package.json was referencing old folder structure

packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.scss, packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.tsx, packages/component-library/stories/TitleBlock.stories.scss, packages/component-library/stories/TitleBlock.stories.tsx
Current issue:
When scrolling, the sticky TitleBlock's navigation bar should get the same background color as its `stickyColor`.
=> fix: Ensure that sticky TitleBlock's navigation bar gets a background when scrolling

packages/component-library/components/Layout/_styles.scss
This is unnecessary, as everywhere the sidebar is used should already have a background.
If we wanted this sidebar to be used on a different colour background like white, it wouldn't work
in it's current implementation anyway (there's no padding, so there'd be a harsh transition from
the side of the sidebar to the white background)
=> chore: remove sidebar background color

packages/component-library/components/NavigationBar/NavigationBar.tsx, packages/component-library/components/NavigationBar/components/Menu.tsx
The freemium version of the navbar menu in murmur is already mobile friendly and hence does not need to change shape at lower resolutions.
=> feat: make mobile version of navigation bar menu optional

packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.scss
This PR limits the sticky TitleBlock to tablet and up because NavigationBar doesn't support a sticky hamburger menu.
This gif shows the issue. Notice how the TitleBlock sticks, but the hamburger menu from NavigationBar scrolls away.
This gif shows the proposed fix/workaround. On mobile don't stick the TitleBlock so it goes away naturally with the Navigation Bar. On tablet and up, keep it unchanged from current behaviour (it sticks). On tablet we don't have the hamburger menu, so it's not an issue there.
=> fix: Limit sticky TitleBlock to tablet and up to work better with NavigationBar hamburger menu

packages/component-library/components/NavigationBar/NavigationBar.module.scss, packages/component-library/components/NavigationBar/_styles.scss, packages/component-library/components/NavigationBar/components/Badge.module.scss, packages/component-library/components/NavigationBar/components/Link.module.scss, packages/component-library/components/NavigationBar/components/Menu.module.scss
Reverts cultureamp/kaizen-design-system#140
This couldn't be used in murmur until we are ready for the Zen colour rollout in Murmur. As such, we are blocking an important fix that needs to be released. So, we will revert for now, and re-introduce when we are ready.
=> feat: revert Use Zen colours for NavigationBar

packages/component-library/package.json
This mock is useful to consumers of Kaizen components.
=> feat: Include svg mock in published package

site/docs/components/infinite-scroll.mdx, site/docs/components/pagination.mdx, site/docs/guidelines/pagination-infinite-scroll.mdx
Closes #77
Branch preview: <http://dev.cultureamp.design/add-pagination-documentation/guidelines/pagination-infinite-scroll>
* Adds [Pagination and Infinite Scroll](http://dev.cultureamp.design/add-pagination-documentation/guidelines/pagination-infinite-scroll) comparison guidelines, [pagination](http://dev.cultureamp.design/add-pagination-documentation/components/pagination/), and [infinite scroll](http://dev.cultureamp.design/add-pagination-documentation/components/infinite-scroll)
* Uses DOs and DONTs styling for "When to use and when not to use"
* Uses "( not built)" in nav titles as per [this issue to improve visibility](https://github.com/cultureamp/kaizen-design-system/issues/116)
Screenshot:
=> docs: Add Pagination and Infinite Scroll documentation

site/docs/guidelines/layout-spacing-sizing-vertical-rhythm.mdx
Remove default tags from Layout, Spacing, Sizing, Vertical Rhythm, and Alignment page
Branch preview: https://dev.cultureamp.design/update-tags-on-layout/guidelines/layout-spacing-sizing-vertical-rhythm/
=> docs: update tags on layout guidelines

packages/component-library/components/Notification/InlineNotification.tsx, packages/component-library/components/Notification/_styles.scss, packages/component-library/components/Notification/components/GenericNotification.module.scss, packages/component-library/components/Notification/components/GenericNotification.tsx
I'm working on something where I could use this component but need to remove the margin-bottom.
This PR just adds a prop to the React version of `InlineNotification` to allow us to remove the bottom margin.
=> feat: add noBottomMargin prop to inlineNotification

packages/component-library/draft/Kaizen/Select/Select.tsx
Enable the `className` prop to be enabled for the `Select` class names.
The primary purpose is to allow "needsclick" for the `React Select` component that breaks on mobile devices due to the `fastclick` library.
=> fix: Ensure that className prop also taken into account for Select

packages/component-library/draft/Kaizen/Modal/Primitives/GenericModal.elm, packages/component-library/stories/ModalStories.elm
The scrollLayer style needs to be duplicated in the parent span in order for elm modal to not take up additional space. This differs from how React modal implements the style.
=> fix: Add scroll layer style to parent span

packages/component-library/draft/Kaizen/Modal/Primitives/GenericModal.scss, packages/component-library/draft/Kaizen/Modal/Primitives/ModalBody.elm, packages/component-library/draft/Kaizen/Modal/Primitives/ModalFooter.elm, packages/component-library/stories/ModalStories.elm
When combining styles with the react modal some key css was removed from the elm version that actually needs to remain.
These relate to how the modal is laid out using flex.
=> fix: Add missing flex styles for GenericModal

packages/component-library/draft/Kaizen/Form/Primitives/Checkbox/Checkbox.tsx, packages/component-library/draft/Kaizen/Radio/Primitives/RadioInput.tsx, packages/component-library/draft/Kaizen/RadioGroup/__snapshots__/RadioGroup.spec.tsx.snap
Hello! Ran into two more components this morning that fall victim to `fastclick` - not the worst outcome, but they require double tapping to select.
If this is the desired effect, please let me know! Gif attached. Might be hard to see, but you can see the first tap does not select anything (but some styles update) and requires a double click to activate. 
Not sure how the double tap impacts when it comes to those using features like `VoiceOver` but also worth considering. 
When I am off the simulator and using my device for QA swarm this afternoon, I will investigate the VoiceOver usage.
=> fix: Disable fastclick so mobile devices don't require double click

packages/component-library/draft/Kaizen/Popover/Popover.tsx, packages/component-library/draft/Kaizen/Popover/styles.scss, packages/component-library/stories/Popover.stories.tsx
Add `boxOffset` property to the `Popover` component. It will shift the popover box a specified amount, without moving the popover arrow.
*(the snapshot above is slightly off centre, but that has now been fixed)*
This task links to a requirement of ticket CORE-348 in perform. We needed to show a popover, have the popover arrow centered to the sibling button, but the box to not go past the main body margin. This new property will give us the flexibility to achieve this.
Side updates:
* Removal of some dead scss code in the `arrow` mixin
* Removal of the `position` `left` and `right` options, since they aren't yet implemented.
* Separate the popover arrow to its own element, as to give more flexibility on how it is positioned.
Notes:
One of the ugly things that I've introduced is some …
=> feat: Add `boxOffset` property to the `Popover` component

site/src/styles/global.scss, site/src/styles/markdown.scss
Before:
After:
Branch previews of pages with code blocks (and inline code):
- http://dev.cultureamp.design/di/fix-illegible-code-blocks/guidelines/animation/
- http://dev.cultureamp.design/di/fix-illegible-code-blocks/guidelines/layout/
This PR does:
- Move background color from `code` to `pre` for code blocks and updates the color value to make text legible again.
- Fix padding on `code` inside `pre`
- Move `code` styles from `.md-code {}` scope to `code {}` scope because
`md-code` class isn't being applied to `code` elements at this time.
=> docs: Fix styles for inline code on Kaizen Site

site/docs/components/badge.mdx, site/docs/components/button-group.mdx, site/docs/components/card.mdx, site/docs/components/divider.mdx, site/docs/components/loading-skeleton.mdx, site/docs/components/loading-spinner.mdx, site/docs/components/tile.mdx, site/src/components/SidebarAndContent.scss, site/src/styles/global.scss
This PR:
- Adds “not built” to component nav titles for components that haven't been built
- Adjusts sizing for sidebar tabs for longer names
- Adjusts the layout so the sidebar aligns with "Need to know" heading
Branch previews:
- https://dev.cultureamp.design/di/improve-visibility-of-unbuilt-components/components/badge
- https://dev.cultureamp.design/di/improve-visibility-of-unbuilt-components/components/button-group
- https://dev.cultureamp.design/di/improve-visibility-of-unbuilt-components/components/card
- https://dev.cultureamp.design/di/improve-visibility-of-unbuilt-components/components/divider
- https://dev.cultureamp.design/di/improve-visibility-of-unbuilt-components/components/loading-skeleton
- https://dev.cultureamp.design/di/improve-visibility-of-unbuilt-components/components …
=> docs: improve visibility of unbuilt components

package.json, site/gatsby-node.js
This PR adds makes storybook work in ie11 by adding @babel/preset-env.
In a previous PR (https://github.com/cultureamp/kaizen-design-system/pull/198), I added the name of the preset only, and this led to a break when running `yarn gatsby develop` (Which uses setBabelPreset to add an options object with a `plugins` field to each preset - which @babel/preset-env doesn't accept)
To address this break, this PR also adds a specific options object to @babel/preset-env (specifying ie11), and some logic in gatsby-node.js to check if a preset already has it's own options (and use that instead if it exists)
=> fix: Specify ie11 for @babel/preset-env

packages/component-library/draft/Kaizen/Form/Primitives/Input/Input.tsx, packages/component-library/draft/Kaizen/Form/TextField/TextField.tsx, packages/component-library/stories/TextField.stories.tsx
Enable focus events (onBlur, onFocus) for the `TextField`.
Required for:
1. Analytics (event measurements required for event focus/blur).
2. Alignment with what we state in our guidelines (https://cultureamp.design/components/text-field/): `Most of the time, we validate text fields on "blur" (when leaving the text fields) or on form submission as needed. We don’t validate on key strokes.`
Added:
1. Optional focus events to types + component.
2. Example Story with events firing.
Note that this aligns to `open/closed` principle and should only be a minor update as the API is backwards compatible.
=> feat: add focus events to TextField

packages/component-library/draft/Kaizen/HeroCard/README.mdx
This adds an accompanying guide for the Hero Card component, which already exists in kaizen.
**Branch preview:** https://dev.cultureamp.design/pex/add-hero-card-guideline/
=> docs: Add initial guide for HeroCard

packages/component-library/draft/Kaizen/Popover/Popover.tsx, packages/component-library/stories/Popover.stories.tsx
Hello DST 👋 
In Perform, we're in the need of a `Popover` that doesn't have a heading. If that prop isn't provided, the current `Popover` component still displays the header divider line and looks a bit out of place.
What I did is to render the header (divider included) only if the `heading` prop is passed. The downside of this is that the dismiss button lives within the header, so with this change there's no way to have a dismissable, headerless popover. Is that ok?
=> feat: Remove header divider if no heading prop is provided

packages/component-library/draft/Kaizen/HeroCard/HeroCard.scss
- Fixes an issue where number wasn't centred inside `HeroCard` badge
Before:
After:
=> fix: IE11 fixes for HeroCard

packages/component-library/draft/Kaizen/HeroCard/HeroCard.scss, packages/component-library/draft/Kaizen/HeroCard/HeroCard.tsx, packages/component-library/stories/HeroCard.stories.tsx
- Removed image wrapper - allows for more granular control of image placement from outside of the component
- Made left column 1/3 to align with designs
- Made content under title stretch to fill rest of card
- Allow for `minHeight` attribute to set minimum height of the card from outside the card. (For IE11 compatibility) - known IE11 flex bug.
=> feat: HeroCard enhancements

site/docs/guidelines/color.mdx
Fixes: #217 
Changed references to Ocean (below) to Cluny:
- To indicate links and on-page actions, use Ocean.
- Colors can help to create visual patterns that the user can recall (for example, links are always Ocean colored or negative favorability scores, errors, and destructive actions are always Coral).
=> docs: Updated references of Ocean to Cluny

packages/component-library/draft/Kaizen/Select/Select.tsx, packages/component-library/draft/Kaizen/Select/index.ts, packages/component-library/stories/Select.stories.tsx
Add `AsyncSelect` component into Kaizen. 
This components expose the `Async` component from `react-select`. A couple of props of this component gave us the ability to search asynchronously when the user is typing.
Inside the `Select.tsx` added a new component called `AsyncSelect` that basically render the `Async` component from `react-select/async` --> [more info here](https://react-select.com/async).
Decided to add it here since we reuse all the components created for the `Select` component like `Control` `Placeholder` `Dropdownindicator` etc.
Created a separate component since react-select exposes it as a separate component as well. 
In the `index.ts` export the `Select` and `AsyncSelect`
Included a couple of stories inside the `Select.stories.tsx` as well.
At least for now only used …
=> feat: Add AsyncSelect component

.buildkite/scripts/build-site.sh, .buildkite/scripts/build-storybook.sh, .buildkite/scripts/compile.sh, .buildkite/scripts/lint.sh, .buildkite/scripts/publish.sh, .buildkite/scripts/test.sh, package.json
Includes adding `set -e` to exit on first error — equivalent to the existing behaviour, except that all scripts previously were only a single line.
=> ci: Minor refactors to Buildkite scripts

packages/component-library/draft/Kaizen/Form/Primitives/ToggleSwitch/styles.scss
A recent change to the toggle positioning broke the styling within freemium, this was due to it inheriting box-sizing from a parent. This fix explicitly sets the box-sizing to keep the thumb and track positioning of the toggle field consistent throughout.
This also updates the colour scheme for freemium to use kz colour tokens.
=> fix: toggle switch field positioning bug

packages/component-library/draft/Kaizen/Modal/Primitives/GenericModal.scss, packages/component-library/draft/Kaizen/Modal/Primitives/GenericModal.tsx
The problem is, when a modal is opened, we prevent body scroll behind it, this causes the scrollbar (if there is one) to disappear - the causes a 'jump' in body width.
Currently we make up for this disappearing scrollbar by creating a 15px padding on the `documentElement`. Problem with this approach is that it doesn't account for 2 scenarios:
- When the documentElement does not have enough content to scroll - hence no scrollbar
- When the browser doesn't have a scrollbar (or had a floating scrollbar, like on a mac)
In the above 2 scenarios we are currently getting the opposite effect, we add padding when there was no scrollbar, causing the 'jump' in body width in the other direction.
Some research found this article from a bootstrap contributor:
[Javascript Scrollbar …
=> fix: fixed modal body padding issue

packages/component-library/components/Icon/README.mdx, packages/component-library/stories/Icon.stories.tsx, site/docs/components/icon-button.mdx
Branch previews:
- https://dev.cultureamp.design/di/update-icon-guidelines-and-fix-story-id/components/icon
- https://dev.cultureamp.design/di/update-icon-guidelines-and-fix-story-id/components/icon-button
This PR fixes the story ID for the Icon component.
It also updates documentation around "Icon and Tooltip" and "Icon Button and Tooltip". I expect to follow up in the future with more specific guidelines around Icon Buttons for Default, Primary, Secondary, and Destructive options, Zen UI Kit assets, and someday an IconWithTooltip component.
=> docs: update Icon and Icon Button component and fix story

packages/component-library/icons/arrow-left.icon.svg, packages/component-library/icons/arrow-right.icon.svg
_This PR will be a "breaking design change" (the look of the arrows is changing) but not a breaking change._
We currently have two pairs of left and right arrows in the platform that look different:
Designers would like to keep the bottom pair and get rid of the top pair.
However, due to the fact that "right" and "left" are more RTL-friendly than "backward" and "forward", we want to _rename_ the bottom pair to "Arrow Right" and "Arrow Left".
**This PR preserves the filenames, but makes the top pair look like the bottom pair.**
It does not delete the now-redundant bottom pair yet, because my plan is to first remove references to the bottom pair in consuming repos, and then do another PR in `kaizen-design-system` to remove the icons themselves.
=> feat: Make right/left arrows look like forward/backward

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.elm, packages/component-library/stories/Modal.stories.tsx, packages/component-library/stories/ModalStories.elm
This adds the positive and negative modal variants.
=> feat: Add elm modal positive, negative variants

packages/component-library/components/Text/Text.elm
Setting an ID on the elm text component will assist in cases where the Text component can be targeted by an ariaDescribedBy or ariaLabelledBy attribute.
The elm modal confirmation variants are a perfect example of where this would be utilised.
Currently the modal  h1 and p elements that could be used to accurately describe the modal cannot be set with an ID.
=> feat: set id on elm Text component

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/stories/ModalStories.elm
The elm modal currently does not support closing by pressing the escape key.
By subscribing to onKeyDown and decoding for the escape key we can ensure the modal runs the closing animation.
Care was taken to ensure a subscription to onKeyDown is only applicable when the modal is not closed. This means that pressing escape whilst the modal is opening will disrupt the animation and close it again.
=> feat: close elm modal with escape

packages/component-library/draft/Kaizen/SplitButton/DropdownMenu.spec.tsx, packages/component-library/draft/Kaizen/SplitButton/DropdownMenu.tsx, packages/component-library/draft/Kaizen/SplitButton/SplitButton.tsx, packages/component-library/draft/Kaizen/SplitButton/styles.scss, tslint.json
* Change the menu positioning from `position: relative` to `position: absolute`. I noticed when opening the dropdown menu, the content below it was getting pushed down. I am surprised that this wasn't causing issues in perform-ui, but I fixed this issue anyway, as it will likely cause unexpected behaviour in the future. @vicchirino if you could just confirm that I haven't broken any behaviour from your end.
Before:
After:
* Fix how the dropdown menu would be positioned when we run out of room. There was some logic that would show the menu above the SplitButtons, if we didn't have enough room below. The problem was that sometimes we didn't even have room above, causing menu items to become unselectable. Example:
My first iteration at fixing the issue was to have the menu overlap the …
=> feat: SplitButton positioning improvements

CONTRIBUTING.md
I recently added elm stories, but couldn't see them showing on the storybook. I spent a while troubleshooting, digging docs, without success. I was only able to fix the issue after talking to an old contributor.
This PR documents an extra step you have to do after adding an elm story.
=> docs: update contributing docs the steps to add elm stories

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/stories/ModalStories.elm
The elm modal api is currently not flexible enough for handling things such as focus management and subscriptions in an opaque manner.
This is largely due to the fact that the elm modal can be passed custom views from the consumer that satisfy Cmd msgs they determine. In this scenario firing messages internal to the Modal will be seen by consumers and create unnecessary noise. 
The way for a consumer to be alerted when the modal is fully closed or open is to use dispatch helper methods which were confusing and overly complicated to understand. 
Consumers can create custom modals with whatever Cmd msgs they want and also allow the modal to handle the internal stuff without bothering the consumer. This is very important for building out a focus management engine in a way that doesn't affect …
=> refactor: Allow modal to send internal Cmd msgs 

site/docs/guidelines/language.mdx
=> docs: Delete "e.g." section in language guidelines

packages/design-tokens/tokens/color.ts
BREAKING CHANGE:
* Sass and Less tokens will now strictly follow the kebab case convention.
* Sass and Less variables are all lower-case
Context: 
I accidentally removed the `BREAKING CHANGE` from the commit footer when I merged the previous commit. This means it was released as a patch (the default) instead of a major release. Instead of rolling back and removing the published package from NPM this is a bit of a dummy commit with some better comments that I will use as the major release.
=> refactor: Rebuild as major change

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.elm, packages/component-library/draft/Kaizen/Modal/Primitives/Constants.elm, packages/component-library/draft/Kaizen/Modal/Primitives/GenericModal.scss, packages/component-library/draft/Kaizen/Modal/Primitives/ModalHeader.elm, packages/component-library/stories/ModalStories.elm
The elm modal currently doesn't place browser focus on to a default focusable element within the modal view. This is problematic as the focus is likely left under the modal somewhere which is not ideal for accessibility or general modal ease of use.
issue: https://github.com/cultureamp/kaizen-design-system/issues/172
This PR Follows https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role advice that the modal focus should be placed on to a default focusable control such as the Confirm button.
When the elm modal is forced open without a user action (storybook examples) subscriptions trigger the update of the modal so that all the Cmds run and the default focus is set.
Whilst we might usually want the Confirm/Action button to be focused on open the PR has allowed …
=> feat: Elm modal focus first focusable element

packages/design-tokens/tokens/typography.json
This adds tokens to represent our data-related type styles, as shown below:
The units like `$%` are not a consistent proportion to their numerical text.
- For the `large` and `medium` styles, the units' font size is 50% of the numerical text font size.
- For the `small` style, the units' font size is 75% of the numerical text font size.
Two potential ways of solving this:
1. Create 3 extra full type styles just for the units, like `dataLargeUnits` to sit alongside `dataLarge`. A bit gross, but simple and easy.
```
"dataLarge": {
"fontFamily": "\"Greycliff CF\"",
"fontWeight": "700",
"fontSize": "5.25rem",
"lineHeight": "5.25rem",
"letterSpacing": "normal"
},
"dataMedium": {
"fontFamily": "\"Greycliff CF\"",
"fontWeight": "700",
"fontSize": "3rem",
"lineHeight": "5rem",
"letterSpacing": …
```
=> feat: Add type styles for data

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/stories/ModalStories.elm
Instead of returning Cmd ModalMsgs when triggering the modal it makes
more sense to simply ask the modal to run. This is a simple field in the
modal data that will be picked up by subscriptions.
This will then trigger the modal update in which case the modal can do
all the normal things it was doing previously. This moves all the modal
running logic to just one flow.
Old trigger
```
triggerModal : (ModalState msg, Cmd (ModalMsg), ModalStatus)
triggerModal =
trigger modalState
```
New trigger
```
triggerModal: ModalState msg
triggerModal =
trigger modalState
```
=> refactor: Make elm modal completely dependant on subscriptions

packages/component-library/draft/Kaizen/Form/CheckboxField/CheckboxField.tsx, packages/component-library/draft/Kaizen/Form/Primitives/Checkbox/Checkbox.tsx
This PR adds the ability to set a tab index on a Checkbox and CheckboxField.
The motivation behind it was that I wanted to have a checkbox that was purely presentational, so to do that I needed to set the `tabIndex` of the checkbox as -1.
=> feat: Add ability to set a tab index on a Checkbox and CheckboxField

packages/component-library/components/Button/Button.elm
Set focus and blur attributes on the Button component.
Elm modal when handling focus-lock will need these attributes on the buttons that are used in Confirmation variants.
=> feat: set focus and blur attributes

packages/component-library/components/Button/Button.elm
We are using elm 19 exclusively so this PR removes uses of Elm18 compatible modules for the Button component.
=> fix: remove elm18 module reference

packages/component-library/components/Text/Text.elm, packages/component-library/components/Text/Text.module.scss, packages/component-library/components/Text/Text.tsx, packages/component-library/stories/Text.stories.tsx, packages/component-library/stories/TextStories.elm, storybook/preview.ts
This adds optional Zen headings and hero data styles to the React and Elm Text components
https://dev.cultureamp.design/dst/text-component-zen-headings/storybook/
=> feat: Add Zen headings and hero data styles to Text component

packages/component-library/package.json
add `@kaizen/deprecated-component-library-helpers` dependency to `packages/component-library`
Not having this causes builds to break when the package is consumed.
=> fix: add @kaizen/deprecated-component-library-helpers depency to packages/component-library

packages/component-library/components/Text/Text.module.scss
Depending on the specific webpack setup, this was previously breaking builds.
=> fix: fix an scss import statement in Text.module.scss

packages/component-library/components/Button/Button.elm
This adds the ability to prevent default behaviour on keydown when
interacting with the button.
The modifier function takes a list of decoders provided by the consumer.
The successful decoders will prevent default behaviour.
Say we want to prevent default behaviour when the user presses 'tab' on the button.
```
Button.view (Button.default |> Button.preventKeydownOn [isTabDecoder]) "Button"
```
The elm Modal component handles focus lock which is important for overall modal accessibility. It internally uses the Button component and needs to be able to prevent the default behaviour of the Tab key in specific situations 
e.g. When the user is focused on the first focusable element and shift/tabs. We prevent the native tab which will place the focus somewhere outside the modal and instead …
=> feat: Add prevent default on keydown to Button

packages/component-library/styles/fonts.scss
Webpack will resolve to the JavaScript index file and tries to parse it as Sass, for some reason (at least in BFR)
Update the import path to directly reference the name of the file
=> fix: Use correct import path for hosted-assets sass file in fonts

packages/component-library/draft/Kaizen/Events/Events.elm, packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.elm, packages/component-library/draft/Kaizen/Modal/Primitives/ModalBody.elm, packages/component-library/draft/Kaizen/Modal/Primitives/ModalHeader.elm, packages/component-library/draft/Kaizen/UserInteractions/KeyCodes.elm, packages/component-library/draft/Kaizen/UserInteractions/Keyboard.elm, packages/component-library/stories/Modal.stories.tsx, packages/component-library/stories/ModalStories.elm
Elm modal was previously not handling focus. This meant when the modal opened the focus was left somewhere on the main page and not with the content within the modal.
Also, if focus did happen to be within the modal content, a user could essentially tab focus their way out of the open modal.
In order to properly manage focus we create a focus-lock. Essentially this traps focus within the confines of the first and last focusable elements of the modal content.
If focus for example is on the last focusable element and the user "tabs", we reset focus onto the first focusable element. The same applies for focus on the first focusable element i.e. shift tabbing would set focus to the last focusable element.
Currently focus lock works for Confirmation variants only. This is because they are …
=> feat: apply focus lock on modal

packages/hosted-assets/README.md
There's a bug where css-loader will use node's package resolution strategy for scss imports, and so follows the `main` key in the package.json for imports which only specify the package name. This results in the published javascript being parsed as css during builds in consuming projects.
This change updates the API docs for this package to specifically recommend importing the scss file.
=> docs: Fix sass module resolution issue in package docs

packages/component-library/package.json
The `Text.module.scss` file is importing a file that doesn't exist in the version of `design-tokens` that's listed as the peer dependency.
Bump to the correct version
=> fix: Bump design-tokens peer dependency

packages/component-library/package.json
fix: Added @kaizen/hosted-assets as a dependency of @kaizen/component-library, as it is used in font-face.scss
see here: https://github.com/cultureamp/kaizen-design-system/blob/master/packages/component-library/styles/type.scss#L1
=> fix: Added @kaizen/hosted-assets as a dependency of component library

packages/deprecated-component-library-helpers/package.json
I don't know that this is currently specifically causing any issues, but it's a timebomb waiting to happen.
This would break any consuming project that doesn't have `@kaizen/design-tokens` somewhere in the `node_modules` hierarchy.
=> fix: add missing @kaizen/design-tokens dependency to deprecated-component-library-helpers

packages/component-library/draft/Kaizen/TitleBlock/NavigationButton.scss, packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.scss
This PR uplifts the heading of the Title Block from Ideal Sans to Greycliff.
It uses styles Heading 1, 2 and 3 for the desktop, tablet and mobile viewport widths respectively:
The Title Block is currently only used in Murmur, so it can be safely uplifted without causing issues in other repos. It is being uplifted as part of the work Design Systems Team is doing as part of our rollout of the typography uplift in Murmur.
=> feat: Uplift Title Block heading to Greycliff

packages/component-library/draft/Kaizen/EmptyState/EmptyState.tsx, packages/component-library/draft/Kaizen/EmptyState/styles.scss, packages/component-library/stories/EmptyState.stories.tsx
- adds optional Zen headings (using the Greycliff font), controlled by a boolean `useZenStyles` prop that is false by default
- updates all Storybook stories to use this prop by default
- adds an extra Storybook story to demonstrate the legacy version without the prop
Design Systems Team is uplifting Murmur now, and Perform soon. Murmur uses the Empty State component consistently, but Perform uses a forked version of it _except in one particular case where it uses the Kaizen Empty State_.
Because of this, we want to uplift the Empty State as part of our Murmur work without making the single Empty State instance in Perform look strange. This prop means we can ship the Murmur uplift by using the prop without affecting the instance of it in Perform.
The Perform Empty State can then be …
=> feat: Uplift Empty State with Greycliff headings

packages/component-library/draft/Kaizen/EmptyState/EmptyState.elm
=> feat: use zen css styling for Elm Empty State by default

packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.scss
There was a recent update to the Title Block that added an explicit color rule, so that the Title Block would stop inheriting its default text color from its container.
Unfortunately the color rule was put on the wrong class, so that the `.reversed` class that overrides the color with `#fff` was not overriding it properly, leading to the following bug (see barely visible Wisteria text):
This PR moves it to the correct class.
=> fix: Fix Title Block color bug

packages/component-library/components/Paragraph/Paragraph.elm, packages/component-library/components/Paragraph/Paragraph.module.scss, packages/component-library/stories/Paragraph.stories.elm, packages/component-library/stories/Paragraph.stories.tsx
Usage is very similar to the Heading component for Elm. Variant is the only required property, and there's also support for tags, classNames (AndIHaveSpokenToDST), ids, and data attributes.
```
Paragraph.view
(Paragraph.p |> Paragraph.variant IntroLede)
[ Html.text "IntroLede Paragraph" ]
```
=> feat: Paragraph component for Elm

site/gatsby-config.js
This change addresses an issue in the gatsby build for kaizen site, where kebab-cased classnames for the new `Heading` component were being dropped from the CSS modules classnames.
Example build: https://dev.cultureamp.design/louis/fix-gatsby-kebab-demo/
=> build: Don't transform kebab-cased classnames in gatsby

packages/component-library/components/Paragraph/Paragraph.module.scss, packages/component-library/components/Paragraph/Paragraph.spec.tsx, packages/component-library/components/Paragraph/Paragraph.tsx, packages/component-library/components/Paragraph/__snapshots__/Paragraph.spec.tsx.snap, packages/component-library/components/Paragraph/index.tsx, packages/component-library/stories/Paragraph.stories.tsx
Paragraph only has one required prop, which is variant. The options are identical to the Zen UI Kit in Figma: `intro-lede`, `body`, `small`, `extra-small`. 
Usage is similar to the Heading component: 
```
<Paragraph variant="body">
Some text, or nest other <Link>Components</Link>.
</Paragraph>
```
`data-*`, `tag` and `classNameAndIHaveSpokenToDST` are all optional props.
=> feat: Paragraph component for React

yarn.lock
Majority of these were originating from older versions of Jest and Gatsby.
Before: 
After:
=> chore(deps): Updated lock file to remove vulnerable dependencies

packages/component-library/stories/Modal.stories.tsx, packages/component-library/stories/ModalStories.elm
... to avoid surprises whether a story will automatically
open the modal or not
=> docs: make Elm modal stories more descriptive

packages/component-library/components/Button/styles.scss
If a button has a icon inside, the text only has the right/left margin
If a button has no icon inside, the text has the both right left margin which makes the button bigger
=> fix: Remove text margin in the button

packages/component-library/components/Button/styles.scss
Reverts cultureamp/kaizen-design-system#338
I was too eager to approve this PR. I think this PR and https://github.com/cultureamp/kaizen-design-system/pull/339 need to be QA'ed and released at the same time to avoid breakages, as they are related to one another, so I want to hold off on releasing this until we have a better plan for QA.
=> fix: revert "Remove text margin in the button"

packages/component-library/components/Button/styles.scss
Reverts cultureamp/kaizen-design-system#340, which was a revert of https://github.com/cultureamp/kaizen-design-system/pull/338.
Please see https://github.com/cultureamp/kaizen-design-system/pull/338 for a description of changes that this PR will introduce.
The original PR was reverted because we didn't have a QA plan in place and there was a danger that the Kaizen change would be released to Murmur before it was QA'ed. We have a QA plan now: this PR and https://github.com/cultureamp/kaizen-design-system/pull/339 will be released and QA'ed at the same time as they are related.
=> fix: unrevert "Remove text margin in the button""

packages/component-library/components/Dropdown/Dropdown.module.scss, site/docs/components/icon-button.mdx
There is a padding around all buttons:
But there is no padding around the dropdown:
So when we have button+dropdown, it looks like the edit icon is in the middle:
What's the new expected behaviour?
Add the same padding around the dropdown.
=> fix: Add padding in dropdown

README.md
Users often encounter issues with Yarn that can be solved by Yarn. Adding a note to the README might help make this clear to readers.
=> docs: Add note on yarn errors

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.elm, packages/component-library/stories/Modal.stories.tsx, packages/component-library/stories/ModalStories.elm
BREAKING CHANGE: everywhere the modal is used will need to now have the 'onConfirmDisabled' in the config
Context:
- I'm looking to create something like an ApplyChanges confirmation modal in Elm - where the user has to input a number that matches for example the number of ignored users, before going ahead with their employee data import and applying the changes. 
- If the user hasn't entered any numbers or entered a number that doesn't match, the confirm button should be disabled.
Example screenshot of current react modal I'm trying to have in Elm.
=> feat: add disabled confirmButton feature to elm modal

package.json, yarn.lock
`minimist` was a transitive dependency of `lerna`. Upgrading `lerna` to the latest version did not fix the vulernatbility (it appears that `lerna` has not upgraded it yet), so I used the `resolutions` feature of yarn/npm to upgrade the transitive dependency.
I left in the lerna upgrade, because why not.
=> fix: update minimist transitive dependency to fix vulnerability

packages/deprecated-component-library-helpers/styles/type.scss
The greycliff heading mixins in `@kaizen/deprecated-component-library-helpers` did not have any `font-family` fallbacks, and they were overriding any font-family fallbacks set in `body` tags.
**Note:** the storybook book stories are just temporary for QA. They are necessary to be able to QA this, but we don't want them on the public site. The plan is that once this is approved, I'll remove the commit with the stories before releasing (I cherry picked the commit from a previous PR)
This shows the font falling back to Helvetica (I just changed the Greycliff name in dev tools). Previously it would fall back to the default system font (a serif font)
=> fix: add missing font-family fallbacks to zen heading mixins

packages/component-library/draft/Kaizen/Modal/Modal.elm, packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.elm
The feature to be able to disable the confirm button broke the focus-lock implementation to Confirmation variant modals.
In the case the confirm button is disabled the footer dismiss button will be promoted to the last focusable element. Setting the focusable attributes on that the dismiss button doesn't disrupt the focus-lock implementation.
=> fix: Focus lock fix when confirm button disabled

packages/component-library/components/Heading/Heading.elm, packages/component-library/components/Heading/Heading.module.scss, packages/component-library/components/Heading/Heading.spec.tsx, packages/component-library/components/Heading/Heading.tsx, packages/component-library/components/Heading/__snapshots__/Heading.spec.tsx.snap, packages/component-library/components/Paragraph/Paragraph.elm, packages/component-library/components/Paragraph/Paragraph.tsx, packages/component-library/stories/Heading.stories.elm, packages/component-library/stories/Heading.stories.tsx
- added the `color` prop to both the React and Elm components
- make sure both components are correctly applying `.small` and `.large` classes, which affect the color output if the `color` prop is set to `positive` or `negative` (if the `variant` is a Heading 2 or larger, it should get `.large` and it will be a different colour to Heading 3 or smaller, which gets `.small`).
- updated both React and Elm stories
- updated the React spec
- removed the `a` tag as an available option for both the React and Elm components (see below)
This was following up on a discussion that DST had where we agreed that anchor tags do not belong here. Links tends to wrap things completely, or wrap a piece of text inside a larger bit of text. That means that you would be more likely to **pass in a link as a …
=> feat: Add color to Heading

packages/component-library/components/Paragraph/Paragraph.elm, packages/component-library/components/Paragraph/Paragraph.module.scss, packages/component-library/components/Paragraph/Paragraph.spec.tsx, packages/component-library/components/Paragraph/Paragraph.tsx, packages/component-library/components/Paragraph/__snapshots__/Paragraph.spec.tsx.snap, packages/component-library/stories/Paragraph.stories.elm, packages/component-library/stories/Paragraph.stories.tsx
This follows the recently-shipped PR that adds color support to the Heading component (https://github.com/cultureamp/kaizen-design-system/pull/343).
It uses the same `AllowedColors` types as the Heading, but removes the distinction of positive and negative colors being over 24px or under, since all paragraph type styles are under 24px.
Updated:
- React component
- React unit tests
- React snapshot tests
- React stories
- Elm component
- Elm stories
=> feat: Add color support to Paragraph component

packages/component-library/components/NavigationBar/NavigationBar.module.scss
=> fix: Adjust active link color for content colorscheme

packages/component-library/package.json, yarn.lock
This allows elm programs in storybook to leverage ports and execute
javascript.
Creating elm views that rely on ports brings up questions around how
this dependency is communicated to consumers.
Ongoing discussions are being had with the design systems team around
documentation.
The use of ports as it stands should ideally be used as a performance
enhancer to a problem not able to be solved with Elm alone.
=> chore: Bump elm-storybook

draft-packages/well/tsconfig.dist.json
This broke master :/ 
The build was trying to find a config file that does not exist: 
https://buildkite.com/culture-amp/kaizen-design-system/builds/1966#3ea6bceb-f21e-46cb-942a-4924d3a03483
=> fix: Point to correct tsconfig file

packages/component-library/draft/Kaizen/Tabs/styles.scss
* Tweak the vertical centering of the `Tab` component. When I added these tabs to the preform site, they were added to a sticky header, which made them positioned flush up against the top of the viewport, and therefore they looked a bit misaligned.
The fix I implemented was to add an invisible top border, as to compensate for the bottom one.
Before:
After:
=> feat: Tweak the vertical centering of the Tab component

packages/component-library/components/NavigationBar/components/Menu.tsx, packages/component-library/components/NavigationBar/types.ts
- needed to implement correct routing in performance-ui
=> feat: allow menu items to return click event

packages/component-library/components/Button/styles.scss
Reverts cultureamp/kaizen-design-system#401
This appears to be causing issues with IconButton alignment, so this is being reverted.
The bug in IE11 is much less impactful than the bug that's this PR was affecting IconButton. Let's revisit the IE11 issue after this has been reverted.
=> fix: revert "update caButtonContainer display type to avoid IE11 issue"

packages/component-library/draft/Kaizen/Modal/README.mdx
Adding to modal documentation about not using custom spot illustrations on confirmation variants of the modal component.
=> docs: Custom illustrations in confirmation modals

site/docs/guidelines/typography.mdx
This PR updates our typography guidelines to recommend Greycliff, Inter, and IBM Plex Mono.
Branch preview:
- https://dev.cultureamp.design/dst/update-typography-guidelines/guidelines/typography/
Out of scope: updating the numerical variant guidelines.
=> docs: update typography guidelines

site/docs/components/divider.mdx
This PR adds:
- **Content dividers** are used to separate content within a card, table, or any white content area.
- **Canvas dividers** are used on the canvas (not cards) to separate large blocks of content. For example, a canvas divider is used to define the area under the [Title Block](/components/title-block) to create a single hierarchical plain at the top of the page.
=> docs: update docs for content/canvas dividers

.buildkite/pipeline.yaml
We are very quickly burning through our open source plan snapshot limit. We are already on 18000 / 35000, and that's after 2 days. This is not going to work if we do a chromatic build on every commit. So, this makes it optional - you would generally only do it on the final commit of a PR. This was a very quick PR, and there might be a better sequence (such as not having to wait for the dev site build), but it works .
**I'm really concerned about burning our credits and having to wait a month.** That would be a real bummer, as there are lots of useful things we can do with this over the next month. This is out of scope for our current work, but I think this quick fix is much better than the current config which will burn all our credits within the next day or two.
It looks like this if you …
=> ci: make chromatic build optional

packages/deprecated-component-library-helpers/styles/layout.scss
Copy the `layout.scss` to `deprecated-component-library-helpers`.
This is
- because we eventually want to do this anyway, and
- so that the new Button draft component can get all its style imports from either `design-tokens` or `deprecated-component-library-helpers` without having a `component-library` import in there as well.
I.e. after this change, the draft component Button styles can look like this:
=> feat: Copy layout styles to deprecated-helpers pkg

draft-packages/modal/KaizenDraft/Modal/Modal.elm, draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.elm, draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.scss, draft-packages/stories/ModalStories.elm
We extend the input edit modal to be able to receive generic children as opposed to be scoped only to the input text fields as before.
The driver decision for this was when we wanted a modal containing a dropdown. We realised that the current implementation would accept only text fields and instructional text. There was no flexibility.
We combed the code looking for usages. Seems like only the story board was actually using it.
=> feat: pass arbitrary children to input edit model instead of text fields

draft-packages/stories/TextAreaField.stories.tsx, draft-packages/stories/TextField.stories.tsx, packages/component-library/draft/Kaizen/Form/TextAreaField/TextAreaField.tsx
Adds a couple of props to `TextAreaField`, with the same functionality as the equivalent props on `TextField`:
Description:
Inline (removes the bottom margin):
=> feat: Create description prop for TextAreaField

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuGroup.tsx, draft-packages/zen-off-canvas/KaizenDraft/ZenOffCanvas/ZenOffCanvas.tsx
When a user in the mobile nav clicks into a sub-menu, the navigation closes thinking there has been a route change. This has been fixed by checking if a trigger before triggering the nav change event.
Also added missing keys in list renders.
=> fix: bugfix for navigation route change

draft-packages/stories/Table.stories.tsx, draft-packages/table/KaizenDraft/Table/Table.spec.tsx, draft-packages/table/KaizenDraft/Table/Table.tsx, draft-packages/table/KaizenDraft/Table/index.ts, draft-packages/table/KaizenDraft/Table/styles.scss
1. Enable the `TableHeader` to accept an optional prop to override the background color.
2. Revert the box shadow on the `TableCard` back to previous post-feedback.
Slack convos based on tickets:
- https://cultureamp.slack.com/archives/CETLTFG9G/p1588587636273700
- https://cultureamp.slack.com/archives/CETLTFG9G/p1588295755236700?thread_ts=1588295755.236700
- https://cultureamp.slack.com/archives/CHZQVHRK5/p1588295527203600
- https://cultureamp.slack.com/archives/CHZQVHRK5/p1588119044429700?thread_ts=1588118180.426800
- https://cultureamp.slack.com/archives/CHZQVHRK5/p1588553720324800?thread_ts=1588553720.324800
- https://cultureamp.slack.com/archives/CHZQVHRK5/p1588761923140000?thread_ts=1588760979.139100
JIRA tickets:
- https://cultureamp.atlassian.net/browse/FOW-1140
- …
=> feat: Extend TableHeader API for bg colors + revert box shadow

draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx
This PR updates the draft packages version of TextAreaField so that it's up to date with the component library version. A previous PR had accidentally shipped the changes there and the corresponding stories to draft packages, so the stories for this already exist.
See https://github.com/cultureamp/kaizen-design-system/pull/464 for the original PR.
=> feat: Add description prop to TextAreaField

draft-packages/select/KaizenDraft/Select/Select.tsx
`react-select` has this frustrating type on their `onChange` prop. This hasn't been any issue for us so far because in Flow you don't have to specify the type for this param, but in TypeScript we have to. So we'll need this `ValueType` type.
https://github.com/JedWatson/react-select/issues/2902
=> chore: Export ValueType from react-select in Select

packages/component-library/draft/Kaizen/Select/Select.tsx
I forgot to update both versions of `Select` in https://github.com/cultureamp/kaizen-design-system/pull/494
=> fix: Add ValueType export to old component-library location as well

packages/component-library/draft/Kaizen/Table/Table.tsx, packages/component-library/draft/Kaizen/ZenNavigationBar/NavigationBar.tsx, packages/component-library/draft/Kaizen/ZenNavigationBar/components/Menu.tsx, packages/component-library/draft/Kaizen/ZenOffCanvas/ZenOffCanvas.tsx, packages/component-library/draft/Kaizen/ZenOffCanvas/components/Header.module.scss, packages/component-library/draft/Kaizen/ZenOffCanvas/components/Header.tsx
Some components in (now deprecated) drafts were incorrectly linking to the new draft packages. 
This was changed when we last did a large sweep of Kaizen to change any draft imports.
=> fix: Make Navigation Bar consume core components

draft-packages/select/KaizenDraft/Select/index.ts, packages/component-library/draft/Kaizen/Select/index.ts
I missed this part in https://github.com/cultureamp/kaizen-design-system/pull/494 and https://github.com/cultureamp/kaizen-design-system/pull/495
=> fix: Export ValueType from Select index.ts

draft-packages/checkbox-group/package.json, draft-packages/collapsible/package.json, draft-packages/dropdown-menu/package.json, draft-packages/dropdown/package.json, draft-packages/empty-state/package.json, draft-packages/events/package.json, draft-packages/form/package.json, draft-packages/guidance-block/package.json, draft-packages/hero-card/package.json, draft-packages/hero-panel/package.json, draft-packages/loading-placeholder/package.json, draft-packages/menu-list/package.json, draft-packages/modal/package.json, draft-packages/popover/package.json, draft-packages/radio-group/package.json, draft-packages/radio/package.json, draft-packages/select/package.json, draft-packages/split-button/package.json, draft-packages/table/package.json, draft-packages/tabs/package.json, draft-packages/tag/package.json, draft-packages/title-block/package.json, draft-packages/tooltip/package.json, draft-packages/user-interactions/package.json, draft-packages/vertical-progress-step/package.json, draft-packages/well/package.json, draft-packages/zen-navigation-bar/package.json, draft-packages/zen-off-canvas/package.json
They should not be pinned to a specific patch version. This causes a lot of peer dependency warnings in other packages.
=> fix: unpin unintentionally pinned @kaizen/design-token peer dependencies

draft-packages/menu-list/KaizenDraft/MenuList/MenuList.elm
* The Elm styles in Menu List were broken in the last big find and replace
=> fix: Menulist styles linking to incorrect location

draft-packages/select/KaizenDraft/Select/Select.elm
When using a Multi Select variant and having some text populated in the
input, deleting a tag whilst focused should not resize the input.
This follows the react select functionality.
This bug was only present when using the `usePorts` is `True` config modifier.
=> fix: Conditionally dispatch port for Multi Select variant

draft-packages/dropdown-menu/KaizenDraft/DropdownMenu/DropdownMenu.elm
This was found by this quick Python script for linting Elm css references which aren't currently picked up by CI:
```
import os
import shutil
import subprocess
import re
import os.path
kaizen_dir = "../kaizen-design-system"
draft_packages_dir = kaizen_dir + "/draft-packages"
os.chdir(draft_packages_dir)
grep_cmd = "grep --no-filename -r ' css \"' ."
def lint_absolute_css_path(path):
regex = "\@kaizen\/draft-([a-z-]*)(\/.*)"
regex_result = re.match(regex, path)
relative_path = regex_result.group(1) + regex_result.group(2)
if not os.path.exists(relative_path):
print("'{}' does not exist".format(path))
kaizen_paths = []
code_lines = subprocess.check_output(grep_cmd, shell=True).splitlines()
for code_line in code_lines:
code_line_str = str(code_line)
path = code_line_str.split('"')[1]
if …
```
=> fix: Elm css reference to DropdownMenu.scss was broken

draft-packages/stories/ZenNavigationBar.stories.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Badge.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Dropdown.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.tsx, draft-packages/zen-off-canvas/KaizenDraft/ZenOffCanvas/components/Menu.tsx, yarn.lock
- Mobile menu now uses ellipses instead of arrows to suggest sub-menu
- Navigation spacing has been reduced
- Navigation bar height has been reduced
- Divider now present between secondary menu and final menu in mobile navigation
- Fixed bug where dropdown gap was calculated in percentages
- Removed duplications from storybook story
=> feat: navigation bar spacing alterations

draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx, draft-packages/stories/Modal.stories.tsx
The current `<GenericModal>` implementation has an issue with iOS VoiceOver where the focus lock implementation allows focus to escape if someone uses the swipe left/right gestures to move focus.
This PR fixes that issue by adding `aria-hidden="true"` attributes to every direct descendant of the `<body>` that _isn’t_ a parent of the passed reference modal node, and then undo-ing that change once the modal is closed.
The implementation is cribbed directly from the [reach-ui implementation solving the same issue](https://github.com/reach/reach-ui/blob/de0655b2de8698f5e7add2e4507dee5062750b36/packages/dialog/src/index.tsx#L320-L362).
You should be able to confirm the existing behaviour/new on these pages with VoiceOver on:
* [Broken focus lock in …
=> feat: Ensure focus-lock for modals when using iOS VoiceOver [CAP-54]

.buildkite/dockerfiles/publish.Dockerfile, .buildkite/dockerfiles/release.Dockerfile, docker-compose.yml
Fixes an error when building these images, which was introduced when the latest tag moved to 3.12
See: https://buildkite.com/culture-amp/kaizen-design-system/builds/2780
=> ci: Specify alpine 3.11 in publish/release steps

draft-packages/select/package.json
`draft-select` depends on some styles from form, which are not specified in `draft-select`s package.
=> fix: Removed circular dependency and added form as a dependency

.prettierignore, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.scss, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleContext.ts, draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss, draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/constants.ts, draft-packages/modal/package.json
[🎫 ](https://cultureamp.atlassian.net/jira/software/projects/CAP/boards/80?selectedIssue=CAP-67)
The existing behaviour for modals is that when they open we let the `<FocusLock>` component from the `react-focus-lock` package handle auto-focusing whatever it thinks is the "right" element to focus on (usually the first button or input element).
This isn’t ideal for a couple of reasons:
1. From an accessibility perspective, as a default, it means we can skip over framing content that is important for screen readers
2. It causes blocking issues on iOS using VoiceOver when it tries to auto-focus on a textarea — the keyboard isn’t invoked when the input is focusesd and is impossible to invoke.
After much discussion about the right default behaviour, we’ve decided that the best default rule …
=> feat: Change default behaviour for modal focus [CAP-67]

CONTRIBUTING.md
The contributing docs didn’t explicitly mention the `draft-*` packages, and so I was momentarily confused. Hopefully this means those that follow are not :)
=> docs: Add note on using draft components with yarn link

draft-packages/button/KaizenDraft/Button/Button.elm, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx
Mousedown events fire before blur events and this is handy for when we need to stop native browser behaviour.
Icon buttons for example can control a RTE (Rich Text Editor) by toggling text modifiers on and off such as Bold, Italic etc. Clicking these modifier buttons will currently remove focus from the focused editor. Typically this is not an ideal flow as the cursor should not leave the editor. 
To achieve this we need to intercept the onMouseDown event of the button component which fires before the input blur. We can then `preventDefault()` and stop the editor from losing focus.
=> feat: add mousedown event handler

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/form/KaizenDraft/Form/CheckboxField/CheckboxField.tsx, draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.tsx, draft-packages/form/KaizenDraft/Form/Primitives/ToggleSwitch/ToggleSwitch.tsx, draft-packages/form/KaizenDraft/Form/ToggleSwitchField/ToggleSwitchField.tsx, packages/component-library/components/Button/components/GenericButton.tsx
With the new form validations in perform, we would like to keep track of the "touched" state of each field, as so we can determine when best to show an inline validation error.
This PR adds the `onFocus` and `onBlur` callbacks, as to allow for this.
The affected components are the Buttons, Checkboxes, and ToggleSwitches
=> feat: Add blur and focus callbacks to form components

packages/component-library/styles/type.scss
We attempted to point existing usages to the `deprecated-component-library-helpers` so that this wouldn't be necesdsary, but the Kaizen build doesn't pick everything up (thanks to scss implicit imports). We don't find out until we try to build in another repo, which is extremely time consuming. This should fix any ca-inter-xxx usages missing imports.
So, now there are two copies of these mixins, one in `packages/component-library/styles/type.scss` and one in `packages/deprecated-component-library-helpers/styles/type.scss`. The latter is the one we want to keep - we want to delete `packages/component-library/styles/type.scss` entirely but it's difficult to do, becuase there may be implicit imports that can't easily be detected (and don't even get detected by the Kaizen build)
Part of the …
=> fix: Copy inter mixins from helper packages back to legacy type.scss

packages/component-library/styles/type.scss
As part of a sweeping rename of $ca-type-ideal-sans-xxx to $ca-type-inter-xxx, the type.scss files were meant to be left alone, but this snuck in due to human error (it me)
=> fix: a legacy var was accidentally renamed

draft-packages/well/styles.scss
Does what it says on the tin.
Note: the way we’re setting no-border has changed to use a transparent border rather than removing the border so we need to change the order of all the rules to ensure the colour rules are last.
=> fix: Update <Well> to latest colours/tokens

draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/styles.scss
Bootstrap styles in murmur mess with the width, height and margin
properties of the kaizen checkbox. This specificity hack overrides those
styles.
=> fix: use specificity hack to overide bootstrap styles

draft-packages/button/index.ts
In order for other components to enforce type restrictions in their APIs to force consumers to pass in a Button component, we need to expose the props so that they can be accessed.
Two use cases for this are:
1. In TitleBlockZen, where we may choose to accept only Buttons as children,
2. In Menu, where we only want a Button to be used as the clickable area (for now).
=> feat: Expose ButtonProps

draft-packages/menu/KaizenDraft/Menu/Menu.spec.tsx, draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/menu/KaizenDraft/Menu/__snapshots__/Menu.spec.tsx.snap, draft-packages/menu/KaizenDraft/Menu/components/MenuContent.module.scss, draft-packages/menu/KaizenDraft/Menu/components/MenuContent.tsx, draft-packages/menu/KaizenDraft/Menu/components/MenuHeader.tsx, draft-packages/menu/KaizenDraft/Menu/components/MenuItem.tsx, draft-packages/menu/KaizenDraft/Menu/components/MenuSeparator.tsx, draft-packages/menu/KaizenDraft/Menu/styles.scss, draft-packages/menu/index.ts, draft-packages/menu/package.json, draft-packages/menu/tsconfig.dist.json, draft-packages/stories/Menu.stories.tsx
- Creates a new draft component called `Menu`. (We had discussions about the name – `dropdown`, `dropdown-menu` are already names of draft packages, which limited the choices here.)
- This component mixes together the existing `Dropdown` and `MenuList` components into one thing, while exposing the Menu stuff for consumers to build their own menus.
- It allows consumers to pass in any Button they want, including IconButtons (such as kebabs/meatball icons).
A number of engineers have never been happy with the dropdown/menu situation. We currently have two components, `Dropdown` and `MenuList`. `MenuList` is just the content that fills the dropdown menu container, and `Dropdown` provided the container and the clickable button/control action/icon.
A major problem with `Dropdown` is that it …
=> feat: Create Menu component

packages/component-library/styles/type.scss, packages/deprecated-component-library-helpers/styles/type.scss
These were incorrectly set to `400` which as the same as the regular styles.
FYI, the reason that there are two copies of these mixins (`packages/component-library/styles/type.scss` and `packages/deprecated-component-library-helpers/styles/type.scss`), is that originally we deleted the ones in `packages/component-library/styles/type.scss` but ran into a problem where a consuming package was using an older version of a package that was expecting them due to peer dependencies (it's confusing). 
Once all consuming repos and packages have been upgraded, we will be able to delete `packages/component-library/styles/type.scss` which should be considered deprecated+++
=> fix: correct font weights for legacy ca-type paragraph bold mixins

draft-packages/button/KaizenDraft/Button/styles.scss, draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/styles.scss, draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.elm, draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.tsx, draft-packages/form/KaizenDraft/Form/Primitives/Input/styles.scss, draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.tsx, draft-packages/form/KaizenDraft/Form/Primitives/TextArea/styles.scss, draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx, draft-packages/stories/TextAreaField.stories.tsx, draft-packages/stories/TextField.stories.tsx, packages/component-library/styles/border.scss
Two main things...
https://dev.cultureamp.design/dug/textarea-reversed-and-zen/storybook/
I've also updated a couple of colours here and there to match Zen styling.
=> feat: Add focus rings to TextField & TextAreaField + reversed support for TextAreaField

draft-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss
Using titleblock in a new repo causes some layout inconsistencies due to box-sizing. Ideally the component should not need to rely on the consuming app's style to have consistent layout.
Local verification using yarn link confirms the layout inconsistency issue is fixed.
=> fix: Specify box-sizing so layout is consistent without depending on the consuming app

draft-packages/radio/KaizenDraft/Radio/styles.scss
Same follow-up as https://github.com/cultureamp/kaizen-design-system/pull/556 which replicates the behaviour for `<Radio>`.
=> fix: Disable pointer-events on input wrapper for Radio

draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.tsx, draft-packages/modal/KaizenDraft/Modal/Presets/InformationModal.tsx, draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx
Allows us to put automation ids on all types of modals. It will add the automation id to the container and then on each button with a `-action-[index]` suffix.
=> feat: Add automation ids to modal container and actions

draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/styles.scss, draft-packages/radio/KaizenDraft/Radio/Primitives/styles.scss
This is so the styling doesn't conflict with codebases with the `*:after { box-sizing: border-box }` hack (such as `performance-ui`).
Before:
After:
=> fix: Explicitly set the box-sizing for the checkbox & radio focus ring

CODEOWNERS
Draft packages were separated from "core Kaizen" with the intention of teams having the ability to iterate quickly on components, while not affecting other stable components in the system.
Now that they've been around for a little while, and we have [better support for creating components](https://github.com/cultureamp/kaizen-design-system/tree/master/packages/generator) and slightly better [quality control](https://github.com/cultureamp/kaizen-design-system/pull/545) and [testing](https://github.com/cultureamp/kaizen-design-system/pull/224) we're in a position to ease up the need for DST to review all changes draft components. We hope that teams still reach out to us if they need our support or they're unsure about how to contribute.
=> ci: relinquish control of draft packages

draft-packages/stories/ZenNavigationBar.stories.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Badge.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Link.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/types.ts, draft-packages/zen-off-canvas/KaizenDraft/ZenOffCanvas/OffCanvas.module.scss, draft-packages/zen-off-canvas/KaizenDraft/ZenOffCanvas/ZenOffCanvas.tsx, draft-packages/zen-off-canvas/KaizenDraft/ZenOffCanvas/components/Header.tsx
Will be used on performance admin pages:
https://www.figma.com/file/q4kRnrtKZnzo2nx2jkyXeD/Perform-headers?node-id=61%3A12160
=> feat: add colour scheme to navigation bar

draft-packages/form/KaizenDraft/Form/Primitives/Label/Label.elm
This adds radio styles to label like its React counterpart.
=> feat: add radio styles to label

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Badge.module.scss, packages/design-tokens/less/layout.less, packages/design-tokens/sass/layout.scss, packages/design-tokens/tokens/layout.json
• Add a new layout token for navigation bar height
This is currently in more than one place, and could conceivably pop up in more places (e.g. setting the top margin on a page underneath the nav bar) so it would be good to have a single implementation of it.
=> feat: Add layout token for nav bar height

draft-packages/select/KaizenDraft/Select/Select.tsx, draft-packages/stories/Select.stories.tsx
The implementation of draft-select rendered `null` for the `ClearIndicator` component. This meant you could use `isClearable` as a prop but it would not actually render the button to allow you to clear it.
=> fix: Add clear button to React Select implementation

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/index.ts
• Exposes `TitleBlockProps` so that consumers can access it as well as its internal types (such as `PrimaryActionProps`).
=> feat: Expose TitleBlockProps from TitleBlockZen

draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/menu/KaizenDraft/Menu/components/MenuContent.module.scss, draft-packages/menu/KaizenDraft/Menu/styles.scss, draft-packages/stories/Menu.stories.tsx
⚠️ This PR contains a BREAKING CHANGE ⚠️ 
Storybook previews: https://dev.cultureamp.design/dst/menu-align-left-right/storybook-static/?path=/story/menu-react--label-and-icon
adds an `align` prop to Menu and MenuDropdown with options `"left"` and `"right"`. Previously rigtht-aligned
was the only option. Now left aligned is an option and it becomes the default. ⚠️ **Consumers must add `align="right"`
to any existing usages to retain identical functionality.** ⚠️ 
- there is now a small gap between the button and the dropdown
- the dropdown is flush to the left/right of the button
The Menu had some functionality so that it would still appear on screen if the bottom of the dropdown dissapears below
the bottom of the screen. I added this story to make sure I hadn't broken that functionality. …
=> feat: Menu is now left aligned by default

draft-packages/badge/KaizenDraft/Badge/styles.module.scss, draft-packages/stories/Badge.stories.tsx
This stops the badge going narrower than a perfect circle when the content is narrow (a "1" for example)
=> fix: add min-width and text-align:center to Badge

draft-packages/button/KaizenDraft/Button/Button.elm, draft-packages/button/KaizenDraft/Button/components/GenericButton.module.scss, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/KaizenDraft/Button/styles.scss, draft-packages/stories/IconButton.stories.tsx
Icon Buttons currently do this on hover:
This is particularly a problem on a "reversed" background, where:
- the button takes on _less_ contrast on hover,
- the fact that the hover state is a transition rather than instantaneous makes it hard to see, and
- the hover state is inconsistent with other types of Buttons.
Eventually, the vision is that Icon Buttons will look like the sticker sheet (rounded touch point backgrounds), so this PR is just a temporary measure to make the Title Block rollout look fresher.
Note that because this is only a change to the new draft package of Button which is not widely used yet, there's less to worry about in terms of pre-existing Icon Buttons.
- Removes the `interactiveIconWrapper` dependency on the `Icon` component that was being used via CSS Modules …
=> fix: Remove IconButton opacity styles

draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.scss
Some of the header colours in the ConfirmationModal do not meet WCAG contrast requirements. This nudges them up a shade to ensure they do.
The modal headers are intended to be uplifted in the not-too-distant-future to these colours anyway, but good to have them accessible in the interim.
=> fix: Ensure headers meet WCAG contrast

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
I had previously attempted to force a value of `true` for the `primary` prop when the consumer passes in a button as the `primaryAction` of TitleBlockZen:
```
export type PrimaryActionProps =
| MenuGroup
| (ButtonWithOnClickOrHref & { primary: true })
```
However TS does not work this way – it treats `true` as a _type_ rather than a value, leading to weird issues on the consumer side, such as this:
It now simply uses a `boolean` type, which can be false, but does its job of forcing the consumer to make a conscious decision about whether or not the button is a Primary one, which was the original intention.
```
export type PrimaryActionProps =
| MenuGroup
| (ButtonWithOnClickOrHref & { primary: boolean })
```
=> fix: Use bool for TitleBlockZen "primary" btn prop

draft-packages/menu/KaizenDraft/Menu/Menu.spec.tsx, draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/StatelessMenu.tsx, draft-packages/menu/index.ts, draft-packages/stories/Menu.stories.tsx
`StatelessMenu` is the same as `Menu` but it does not have any internal state. The consumer holds the state and is responsible for passing the state to the component, and handling user interactions that change that state. This provides much more flexibility than `Menu`, but comes at the cost of needing more setup code.
Story for `StatelessMenu` demonstrating some things you can do: https://dev.cultureamp.design/dst/stateless-menu/storybook-static/?path=/story/menu-react--default-stateless-menu
- New module `StatelessMenu` which tries to re-use as much code from
- In order to achieve code reuse, Menu was significantly refactored to use hooks, so that re-usable view functions could be extracted and re-used between Menu and StatelessMenu. The diff is huge and probably impossible to read - …
=> feat: StatelessMenu

draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
- Consumer must now provide a `handleHamburgerClick` prop for the hamburger to render
- I updated all TitleBlockZen stories to provide that prop (it's the intended look)
- I also added a `cursor: pointer` to the hover state in case the hamburger is ever used on desktop (it only shows at viewport sizes under 1080px).
=> fix: Make TitleBlockZen hamburger render only when handler is provided

draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/menu/KaizenDraft/Menu/styles.scss, draft-packages/stories/Menu.stories.tsx
`dropdownWidth="default"` (the default: fixed width at 248px, this is a non-breaking change)
https://dev.cultureamp.design/dst/menu-dropdownwidth-prop/storybook-static/?path=/story/menu-react--default-kebab
`dropdownWidth="contain"` (optional)
https://dev.cultureamp.design/dst/menu-dropdownwidth-prop/storybook-static/?path=/story/menu-react--dropdown-width-contain
**I also added some JSDocs to the Menu props while I was at it**
=> feat: add dropdownWidth prop to Menu

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx
Does what it says on the tin.
Context:
We had an improvement suggested by Intopia for Capture, that we associate the 'x questions answered' text to our submit button.
=> feat: Add ariaDescribedBy prop to Button

check-install.sh, package.json
We've had a query about storybook not working locally, which is a result of developers not running `yarn install` after pulling a branch. This PR adds `yarn install` to the `storybook` script. 
I was initially worried this would add extra time to run storybook, but in real terms it only adds an additional ~1-2s to the script (assuming the branch is up to date):
```
$ time yarn
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.97s.
real    0m1.282s
user    0m1.589s
```
In my first attempt I wrote a bash script that runs `yarn check --integrity`, [but that will be removed in the near future,](https://github.com/yarnpkg/rfcs/pull/106) and takes a little bit of time.
=> ci: Run yarn before running Storybook

packages/design-tokens/tokens/typography.json, packages/design-tokens/tokens/typography.ts
Adds a `paragraphBodyBold` token to match the small/extra-small versions.
I’ve run the build script locally to check the output and diff gives me these additional lines (no removals):
Sass:
```scss
$kz-typography-paragraph-body-bold-font-family: "Inter", "Noto Sans", Helvetica,
Arial, sans-serif;
$kz-typography-paragraph-body-bold-font-weight: 600;
$kz-typography-paragraph-body-bold-font-size: 1rem;
$kz-typography-paragraph-body-bold-line-height: 1.5rem;
$kz-typography-paragraph-body-bold-letter-spacing: normal;
```
Less:
```less
@kz-typography-paragraph-body-bold-font-family: "Inter", "Noto Sans", Helvetica,
Arial, sans-serif;
@kz-typography-paragraph-body-bold-font-weight: 600;
@kz-typography-paragraph-body-bold-font-size: 1rem;
@kz-typography-paragraph-body-bold-line-height: 1.5rem; …
```
=> feat: Add missing paragraphBodyBold typography token

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx
This PR adds optional `ariaExpanded` and `ariaControls` props to `@kaizen/draft-button`. The button is intended to be used for a menu/dropdown. See https://www.w3.org/TR/wai-aria-practices/#disclosure for more details on intended usage.
=> feat: add aria-expanded and aria-controls props to Zen Button

draft-packages/select/KaizenDraft/Select/README.mdx
This removes excess Figma embeds so that secondary selects are shown on
the main frames as the default selects.
=> docs: update UI guidance for secondary selects

draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/stories/Menu.stories.tsx
Adds the ability to pass a `dropdownId` prop to Menu, which is used by the internal `MenuDropdown` component.
=> feat: add `id` prop to MenuDropdown and Menu

site/docs/guidelines/color.mdx
• Remove the advice to use the custom helper `add-alpha()` from the Kaizen SIte color guidelines.
• Recommend users use the built-in `rgba()` instead.
Until now we have unofficially been following a policy of recommending that users do not use `add-alpha()` for transparency, and instead use the built-in function `rgba()`.
But since this is not set in stone anywhere, this is confusing, and is made worse by the fact that the Kaizen Site is encouraging the opposite.
Firstly, `add-alpha()` was always a redundant function. It does the same thing as `rgba()`, but with a slightly different API – a percentage instead of a decimal for the alpha value. I wrote it when I created `add-tint()` and `add-shade()` because I thought the consistency would be more intuitive to users if all 3 functions …
=> docs: Remove add-alpha from color guidelines

site/src/pages/index.tsx
The main page was built before a Components overview page existed, and this link hadn't been updated to match. Now it links to the overview page correctly.
=> fix: Fix out-of-date component overview link

draft-packages/button/KaizenDraft/Button/FilterDrawerButton.module.scss, draft-packages/button/KaizenDraft/Button/FilterDrawerButton.tsx, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/KaizenDraft/Button/styles.scss, draft-packages/stories/Button.stories.tsx
Adds an optional `additionalContent?: React.ReactNode` prop to `GenericButton`. Can be any React node. Additional content appears to right of the button. Note that this can only be applied to GenericButton, not `Button` or `IconButton`. What this means is that you can't add additionalContent to Button, or IconButton, but you can create a new button type that can take the additionalContent prop. The motivation for this is to be able to add a `Badge` to the `FilterDrawerButton`, which will be used in the `Filter Drawer` component (currently a separate PR that's waiting on this one).
This enables us to create a variant of Button, without needing to change the Button or IconButton APIs (the existing "concrete" buttons). This does require one **slightly controversional change**: `GenericProps` …
=> feat: abillity to add additional content to GenericButton

draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
This PR resolves the issue where there is too much space between the subtitle and tag when both are used simultaneously.
It also makes some minor adjustments to the stories for the component.
=> fix: Fix subtitle and tag bug in Title Block

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/Toolbar.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/matchMedia.mock
- Adds basic tests for primary and default actions (secondary still to come).
- Fixes two bugs relating to:
1. the mobile actions drawer handle not rendering when a default action but no primary action is passed in
2. a missing check for the presence of `title` before checking its length (previously relied on TS to enforce this)
=> fix: Add basic tests for TitleBlockZen

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx, draft-packages/stories/IllustrationScene.stories.tsx, site/docs/components/illustration.mdx, site/src/components/ContentOnly.scss, site/src/components/Footer.tsx, site/src/components/Head.tsx, site/src/components/Layout.tsx, site/src/components/PageHeader.scss, site/src/components/PageHeader.tsx, site/src/pages/404.tsx, site/src/pages/index.scss, site/src/pages/index.tsx
This PR:
- adds the Kaizen Site Language illustrations
- uses the main Kaizen Site Language illustration on the homepage
- adds link to illustration process
- improves accessibility
- updates 404 page links
=> feat: add language illustration

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx, draft-packages/stories/IllustrationScene.stories.tsx
Makes these Manager Lab signup illustrations available:
=> feat: Add Manager Lab signup illustrations

site/src/components/PageHeader.scss
Instead of depending on pre-wrap for a single text layout, which results
in awkward line breaks at different font sizes and screen sizes, we'll
let it wrap normally, and add a max width.
Fixes:
Like this:
=> docs: update Kaizen Site heading only text layout

CONTRIBUTING.md, README.md, packages/component-library/README.md, packages/design-tokens/README.md, site/README.md
Key changes:
- Link to design tokens package
- Link to new draft package generator
- Includes a TLDR for contributing
- Defines design tokens
- Adds Kaizen Site dev info
=> docs: update repo docs

draft-packages/button/KaizenDraft/Button/styles.scss
Turns out that in IE11, pseudo elements on buttons are constrained visually to the dimensions of the button, unless you explicitly add `overflow:visible`. The focus ring styles we have rely on the pseudo element being a bit bigger than the button, so it wasn't able to be seen at all.
=> fix: Adds overflow:visible to buttons to fix IE11 clipping issue

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.tsx
The `Other Actions` header was present -
Have followed up with Seb to write tests - but quickfix for now:
=> fix: removed other actions header when default action is link

package.json, yarn.lock
This was required in the past because a dependency had a transitive dependency on a version of minimist that had a security issue. This is no longer necessary.
=> fix: remove minimist from package.json resolutions

storybook/header-preset/header.tsx
On branch previews we returned a base URL including the forward slash, but on production we weren't. This patches that error.
=> docs(site): Fix url from storybook on production

draft-packages/stories/ExampleLayout.module.scss, draft-packages/stories/Tabs.stories.tsx, draft-packages/tabs/KaizenDraft/Tabs/styles.scss
Updated to reflect the design in Figma. 
Stories: 
https://dev.cultureamp.design/ally/update-tabs/storybook/?path=/story/tabs-react--with-layout-vertical-ltr
https://dev.cultureamp.design/ally/update-tabs/storybook/?path=/story/tabs-react--with-heading
Checklist:
=> fix: Vertical tabs are bold in both active and inactive states

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
Issue only present in murmur.
Becomes:
Additionally I've explicitly set the cursor to pointer
=> fix: title block explicitly sets color of breadcrumb text

draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.elm, draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.tsx, draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx, draft-packages/form/KaizenDraft/Form/TextField/TextField.elm, draft-packages/form/KaizenDraft/Form/TextField/TextField.tsx, draft-packages/stories/ElmTextField.stories.tsx, draft-packages/stories/TextField.stories.tsx, draft-packages/stories/TextFieldStories.elm
This allows arbitrary Html to be optionally used for description/message fields in relevant form fields. Currently
it is restricted to just strings. The use case was being able to put a link in the description to a page with more details.
The following components have been updated:
`FieldMessage` (named `message`, React and Elm, used by TextField and TextAreaField)
`TextField` (React and Elm)
`TextAreaField` (React only, Elm TextAreaField does not exist yet)
We wanted to avoid a breaking change. For React, we just needed to loosen the type of the `description`/`message` fields. In Elm a change from `string` to `Html msg` would be a breaking change, so instead we have introduced new fields `descriptionHtml` and `messageHtml` respectively. We also considered using the type system to …
=> feat: allow arbitrary Html in TextField description fields (Elm & React)

draft-packages/select/package.json, packages/component-library/package.json, yarn.lock
This fixes a bug where the dropdown doesnt scroll to the selected option
Updated it in a couple of places. Only a minor update that fixes a few
bugs and adds a new feature. Should be backwards compatible.
.. see how when you re-open it's at the top?
.. now when you open the select, the current selection is visible.
=> fix: Update react select version to fix scroll bug

draft-packages/button/KaizenDraft/Button/Button.tsx, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/index.ts, draft-packages/stories/Button.stories.tsx, packages/component-library/components/Button/Button.tsx, packages/component-library/components/Button/components/GenericButton.tsx, packages/component-library/components/Button/index.ts, packages/component-library/stories/Button.stories.tsx
* Give the ability to imperatively call `focus` the two `Button` components.
* Forward down any `aria-*` props down to the two `Button` components. Edit: support has been updated to allow for all kebab cased props.
I'm going through perf-ui at the moment, and making some a11y improvements. One of those improvements is for a dropdown menu, which uses this kaizen button. When the user presses escape, and we've closed the dropdown menu, we need to place the focus back on the original button.
The menu in perform, under "Goals":
I realised after the fact, that we already have a button dropdown in kaizen, and I should have just replaced the perform-ui code. But, I think the updates will still be handy at some point.
=> feat: Add focus support to the Button components

draft-packages/table/KaizenDraft/Table/Table.tsx
Enable ability to add an automation ID for the button + checkbox. 
I decided to let that same automation ID apply to the `div`.
This is part of my e2e test generate for Performance. Every one of these will be a blocker, so any help to merge as I go would be delightful.
=> fix: Extend TableHeaderRowCell to have automationId options

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.tsx
See title
I did see that the `div` was within the `a` tag but decided not to look into it.
=> fix: Extend TitleBlockZen API so NavigationTabs can take an automation ID

draft-packages/divider/KaizenDraft/Divider/Divider.elm, draft-packages/stories/Divider.stories.elm, draft-packages/stories/ElmDivider.stories.scss, draft-packages/stories/ElmDivider.stories.tsx, elm.json
Adds Elm divider for draft-divider package
=> feat: add divider for Elm

site/docs/components/slider.mdx, site/docs/guidelines/forms.mdx
This PR adds documentation for a Slider component and examples of visuals.
Branch preview:
- https://dev.cultureamp.design/di/add-slider-page/components/slider/
Closes: https://github.com/cultureamp/kaizen-design-system/issues/248
=> docs: add slider page

draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
- Fixes a bug where the title was not extending to its full width even when there was space available.
Other small changes relating to horizontal positioning are also piggybacking on this PR:
- Fixes a title truncation issue where at smaller "desktop" widths the title was not getting an ellipsis but just being cut off abruptly.
- Adds a story for the case where there is only a long title plus a subtitle – not buttons.
- Fixes the bug where the top row of the Title Block was exceeding its max-width at the smallest "desktop" width when the content is cramped. This was fixed by setting `min-width: 0` on various elements to allow `flex-shrink` to work as intended.
- Puts `flex-shrink: 0` on the Main Actions (the 1 or 2 buttons in the top right corner). This is a trade-off that offers less …
=> fix: Make TitleBlockZen title extend full width when no buttons

packages/component-library/components/Notification/__snapshots__/GlobalNotification.spec.tsx.snap, packages/component-library/components/Notification/__snapshots__/InlineNotification.spec.tsx.snap, packages/component-library/components/Notification/__snapshots__/ToastNotification.spec.tsx.snap, packages/component-library/components/Notification/components/GenericNotification.tsx
This will add a ` data-automation-class` to each notification with their `type` and `style` to find a generic match as opposed to specific notification matches. 
Reference conversation: https://cultureamp.slack.com/archives/C2ZNME08P/p1597132217066600
=> feat: Add data-automation-class to generic notification

draft-packages/select/KaizenDraft/Select/Select.elm, draft-packages/select/KaizenDraft/Select/Select.tsx
Currently, [system-tests](https://github.com/cultureamp/system-tests/blob/6b55526ad039906499f9c3880536ccbdf1cfb16f/lib/qa_tests/pages/comments_page.rb) have trouble interacting with the Kaizen Select. This change adds automation-ids for the Select control and its options to solve that. The naming convention follows that of newer components like the [TitleBlock](https://github.com/cultureamp/kaizen-design-system/blob/cb1dc2aead68e591cc21c665fb25c1817633c4d7/draft-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.tsx#L139).
=> feat: add basic automation-ids to Select

draft-packages/modal/KaizenDraft/Modal/Primitives/ModalHeader.scss
The previous top position value was pushing the button above the modal.
This would become clear when hovering over the button, as the div fills
in and overflows the modal.
=> fix: Fix dismiss button overflow

package.json, storybook/gtm-addon/.babelrc, storybook/gtm-addon/register.js, storybook/header-preset/index.tsx, storybook/main.ts, storybook/manager.ts, storybook/preview-head.html, yarn.lock
This PR creates a GTM plugin for Storybook. 
Previously GTM tags were injected into the iframe that loads the story. The intention of analytics in Storybook is to give us an idea about how developers use our dev documentation - such as what stories are highly trafficked. This does not give us adequate tracking as we miss listening to `history.pushState`/`history.popState`. 
The changes correctly configure GTM so it's added into the head of the document, not the head of the story. 
https://github.com/storybookjs/storybook/pull/11336
https://github.com/storybookjs/storybook/pull/11340
=> ci: Added a gtm plugin to manage analytics

packages/component-library/components/Box/Box.elm, packages/component-library/components/Spacing/Spacing.elm, packages/component-library/stories/Box.stories.elm, packages/component-library/stories/ElmBox.stories.tsx
This is a the Elm version of the React Box component.
Example: heading with 1 grid unit margin bottom:
```elm
box [ marginBottom 1 ]
[ Heading.view
(Heading.h1 |> Heading.variant Display0)
[ Html.text "Display0" ]
]
```
Storybook: https://dev.cultureamp.design/mab/elm-box-inline-styles/storybook/?path=/story/box-elm--box-default
_Notes:_
Not even a CSS-in-JS or CSS-in-Elm framework, just good old fashioned inline styles! ☠️ ☠️ ☠️ 
I know!! But hear me out:
- We've decided to go with a "component only" approach for the Box (in TS and Elm), where you don't have to write a line of CSS. I think this is very good for decoupling the design system from the underlying technology (scss). But it has a problem:  css classes are finite, but we want to be able to create a near-infinite number of …
=> feat: Elm Box component

draft-packages/hierarchical-menu/KaizenDraft/HierarchicalMenu/HierarchicalMenu.tsx, draft-packages/hierarchical-menu/KaizenDraft/HierarchicalMenu/KeyboardNavigableList.tsx, draft-packages/hierarchical-menu/KaizenDraft/HierarchicalMenu/styles.module.scss, draft-packages/hierarchical-menu/package.json, draft-packages/hierarchical-select/KaizenDraft/HierarchicalSelect/HierarchicalSelect.tsx, draft-packages/hierarchical-select/KaizenDraft/HierarchicalSelect/styles.module.scss, draft-packages/hierarchical-select/package.json, draft-packages/stories/HierarchicalSelect.stories.tsx, draft-packages/stories/hierarchicalStoriesHelpers.ts
Follow up to https://github.com/cultureamp/kaizen-design-system/pull/687. Fixes the known issues from that PR and some more.
**Screenshot:**
**Storybook:**
https://dev.cultureamp.design/lijuenc/hierarchical-menu-improvements/storybook/?path=/story/hierarchicalselect-react--default-story
**Menu and select:**
- Make focus styles consistent with other Kaizen inputs and buttons
**Menu:**
- Truncate long option names with ellipses (screenshot above)
- Support disabled state for drill down button (<kbd>></kbd> in last option in screenshot above)
- Make current hierarchy node clickable ("Didier Elzinga" in screenshot above) so that the current level can selected without having to go back to the parent
- IE11 compatibility for:
- keyboard navigation (<kbd>↑</kbd>, <kbd>↓</kbd>, <kbd>←</kbd>, …
=> feat: Hierarchical menu and hierarchical select improvements [PHRI-32]

draft-packages/tabs/KaizenDraft/Tabs/Tabs.tsx
Adds automation IDs to both vertical and horizontal tabs.
Usage example from performance:
```js
const modifiedTabs = filteredTabs.map((t: Tab) => {
return {
...t,
// add here 
automationId: t.automationId,
onClick: (e: React.MouseEvent<HTMLAnchorElement>) => {
if (t.onClick) {
t.onClick(e)
}
if (e.defaultPrevented) return
if (t.href && isRegularMouseClick(e)) {
e.preventDefault()
router.replace(t.href as string)
}
if (isSticky) {
scrollToTopOfTabContentIfNecessary(ref.current)
}
},
}
})
return (
// This first wrapper is needed as so we can calculate where the tabs should be,
// when not in sticky mode.
// The inner wrapper is needed to set the css styling for position: sticky,
// only if isSticky is true.
<span className={cx(isSticky && styles.rootSticky)} ref={ref}>
<div …
```
=> feat: Add automation IDs to Tabs

draft-packages/stories/SplitButton.stories.tsx
The stories for the React `<SplitButton>` were using the Menu* components from the deprecated version. This updates the stories to use the equivalent components from `@kaizen/draft-menu`.
=> fix: Update SplitButton stories with draft-menu

site/docs/guidelines/header.mdx
This PR adds a Header page to Kaizen Docs
Branch preview: https://dev.cultureamp.design/dst/add-header-guidelines/guidelines/header/
=> docs: add Header guidelines page

draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
Previously there was a bug where the secondary actions did not show on a tablet view when the absence of either a primary or default action.
Image shows the secondary menu which was not shown when other 2 buttons were not present.
=> fix: title block secondary actions tablet view bugfix

draft-packages/stories/ZenNavigationBar.stories.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Indicator.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Indicator.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Link.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuGroup.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuItem.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuItem.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/types.ts, packages/component-library/components/NavigationBar/NavigationBar.tsx, packages/component-library/components/NavigationBar/components/Indicator.module.scss, packages/component-library/components/NavigationBar/components/Indicator.tsx, packages/component-library/components/NavigationBar/components/Link.tsx, packages/component-library/components/NavigationBar/components/Menu.module.scss, packages/component-library/components/NavigationBar/components/Menu.tsx, packages/component-library/components/NavigationBar/types.ts, packages/component-library/stories/NavigationBar.stories.tsx
This PR adds new badge to dropdown menu items in both the new and old navbar.
It also adds the option of adding an indicator on Menu link.
=> feat: Add new badge to menu items

draft-packages/button/KaizenDraft/Button/components/GenericButton.module.scss, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/KaizenDraft/Button/styles.scss
I have extended the functionality of the hidden `additionalContent` api, to position it before the icon when `iconPosition` is set to `end`. 
This considers the margin needed to space additional content and icon apart.
I have searched our major repos and there is currently no use case where `iconPosition` is set to `end` as well as `additionalContent` being provided. 
This produces a button where the additional content - in this case a badge - can live before the icon. And does not effect the filter drawer button.
=> fix: consider icon position end when additional content is used on generic button

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
Small bugfix where the margin was incorrect.
=> fix: fixes margin when a status tag and page switcher are used together

draft-packages/form/KaizenDraft/Form/TextAreaField/README.mdx
This PR adds details of the Prominent Text Area to the Text Area Field including copy and usage guidelines.
Branch preview: https://dev.cultureamp.design/dlimiter-adds-prominent-text-area/components/text-area-field/
=> docs: update to include Prominent variant

site/docs/components/divider.mdx, site/docs/guidelines/filtering.mdx, site/docs/guidelines/localization.mdx, site/docs/language/grammar.mdx, site/src/components/ContentOnly.scss, site/src/components/Layout.scss, site/src/components/Layout.tsx, site/src/components/PageHeader.scss, site/src/components/PageHeader.tsx, site/src/components/SidebarAndContent.scss, site/src/components/SidebarAndContent.tsx, site/src/pages/404.tsx, site/src/pages/index.tsx, site/src/styles/global.scss, site/src/styles/markdown.scss, site/src/templates/componentPage.tsx, site/src/templates/guidelinePage.tsx, site/src/templates/languagePage.tsx
This PR:
- Adds a "table of contents" to each content page on the site
- Reduces type size in line with Zen style now that we are using Greycliff and Inter
- Adjusts layout to accommodate table of contents
- Makes content amendments to fix heading levels and missing headings
- Swaps "Guidelines" and "Comparing components" subsections in the sidebar in line with Google Analytics content usage
The table of contents specifically only shows heading levels 2 and 3 at this time to reduce level of indentation in the visual output and encourage people to avoid skipping heading levels because if they go from 2 to 4, level 4 won't show.
Branch previews:
- Storybook demo and Figma embed: https://dev.cultureamp.design/di/add-table-of-contents-to-site/components/modal/
- No TOC: …
=> docs: add table of contents to site

draft-packages/button/KaizenDraft/Button/README.mdx, draft-packages/empty-state/KaizenDraft/EmptyState/README.mdx, draft-packages/form/KaizenDraft/Form/CheckboxField/README.mdx, draft-packages/form/KaizenDraft/Form/TextAreaField/README.mdx, draft-packages/form/KaizenDraft/Form/TextField/README.mdx, draft-packages/form/KaizenDraft/Form/ToggleSwitchField/README.mdx, draft-packages/guidance-block/KaizenDraft/GuidanceBlock/README.mdx, draft-packages/menu/KaizenDraft/Menu/README.mdx, draft-packages/radio-group/KaizenDraft/RadioGroup/README.mdx, draft-packages/tooltip/KaizenDraft/Tooltip/README.mdx, site/docs/components/inline-notification.mdx, site/docs/guidelines/moods.mdx
Designers sometimes misunderstand copy guidelines because they appear before the introduction of key terms outlined in the Anatomy section. For consistency, we're moving all copy guidelines below the "To keep in mind" section.
=> docs: move copy guidelines

draft-packages/badge/KaizenDraft/Badge/Badge.tsx, draft-packages/badge/KaizenDraft/Badge/styles.module.scss, draft-packages/stories/Badge.stories.tsx, draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
What has happened?:
-We have added the `dark` variant for use case with the green kaizen button.
- We have created a new component that animated a badge change - see gif.
- We have allowed the title block to accept a badge for a primaryAction
- Stories updated!
=> feat: add animated badge component

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.scss
Navigation Tabs were previously relying on global styles in Storybook and consuming repos to remove the underline from links in their default non-hovered state.
This PR makes that rule explicit.
=> fix: Add explicit rule for underline on nav tabs

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
Broken - invisible unless highlighted:
Fixed:
=> fix: admin theme subtitle fix

draft-packages/card/KaizenDraft/Card/Card.elm
the draft card has a tag function to be piped when initialising a card
we only used the default configuration before
when creating a new card of type section I noticed that the tag function
and the Tag types were not exposed.
usage in murmur: https://github.com/cultureamp/murmur/pull/14416/files#diff-07e2d306a4bcf6ded329f8e77cc2cf1cR110
(search for Card.tag on the files)
=> fix: expose public function in draft card

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx, draft-packages/guidance-block/package.json, draft-packages/stories/GuidanceBlock.stories.tsx
In a recent project using the GuidanceBlock component - I found that I needed to be able to use more than just the `label`, `onClick` and `disabled` props for the buttons. 
This PR allows you to send through any button props, rather than just the 3 that were specified previously. This also means that we won't need to adjust this package if the Button API changes.
=> feat: Allow any Button props to be sent to GuidanceBlock actions

draft-packages/form/KaizenDraft/Form/Primitives/Label/styles.scss
Fixes bug from #740  - where every label receives margin. We only want the additional spacing around labels when it is inline with form controls. When labels sit within a container with no other content around it, there should be no left padding when LTR, and no right padding when RTL.
=> fix: Apply spacing to labels when inline with form controls

draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.elm, draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.elm, draft-packages/stories/ElmTextAreaField.stories.tsx, draft-packages/stories/ElmTextField.stories.tsx, draft-packages/stories/TextAreaField.stories.elm, draft-packages/stories/TextFieldStories.elm
- it makes use of the defaultValue html property, to set
a default value when the dom node is first created
- it's less risky than the controlled variant, which can have
issues on old devices as the component isnt' updated quickly
enough. Users can experience sluggish text entry or strange
cursor behaviour.
- however, there is a big limitation: you cannot automatically change
the value once the dom element has been created (for example, pressing
button to fill the value). Most forms don't require this functionality.
- also do the same for `TextField`
Stories:
https://dev.cultureamp.design/mab/uncontrolled-elm-text-area-field/storybook/?path=/story/textfield-elm--default-controlled-prefilled-value
https://dev.cultureamp.design/mab/uncontrolled-elm-text-area-field/storybook/?path=/story/text …
=> feat: allow uncontrolled Elm TextArea to be pre-fillable

draft-packages/select/KaizenDraft/Select/styles.elm.scss
there is still more to do but this makes it gel much better with
existing components like text inputs
**new**
**old**
=> feat: basic Zen uplift for Select border and hover state

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Link.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Link.tsx
Final Items now render with font weight as per design.
Tooltips no longer appear on hover in murmur on desktop.
=> fix: navigation bar design review

packages/component-library/icons/delta-negative.svg, packages/component-library/icons/delta-none.svg, packages/component-library/icons/delta-positive.svg
add new icons 20x20
They are used on the tooltip of a program trend
=> feat: add positive, negative and neutral delta icons

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
**Objective**
Add automation IDs in a non-breaking way for previous hard-coded automation IDs.
**Notes**
`renderSectionTitle` automation ID props were set to be optional given all other IDs are optional, but the defaults will actually mean this is always provided. It is the one oddball case in terms of the pattern.
In the spec, I also left the default test `automationIDs` assignment as an object for consistency with the following test and readability, although I do note that the keys are never used!
=> feat: extend TitleBlockZen API for automation IDs

draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
This PR affects TitleBlockZen.
Previously, consumers had to specify
```
primary: true,
reversed: true
```
for both primary (when not a menu) and default actions.
This PR removes that requirement.
Users can still override these defaults if they want, e.g. `primary: false`.
=> feat: Remove need to specify primary & reversed

packages/component-library/styles/layers.scss
Follows from [this PR](https://github.com/cultureamp/kaizen-design-system/pull/785).
It turns out that we're using the dropdown z-index for other items, which was causing layout bugs on perform. I don't have the time to look into this, so doing a quick revert for now.
=> fix: Revert z-index update to dropdown menu

packages/component-library/icons/delta-flat.icon.svg
The svgo-loader expects this value to ensure automatically convert the fill to `currentColor`
=> fix: Ensure delta-flat icon has path fill set to black

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
Reverts erroneous import introduced in [this PR](https://github.com/cultureamp/kaizen-design-system/pull/781/files#), where the button/buttonProps were changed from draft to core.
=> fix: Use correct props for button

draft-packages/stories/Table.stories.tsx, draft-packages/table/CHANGELOG.md, draft-packages/table/KaizenDraft/Table/Table.spec.tsx, draft-packages/table/KaizenDraft/Table/Table.tsx, draft-packages/table/KaizenDraft/Table/TableHeaderRow.elm, draft-packages/table/KaizenDraft/Table/TableHeaderRowCell.elm, draft-packages/table/KaizenDraft/Table/styles.scss, draft-packages/table/package.json
Reverts cultureamp/kaizen-design-system#803
This was mistakenly published as a minor change when it should have been a major change. I have unpublished the package on NPM and will reopen my previous PR so we have a clean version history and changelog
=> fix: Revert "feat: Uplift the table to the new Zen designs"

CODEOWNERS
Update the CODEOWNERS for core Kaizen to the FE Advocates 
Previously DST Engineers were the codeowners for core Kaizen - I'd like to extend this to the entire advocacy program to reduce bus factor and reduce us becoming a bottleneck.
=> ci: Update CODEOWNERS

draft-packages/select/KaizenDraft/Select/Select.tsx, draft-packages/select/KaizenDraft/Select/styles.react.scss, draft-packages/stories/Select.stories.tsx
This adds a specific style to the `Option` values with the `<Select>` component when the `isDisabled` attribute for that option is set to `true.
You can view this live in the branch preview: https://dev.cultureamp.design/select/add-disabled-style/storybook/?path=/story/select-react--single
Currently the `isDisabled` attribute functions correctly — the option cannot be chosen — but it does not look any different from the enabled options and so could case confusion.
The disabled class sets the opacity to 30%, which is the same as the overall disabled style for the `<Select>`. It also adds a `not-allowed` cursor on hover to make it clear to users that the action is disabled.
[x] I have considered likely risks of these …
=> fix: Add style disabled options in <Select>

draft-packages/select/CHANGELOG.md
Our changelogs are parsed in MDX, so unclosed JSX throws an error. This PR removes JSX from the Changelog.
=> docs: Remove JSX from CHANGELOG

storybook/preview-head.html, yarn.lock
This PR fixes the "Uncaught ReferenceError: exports is not defined" error. 
I am unsure about the exact cause of this issue. For completeness, I've also updated the lockfile. 
https://stackoverflow.com/questions/42497479/uncaught-referenceerror-exports-is-not-defined-in-filed-generated-by-typescript/42510255
The error in the bundle is caused by this: 
```
line 4406: exports.__esModule = true;
// throws "Uncaught ReferenceError: exports is not defined" error
```
Further down in the bundle this has been defined: 
```
line 7554: Object.defineProperty(exports, "__esModule", {
value: true
});
```
[ ] I have or will communicate …
=> ci: Added hack to allow TS modules to work in Storybook

draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/CHANGELOG.md, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx, draft-packages/title-block-zen/package.json, packages/component-library/styles/type.scss, packages/deprecated-component-library-helpers/styles/type.scss, storybook/preview-head.html, yarn.lock
This is a **canary release**
This removes all traces of Open Sans from Kaizen, and makes Inter the default for `$ca-default-font-xxx`
The `$ca-default-font-xxx` vars are legacy (in both files) and should be removed eventually, but this is far easier (not a breaking change, codewise). The nice thing is that the name `$ca-default-font-xxx` is still applicable, so there's no need to change the name like we needed to do for `$ca-font-ideal-sans` (which was a huge change❗). 
The consuming repo (guess which one!) will just need need to bump Kaizen, and hopefully most of the Open Sans usages will dissappear.
This has not been tested (by for example yarn linking locally), so there may be mistakes. Please let me know if find any in code review! I made it a canary release to be able to use our …
=> feat: point $ca-default-font-xxx to $ca-inter-font-xxx

draft-packages/stories/Button.stories.elm
Fix the consistency of the Elm and React Zen Button stories on `cultureamp.design/storybook`.
For example, the Elm primary button is green (outdated) while the React one is blue. This is because the Elm stories are referencing `component-library/components/Button` when they should be referencing `draft-packages/button`.
https://cultureamp.design/storybook/?path=/story/button-zen-elm--primary
https://cultureamp.design/storybook/?path=/story/button-zen-react--primary
[x] I have or will communicate these changes to the front end practice
=> fix: Use correct Button package for Elm Zen Button stories [EOP-367]

draft-packages/stories/TitleBlockZen.stories.scss, draft-packages/stories/TitleBlockZen.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
The current implementation of `TitleBlockZen` intentionally includes a large space where the navigation tabs would appear, even when there are no tabs that would fill that space. This makes it rather awkward to implement designs that butt up more tightly to fill that area with content.
To counter that, this PR adds a `collapseNavigationAreaWhenPossible` prop to the component that decreases that space to a more "natural" feeling padding.
Example stories:
* [Admin variant](https://dev.cultureamp.design/allow-title-block-to-collapse-when-no-navigation/storybook/?path=/story/titleblockzen-react--admin-variant-navigation)
* [Default with collapsed nav](https://dev.cultureamp.design/allow-title-block-to-collapse-when-no-navigation/storybook/?path=/story/titleblockzen-react--default-collapsed-nav …
=> feat: Allow TitleBlockZen to collapse when no navigation

site/docs/guidelines/typography.mdx
Missed some of the comments from the [previous PR](https://github.com/cultureamp/kaizen-design-system/pull/834).
https://dev.cultureamp.design/katsambarcus-typography-guidelines/guidelines/typography/
=> docs: fixed language across document

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/stories/Button.stories.tsx
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pag …
=> fix: button should only be working when working prop is true

draft-packages/popover/KaizenDraft/Popover/Popover.tsx, draft-packages/stories/Popover.stories.tsx
Due to the fact we don't have a way to set yPosition relative to target in popover, this is an intermediary solution to fix that problem. Ideally, we'd actually do this as part of the popover class, but this method allows us to set this in the meantime prior to the popover component re-engineering process.
In the 1-on-1s tool, we want to set positioning of the popover to be above an icon, but due to the way we set the x offset, it makes the y offset positioning unnecessarily difficult.
A conscious decision that was made was that we will not be adding the padding for the little notch as part of this y offset so all of those calculations are up to the user; in the eventual ideal solution, this would be taken into consideration.
[ ] If this contains visual changes, has it been reviewed by a …
=> feat: Added y box offset option to Popover component

packages/component-library/components/Dropdown/Dropdown.tsx, packages/component-library/components/Dropdown/DropdownMenu.tsx, packages/component-library/components/MenuList/MenuHeader.tsx, packages/component-library/components/MenuList/MenuItem.tsx, packages/component-library/components/MenuList/MenuList.tsx, packages/component-library/components/MenuList/MenuSeparator.tsx
Make engineers aware that deprecated components are in fact deprecated. Closes #852.
The `draft-menu` component should be used for every case that these deprecated components used to cover.
[ x ] I have considered likely risks of these changes and got someone else to QA as appropriate
[ x ] I have or will communicate these changes to the front end practice
=> chore: Add deprecated line to Dropdown and related components

draft-packages/popover/KaizenDraft/Popover/Popover.tsx, draft-packages/stories/Popover.stories.tsx
Allows you to pass a custom icon into the popover, to override the icon for a specific variant.
Testing for default agenda items in 1-1s has suggested that the guidance icon is more appropriate than an informative icon. At the moment the icon usage is tied to the variant. We want to allow for a custom icon to allow this kind of 'snowflake' where suitable.
This change was previously introduced as a new variant due to a misunderstanding on my behalf.
https://github.com/cultureamp/kaizen-design-system/pull/853
https://cultureamp.slack.com/archives/C2ZNME08P/p1604544453303100
=> feat: Allow custom icons for popovers

draft-packages/stories/Table.stories.tsx, draft-packages/table/KaizenDraft/Table/Table.tsx, draft-packages/table/KaizenDraft/Table/TableHeaderRowCell.elm, draft-packages/table/KaizenDraft/Table/styles.scss, draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx
Adds a `tooltipInfo` property to the `Table` component. Using this prop will wrap the cell in a tooltip, and add a blue info icon to the left hand side.
The problem with simply wrapping the heading cell with a `Tooltip`, is that it ruined a lot of the flex styling. To overcome this, I needed to make some minor refactors to `TableHeaderRowCell`.
On the new Evaluation Cycle dashboards work, we needed to include a tooltip, to provide more context on the table header column name. We've had some confusion from customers in regards to when a request is "from" someone, vs "for" someone. We have very little horizontal realestate on this table, so a Tooltip was our option of last resort.
=> feat: Add tooltip to the Table header

packages/design-tokens/package.json, packages/generator/package.json, packages/hosted-assets/package.json
Adds coverage of `.js` and `.d.ts` files to the `clean` script in the `package.json` of a few packages.
I (and possibly others) was running into problems every time I tried to push a branch, because the auto-linting that Prettier runs was erroring on this files and aborting the push:
[ x ] I have or will communicate these changes to the front end practice
=> fix: Add coverage of .js and .d.ts files to clean scripts that were missing them

draft-packages/dropdown-menu/KaizenDraft/DropdownMenu/DropdownMenu.scss, draft-packages/likert-scale-legacy/KaizenDraft/LikertScaleLegacy/styles.module.scss, draft-packages/popover/KaizenDraft/Popover/styles.scss, draft-packages/split-button/KaizenDraft/SplitButton/styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, legacy-packages/menu-list/KaizenDraft/MenuList/MenuList.scss, legacy-packages/title-block/KaizenDraft/TitleBlock/NavigationButton.scss, legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss, packages/component-library/components/MenuList/Menu.module.scss, packages/component-library/components/NavigationBar/NavigationBar.module.scss, packages/component-library/components/NavigationBar/_styles.scss, packages/component-library/components/NavigationBar/components/Badge.module.scss, packages/component-library/components/NavigationBar/components/Menu.module.scss, packages/component-library/components/OffCanvas/components/Header.module.scss, packages/component-library/styles/color.scss, packages/deprecated-component-library-helpers/styles/color.scss, packages/design-tokens/sass/color.scss, site/src/components/ContentOnly.scss, site/src/components/Footer.scss, site/src/components/PageHeader.scss, site/src/components/SidebarAndContent.scss, site/src/pages/index.scss, site/src/styles/global.scss
Fixes stylelint warnings that were appearing in pre-commit linting.
These were all based on the rule preferring `black` and `white` over `#000`/`#000000` and `#fff`/`#ffffff`.
[ x ] I have or will communicate these changes to the front end practice
=> chore: Fix stylelint warnings for color names

site/docs/components/drawer.mdx
**Objective**
Update embed links to point to correct Figma file. 
**Motivation and Context**
Embedded examples were pointing to the UI Kit. I have updated these to point to the Figma file set up specifically for Kaizen site embeds. Content of examples hasn't changed.
=> docs: Update drawer.mdx

draft-packages/stories/Table.stories.tsx, draft-packages/table/KaizenDraft/Table/Table.tsx, draft-packages/table/KaizenDraft/Table/styles.scss
* Add ability to change the table sorting arrow from descending to ascending. Before, we only had an `active` prop, which accepted true or false. Now there's a `sorting` prop, with `ascending` | `descending` | undefined.
* Side update: add `href` property to the table header. In perform, our sort values are stored in the url. Whenever we use routing, we should (pretty much) always use `a`nchor tags, this allows the user to do things like open the link in a new tab etc.
=> feat: Add ability to change the table sorting arrow from descending to ascending

draft-packages/stories/Table.stories.tsx, draft-packages/table/KaizenDraft/Table/Table.tsx
Our design style guides have stated that table header row cells that can be sorted should show the arrow on hover/focus. To prevent issues across platform, I have made this optional for now but added in the capability.
BEFORE: (note you can't see anything as there's no hover effect)
AFTER:
On hover:
On focus:
[x] I have considered likely risks of these changes and got someone else to QA as appropriate
[x] I have or will communicate these changes to the front end practice
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/2045 …
=> feat: created hover ability for header table row cells

draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.elm, draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.tsx, draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/styles.scss, draft-packages/form/KaizenDraft/Form/Primitives/Label/Label.tsx, draft-packages/form/KaizenDraft/Form/Primitives/Label/styles.scss, draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.tsx, draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx, draft-packages/stories/TextAreaField.stories.tsx
Adds the `prominent` variation on the TextAreaField component which exists in the UI Kit: https://www.figma.com/file/GMxm8rvDCbj0Xw3TQWBZ8b/Zen-UI-Kit?node-id=1929%3A30084
Also adds a `maxLength` prop to `TextArea` and `TextAreaField`, and updates the colour of the `FieldMessage` text to match the UI Kit.
I'm adding this to Capture and need this variation :-)
https://dev.cultureamp.design/dug/prominent-text-area/storybook/?path=/story/textareafield-react--default-prominent-desc
- Does there need to be right-to-left (RTL) options for localization and …
=> feat: Add prominent variant to TextAreaField (React)

draft-packages/stories/Table.stories.tsx, draft-packages/table/KaizenDraft/Table/Table.tsx, draft-packages/table/KaizenDraft/Table/styles.scss, yarn.lock
Just updating a UX behaviour to a better one to prevent labels in the header table row cell component from moving around when they are center or right aligned and hover is available.
It was okay, but pretty poor UX so this is just improving it.
[x] I have considered likely risks of these changes and got someone else to QA as appropriate
[x] I have or will communicate these changes to the front end practice
- Have you updated …
=> fix: fixed issue where hover on table row moves label for center/right aligned cells

draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.tsx, draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx
Allows consumers of `TextAreaField` and `TextArea` to send in any generic `textarea` props.
If you need to add a generic prop to our text area component (such as `maxLength` or any `aria` property`) - we need to go through the process of adding it to the component in Kaizen, then update the package on the consuming repo, which is a time consuming process, and causes code bloat. 
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/2045395 …
=> feat: Allow generic textarea props on TextArea and TextAreaField

.eslintrc.js, draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx
Tooltip to allow for React.ReactNode, instead of just string
In perform, we needed to be able to have a multi line tooltip. The tooltip has a new line for every collaborator on a cycle.
* Remove the max-len eslint rule, since this is now enforced by prettier. Prettier is more lenient for things like comments, and large string values, hence the rule conflict. This also removes the one lint warning that we have at the moment.
In perform, we actually have the `--max-warnings=0` option set, which will stops the warning list from growing. LMK if you'd like me to update this in kaizen also.
[ ] If this contains visual changes, has it been reviewed by a designer? - NA
[X] I have considered likely risks of these changes and got someone else to QA as appropriate
[X] I have or will communicate …
=> feat: Tooltip to allow for React.ReactNode, instead of just string

packages/react-deprecate-warning/tsconfig.dist.json
Use the correct tsconfig for the new @kaizen/react-deprecate-warning package.
The react-deprecate-component package was extending from the old distribution config (tsconfig.json), which includes stories that we'd rather not publish with the package. 
~[ ] If this contains visual changes, has it been reviewed by a designer?~ 
~[ ] I have considered likely risks of these changes and got someone else to QA as appropriate~
=> fix: Extend tsconfig from the distribution config

draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.tsx, draft-packages/popover/KaizenDraft/Popover/index.ts, draft-packages/split-button/KaizenDraft/SplitButton/index.ts
Allow for the modal confirmation button to be optional
I was requested to show a cautionary modal, to let admins know that they can't view their own reviews. The designs only have one button.
Export props for the Popover and SplitButton components. Sometimes in perform, we add wrappers around the kaizen components to enhance the functionality. The common use case being linking them to react-router, or automatically assigning the translation strings. Exporting the props in kaizen, then allows for the wrapper component to take in the same props as its child.
[X] If this contains visual changes, has it been reviewed by a designer? 
[X] I have considered likely risks of these changes and got someone else to QA as appropriate
[X] I have or will communicate these changes to the front end …
=> feat: Allow for the modal confirmation button to be optional

draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.tsx
This can happen if the textarea is added to the DOM tree but not actually rendered on screen (e.g. it's in a collapsible section).
The result is a textarea that's been given a 4px height (the border height) once it's rendered:
In an ideal world, we would render a clone of the textarea off-screen to get the actual height, but this is a much quicker fix to resolve the issue for the most part for now.
=> fix: Don't set TextArea if calculated height is 0

.buildkite/scripts/release.sh
The canary branch fails because `elm-format`, `eslint` etc are not installed before the pre-push hook is called. 
When resetting the canary branch, `git push` will activate the pre-push hook. We can assume that if something is on master it is green and hence can be safely pushed to the canary branch without running pre-push checks. 
=> ci: Ignore linting on git push to reset canary branches

packages/deprecated-component-library-helpers/package.json
Moves design tokens from a dependency to a peerDependency. 
The target repo will have a version of design tokens that the package can resolve to, so enforcing this package to BYO it's own design tokens doesn't make sense.
=> feat: Move design tokens from a dependency to a peerDependency

packages/deprecated-component-library-helpers/package.json
BREAKING CHANGE: Tokens are now a peer dependency of component-library-helpers. When upgrading ensure dependants are using v2 or greater
Moves design tokens from a dependency to a peerDependency.  
The target repo will have a version of design tokens that the package can resolve to, so enforcing this package to BYO it's own design tokens doesn't make sense. The content is the same as [this PR](https://github.com/cultureamp/kaizen-design-system/pull/891), but will be released as a breaking change.
=> feat: Move design tokens to peer dependency

draft-packages/stories/Tile.stories.tsx, draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx
This makes it so the `information` prop can either be the info object or a custom element, thus allowing more flexibility with what can be displayed on the back of the card.
- Have …
=> feat: Add ability to use custom element on back of Tile

site/docs/components/tabs.mdx
Section Tabs was the 'working name' we initially used to refer to tabs that control content within a page. The intent was to eventually change this to Content Tabs. Have updated the guidelines to reflect this.
=> docs: updated 'Section tabs' to 'Content tabs'

draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.tsx, draft-packages/stories/TextAreaField.stories.tsx
When autogrow was added to this component, I created something called `internalValue` for when the textarea is uncontrolled by the consumer, but autogrow still needs to know the value. React throws an error if you specify both a `value` and `defaultValue` on a textarea, so I took away this defaultValue assignment, which was no longer required at the time with `internalValue` now taking over. I then decided that I wanted to avoid holding the internal state if I could (when autogrow is false), but didn't add this back in. This meant that uncontrolled textareas no longer had their default value going through.
=> fix: Restore defaultValue on textarea

draft-packages/divider/KaizenDraft/Divider/styles.module.scss
Add an explicit `visibility: visible` rule to the `hr` element in the Divider component.
Murmur, our biggest consuming repo, has [global styles](https://github.com/cultureamp/murmur/blob/master/app/assets/stylesheets/legacy/modules/_body.scss#L95) that include
```
hr {
visibility: hidden;
}
```
This makes for a poor user experience when someone uses the Divider component in Murmur, because they can't see it and may waste time figuring out why.
Removing this global rule from Murmur is risky, and adding an explicit rule to Kaizen seems like a compromise that is fairly harmless and does not couple the component to Murmur in any way.
=> fix: Add explicit visibility style rule

site/docs/components/rich-text-editor.mdx
Fixed resizing issues of the UI kit component and created a embed for docs
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and …
=> docs: added figma embed

draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterSplitButton.module.scss, draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterSplitButton.tsx
Refine the styling of the `FilterMenuButton` component to match with the latest Figma design.
When we first release the `FilterMenuButton` component, there's some styling that hasn't been implemented yet due to the decision that hasn't been made within the broader design/frontend practice.
Some of the design that hasn't been implemented:
* Active state for the button when it's clicked and the dropdown content is visible
* The button that's expanded as the metadata text grows.
- Have you updated any …
=> fix: Refine filter menu button styling

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Link.tsx
In an effort to clean up the console errors in perf-ui, here's one of them. It appears we were passing a boolean into `className`
=> fix: console error, where boolean was passed into `className`

packages/deprecated-component-library-helpers/styles/type.scss
DUPLICATE OF https://github.com/cultureamp/kaizen-design-system/pull/916
**Note: this is a canary release**
The motivation is to test murmur against this branch which replaces open sans with inter.
These same changes were originally made in this  (canary) PR: https://github.com/cultureamp/kaizen-design-system/pull/916. That PR created a canary release from `@kaizen/component-library` but it did not appear to create a canary release for `@kaizen/deprecated-component-library-helpers` (which also had changes). I resumed work on this, and only just realised. I'm not sure why - is there a limitation where you can only do one canary release per PR per package? This was three months ago, so not worth worrying about! This PR, which only changes code in depredated-component-library-helpers is an …
=> feat: point deprecated helpers default font to Inter

draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterSplitButton.module.scss, draft-packages/filter-menu-button/docs/FilterMenuButton.stories.tsx
Remove the `max-width` from the action button to make the button expand along with the metadata.
**Previously with `max-width: 500px`**
**Updated Version**
- Have you reviewed Culture …
=> fix: remove the max-width to make the button expand with the metadata

draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterSplitButton.module.scss, draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterSplitButton.tsx, draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/styles.module.scss
Add metadata class for the label with a style that matches secondary button.
In this change, I also add hover state for the button to use Cluny 600
to make it thicker for an accessibility purpose
Make the metadata label for the `FilterMenuButton` component thicker
- …
=> fix: update styling for FilterMenuButton metadata label

draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterMenuButton.tsx, draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/styles.module.scss, draft-packages/filter-menu-button/docs/FilterMenuButton.stories.scss
Remove the styling for `div` inside `MenuContent`
The padding surrounding the children inside `MenuContent` makes it difficult for the consumer to style the children component to utilise the whole areas. These changes remove the style for the wrapper inside `MenuContent`.
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participa …
=> fix: remove content wrapper for FilterMenuButton children

draft-packages/tag/KaizenDraft/Tag/Tag.scss
Remove cursor css for Tag components
In perform, we use the `Tag` component inside clickable table rows. Because the `Tag` component has a `cursor: default` css property, the cursor will actually change from a `pointer`, to a `default` cursor, if they hover over the Tag. It kind of makes the site look broken.
I think removing the custom cursor is the best thing to do. Although I'm not sure who to tag on this one, since there's no one on the git history.
[ ] If this contains visual changes, has it been reviewed by a designer? - NA
[X] I have considered likely risks of these changes and got someone else to QA as appropriate
[X] I have or will communicate these changes to the front end practice
=> feat: Remove cursor css for Tag components

packages/design-tokens/less/border.less, packages/design-tokens/sass/border.scss, packages/design-tokens/sass/color.scss, packages/design-tokens/tokens/border.json
This adds a new border color token to the design tokens. 
In the current state, the default color for solid borders is wisteria-100. This formalises that decision as a token. As an added bonus, usage of this token will help us with the upcoming brand uplift.  
- …
=> feat: Added color token for solid borders

draft-packages/search-box/KaizenDraft/SearchBox/SearchBox.tsx, draft-packages/search-box/package.json
Previously, the `SearchBox` component import `FieldMessage` and `Label`
component directly using a relative path. I change the import to use
`@kaizen/draft-form` package
The relative path import to the `form` packages cause an error when the component is used as an individual package.
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers- …
=> fix: update the import to @kaizen/draft-form component

draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/menu/docs/Menu.stories.tsx
Add the ability to change the autohide behaviour of dropdowns
We have a custom dropdown in perform, which has a list of checkbox items. We don't want the dropdown to hide every time we check a checkbox.
There's a dropdown for every type of `autoHide` value in the storybook story. …
=> feat: Add ability to change the Menu auto hide behaviour

draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/menu/docs/Menu.stories.tsx
Fix menu position, when not enough room above the toggle button.
This problem would happen frequently in my personal dev environment, because I often have my dev tools below the viewport, therefore I do not have much vertical realestate. I don't know of any customer complaints, but I would assume that this issue has been seen by a few customers.
Before:
After:
Storybook story, so we can test this behaviour:
* Fix the menu position, when placed above the dropdown button, so it's not overlapping it.
=> feat: Fix menu position, when not enough room above the toggle button

.github/workflows/add_branch_preview_link_to_pr.yml
Make the branch previews easier to find.
Currently the branch preview links are hidden inside the "status" checks, which are collapsed if the build is passing - it's not very easy for people to find the branch previews, especially if they are not familiar with Github.
[Here is what it looks like on a test repo](https://github.com/jasononeil/github-action-status-test/pull/2#issuecomment-768729378):
(Note: we can't test this on this repo until it's merged to master. Hopefully it all works as well as it does in the test repo!)
=> chore: add a Github workflow that adds comments to PRs with branch preview links

draft-packages/button/KaizenDraft/Button/decision-tokens.scss, draft-packages/button/KaizenDraft/Button/styles.scss, package.json, storybook/main.ts, storybook/theme-switcher-addon/addon.tsx, storybook/theme-switcher-addon/preset.ts, storybook/theme-switcher-addon/register.tsx, storybook/theme-switcher-addon/tokens.ts, yarn.lock
This gives consumers of Kaizen the ability to see the difference between Heart and Zen themes.
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic …
=> feat(canary): Add theme switcher preset to add CSS Variables to the root of story iframes

packages/component-library/package.json
Removed a bunch of dependencies that are not used in component-library.
`@kaizen/component-library` brings along a bunch of dependencies that it no longer needs. This PR removes them.  …
=> fix: Remove unused dependencies from component-library

packages/component-library/styles/type.scss, packages/deprecated-component-library-helpers/styles/type.scss
Release this Canary PR (https://github.com/cultureamp/kaizen-design-system/pull/828) to master (more details are in that PR).
Copy of the commit message regarding the breaking change:
```
BREAKING CHANGE
The breaking change is in only in the most legacy parts of Kaizen (`ca-` scss mixins and variables)
that are only used in the Big M repo.
For all other repos (non Big M), this won't affect them, so this release can be blindy
upgraded without testing. However, if you're unsure you can just do a search
for `ca-` in scss files in your repo, and if there are no results, no need to
worry about the major update
If you are bumping the Big M repo with this release, please PM michael.bylstra@cultureamp.com
for more details.
Description of changes:
- This removes all traces of Open Sans from …
```
=> feat: point legacy Open Sans vars at Inter (release canary PR to master)

draft-packages/menu/KaizenDraft/Menu/components/MenuContent.module.scss
- Replaces container padding with margin on content elements
- This allows the divider to bleed to the edges (and makes other custom full-bleed sections easier)
- Also uses flexbox on the main container (with `flex-direction: column`) instead of relying on menu items to make themselves 100% width
⚠️  (This message is also in a commit body) This includes a potential visual breaking change, since it restructures the way margins and padding work. If any consumers are using the Menu in non-standard ways, such as creating a section at the top of the dropdown that bleeds all the way to the edges by using a negative margin to override the dropdown container's padding, those could break.
Under the new model, instead of the container using padding to add space, the *content* is responsible for …
=> fix: Fix spacing issues on Menu dropdown

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/select/package.json, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx, draft-packages/title-block-zen/package.json, yarn.lock
Upgrades the draft-button dependency in title-block-zen, and solves any consequential issues, such as adding `@types/react-select@3.0.22` to draft-select
We just love dependency upgrades ❤️
- If this …
=> fix: unpin draft-button dependency in zen-title-block

packages/design-tokens/package.json
I forgot to add some very important files to the `package.json` in a previous release containing CSS variable tokens, which means they aren't published.
This PR fixes that. …
=> fix: Add missing files to publications

draft-packages/button/KaizenDraft/Button/decision-tokens.scss
Update Button to use the correct Heart CSS variables. Without this, the Heart buttons fallback to Zen even though the Heart theme is active. 
Related to this PR: https://github.com/cultureamp/kaizen-design-system/pull/1030
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web …
=> fix: Rename CSS variables

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss, legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.tsx
One legacy, and one soon-to-be legacy component, have different breakpoints for mobile. Specifically the Legacy Title Block and the Current Navigation.
We will be rolling out a new navigation with a mobile breakpoint defined design tokens. This will align the legacy components with their replacements. 
The problem exists because we will be rolling the new navigation out behind a feature flag, but we won't be upgrading the legacy title block as there is no new version in Elm. The title block needs to make space for the hamburger menu. And frankly it will just be 100x easier to work with.
This issue actually persists before this change so I guess I'm fixing a bug? IDK
=> feat: align breakpoints to mobile design token to make rollout of new title block and navigation easier

packages/design-tokens/src/types.ts
Super simple change just to allow for potential extra custom themes, such as a "High Visibility" or transparent theme.
- If this contains substantial visual changes, especially far reaching ones, have you …
=> fix: "custom" variant for ThemeKey

packages/component-library/components/Heading/Heading.module.scss
Provide an explicit text-transform on h6 elements.
Murmur has global h6 styles that mean that `<Heading variant="heading-6" />` has the wrong case when used there.
There are no similar rules that are overridden on other heading elements – only h6.
=> fix: Provide explicit text-transform on Headings

draft-packages/loading-spinner/KaizenDraft/LoadingSpinner/LoadingSpinner.tsx, draft-packages/loading-spinner/docs/LoadingSpinner.stories.tsx
Modifies the LoadingSpinner component to inherit its color rather than setting it.
We needed this as part of the work required for the [secondary destructive variant of the Button](https://github.com/cultureamp/kaizen-design-system/pull/1109) (and it had to be done at some point anyway).
=> feat: Make LoadingSpinner inherit color

draft-packages/menu/KaizenDraft/Menu/Menu.tsx, draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx, draft-packages/menu/KaizenDraft/Menu/StatelessMenu.tsx, draft-packages/menu/KaizenDraft/Menu/__snapshots__/Menu.spec.tsx.snap, draft-packages/menu/KaizenDraft/Menu/styles.scss, draft-packages/menu/docs/Menu.stories.tsx, draft-packages/menu/package.json, draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx, draft-packages/tooltip/docs/Tooltip.stories.tsx
Add automatic positioning for the Menu component, using popper. This is similar to what was recently implemented for `Tooltip` ([PR 1](https://github.com/cultureamp/kaizen-design-system/pull/1041), [PR 2](https://github.com/cultureamp/kaizen-design-system/pull/1058)). It's basically so we can display a dropdown menu, even when inside a scrollable element. It will also automatically detect when a menu will go outside the viewport, and find the next best position for it. - 196973b, 6c9b00b
* `popper` has been integrated into the `Menu` components. Although I've tried to avoid adding breaking changes, I can't provide guarantees. Please test your dropdown menus after upgrading this package.
* Convert `MenuItem` to a functional component - 1d58ba7
* Move code from the `Menu.render` function, …
=> feat: Add automatic positioning for the Menu component, using popper

draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx
Fix an issue introduced in this PR https://github.com/cultureamp/kaizen-design-system/pull/1110 and more specific this commit --> https://github.com/cultureamp/kaizen-design-system/commit/ae49d577661fe2910aaaf8a960523009567f0eb5
The problem introduced is that when importing `spacing` from `@kaizen/design-tokens/tokens/spacing` it was undefined and made crash the Menu component.
Use the value instead. This value was already used in the PR in this commit https://github.com/cultureamp/kaizen-design-system/pull/1110/commits/37e5223308559d554443c6d5b9910ab52814a42a so is ok.
=> fix: Menu crashing fix

packages/design-tokens/react/ThemeProvider.tsx
Export the ThemeContext so that we can use the ThemeContext.Consumer element in a class component
Wanted to use it in a react class like so... 
```
<ThemeContext.Consumer>
{({ typography }) => ( ... ) }
</ThemeContext.Consumer>
```
(if that's not the correct way to use a HoC please tell me)
=> fix: export the ThemeContext

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Badge.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Dropdown.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Indicator.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuGroup.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuItem.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/decision-tokens.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/helpers/OffCanvas.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/helpers/components/Header.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/helpers/components/Menu.module.scss, packages/component-library/components/NavigationBar/NavigationBar.module.scss, packages/component-library/components/NavigationBar/_styles.scss, packages/component-library/components/NavigationBar/components/Badge.module.scss, packages/component-library/components/NavigationBar/components/Indicator.module.scss, packages/component-library/components/NavigationBar/components/Link.module.scss, packages/component-library/components/NavigationBar/components/Menu.module.scss, packages/component-library/components/NavigationBar/decision-tokens.scss, packages/component-library/stories/NavigationBar.stories.tsx
Update navigation bar (both the component library and Zen packages) to support Heart. The changes here are: 
* Update to use the new `kz-var` variables
* Change default navigation bar  to be wisteria-600 on Heart, and keep wisteria-700 on Zen
* Change content navigation bar to be cluny-200 on Heart, and keep cluny-100 on Zen
* Add a separator on content and admin variants 
Related stories:
https://dev.cultureamp.design/ally/heart-navigation/storybook/?path=/story/zennavigationbar-react--admin-colours
https://dev.cultureamp.design/ally/heart-navigation/storybook/?path=/story/navigationbar-deprecated-react--content-colors
- Have you done cross-browser testing for …
=> feat: Update navigation bar to support Heart

draft-packages/page-layout/KaizenDraft/useResizeObserver.ts
Fix error that happens sometimes in storybook when navigating between 2 stories. 
It is happening because `node === null` instead of undefined. Not sure why is it happening, but this fixes that reliably.
```
useResizeObserver.js:35 Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
at useResizeObserver.js:35
at HTMLUnknownElement.callCallback (react-dom.development.js:188)
at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
at invokeGuardedCallback (react-dom.development.js:292)
at safelyDetachRef (react-dom.development.js:19602)
at commitUnmount (react-dom.development.js:20118)
at commitNestedUnmounts (react-dom.development.js:20163)
at unmountHostComponents (react-dom.development.js:20443)
at commitDeletion …
```
=> fix: error in useResizeObserver in Storybook

draft-packages/popover/KaizenDraft/Popover/Popover.elm, draft-packages/popover/KaizenDraft/Popover/Popover.tsx, draft-packages/popover/KaizenDraft/Popover/PopoverLegacy.tsx, draft-packages/popover/KaizenDraft/Popover/classMappers.ts, draft-packages/popover/KaizenDraft/Popover/index.ts, draft-packages/popover/KaizenDraft/Popover/styles.scss, draft-packages/popover/KaizenDraft/Popover/types.ts, draft-packages/popover/docs/Popover.stories.tsx, draft-packages/popover/package.json
* Add the popper layout engine to `Popover`. This will allow the popover to automatically change
For the sake of backwards compatibility, internally I created `PopoverLegacy`, which gets used if the `referenceElement` prop has not been included. Keeping this up to date is going to be a problem. I'm tempted to go "No, you must go through every `Popover` component in your codebase, and update the props accordingly". I'm happy to fix all the existing code in perf-ui. LMK if you'd like to go down this path.
Contrary to the Tooltip and Menu components, I did not add a `portalSelector` prop. It will be the consumer's responsibility to wrap the popover in a portal if needed. This is due to a difference in the component design. The Popover doesn't wrap around an element, you pass it the …
=> feat: Add popper layout engine to `Popover`

draft-packages/badge/KaizenDraft/Badge/decision-tokens.scss, draft-packages/badge/KaizenDraft/Badge/styles.module.scss
The background colour is slightly different.
Assume "zen" theme is no CSS variable is present.
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic …
=> feat: Update Badge component to heart theme

draft-packages/tile/KaizenDraft/Tile/TileGrid.scss
The `max-width` rule on TileGrid was the source of a confusing bug in a consuming repo owned by Team Unify. It was causing margins to not be respected on a containing element a few layers up.
Since
- turning it off solves the problem, and
- the TileGrid should not be responsible for constraining its own width anyway (that is the page's responsibility),
I decided to remove it.
=> fix: Remove max-width to prevent bugs outside grid

draft-packages/tooltip/KaizenDraft/Tooltip/useUuid.ts
Updates an import of uuid that was recently added. This appears to be giving us the following error when attempting to upgrade tooltip in a consuming repo, or packages that use tooltip:
```
ERROR in ./node_modules/@kaizen/draft-tooltip/KaizenDraft/Tooltip/useUuid.js
Module not found: Error: Can't resolve 'uuid/v4' in '/workdir/node_modules/@kaizen/draft-tooltip/KaizenDraft/Tooltip'
```
See https://github.com/uuidjs/uuid/issues/245
Clearly @jeremy8883 sabotaging us right before leaving Culture Amp! :trollface:
=> fix: Use named v4 import from uuid

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
This solves a few minor miscellaneous visual bugs:
- Hides `overflow-x` on the Title Block to prevent the scroll bar overlay from pushing the Title Block's width beyond the viewport, which was creating a scrollbar on mobile
- Removes the underline from the text used in the "back" button when the button is hovered (text gains an underline on hover still)
- Removes the mobile navigation tab section's scroll overlay (the translucent gradient) when there are no navigation tabs
- Removes text underline on the link in the mobile actions drawer
These bugs are fixed in this PR:
=> fix: Fix styling bugs in TitleBlockZen

draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx, draft-packages/form/KaizenDraft/Form/TextField/TextField.tsx
Allows React Nodes, not just strings for the `validationMessage` prop on `TextField` and `TextAreaField`. This prop gets passed into `FieldMessage`, which already accepts a React Node.
I would like to be able to send in a `<Trans>` component for localisation. …
=> fix: Allow ReactNode for TextField and TextAreaField validationMessage

packages/component-library/components/Notification/InlineNotification.tsx, packages/component-library/components/Notification/_styles.scss, packages/component-library/components/Notification/components/GenericNotification.tsx, packages/component-library/stories/InlineNotification.stories.tsx
Inline notifications do not always need children. This PR makes them non-mandatory and remove padding issues that occur when notifications have no children.
This PR also makes other slight padding adjustments to inline notification.
Padding issue when no children: …
=> fix: Adjust padding and sizing within inline notifications

draft-packages/loading-placeholder/KaizenDraft/LoadingPlaceholder/decision-tokens.scss, draft-packages/loading-placeholder/KaizenDraft/LoadingPlaceholder/styles.scss
Note about Zen fallback:
- The "Zen" fallbacks are actually updated in this PR to match the Zen UI Kit.
- Zen default bg was Wisteria 100, now Wisteria 200
- Zen reversed bg was white 50% opacity, now white 65% opacity
The pattern I've used to add alpha to the token _only if using the custom property_
relies on cascading fallbacks in CSS Custom Properties.
I did a codepen to demonstrate how this works:
https://codepen.io/jasononeil/pen/vYyjzMz?editors=1100
Alternatively, I could use React Context to get the theme, but that won't work with the Elm version.
:shrug: …
=> feat: update LoadingPlaceholder to support Heart theme

draft-packages/menu/KaizenDraft/Menu/components/MenuContent.module.scss, draft-packages/menu/KaizenDraft/Menu/components/MenuSeparator.tsx, draft-packages/menu/package.json
Update Menu for Heart theme. This is a simple old -> new token change with no decision tokens.
Also:
* MenuSeparator component now using the Divider component with the menuSeparator variant
* Slight margin fix on the Menu container.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428 …
=> feat: Update Menu component to support Heart

draft-packages/table/KaizenDraft/Table/styles.scss
- Fixes Table styles that we're accidentally migrated incorrectly (a typo)
- Move to spacing token variants rather than `calc()` in some declarations.
=> fix: Table styles regression from Heart update

packages/component-library/components/Notification/_styles.scss
Fixes the negative margin on InlineNotification's cancel button (needed a `calc()` function to negate a CSS variable; silently failed)
=> fix: InlineNotification issue from Heart update

packages/component-library/ElmStories/InlineNotificationStories.elm, packages/component-library/stories/InlineNotification.stories.tsx
Just add some pointless text to the multiline variant of inline notification, so that the story makes sense, and Chromatic can perform a more accurate test.
=> docs: Multiline inline notification text

draft-packages/hero-card/KaizenDraft/HeroCard/HeroCard.scss, draft-packages/hero-card/KaizenDraft/HeroCard/HeroCard.tsx, draft-packages/hero-card/docs/HeroCard.stories.tsx
Adding the ability to change the background color of the left hand side of the HeroCard component. Now several options are available including the default background colour, currently set to wisteria700.
I thought about adding a transparent background, and then controlling the background color in a child element, but there was too much absolute positioning and/or negative margins involved for it to feel like a clean solution.
This is still not a very extensible way to define variations, but I think a larger conversation needs to happen before dynamic styling is included in any components.
Previously the HeroCard component used wisteria700 as a hardcoded background color, this change allows variations to the background color, allowing the new survey summary page to use it and match the …
=> feat: add additional background colors to HeroCard component

packages/component-library/components/Notification/ToastNotification.tsx, packages/component-library/package.json
Deprecate the `<ToastNotification>` component API in favour of the imperative API introduced in: https://github.com/cultureamp/kaizen-design-system/pull/758
The component itself remains for backwards compatibility, and the stories et al have already all been updated in the linked PR above.
=> fix: Deprecate ToastNotification component

draft-packages/modal/KaizenDraft/Modal/Modal.elm, draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.spec.tsx, draft-packages/modal/KaizenDraft/Modal/Presets/InformationModal.spec.tsx, draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.spec.tsx, draft-packages/modal/KaizenDraft/Modal/Presets/RoadblockModal.spec.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.scss, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.spec.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx, draft-packages/modal/package.json, yarn.lock
Replace CSSTransition from react-transition-group with Transition from headlessui/react. The API is very close making it a near drop-in replacement.
For this PR, the relevant change happens in `GenericModal.scss` and `GenericModal.tsx`. There is also a minor change to `Modal.elm` to make the CSS class names consistent.
The rest of the PR is adding tests to GenericModal and the presets we have (ConfirmationModal, InformationModal, InputEditModal, RoadblockModal) to hopefully catch issues like this in the future.
react-transition-group is not actively maintained (https://github.com/reactjs/react-transition-group/issues/630#issuecomment-797733168) and is not fully compatible with React 17 (https://github.com/cultureamp/kaizen-design-system/issues/1184).
A …
=> fix: React 17 fix - replace react-transition-group in draft-modal

draft-packages/form/KaizenDraft/Form/SelectField/SelectField.elm
This is a follow up to https://github.com/cultureamp/kaizen-design-system/pull/1351, but also adds the clearable option to SelectField (not just Select, I forgot to do this) …
=> feat: add clearable option for SelectField.elm

draft-packages/form/KaizenDraft/Form/SelectField/SelectField.elm
Export the `clearable` config option of the Elm SelectField so it can actually be used!
=> fix: export elm select field clearable

packages/react-deprecate-warning/src/util.ts
All our consumers use Webpack's DefinePlugin to emulate process.env. This either generates a string, "process.env.NODE_ENV", or an object process.env with properties such that they can be referenced like so process.env["NODE_ENV"]. This makes it safe to not need to check if process.env is a valid object.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers …
=> fix: Update environment check to not use optional chaining

draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.spec.tsx, draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.stories.tsx, draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.tsx, draft-packages/collapsible/KaizenDraft/Collapsible/__snapshots__/Collapsible.spec.tsx.snap, draft-packages/collapsible/KaizenDraft/Collapsible/styles.scss
- Update the Collapsible component to have a clear variant, that when open, will have a border on the bottom of it. This change is also keeping the default the way it is and tests/snapshots have been updated.
- This has been updated so we can reflect the new designs for the survey overview page. Where a collapsible component can be open with a border bottom on it.
- Closes this: https://cultureamp.atlassian.net/secure/RapidBoard.jspa?rapidView=186&projectKey=EARTH&modal=detail&selectedIssue=EARTH-307&quickFilter=194
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for …
=> feat: Add clear variant to Collapsible component

draft-packages/select/package.json
add an explicit `@kaizen/draft-button` dependency to `@kaizen/draft-select`
The Elm Select now uses a button, an explicit `@kaizen/draft-button` import was missing, so it wouldn't compile when used in downstream repos.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Acc …
=> fix: add explicit @kaizen/draft-button dep to @kaizen/draft-select

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
In https://github.com/cultureamp/kaizen-design-system/pull/1232 there was an `overflow-x: hidden` added to the Title Block in order to avoid a scroll bar appearing on smaller viewports. This created a new bug:
https://user-images.githubusercontent.com/1811583/115176603-c74a0e00-a110-11eb-8a5f-62c6e905e2c6.mov
This PR removes the `overflow-x: hidden` that was added, and fixes the root cause of the scroll bar. The scroll bar was caused by an element that adds a shadow to the tabs:
This element is rotated 270deg, which was causing a scroll bar to appear. We've fixed this by making this element square. …
=> fix: Stop shadow from overflowing and remove overflow-x:hidden

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx, draft-packages/illustration/docs/IllustrationScene.stories.tsx
Work:
- Added an illustration here: https://github.com/cultureamp/kaizen-design-system-assets/pull/24
- Now added it to Kaizen for use
=> feat: Add get started illustration to storybook and scene component

packages/design-tokens/src/themes/heart.ts
These were mis-calculated in passing them over originally. @katsambarcus has re-calced them for me.
=> fix: Update data-viz color values for Heart theme

draft-packages/menu/KaizenDraft/Menu/styles.scss
The build wasn't breaking before this fix, but it was breaking consumers when this package was being used due to one of the variables not being present in any of the imports. …
=> fix: Remove unused imports and class

draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx, draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap, draft-packages/illustration/KaizenDraft/Illustration/illustration.spec.tsx, draft-packages/illustration/docs/IllustrationScene.stories.tsx, draft-packages/illustration/docs/IllustrationSpot.stories.tsx, draft-packages/illustration/package.json
Add the Heart spot illustrations, and conditionally render them based on a theme.
Few things to call out: 
* I have used snapshot tests. The removal of any of these illustrations will be a breaking change and we should guard against that in our tests.
* When there is a Heart illustration without a corresponding Zen illustration, a warning will be logged when using these under a Zen theme. I don't feel that we should stop someone from using a Heart illustration in Zen since Zen will eventually be deprecated.
* I've also stopped rendering each of these illustrations as a separate story and have instead made a mega-story that matches the UI kit sticker sheet. I hope that this makes it a little easier to find the illustration needed.
* You're probably best to review this in Chromatic. 
Story …
=> feat: Added Heart spot illustrations

draft-packages/collapsible/KaizenDraft/Collapsible/CollapsibleGroup.tsx, draft-packages/collapsible/KaizenDraft/Collapsible/styles.scss
- Fix current bug in production in a quick way without disturbing the design too much.
- This is the only way without adding a _lot_ of logic around when the collapsible container is open to dynamically move around where to put the border radius. Annoyingly, we can't have it on the outer container (hence this fix) and having it on the inner container, it would need to move around when opening/closing the component and when it turns sticky. Something too large of a task for a fix that is currently hiding content from customers.
- Fixes this: https://cultureamp.atlassian.net/browse/KR-284 …
=> fix: remove hidden overflow on collapsible component

legacy-packages/title-block/ElmStories/TitleBlockStories.elm, legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss, legacy-packages/title-block/docs/ElmTitleBlock.stories.tsx
* Added (deprecated) Elm stories for titleblock
* Changed background color to wisteria-600 on heart (maintaining wisteria-700 on Zen) so that it is consistent with Zen navigation bar and other navs in the platform
=> feat: Improved Heart support for titleblock

draft-packages/table/KaizenDraft/Table/Table.tsx, draft-packages/table/KaizenDraft/Table/styles.scss, draft-packages/table/docs/Table.stories.tsx
Introduce a `reserved` prop for the draft table header text.
Also adding a story to illustrate the reversed style.
For the new performance goals reporting page, a `reversed` prop is needed for header text, so that it is readable on top of the `Skirt` component, styled in Wisteria styling …
=> feat: add reversed table header styling

draft-packages/tag/KaizenDraft/Tag/Tag.scss, draft-packages/tag/KaizenDraft/Tag/Tag.tsx
Replaces out top and bottom margins on our Tag dismissIcon with 100% height.
`performance-ui` has the following global css coming from Materialize:
```
*, *:before, *:after {
box-sizing: inherit;
}
```
This is causing the following issue with our Tag:
=> fix: Use 100% height for dismissIcon on Tag to avoid global box-sizing css conflicts

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/docs/Button.stories.tsx, draft-packages/button/package.json
Add `badge` props to the button to allow for the button to render `Badge` component to the right of the `Button` label
In the new design for [Filtering](https://www.figma.com/file/kz2iLEjs3HIOMfF6k5X4l1/Global-Filter-Menu?node-id=2132%3A3882), there's a need to have a Button that also shows a Badge with a number of selected filter in it. For this particular case, we need to have new props in the Button component to allow the consumer to show badge information in the UI.
- Have you updated any …
=> feat: add badge component to the button

draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.tsx, draft-packages/collapsible/KaizenDraft/Collapsible/CollapsibleGroup.tsx, draft-packages/collapsible/KaizenDraft/Collapsible/__snapshots__/Collapsible.spec.tsx.snap, draft-packages/collapsible/KaizenDraft/Collapsible/styles.scss
- Get the border radius back onto the collapsible component without cropping content
- Without this fix, the corners of the collapsibles aren't rounded
- With this fix, they all are _except_ the sticky component when scrolling - negible and a huge task (e.g. InteractionObserver in a HOC) for something so small.
- Last PR removing the overflow: https://github.com/cultureamp/kaizen-design-system/pull/1509
- Have you …
=> fix: border radius on collapsible component

draft-packages/menu/KaizenDraft/Menu/StatelessMenu.tsx
Adds `e.preventDefault()` to the button that opens the dropdown menu.
Unify found a bug where one of our Menus was behaving as a link when the dropdown button was clicked, without clicking on any of the menu items.
=> fix: Prevent default on Menu trigger button

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/docs/Button.stories.tsx
Use `default` variant for the badge component inside the button when the `reversed` props is passed to the button.
Currently the badge component inside the `Button` use `active` variant and it won't render correctly if the button has `reversed` props pass to it. The `Badge` component needs to use `default` variant for the `reverse` state.
=> fix: add default variant for badge in button component when button is in reversed

packages/component-library/components/Notification/ToastNotification.tsx
Fixes #1545.
The `onHide` prop was being dropped from the ToastNotification. This re-adds it.
[Issue 1545](https://github.com/cultureamp/kaizen-design-system/issues/1545) …
=> fix: Pass the missing onHide prop to the toast

draft-packages/button/KaizenDraft/Button/components/GenericButton.module.scss, draft-packages/button/KaizenDraft/Button/styles.scss
Replaces `display: flex` with `display: inline-flex` on the `%caButton` button styles by default, then applies `display: flex` when the button is full width.
An edge case has been found where, if the parent of the Button has `display: grid` and the .button element is an `<a>` (an `href` prop has been provided), then the container would be full width like this:
Using `inline-flex` instead fixes this issue.
What's still a mystery to me is why this only happens when the element is an `<a>` and not a `<button>`, given both elements have the same `display` property. …
=> fix: use inline-flex for Button to fix edge case

draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.tsx
In order to support translations that happen in some legacy class style components we need to be able to provide a react node to the heading.
=> fix: Allow react nodes for heading text

draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/docs/Button.stories.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx
Refactor the `TitleBlockZen` to use the `badge` props from the `Button` component instead of utilising the `additionalContent` props from the `GenericButton`
With the new `badge` props that's available in the `Button` component, we no longer need to use `additionalContent` props from the `GenericButton` to render a `Badge` component in the `TitleBlockZen`
Fix #1533
=> refactor: modify TitleBlockZen component to render badge from Button instead of additionalContent props

draft-packages/tile/KaizenDraft/Tile/TileGrid.scss, draft-packages/tile/docs/Tile.stories.tsx
This is follow-up to https://github.com/cultureamp/kaizen-design-system/pull/1518 which introduced flexible sizing for `Tile` components within the `TileGrid`. That implementation used `auto-fit` to establish the layout, which works fine when we have a full row of items (at least 4), but when the grid contains fewer than 4 items it means the items _streeetch_ to fill the allowable space.
New behaviour is demonstrated here: https://dev.cultureamp.design/max/fix-tile-grid-with-short-rows/storybook/?path=/story/tile-react--tile-grid-with-few-tiles
With `auto-fit`:
With `auto-fill`: …
=> fix: Ensure tiles don't expand to fill width when they’re short of a row

draft-packages/tile/KaizenDraft/Tile/components/Action.tsx, draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx, draft-packages/tile/docs/Tile.stories.tsx
Actions in Tile components can be links, but aren’t able to open in new tabs. This adds the `newTabAndIUnderstandTheAccessibilityImplications` prop from the `Button` component (which underpins Tile actions) to enable that behaviour.
I need this specifically for the preview links in the updated Template Library tiles:
These currently open in a new tab and I’d like to keep that behaviour the same so that users aren’t taken away from the Template Library when they’re exploring how a particular template looks.
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participa …
=> feat: Allow actions to open in new tabs

packages/hosted-assets/package.json
Fix: Actually publish the `Kaizen.HostedAssets` elm files (they weren't being included in the `package.json` `files`)
We realised after trying to use `@kaizen/hosted-assets` that the Elm code wasn't appearing in the `node_modules` dir.
I'm pretty sure this will fix the issue, but I'm not really sure how to test it without merging the PR first.
- Have you reviewed Culture Amp's Web Accessibility guide [Current …
=> fix: elm Kaizen.HostedAssets code was not being published

draft-packages/tile/KaizenDraft/Tile/MultiActionTile.tsx, draft-packages/tile/KaizenDraft/Tile/__snapshots__/Tile.spec.tsx.snap
Add a half-measure space between the Secondary and Primary actions for `MultiActionTile` components.
Before:
After:
- If this contains substantial visual changes, especially far reaching ones, have you …
=> fix: Add space between actions on MultiActionTile

draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx, draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
There are a few spot illustrations for templates that are missing Zen equivalents. This PR add automatic fallbacks for these to the Zen “Blank Survey” illustration so that consumers don’t have to think about mapping them.
These illustrations are all "template" illustrations and would need to be mapped manually to the same result within consuming code to avoid having Heart illustrations accidentally bleed into Zen-themed interfaces. Doing the mapping here means that we won’t get accidental mix-ups, and that consumers can still override with more specific fallbacks if they’d like to.
<details>
<summary>Zen</summary>
</details>
<details>
<summary>Heart</summary>
</details>
- Has the test suite been …
=> fix: Fallback to blank survey for Heart template illustrations without Zen equivalents

packages/component-library/components/Notification/components/GenericNotification.spec.tsx, packages/component-library/components/Notification/components/GenericNotification.tsx
Toasts were calling setState while unmounted. We don't want this behaviour.
* The set state in requestAnimationFrame needed a mount check
* When a user hides a notification, we weren't clearing the timeout if it uses autohide
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/ …
=> fix: toast unmounted set state

packages/component-library/components/Notification/_styles.scss
The GlobalNotification shows this bug when used in consumers, but it doesn't show up in Storybook:
The bug appears to show because the component sets `box-sizing: border-box` at the top level, and does not reset this to `content-box` for the icon, despite the icon depending on it to show correctly.
=> fix: Make box-sizing explicit

draft-packages/illustration/KaizenDraft/Illustration/illustration.spec.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.spec.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx, packages/component-library/components/Notification/ToastNotification.spec.tsx, packages/react-deprecate-warning/src/index.spec.tsx
The console is a little noisy, cleaning it up so we can more easily catch warnings and errors when we (never!) add them.
Theres some 'real' warnings /errors that are harder to see/catch because we have added warnings for consumers. While the warnings are good, we don't want to pollute our console when running tests.
* Most of these add a `mockImplementation` to the spy that is being created for console.warn. I've changed any tests that are explicitly looking for this to check the `mockImplementation` call.
* The modals needed a `ModalAccessibleLabel` so I added one instead of mocking the warn function. Modals also have a seperate issue that will be addressed in a follow-up PR.
- Has the test …
=> test: mock and or fix deprecation warnings in console when running tests

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss, draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.spec.tsx, draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx, draft-packages/guidance-block/docs/GuidanceBlock.stories.tsx, draft-packages/guidance-block/package.json
We want to render a Spot inside a GuidanceBlock
This is v1, v3 can be found here: https://github.com/cultureamp/kaizen-design-system/pull/1594
Change GuidanceBlock to accept an `illustration` prop of `React.ReactElement<SpotProps>`. Render that where we used to render the `img`. …
=> feat: Add Spot to GuidanceBlock v1

draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx, draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap, draft-packages/illustration/docs/IllustrationSpot.stories.tsx
Add 180 versions for template library illustrations: Individual, Manager, and Leadership. We currently only have 360 versions for these.
The illustrations won’t appear in Storybook until https://github.com/cultureamp/kaizen-design-system-assets/pull/34 is merged. Note that because we don’t have Zen versions of these illustrations that we’re falling back to the "Blank Survey" spot like all other Template Library spots.
We have templates that reference 180s but no illustration to match them.
- Have you …
=> feat: Add 180 versions for performance template library spots

draft-packages/slider/KaizenDraft/Slider/Slider.spec.tsx, draft-packages/slider/KaizenDraft/Slider/Slider.tsx
When the disabledLabel is not provided the slider will continue to show the low and high labels for the scale.
When using the slider with 1-1s we need to show the scale to the manger who is viewing the slider, but cannot edit the slider.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/page …
=> feat: allow the scale labels to show if the disabledlabel is not provided

draft-packages/tooltip/ElmStories/TooltipStories.elm, draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.elm, draft-packages/tooltip/KaizenDraft/Tooltip/TooltipElm.scss, draft-packages/tooltip/docs/ElmTooltip.stories.tsx
There is an issue with the existing tooltip implementation with Elm in that it takes up space when it is hidden. This causes ugly and annoying horizontal scrollbars too appear in confined spaces.
A quick fix is achieved by making `.contentWrap` have `display: none` when the tooltip is not hovered. The downside is that there is no animation.
This adds an optional (not on by default) parameter `dontTakeUpSpaceWhenHiddenQuickFix` that makes the tooltip not take up space, but also disables the animation.
There isn't a simple way to acheive this without completely rewriting the component to use something like popper.js, like has been done for the React version.
- …
=> feat: quickfix option for Elm Tooltip to not take up space

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss, draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
Ok... The width and height of the illustration element must be seperate from the element that has padding for the guidance block style. This is because consumers are likely to implement `box-sizing: border-box` which will destroy the dimensions of the image.
Alternatively, the guidance block should _use_ `box-sizing: border-box` but I don't know anymore, I'm losing my
mind. Or it should specify `box-sizing: content-box` to at least combat top level resets?
Ah... Originally I wanted to render an image but now I just want out.
Previous PRs can be found here:
https://github.com/cultureamp/kaizen-design-system/pull/1595
https://github.com/cultureamp/kaizen-design-system/pull/1606
https://github.com/cultureamp/kaizen-design-system/pull/1610
- Does there need to be right-to-left (RTL) options …
=> feat: add wrapping element to illustration

draft-packages/badge/docs/Badge.stories.tsx, draft-packages/empty-state/ElmStories/EmptyStateStories.elm, draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss, draft-packages/hero-card/docs/HeroCard.stories.tsx, draft-packages/hero-panel/KaizenDraft/HeroPanel/HeroPanel.tsx, draft-packages/hero-panel/package.json, draft-packages/hierarchical-select/docs/HierarchicalSelect.stories.tsx, draft-packages/modal/KaizenDraft/Modal/Primitives/ModalHeader.elm, draft-packages/popover/KaizenDraft/Popover/styles.scss, draft-packages/table/KaizenDraft/Table/styles.scss, draft-packages/table/docs/Table.stories.tsx, draft-packages/vertical-progress-step/KaizenDraft/VerticalProgressStep/VerticalProgressStep.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Menu.tsx, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/helpers/OffCanvas.module.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/helpers/components/Header.tsx, draft-packages/zen-navigation-bar/docs/ZenNavigationBar.stories.tsx, draft-packages/zen-navigation-bar/package.json, site/package.json, site/src/pages/index.tsx
Updates any usages or references to the old `component-library` Button to the new `draft-button` Button.
Affected components:
* HeroCard
* Elm Modal (close button in header only)
* ZenNavigationBar (deprecated anyway)
Otherwise the others were just usages in stories, or importing the stylesheet for the `button-reset` mixin. Plus there was one usage on the Kaizen site.
https://github.com/cultureamp/kaizen-design-system/issues/1466
- Have you updated any relevant documentation or left useful comments …
=> feat: Update all usages and references of deprecated Button

draft-packages/button/docs/Button.stories.tsx, draft-packages/button/docs/ElmButton.stories.tsx
Quick follow up to https://github.com/cultureamp/kaizen-design-system/pull/1632 - remove `(Zen)` from the Button stories because it no longer makes sense.
=> chore: Remove (Zen) from Button stories

draft-packages/menu/KaizenDraft/Menu/MenuDropdown.tsx
This moves the event listener that checks for document-level clicks (and decides whether or not to hide the dropdown menu) into the capturing phase rather than the bubbling phase. In doing so we also need to check that the `referenceElement` isn’t the targeted event (or one of its children).
We’re seeing issues in multiple places where multiple `<Menu>` instances are open as users move between menus. I.e., if a user:
1. Opens a menu by clicking on its button
2. Attempts to open a different menu by clicking on its button
3. Both menus would be open
This strangely doesn’t manifest within the Kaizen Storybook (even though it should), but we’ve seen it occur in multiple different consuming applications (comparisons-service, unified-home). The issue occurs because of the `e.stopPropagation()` …
=> fix: Fix issue with autohide for draft-menu

draft-packages/slider/KaizenDraft/Slider/Slider.spec.tsx, draft-packages/slider/KaizenDraft/Slider/Slider.tsx
Currently, the default Slider component has the dot slightly off-center. To give a symmetrical view in the ui, design agrees to make this change across our products - to show it at the center initially.
When user lands in a page with default Sliders, the ui looks a bit unpolished/unfinished. The rating in our system is saved as a whole number (DB). For the slider to be at the center (UI), it had to accept a floating number. Hence, on the first load - the step is set to accept a floating number, in the event the user changes the position of slider, it goes back to whole number stepping and stays as our existing implementation + behaviour.
https://user-images.githubusercontent.com/26585669/119603689-01ee4700-be31-11eb-8fa7-9deffa8c4fe0.mov
Yes - Has the test suite been updated?
Yes - Have …
=> feat: visually centre rating slider dot on default

draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx
Add an inert-but-named attribute to the `Transition` component in modals.
We’re seeing flaky tests due to timing issues around animations for modals. This allows us to override that timing using a CSS hook while avoiding the previous method of using a global class name:
```css
[data-generic-modal-transition-wrapper] * {
animation: none !important;
transition: none !important;
}
```
- Have you reviewed Culture Amp's Web …
=> fix: Add known attribute name to allow animation overrides

draft-packages/collapsible/KaizenDraft/Collapsible/__snapshots__/Collapsible.spec.tsx.snap, draft-packages/tile/KaizenDraft/Tile/__snapshots__/Tile.spec.tsx.snap, packages/component-library/components/Icon/Icon.tsx, packages/component-library/components/Notification/__snapshots__/GlobalNotification.spec.tsx.snap, packages/component-library/components/Notification/__snapshots__/InlineNotification.spec.tsx.snap
Closes https://github.com/cultureamp/kaizen-design-system/issues/1289
I'd imagine this is what the original author was trying to do here. At the moment `aria-labelledby` is always added to the Icon svg, but it links to nothing if the Icon isn't a meaningful image and the `<title>` part hasn't been added.
=> fix: Only add aria-labelledby when Icon is meaningful img

storybook/theme-switcher-addon/themeManager.ts
The Storybook theme switcher add on is defaulting to Zen. Now that we've GA'ed Heart, let's switch this to default to Heart instead.
=> chore: Default Storybook to Heart

draft-packages/form/ElmStories/SelectFieldStories.elm, draft-packages/form/KaizenDraft/Form/SelectField/SelectField.elm, draft-packages/select/ElmStories/SelectStories.elm, draft-packages/select/KaizenDraft/Select/Select.elm, draft-packages/tag/ElmStories/TagStories.elm, draft-packages/tag/KaizenDraft/Tag/Tag.elm, draft-packages/tag/KaizenDraft/Tag/TagElmExtra.scss, draft-packages/tag/docs/ElmTag.stories.tsx
**NOTE: Elm only, no code that is consumed by React has been touched**
This is a option to deal with tags with user generated content
that is so large that the text escapes the available horizontal
space (such as in a multi-select field). Currently the tag
completely breaks if this happens. There's an existing option
to add truncation (ellipsis) with a fixed max width, but the problem
with that is there is no tooltip, there is no way to distinguish
tags that start with the same text (this is a real problem in production)
Ideally, we'd implement the tooltip when the tag truncates (as is specified in the docs for Tag), but this
is unfortunately in the way too hard basket for Elm. You need to measure
the width of the text with an effect, and then the component requires state
to keep track of …
=> feat: elm tag allow text wrapping option + dismiss button size fix

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx, draft-packages/title-block-zen/docs/TitleBlockZen.stories.tsx
make the title block zen component support the scheduled and closed statuses
When the title block is showing a survey config or report page we show a tag next to the survey title with the status of the survey. When we released title block in Jun 2020, the title block zen had only "draft", "live" and "default" states. The reality is that a survey can have more than that. This changes silently broke a feature released in Oct 2019 by engagement camp where it showed the scheduled status on the title block.
More context in the github issue description: https://github.com/cultureamp/kaizen-design-system/issues/1669
- Have you done cross-browser testing for our …
=> fix: add new survey statuses to title block zen component

.github/dependabot.yml, storybook/theme-switcher-addon/themeManager.ts
This config will supercede the org-level defaults for Dependabot. 
**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.
=> chore: Add dependabot config

stylelint.config.js
https://github.com/cultureamp/kaizen-design-system/issues/1049
we don't use color names like "white" in Kaizen, so we shouldn't warn when not using them. (https://stylelint.io/user-guide/rules/list/color-named/)
(noisy warnings)
```
packages/design-tokens/sass/color-vars.scss
313:48  ⚠  Expected "#ffffff" to be "white"   color-named
packages/design-tokens/sass/color.scss
48:18  ⚠  Expected "#ffffff" to be "white"   color-named
✨  Done in 1.43s.
```
(no noise)
```
✨  Done in 1.65s.
```
=> fix: remove stylelint color-named rule

.buildkite/pipeline.yaml, .buildkite/scripts/build-site.sh, .buildkite/scripts/build-storybook.sh, .buildkite/scripts/compile.sh, .buildkite/scripts/helpers/setup-registry.sh, .buildkite/scripts/lint.sh, .buildkite/scripts/release.sh, .buildkite/scripts/run-chromatic-build.sh, .buildkite/scripts/test-react-16.sh, .buildkite/scripts/test-react-17.sh, .npmrc, README.md, docker-compose.yml, package.json, scripts/check-if-authenticated-to-github-registry.bash
Setup build so that we have the _option_ of consuming private packages in this repo in the future. 
This will allow us to share webpack config so that Kaizen configs do not need to be maintained separately.
=> ci: Allow consumption of private @cultureamp packages

draft-packages/collapsible/KaizenDraft/Collapsible/styles.scss
Getting rid of purple background and borders on the Collapsible component.
This component hasn't been added to the UI Kit yet so it hasn't had a proper Heart uplift on the design or code side, this will tide us over until then.
Before (Zen):
Before (Heart):
After (Zen):
After (Heart): …
=> fix: Update Collapsible colours to be more Heart compatible

packages/brand-moment/package.json, yarn.lock
- Have Storybook stories been updated?
**If you're new to Kaizen, please …
=> chore(deps): Bump component-library dep to 10.0.1 on brand-moment

draft-packages/modal/KaizenDraft/Modal/Primitives/GenericModal.tsx
The modal was causing issues on the Unified Home task list, where if you open it via the overflow menu on a task, its click events bubble up and trigger the click event on the task row, which opens the list of subtasks.
I confirmed that this was happening by logging the value of `e.target` and `e.currentTarget` on the task list row's click handler, and sure enough `e.target` showed whichever node of the modal that I clicked on, including just clicking anywhere on the div (not a button).
This PR stops event propagation at the top level of the modal to fix this issue in any future cases as well. I have called `stopPropagation` on the `Transition` component because it is the highest node in the DOM – if I called it any further down the tree, it would break functionality around dismissing the …
=> fix: Stop propagation at top of modal

draft-packages/empty-state/ElmStories/EmptyStateStories.elm, draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.elm, draft-packages/modal/ElmStories/ModalStories.elm, draft-packages/modal/KaizenDraft/Modal/Modal.elm, draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.elm, elm.json, packages/design-tokens/elm/Kaizen/Theme.elm, packages/design-tokens/package.json, packages/hosted-assets/Kaizen/HostedAssets.elm, packages/hosted-assets/Kaizen/HostedAssets/Image.elm
- Adds Heart theme option to the Elm Modal and Empty State  illustrations (cautionary, success, informative, negative, action). Defaults to Zen if not hooked up to a "prop drilling" solution of passing the react `themeKey` to the component.
- Adds elm code to @kaizen/design-tokens for themes. Includes `Theme` type (`Zen` or `Heart`) that needs to be passed down to the components. Also a `themeDecoder` for passing the theme to the Elm app via React.
- Exposes an `image` helper function/component in `Kaizen.HostedAssets.Image` to create images that use a path from our hosted assets S3 bucket (we are currently not using hosted assets anywhere in Kaizen for Elm yet, so this was required to use the new illustrations)
- I upgraded the usages of zen illustrations in Elm modal to use the ones in …
=> feat: add Heart theme option to Elm Modal and EmptyState (for Heart illustrations)

draft-packages/select/ElmStories/SelectStories.elm, draft-packages/select/KaizenDraft/Select/styles.elm.scss, draft-packages/select/docs/ElmSelect.stories.tsx
wisteria-300 is that ugly pink colour. This now matches the
React component for the default styling of a placeholder for
a select component.
before
after
the React version (for reference)
=> fix: change elm select "faded" placeholder from wisteria-300 to 800

draft-packages/modal/KaizenDraft/Modal/Primitives/ModalHeader.tsx
In `performance-ui`, when I'm writing tests that render modals, in the happy, multiple-`it`s-passing case, I end up polluting the console with:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in ModalHeader (created by InformationModal)
```
I think this is because the ModalHeader has a setState in a requestAnimationFrame and I guess our tests are so damn good that we're unmounting too quickly?
To add a mount check, I needed to make `GenericModalSection` accept a forwardRef. So I made this a feat?
I tried avoiding this in user-land but it's not possible to mock internal references that these components …
=> fix: Remove hasRendered state from ModalHeader

draft-packages/tooltip/KaizenDraft/Tooltip/TooltipElm.scss
The Elm tooltip still has a `wisteria-200` border (now lilac). This is a quick fix to replace them with `ash`. The Heart tooltips are not meant to have borders at all - this is just a quick fix, not a full upgrade.
Before:
After:
=> fix: elm tooltip heart uplift quick fix

.github/workflows/chromatic.yaml
We recently released a PR that added a github Action for Chromatic, that only gets triggered on PR comments containing "run chromatic" There was absolutely no way to test it without merging it to master first (because actions triggered by comments can only be run on the master branch). Guess what, it didn't work! This hopefully fixes it, But there's no way to test this PR until it's merged, so 🤞 .
=> ci: fix the chromatic "find PR" technique so it works for PR comments

packages/brand-moment/package.json, packages/brand-moment/src/BrandMoment.scss, packages/brand-moment/src/BrandMoment.tsx, packages/brand-moment/src/stories/BrandMoment.stories.tsx, packages/brand-moment/src/stories/ExampleHeaders.scss, packages/brand-moment/src/stories/ExampleHeaders.tsx
Main objective here was to add responsiveness to the `BrandMoment` component, which was previously mainly built around larger viewports and didn't scale down well.
Before:
https://user-images.githubusercontent.com/1811583/122691403-d1080300-d272-11eb-8412-6afc9cb6cb24.mov
After:
https://user-images.githubusercontent.com/1811583/122691472-365bf400-d273-11eb-9d18-8ac44371b140.mov
Notes:
* I've switched from flex to grid for the main container so that I could utilise `gap`.
* I've used a mobile first approach to media query styling. Small viewport styles are applied by default, then larger viewport styles are added under `min-width` media queries.
----
I've also bundled in a bunch of small tweaks that came out of a review with @katsambarcus 
**Note:** this doesn't yet changing the typography …
=> feat: Add responsiveness to BrandMoment

draft-packages/form/KaizenDraft/Form/SelectField/SelectField.elm, draft-packages/select/ElmStories/SelectStories.elm, draft-packages/select/KaizenDraft/Select/Select.elm, draft-packages/select/KaizenDraft/Select/SelectInput.elm, draft-packages/select/KaizenDraft/Select/styles.elm.scss, draft-packages/select/docs/ElmSelect.stories.tsx
This adds an optional `controlHasUnconstrainedHeight` option that defaults to false. The default behaviour (as is current) is that the control* is always only takes up one line, and that if the select item is longer than the available spac,e it gets truncated with an ellipsis. That is problematic if being able to read the full text of the selected item is very important for the use case. This gives an option to view the the full option, with text wrapping instead of truncation (with unconstrained height). 
*WTF is "a control", as in the noun, not the verb? You know, that thing you click on that's not the dropdown that opens up. It's just what it's called, don't blame me! ... also, WTF is "a select" - "select" is a verb, not a noun! There is no noun form of "select" in the dictionary. …
=> feat: controlHasUnconstrainedHeight option for Elm Select

packages/brand-moment/src/BrandMoment.scss, packages/brand-moment/src/stories/BrandMoment.stories.tsx, packages/brand-moment/src/stories/ExampleHeaders.scss, storybook/preview.tsx
Adds better RTL support to the `BrandMoment` component, mainly by swapping out directional properties with the awesome new [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties). Browser support: https://caniuse.com/css-logical-props
Also adds an ltr/rtl switcher to the Kaizen storybook for easy RTL support checking on any component.
I had descoped this from the first pass with the intention of coming back and tidying this up. It wasn't too bad because I used a lot of grid and flex, but there were still a few things to fix up.
* Our `Box` component's RTL support isn't so great - it requires you to send in an `rtl` prop which I would like to deprecate in favour of just using logical properties as I have done here. As a result - the spacing between two …
=> fix: Add better RTL support to BrandMoment

draft-packages/empty-state/KaizenDraft/EmptyState/README.mdx
Updates to empty state guidance particularly around:
- responsive variants
- negative mood
- when to use/not use
Branch preview direct link: https://dev.cultureamp.design/dlimiter-empty-state-updates/components/empty-state/
=> docs: empty state updates

draft-packages/avatar/KaizenDraft/Avatar/Avatar.tsx, draft-packages/avatar/docs/Avatar.stories.tsx
Handle fallback case where the the fullname cannot be provided and the default icon should get shown.
During an update of performance-ui it was found that there are a few places where the value may not exist.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility …
=> feat: Allow the Avatar to handle the case where the fullname cannot be provided

packages/brand/src/Brand/Brand.scss, packages/brand/src/Brand/Brand.tsx
Constrains the size of the image on the Brand component to 100% of the container width.
When implementing the Brand component into the new minimal nav, I found that the logo was going over the container width. This fixes that.
=> fix: Constrain brand width to 100% of container

draft-packages/tile/KaizenDraft/Tile/__snapshots__/Tile.spec.tsx.snap, draft-packages/tile/KaizenDraft/Tile/components/GenericTile.scss, draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx
https://cultureamp.slack.com/archives/C0189KBPM4Y/p1623800537096700
Remove the title from the back of the Title component.
Removing the title from the back increases the available space for content. This was prompted by a desire to show a "View available languages" button for survey template tiles, but we're likely to run into space issues pretty regularly.
I've also left-aligned the text, at Marc's direction.
Context: https://cultureamp.slack.com/archives/C0189KBPM4Y/p1623800537096700
Before:
After:
UI Kit:
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Partici …
=> feat: Remove title from back of Tile component

draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.spec.tsx, draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx, draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx
NOTE: mp4 formats do not support transparency. For this reason, whenever the mp4 fallback is active (<IE11, some versions of Safari) a background colour has been encoded into the video. Ensure the background colour always matches your intended usage.
**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.
=> feat: Add mp4 fallbacks to animated illustrations

draft-packages/avatar/KaizenDraft/Avatar/Avatar.tsx
In some cases the onLoad event does not fire if the image is from cache. This change checks if the image is in a complete state when it is rendered and set the loading state to success.
Navigating back and forth on the avatar with photos stories could repo this.
=> fix: remove loading state if avatar is already loaded

draft-packages/form/KaizenDraft/Form/CheckboxField/styles.scss
Closes  https://github.com/cultureamp/kaizen-design-system/issues/1696
The stone hover colour is quite subtle, the last checkbox is unselected and with a hover state. 
- If this contains substantial visual …
=> fix: Change checkbox inactive hover colour to stone

draft-packages/select/KaizenDraft/Select/Select.tsx
When updating the Select draft package in performance-ui, type errors were discovered. It seems no types were being 'passed through' to the Select component so we were getting errors around function types accepting `any`.
On master
This change:
Looks like a recent change converting the component to a forwarded ref component caused the issue even though normally it wouldn't have been a problem. I think the complexity of some of `react-select`'s types caused them to become lost. However switching to the `NamedProps` interface worked as this is the type that is used under `Props` which we were originally using and is probably the one we should have been using.
- …
=> fix: Select types passing through to consumer

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx, draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap, draft-packages/illustration/docs/IllustrationScene.stories.tsx
Makes this available to be used as an illustration https://github.com/cultureamp/kaizen-design-system-assets/pull/42
For use in a new brand moment in Skills Coach
https://www.figma.com/file/RsaX0uZxUWZKwpCRdnvTwj/%F0%9F%9A%A7-Skills-Coach-2021-Q3?node-id=7926%3A48341 …
=> feat: Add starter kit brand moment illustration

.buildkite/scripts/run-chromatic-build.sh
Enables [Chromatic TurboSnap](https://www.chromatic.com/docs/turbosnap) by adding the two required parameters to our storybook build and chromatic cli script.
This will make Chromatic only create snapshots when there are changes, which will save us a ton of credits and allow us to disable the current functionality of only running it if you comment on the PR with "Run Chromatic"
=> chore: Enable Chromatic TurboSnap

.eslintrc.js, draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx, package.json, storybook/theme-switcher-addon/preset.ts, yarn.lock
As discussed on Slack: https://cultureamp.slack.com/archives/C016N8Y1E10/p1627023487120400
The rule that prevents us from defining functions using the `function Name()` syntax is not desired by a few of us in the team (but opening this up to any arguments against the chanage). …
=> refactor: Remove prefer-arrow-function eslint rule

draft-packages/tag/KaizenDraft/Tag/Tag.elm, draft-packages/tag/KaizenDraft/Tag/Tag.scss, draft-packages/tag/KaizenDraft/Tag/Tag.tsx, draft-packages/tag/docs/Tag.stories.tsx
The dismiss button of the Tag component is completely inaccessible.
- It should support keyboard and screen reader accessibility (which can easily be achieved by making it a `button` element instead of a `span`
- it should have a focus ring as per the latest Heart styles
- the border of the entire component should not change colour when focussed or hovered (because only the dismiss button is interactive + this is not in the latest Heart design)
https://github.com/cultureamp/kaizen-design-system/issues/1797
As well as some non-visual accessibility improvements (works with keyboard and screen readers), there are some visual improvements:
before
after
before
after
before
after
- Has the test suite …
=> fix: Tag dismiss button accessibility + uplift

packages/design-tokens/package.json, packages/design-tokens/tsconfig.dist.json
This has caused the following issue in Buildkite:
```
[error] No parser could be inferred for file: sass/tokens.spec.js.map
```
**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.
=> fix: Exclude spec files from being compiled and published

draft-packages/badge/docs/Badge.stories.tsx, draft-packages/button/docs/Button.stories.tsx, draft-packages/button/docs/IconButton.stories.tsx, draft-packages/card/docs/Card.stories.tsx, draft-packages/collapsible/docs/Collapsible.stories.tsx, draft-packages/divider/docs/Divider.stories.tsx, draft-packages/form/docs/TextAreaField.stories.tsx, draft-packages/form/docs/TextField.stories.tsx, draft-packages/guidance-block/docs/GuidanceBlock.stories.tsx, draft-packages/likert-scale-legacy/docs/LikertScaleLegacy.stories.tsx, draft-packages/loading-placeholder/docs/LoadingPlaceholder.stories.tsx, draft-packages/menu/docs/Menu.stories.tsx, draft-packages/select/docs/Select.stories.tsx, draft-packages/table/docs/Table.stories.tsx, draft-packages/tabs/docs/Tabs.stories.tsx, packages/brand/docs/Brand.stories.tsx, packages/component-library/stories/Heading.stories.tsx, packages/component-library/stories/Paragraph.stories.tsx
These names changed in https://github.com/cultureamp/kaizen-design-system/pull/1741/files#diff-b3e4a28d9c367ace4d3bc1ebf576bc4ee1bb1927a3d141a2cf4386224dde60c0L8, but the stories weren't updated. This updates the references to the updated background colour names in our stories.
=> fix: Update Storybook background colour references

draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx, draft-packages/tooltip/docs/Tooltip.stories.tsx
The visual regression tests around the tooltip component render the button that triggers the tooltip, but not the tooltip itself. This means that these tests provide little value, unless we can get the tooltip into the test.
The ideal way to do this would be to trigger a hover event in chromatic before the screenshot is captured, but the current chromatic API doesn't support any interaction or events. Instead, we are putting a new prop into the component to signal that the tooltip should be visible on the first render. This seems like it will only be useful for testing, but someone may find a valid use for it, so it hasn't been named obtusely (a name like `chromaticTestVisibility` would send a signal that this is the only valid usage)
closes #1375 
- Does there need to be right-to-left …
=> fix: show tooltips in chromatic tests

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.tsx, draft-packages/zen-navigation-bar/docs/ZenNavigationBar.stories.tsx, draft-packages/zen-navigation-bar/package.json, legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.tsx, packages/component-library/components/Dropdown/Dropdown.tsx, packages/component-library/components/Layout/Layout.tsx, packages/component-library/components/MenuList/MenuList.tsx, packages/component-library/components/NavigationBar/NavigationBar.tsx, packages/component-library/components/OffCanvas/OffCanvas.tsx, packages/component-library/components/Text/Text.tsx
Closes https://github.com/cultureamp/kaizen-design-system/issues/1101
Adds any missing `@deprecated` doc blocks to our deprecated components + wraps them in the `withDeprecatedComponent` HOC where that was missing as well.
This helps to make it clear when engineers are using something that is deprecated.
=> fix: Add deprecated jsdocs and wrap with withDeprecatedComponent

site/docs/components/inline-notification.mdx
Adding guidance around using subtle in-line notifications
Fixing incorrect Figma embed links
Design Systems have found a need to a subtle in-line notification variant. This update provides guidance around when to use subtle vs. prominent notifications, and reworks other guidelines to match changes to the way we configure Figma variants. 
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, …
=> docs: Add subtle in-line notification guidance

packages/stylelint-plugin/package.json
Upgrade the minimum version of design-tokens within the peer dependencies of the stylelint-plugin to 2.10.3
- If this contains substantial visual changes, especially far reaching ones, have you unlocked …
=> fix: Design tokens peer version on stylelint plugin

draft-packages/button/KaizenDraft/Button/Button.elm, draft-packages/button/KaizenDraft/Button/components/GenericButton.module.scss, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/KaizenDraft/Button/styles.scss
BREAKING CHANGE: reverseColor prop removed from Button.
This prop was only changing the font color under certain circumstances.
Color will return to expected color for button (e.g. reversed / not reversed). …
=> feat: Remove reversed color prop

packages/stylelint-plugin/src/rules/lib/fixAlphaModificationFunctions.ts, packages/stylelint-plugin/src/stylelintPlugin.spec.ts, packages/stylelint-plugin/src/stylelintPlugin.ts
Make some code polish changes based on some remaining comments from https://github.com/cultureamp/kaizen-design-system/pull/1743.
- parseFloat instead of parseInt for add-alpha parsePercentage
- test/spec names needed some amending
- typo in lint rule message …
=> fix: Stylelint plugin code polish

packages/stylelint-plugin/src/messages.ts, packages/stylelint-plugin/src/rules/lib/fixAlphaModificationFunctions.ts, packages/stylelint-plugin/src/rules/no-invalid-use-of-tokens.ts, packages/stylelint-plugin/src/rules/no-invalid-use-of-var-tokens-in-equations.spec.ts, packages/stylelint-plugin/src/rules/no-invalid-use-of-var-tokens-in-equations.ts, packages/stylelint-plugin/src/stylelintPlugin.spec.ts, packages/stylelint-plugin/src/util/kaizenTokens.ts
This change improves the no-invalid-use-of-tokens rule to handle both version 2 and 3 of design-tokens, by allowing for the possibility that a token might not exist anymore within it (but still existing in the deprecated tokens list). To do this we had to also slightly modify how `fixAlphaModificationFunctions` worked (as its ability was predicated on Kaizen tokens existing).
We also improve the way we test the stylelint plugin by allowing test cases to supply a `expectedWarningMessages` field, which causes a more specific assertion to made over what warning message texts are reported, rather than just a number of them.
**NOTE** that this branch was developed as a branch off https://github.com/cultureamp/kaizen-design-system/pull/1833 which contains the breaking change of design-tokens. …
=> fix: Support design-tokens v3 in stylelint plugin

draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.tsx
- By default empty state components should animate and play once
- isAnimated and loop props exposed on EmptyState
https://dev.cultureamp.design/ally/animated-brand-moments/storybook/?path=/story/components-empty-state--neutral
=> feat: Animate empty state illustration

draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.spec.tsx, draft-packages/form/KaizenDraft/Form/Primitives/ToggleSwitch/ToggleSwitch.spec.tsx
- Add tests to the TextArea and ToggleSwitch components
- Future-proofs our components
- Closes this: https://github.com/cultureamp/kaizen-design-system/issues/911
=> chore: add tests for textarea and toggleswitch

CONTRIBUTING.md
- As we're not using the draft packages implementation anymore, I've removed it from the contributing readme.
- As a part of making the general guidelines to using Kaizen smoother, we are trying to update as many docs as possible.
=> docs: remove reference of draft in main readme

site/docs/guidelines/vertical-rhythm-and-baseline-grid.mdx
- Update baseline grid documentation
- As @sebpearce [pointed out](https://github.com/cultureamp/kaizen-design-system/issues/1149), our baseline grid documentation is out of date. Spoke with Ally and Mark and gave it a crack of removing all instances of our "baseline shift" approach but referenced it for clarity.
=> chore: update vertical rhythm and baseline grid docs to remove deprecated approach

site/src/components/Layout.tsx, site/src/components/PageHeader.scss, site/src/utils/useSSRHeartTheme.tsx
Uses a delayed instantiation of ThemeManager by utilising the fact that React.useEffect is only run in the browser, not the server.
Also it was abstracted away within a React hook. …
=> docs: Heart theme on Kaizen site

site/docs/components/autocomplete.mdx, site/docs/components/button-group.mdx, site/docs/components/date-picker.mdx, site/docs/components/infinite-scroll.mdx, site/docs/components/loading-skeleton.mdx, site/docs/components/pagination.mdx, site/docs/components/progress-bar.mdx, site/docs/components/tile.mdx, site/docs/guidelines/filtering.mdx
- This information is now encapsulated in the component health tags
- The single source of truth for the status of the component should be the component health indicators (Issues list, and component health tags). 
Before:
After:
=> docs: Remove the "not built" string in documenation pages

packages/component-library/components/Notification/InlineNotification.tsx, packages/component-library/components/Notification/_styles.scss, packages/component-library/components/Notification/components/GenericNotification.module.scss, packages/component-library/components/Notification/components/GenericNotification.tsx, packages/component-library/stories/InlineNotification.stories.tsx
- Adding a new prop to make InlineNotification have it's first line of text underneath the notification heading
- Closes this PR https://github.com/cultureamp/kaizen-design-system/issues/1843
- If this …
=> feat: add ability to have first line underneath the heading

.github/workflows/stale.yml
- To keep on top of our open PRs and to nudge those that may have left them hanging.
- As discussed, the more of these tasks that are automated, the easier it is to manage and spend time helping others contribute to the library. This is just a step for PRs and is _very_ open to what people think about the durations. Once we decide on something, I'll do the same with issues (this may be harder as there could be issues we have that need fixing but no capacity to do so).
=> feat: add github action for closing stale prs

packages/stylelint-plugin/package.json
The design-tokens peer dependency of the stylelint plugin was slightly incorrect.
The current version of the stylelint plugin won't work with anything before version 3 of design-tokens. …
=> fix: Incorrect stylelint plugin design-token peer

packages/stylelint-plugin/README.md
Tiny fix in the stylelint plugin readme where the `prefer-color-tokens` rule was said to be enabled by default when it actually wasn't.
- If this contains substantial visual changes, especially far …
=> docs: Amend stylelint-plugin readme

site/docs/components/overview.mdx
Adds a bit of guidance around component API to the site.
There's not a lot of guidance around this at the moment. This idea has been floating around for a while and Ally wrote up a bunch of stuff here: https://cultureamp.atlassian.net/wiki/spaces/~316784077/pages/1001396888/DRAFT+Kaizen+Consistent+Component+API
This is a compressed version of that, that we can build on in a separate page at a future time if we like
=> docs: Add API guidance to component overview page

draft-packages/avatar/docs/Avatar.stories.tsx
Fixes #1905 
(or more correctly, shows that unicode characters are supported, and the problem probably lies elsewhere).
Add a story showing the use of unicode names in our Avatar component.
Note: this story illustrates that the desired behaviour isn't clear. In this example, the avatar component is showing just one of the names. The idea of "initials" doesn't necessarily make sense in this culture.
Storybook: https://dev.cultureamp.design/jasono/unicode-initials-example-in-avatar/storybook/?path=/story/components-avatar--unicode-initials
=> docs: add an example of passing a name with non-latin characters to Avatar

draft-packages/divider/KaizenDraft/Divider/Divider.tsx, draft-packages/divider/KaizenDraft/Divider/styles.module.scss, site/docs/components/divider.mdx
Closes https://github.com/cultureamp/kaizen-design-system/issues/1920
Also makes a very small adjustment to the `canvas` variant of Divider to match the UI kit (3px height -> 2px height)
=> fix: Add aria-hidden=true to Divider hr

draft-packages/tile/KaizenDraft/Tile/InformationTile.tsx, draft-packages/tile/KaizenDraft/Tile/MultiActionTile.tsx, draft-packages/tile/KaizenDraft/Tile/Tile.spec.tsx, draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx, draft-packages/tile/docs/Tile.stories.tsx
Closes https://github.com/cultureamp/kaizen-design-system/issues/1930
Creates a new `titleTag` prop on our two Tile components (`InformationTile` and `MultiActionTile`) that allows consumers to change the tag that is rendered with the heading (currently hard-coded to `h3`).
Also changes `title` to accept a `ReactNode` rather than just a `string`.
See https://github.com/cultureamp/kaizen-design-system/issues/1930
@OliBridgman and I paired on this and explored a other options, before settling on this:
* Making the `title` prop optional and allow consumers to pass in their own heading via `children`
* This didn't work so well because the title ended up vertically aligned.
* Allowing title to be `ReactNode`, while removing the `<Heading variant="heading-3">` wrapping when the title is *not a …
=> feat: Create titleTag prop on Tile components

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
Switches the 'hamburger' button that shows on mobile from a `<div onClick={}>` to an `<IconButton>` to make it keyboard and screen reader friendly. 
Closes https://github.com/cultureamp/kaizen-design-system/issues/1928
This pushes the hamburger button to the right a bit because IconButton has padding (I've included screenshots of hover so that you can see the full box)
<details>
<summary>Default</summary>
</details>
<details>
<summary>With report switcher</summary>
</details>
<details>
<summary>With subtitle</summary>
</details>
=> fix: Use IconButton for hamburger menu button instead of div

packages/brand-moment/src/BrandMoment.scss
See the first commit for the main objective here - just makes the `min-height: 100vh` that was only on large and up now on smaller view ports as well.
The extra stuff I did here was just revert any use of the logical properties `inline-size` and `block-size` back to `width` and `height` because of our pseudo support for legacy Edge, and given we're probably not going to be supporting Mongolian anytime soon :)
@lloydstubber ran into this while implementing a `BrandMoment` (note the blank white space at the bottom). This happens when your browser height is beyond the height of the content.
I don't think there was any good reason for limiting the `min-height:100vh` to large and up - I probably did it because I originally had it as `height` and not `min-height`
=> fix: Use min-height:100vh on small viewport as well

packages/responsive/src/useMediaQueries.tsx
Stops legacy Edge blowing up when `useMediaQueries` is used.
Removes some functionality for legacy Edge as a result: it will no longer respond to changes after load. It's a legacy browser though so I don't think we care that much, and I wouldn't want to invest anymore in this. Having the values from page load gets you most of the way.
We've noticed errors coming through: `"Object doesn't support property or method 'addEventListener'"`
https://cultureamp.slack.com/archives/C016N8Y1E10/p1630975772292000
=> fix: Disable event listeners on legacy Edge

.buildkite/scripts/run-chromatic-build.sh
Reverts cultureamp/kaizen-design-system#1792
The `--only-changed` parameter started causing storybook builds to fail recently (eg: https://buildkite.com/culture-amp/kaizen-design-system/builds/19137#2ac7200d-3950-430f-b9ad-268e56d3e158/6-927). It looks like this has been disabled for accounts that have explicitly opted in the beta program. We are still on my personal Chromatic account for Kaizen (the key needs to be updated in the secrets settings for Github which I don't have access to). We can easily switch over to the Cultureamp Account, which I think has been opted into the beta turbosnap program, but in any case, there are still issues we're finding with Turbosnap, so it's better to disable it for now. We don't really need it with the manual workflow, as it doesn't get run very often …
=> chore: Revert "Enable Chromatic TurboSnap"

draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.tsx, draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/styles.scss, draft-packages/form/KaizenDraft/Form/Primitives/Input/styles.scss, draft-packages/form/KaizenDraft/Form/TextField/TextField.tsx, draft-packages/form/docs/TextField.stories.tsx
Update the form input (TextField and TextAreaField fields) error message styling 
** in scope **
- background color, border color and warning icon for standard and reversed
** out of scope **
- padding and margins. These aren't quite the same as in the heart designs and haven't been updated. I think a refactor needs to be done first: rather than re-use a single `FieldMessage` component between the error message and description elements, just have completely separate implementations, as they are completely different things with very different styling. It's very fiddly trying to make it work for both. We ran out of time for this in our pairing session.
https://github.com/cultureamp/kaizen-design-system/issues/1786
- Does there need to be right-to-left (RTL) options for localization and …
=> fix: update text field error styles

draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap, packages/design-tokens/elm/Kaizen/Theme.elm, packages/design-tokens/src/themes/index.ts, packages/stylelint-plugin/src/rules/prefer-color-tokens.spec.ts, storybook/theme-switcher-addon/themeManager.ts
Now that all customers have Heart enabled, we can set `defaultTheme` from design-tokens to Heart.
We'll be following up at a later time to delete the zenTheme completely.
=> feat: Change defaultTheme to Heart

draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.spec.tsx, draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.tsx
Adds a default value for the `variant` prop to fix the bug below. Also adds some tests to catch any regressions.
Closes https://github.com/cultureamp/kaizen-design-system/issues/1929
=> fix: Add default value to variant to ensure description displays

draft-packages/avatar/KaizenDraft/Avatar/decision-tokens.scss, draft-packages/avatar/KaizenDraft/Avatar/styles.module.scss, draft-packages/badge/KaizenDraft/Badge/decision-tokens.scss, draft-packages/button/KaizenDraft/Button/decision-tokens.scss, draft-packages/divider/KaizenDraft/Divider/styles.module.scss, draft-packages/empty-state/KaizenDraft/EmptyState/styles.scss, draft-packages/form/KaizenDraft/Form/decision-tokens.scss, draft-packages/loading-placeholder/KaizenDraft/LoadingPlaceholder/decision-tokens.scss, draft-packages/loading-placeholder/KaizenDraft/LoadingPlaceholder/styles.scss, draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.scss, draft-packages/modal/KaizenDraft/Modal/Presets/RoadblockModal.scss, draft-packages/page-layout/KaizenDraft/decision-tokens.scss, draft-packages/popover/KaizenDraft/Popover/styles.scss, draft-packages/select/KaizenDraft/Select/styles.elm.scss, draft-packages/select/KaizenDraft/Select/styles.react.scss, draft-packages/slider/KaizenDraft/Slider/styles.module.scss, draft-packages/split-button/KaizenDraft/SplitButton/styles.scss, draft-packages/table/KaizenDraft/Table/styles.scss, draft-packages/table/docs/Table.stories.scss, draft-packages/tag/KaizenDraft/Tag/Tag.scss, draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/decision-tokens.scss, draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.scss, draft-packages/well/styles.scss, draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/decision-tokens.scss, legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss, packages/component-library/components/NavigationBar/decision-tokens.scss, packages/notification/src/_styles.scss
Removes all usages of `var()` in `scss` that were being used as a way of doing `var([heart_value], [zen_value])`.
This was a method we used to switch tokens based on Zen or Heart, because we knew that no CSS vars existed for Zen, and it would use the fallback value.
=> feat: Remove all usages of var() in scss to provide Zen fallbacks

draft-packages/button/KaizenDraft/Button/styles.scss
BREAKING CHANGE: colors of destructive variant of IconButton (and destructive disabled) modified
IconButton `destructive` variant does not match the current design but instead matches the `secondary destructive` variant.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+A …
=> feat: change IconButton destructive colors to match design

packages/component-library/components/Heading/Heading.tsx, packages/component-library/components/Paragraph/Paragraph.tsx, packages/component-library/stories/Heading.stories.tsx, packages/component-library/stories/Paragraph.stories.tsx
Uses `extends Omit<HTMLAttributes<HTMLElement>, "className">` on our `Heading` and `Paragraph` components to allow native props like `id` on these components.
Additionally, adds `label` to the list of allowed tags for these components.
Ran into this as part of https://github.com/cultureamp/kaizen-design-system/pull/1956, where we need to put an `id` on a `Paragraph` component.
Regarding the `label` as an allowed tag - that's also related to the new Slider - we have a case in 1-on-1s where we want a label with heading styling.
=> feat: Allow generic HTMLElement props on Heading and Paragraph

packages/component-library/components/Dropdown/__snapshots__/Dropdown.spec.tsx.snap, packages/component-library/components/Icon/Icon.spec.tsx, packages/component-library/components/Icon/Icon.tsx, packages/notification/src/__snapshots__/GlobalNotification.spec.tsx.snap, packages/notification/src/__snapshots__/InlineNotification.spec.tsx.snap
Update to the Icon following A11Y audit that requested we remove the `aria-labelledby` and the `aria-hidden` tag in certain circumstances.
Going through the A11Y audit report and fixing issues that have been called out. Being done as part of Earthings Tickets.
https://cultureamp.atlassian.net/jira/software/c/projects/EARTH/boards/186?selectedIssue=EARTH-821&modal=detail&atlOrigin=eyJpIjoiZTc4ZWE5MjdkMTY3NDU1NWFiYjNlMTE4ZGZjNzhiYWYiLCJwIjoiaiJ9
=> fix: a11Y change for aria label on hidden for undefined

draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.tsx, draft-packages/form/docs/CheckboxGroup.stories.tsx
Fix the checkbox background not change back to white when the state of the checkbox is no longer `mixed`
Fix #1599 
https://github.com/cultureamp/kaizen-design-system/issues/1599 …
=> fix: Wrong background-color for the checkbox after transition from mixed to off state

packages/brand-moment/src/BrandMoment.tsx
This PR makes the primary action prop optional. 
Some Brand Moments, such as the new maintenance page, do not have any call to action within the Brand Moments. 
I've also exported the `BrandMomentProps` interface so that it's consistent with other Kaizen components.
=> feat: Change the primaryAction to be an optional prop

draft-packages/button/KaizenDraft/Button/IconButton.tsx, draft-packages/button/KaizenDraft/Button/components/GenericButton.tsx, draft-packages/button/KaizenDraft/Button/styles.scss, draft-packages/button/docs/IconButton.stories.tsx
`IconButton` needs secondary destructive variant now that destructive variant [has been fixed](https://github.com/cultureamp/kaizen-design-system/issues/1892) to match the latest design.
**Secondary destructive design:**
We also need to make sure there cannot be the combination of secondary, destructive, and reversed as this does not exist the designs.
- Have you reviewed Culture Amp's Web Accessibility guide [Current …
=> fix: add secondary destructive variant to IconButton

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx
Issue: https://github.com/cultureamp/kaizen-design-system/issues/1916
Same thing as https://github.com/cultureamp/kaizen-design-system/pull/1938, but for the MainActions -> overflow button (basically the same button but only shows on smaller viewports). We didn't realise that there were two cases that needed this.
=> fix: Add label to TiltleBlockZen overflow meatball IconButton

draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.spec.tsx, draft-packages/empty-state/KaizenDraft/EmptyState/EmptyState.tsx, draft-packages/empty-state/KaizenDraft/EmptyState/styles.scss, draft-packages/empty-state/docs/EmptyState.stories.tsx
Removing the Zen style option from the `EmptyState` component.
The Zen theme is not in use anymore.
* _Yes, added a new test file with rudimentary tests as there was none_
=> feat: [BREAKING CHANGE] Removed Zen styling option from EmptyState component

packages/brand/src/Brand/Brand.tsx
Forced reversed/not-reversed variant of logo when the user has forced colors (high contast mode).
Images are not adjusted at all in high contrast/forced colors mode. So if we have a logo that is for use on a light background, and the user forces a dark background - they no longer see the logo.
=> fix: Adjust Brand variant based on forced-colors user preference

packages/a11y/src/VisuallyHidden/VisuallyHidden.tsx
Work:
- Build was broken: https://buildkite.com/culture-amp/kaizen-design-system/builds/23939#25367a04-b11f-4f63-8d58-9515652a015b
- We just needed to export the props of the component and should be good to go
=> fix: export visiuallyHidden props to fix build

draft-packages/illustration/KaizenDraft/Illustration/style.module.scss
- Remove the margin styles that crept into `figure` with Material UI
- Closes this: https://github.com/cultureamp/kaizen-design-system/issues/2210
=> fix: override global figure styles coming from material ui

packages/tabs/docs/Tabs.stories.tsx, packages/tabs/src/TabList.tsx, packages/tabs/src/TabPanels.tsx, packages/tabs/src/styles.scss
@ActuallyACat [was right, I was wrong](https://github.com/cultureamp/kaizen-design-system/pull/2203/files#r743419878) 😅 Started implementing these on survey summary and we don't want this padding 😐
You might be wondering why I moved the border-bottom on tabList to a border-top of tabPanels:
Unfortunately I couldn't do the following, because it loses the `isSelected` prop that is magically passed from `TabList`. 
```
<Tabs>
<TabList>
<Box pl={1} pr={1}>
<Tab>
</Box>
</TabList>
</Tabs>
```
So I had to move the border and then put the padding on the outside of TabList.
=> fix: Remove inbuilt padding on Tabs

packages/brand/src/Brand/Brand.scss
Centers the Brand component vertically within `picture` element. This is necessary as the `picture` element expands to fill whatever it's rendered inside of.
=> fix: Center Brand img vertically

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.tsx
Fixes a parsing error due to `div` not being allowed inside `<button>`. Already has a `display` property in CSS so no styling changes required.
=> fix: Replace div with span inside TitleBlock mobile button
