cultureamp/kaizen-design-system

packages/binary-assets/README.md
packages/binary-assets/lib/index.scss

feat: Add scss variable and function

---

packages/component-library/draft/Kaizen/Select/Select.elm

Selecting menu items with a mouseup can cause weird auto select bugs when Elm Select is rendered inside an element that suddenly changes scroll height. 
Considering Elm Select was built in the spirit of the very excellent React Select which does not cater for mouseup selection, the mouseup selection feature has been removed. Consequently this makes the code a lot more simple and easy to navigate.

fix: Remove mouseup selection

---

site/docs/guidelines/icons.mdx

Fixes #113.
Branch preview: https://dev.cultureamp.design/di/icon-process/guidelines/icons/

docs: add guidance for adding new icons

---

packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.elm

fix: ensure that the Elm TitleBlock component reflects recent changes to the JS version

---

packages/component-library/draft/Kaizen/Modal/README.mdx

Branch preview: https://dev.cultureamp.design/update-modal-docs/components/modal/

docs: Update Modal README

---

packages/component-library/draft/Kaizen/Modal/Presets/InputEditModal.tsx
packages/component-library/stories/Modal.stories.tsx

We are now using this modal on capture, so we need to support rtl locales. Also added a story for the rtl input modal.

feat: Add basic rtl support to input modal

---

site/docs/guidelines/file-upload.mdx

Fixes: #159 
Branch preview: https://dev.cultureamp.design/add-file-upload-docs/guidelines/file-upload/

docs: Add file upload guidelines

---

site/docs/guidelines/typography.mdx

Fixes: #117.
Branch preview: https://dev.cultureamp.design/di/update-typography-documentation-for-numbers/guidelines/typography/#numbers

docs: Update typography documentation for numbers

---

CONTRIBUTING.md
README.md

Fixes: https://github.com/cultureamp/kaizen-design-system/issues/115
Preview: 
- https://github.com/cultureamp/kaizen-design-system/tree/di/update-kaizen-readme-for-designers
- https://github.com/cultureamp/kaizen-design-system/blob/di/update-kaizen-readme-for-designers/CONTRIBUTING.md

docs: update README and CONTRIBUTING for designers

---

CONTRIBUTING.md

added a description of what an issue is for newbies.

docs: defining what an issue is

---

yarn.lock

No noticeable changes, but it unlocks the potential to use MDX docs should we choose (https://medium.com/storybookjs/rich-docs-with-storybook-mdx-61bc145ae7bc)
Link for QA: https://dev.cultureamp.design/dst/upgrade-storybook/storybook/

feat: upgrade storybook to 5.3.1

---

packages/component-library/draft/Kaizen/HeroCard/HeroCard.scss

Bugfix from incorrect width, only affects FullWidth variation

fix: Fixed off-by-one percent error added with last update

---

packages/component-library/draft/Kaizen/Modal/README.mdx

Fixes: #216 
https://dev.cultureamp.design/katsambarcus-patch-1/components/modal/

docs: Changed Ocean to Cluny

---

packages/component-library/draft/Kaizen/EmptyState/styles.scss
packages/component-library/draft/Kaizen/Form/Primitives/Label/styles.scss
packages/component-library/draft/Kaizen/Form/Primitives/ToggleSwitch/styles.scss
packages/component-library/draft/Kaizen/Modal/README.mdx
packages/component-library/draft/Kaizen/Popover/README.mdx
packages/component-library/draft/Kaizen/Select/README.mdx
packages/component-library/draft/Kaizen/Tooltip/README.mdx
packages/component-library/stories/Table.stories.tsx
packages/component-library/stories/TextField.stories.tsx
packages/component-library/stories/ToastNotification.stories.tsx
packages/component-library/stories/ToggleSwitchField.stories.tsx
site/src/components/StorybookDemo.tsx
site/src/templates/componentPage.tsx
storybook/backgrounds.ts
storybook/webpack.config.ts

See attached [Trello card](https://trello.com/c/OFn5qeij/574-fixes-for-kaizen-storybook-demos) for details.

fix: Fix small Storybook and component bugs

---

packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.elm
packages/component-library/draft/Kaizen/TitleBlock/TitleBlock.tsx

This is needed for some tests to work

fix: Add automation ID to TitleBlock breadcrumb

---

packages/component-library/draft/Kaizen/Table/Table.tsx

Fix style regression with Table component
Before:
After:

fix: Style regression with Table component

---

packages/component-library/stories/IconButton.stories.tsx
site/docs/components/icon-button.mdx

Branch Preview with Story demo for Icon button: https://dev.cultureamp.design/di/add-icon-button-story-id/components/icon-button/

docs: Update Icon Button demoStoryId

---

packages/component-library/draft/Kaizen/Modal/README.mdx
packages/component-library/draft/Kaizen/Select/README.mdx

Fixes: https://github.com/cultureamp/kaizen-design-system/issues/147

docs: Update Modal docs for scrollable body

---

packages/component-library/draft/Kaizen/Modal/Modal.elm
packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.elm
packages/component-library/stories/Modal.stories.tsx
packages/component-library/stories/ModalStories.elm

This PR adds the cautionary modal variant.

feat: Add cautionary modal variant

---

packages/component-library/draft/Kaizen/Modal/Modal.elm
packages/component-library/draft/Kaizen/Modal/Presets/ConfirmationModal.scss
packages/component-library/draft/Kaizen/Modal/Presets/InputEditModal.elm
packages/component-library/draft/Kaizen/Modal/Presets/InputEditModal.scss
packages/component-library/draft/Kaizen/Modal/Primitives/Configuration.elm
packages/component-library/draft/Kaizen/Modal/Primitives/GenericModal.scss
packages/component-library/draft/Kaizen/Modal/Primitives/ModalAccessibleDescription.elm
packages/component-library/draft/Kaizen/Modal/Primitives/ModalAccessibleLabel.elm
packages/component-library/draft/Kaizen/Modal/Primitives/ModalBody.elm
packages/component-library/draft/Kaizen/Modal/Primitives/ModalBody.scss
packages/component-library/draft/Kaizen/Modal/Primitives/ModalHeader.elm
packages/component-library/stories/Modal.stories.tsx
packages/component-library/stories/ModalStories.elm

This PR adds the InputEditModal variant to the elm modal.

feat: Add InputEditModal variant for Elm Modal

---

site/docs/components/icon-button.mdx

The updated docs describe the Icon Button variants in Zen and update the interaction guidelines.
Branch preview: https://dev.cultureamp.design/di/update-icon-button-readme-for-zen/components/icon-button/

docs: update Icon Button README

---

CONTRIBUTING.md

Closes: https://github.com/cultureamp/kaizen-design-system/issues/218

docs: update CONTRIBUTING guidelines

---

packages/component-library/components/NavigationBar/NavigationBar.module.scss
packages/component-library/components/OffCanvas/components/Menu.module.scss
packages/component-library/components/OffCanvas/components/Menu.tsx

Fixes a small gap in navigation list items and ul specificity issue

fix: ul selector specificity and add margin to navigation list items.

---

packages/component-library/stories/Layout.stories.tsx

The layout component story was still using the now outdated navigation bar API. This was missed when updating the component in a previous release.

fix: NavigationBar component using old API in Layout

---

packages/component-library/draft/Kaizen/ZenOffCanvas/OffCanvas.module.scss
packages/component-library/draft/Kaizen/ZenOffCanvas/ZenOffCanvas.tsx

Add ca logo icon in it's place

feat: Move header compoment out of mobile heading

---

draft-packages/title-block/package.json
yarn.lock

this fixes a security vulnerability

fix: upgrade lodash in draft-title-block

---

draft-packages/stories/TextAreaField.stories.tsx

This story was lost in the move to it's new home in `draft-packages/stories`

chore: Restore the text area story

---

draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.tsx

- sorry, oversight, one line change to correct behaviour

fix: navbar events - use href to detect if trigger or not

---

site/docs/components/illustration.mdx

- Remove "(not built)"
- Add Illustration demo to Illustration page
Branch preview: https://dev.cultureamp.design/dst/update-illustration-docs/components/illustration/

docs: update Illustration navTitle and demoStoryId

---

draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.tsx

Just adds an `aria-label` prop to the `Input` component.

feat: Add aria-label prop to Input

---

draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.elm
draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/styles.scss
draft-packages/form/KaizenDraft/Form/Primitives/Label/styles.scss
yarn.lock

The input used for checkbox was sitting behind styling elements and not initiating the onCheck event. This PR adds`pointer-events: none;' to the `.box` element to ensure the input is clickable.
The checkbox width and height is also conforming to the relevant sizes for the styled element to ensure the clickable area is maximised. Previously the input was a tiny square in the top left corner, it now is sized according to `$checkbox-size`.

fix: add pointer-events none to .box element

---

draft-packages/radio/KaizenDraft/Radio/Primitives/RadioInput.elm
draft-packages/radio/KaizenDraft/Radio/Radio.elm
draft-packages/stories/ElmRadio.stories.tsx
draft-packages/stories/RadioStories.elm

Elm radio component stylistically and functionally identical to the react version.

feat: add elm radio component

---

draft-packages/stories/ZenNavigationBar.stories.tsx
draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/_styles.scss
draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/Link.module.scss

- transition background color on theme change
- added story for theme change

fix: reverse badge colour for admin theme

---

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx

feat: add condition so that sectionTitleDescription can be passed in without sectionTitle

feat: pass in section description by itself

---

draft-packages/button/KaizenDraft/Button/styles.scss
draft-packages/stories/TitleBlockZen.stories.tsx
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MainActions.tsx
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.scss
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.tsx
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.scss
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/NavigationTabs.tsx
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/SecondaryActions.tsx
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockBreakpoints.scss
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.scss
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
draft-packages/title-block-zen/package.json
yarn.lock

PX is building the Zen version of the Title Block to be rolled out across Perform.
The goal of this PR is to get it to a level of quality where it is ready for use in production, even if not yet fully-featured.
I have fixed a number of bugs that existed on the half-finished previous version of TitleBlockZen.

feat: Build MVP of TitleBlock

---

draft-packages/select/KaizenDraft/Select/Select.tsx
draft-packages/select/KaizenDraft/Select/styles.react.scss
draft-packages/stories/Select.stories.tsx

These:
- Adds default secondary single select
- Adds story for default secondary single select
- Adds story for default secondary single select disabled
Built:
Branch preview:
- https://dev.cultureamp.design/dst/update-secondary-select/storybook/:
- https://dev.cultureamp.design/dst/update-secondary-select/storybook-static/?path=/story/select-react--single-secondary
- https://dev.cultureamp.design/dst/update-secondary-select/storybook-static/?path=/story/select-react--single-secondary-disabled

feat: add React default secondary select

---

site/docs/components/tabs.mdx

- Adds demo
- Removes "(not built")

docs: update Tabs page with demo

---

site/docs/components/card.mdx

- Adds demo
- Removes "(not built")

docs: update Card page with demo

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/README.mdx

This also removes trailing full stops in line with latest language
guidelines

docs: update Guidance Block page to use components

---

draft-packages/tag/KaizenDraft/Tag/README.mdx

Fixes minor typo (one character superfluous pluralisation)

docs: fixes typo

---

storybook/webpack.config.ts

Fixes: https://github.com/cultureamp/kaizen-design-system/issues/673
I had previously set the source directory to `../draft-packages` thinking that it would traverse the directory and find the files that it needs. This was not the case. 
I've updated the config so that it gets all the directories within draft-packages. 
Prev: 
Now:

ci: Add draft packages directories to react-docgen-typescript-loader (#673)

---

site/docs/guidelines/forms.mdx

This PR adds a forms page. It is a starting point and we intend to iterate.
- Closes: https://github.com/cultureamp/kaizen-design-system/issues/677
- [Branch preview](https://dev.cultureamp.design/dlimiter/add-new-form-page/guidelines/forms/)

docs: add new forms page

---

draft-packages/popover/KaizenDraft/Popover/README.mdx

Updated doc to include icons + moods popovers.
Closes https://github.com/cultureamp/kaizen-design-system/issues/679
Branch preview: https://dev.cultureamp.design/mindycultureamp-patch-1/components/popover/

docs: update popover documentation

---

site/docs/components/card.mdx

fix: card doc: it *is* a component now!

fix: card doc: it *is* a component now!

---

draft-packages/form/KaizenDraft/Form/Primitives/TextArea/TextArea.elm
draft-packages/form/KaizenDraft/Form/TextAreaField/TextAreaField.elm
draft-packages/stories/ElmTextAreaField.stories.scss
draft-packages/stories/ElmTextAreaField.stories.tsx
draft-packages/stories/TextAreaField.stories.elm

Adds TextArea component for Elm
https://trello.com/c/31VPBD0n/28-build-elm-textareafield

feat: add textarea for Elm

---

site/docs/components/button-group.mdx

closes: #321 
https://dev.cultureamp.design/lindsey/update-button-group-docs/components/button-group/

docs: Update button group documentation

---

draft-packages/stories/Tile.stories.tsx
draft-packages/tile/KaizenDraft/Tile/MultiActionTile.scss
draft-packages/tile/KaizenDraft/Tile/TileGrid.scss
draft-packages/tile/KaizenDraft/Tile/TileGrid.tsx
draft-packages/tile/KaizenDraft/Tile/__snapshots__/Tile.spec.tsx.snap
draft-packages/tile/KaizenDraft/Tile/components/GenericTile.scss
draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx
draft-packages/tile/index.ts

This PR makes several style changes to Tile component. 
* Changes how Tile and TileGrid behave at different breakpoints: https://www.figma.com/file/IoWU34XQEKvmhcSI72Ic72/Skills-Coach?node-id=848%3A773
* Makes it so TileGrid can accept one Tile as it's child
* Other small changes such as vertically aligning content in the footer.

feat: Tile refinements

---

draft-packages/hierarchical-select/KaizenDraft/HierarchicalSelect/HierarchicalSelect.tsx
draft-packages/hierarchical-select/KaizenDraft/HierarchicalSelect/styles.module.scss
draft-packages/stories/HierarchicalSelect.stories.tsx

Add the ability to disable a HierarchicalSelect with the `disabled` attribute.

feat: Add disabled HierarchicalSelect

---

site/gatsby-config.js
site/gatsby-node.js
tsconfig.json

Fixes:  #83
Does what it says on the box. I've set the allowJs flag to false. 
Reference: https://www.typescriptlang.org/docs/handbook/compiler-options.html

fix: Set allowJs to false as we're now not using untyped javascript

---

site/docs/guidelines/data-visualization.mdx

This PR adds sparkline guidance.
Branch preview: https://dev.cultureamp.design/di/update-data-viz-docs/guidelines/data-visualization/

docs: update data viz docs with sparklines

---

site/docs/components/tile.mdx

This PR adds some details around the key differences between the different card types.
[Branch preview](https://dev.cultureamp.design/dlimiter-update-tile-docs/components/tile/)

docs: update details to describe tile types

---

site/docs/guidelines/workflow.mdx

This PR adds details and resources about Hick's Law to the Workflow guidelines page.
Preview: https://dev.cultureamp.design/di/update-workflow-guidance/guidelines/workflow/

docs: update workflow guidance with Hick's Law

---

site/docs/guidelines/brand.mdx

Closes: https://github.com/cultureamp/kaizen-design-system/issues/500
Branch preview: https://dev.cultureamp.design/di/add-svg-logo-files/guidelines/brand/#visuals

docs: add brand logo pack

---

draft-packages/hierarchical-select/KaizenDraft/HierarchicalSelect/styles.module.scss
draft-packages/stories/HierarchicalSelect.stories.tsx

The button is already disabled, but it changes on hover and so looks like it is interactive.

fix: Ensure clear icon indicates disabled state

---

site/docs/components/likert-scale.mdx

This PR adds docs for a Likert scale radio group
Branch preview: https://dev.cultureamp.design/di/add-likert-scale-page/components/likert-scale/

docs: add Likert scale docs

---

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx
draft-packages/stories/IllustrationScene.stories.tsx

Pair with https://github.com/cultureamp/kaizen-design-system-assets/pull/16

feat: Add programs illustration

---

site/docs/guidelines/data-visualization.mdx

Branch preview: https://dev.cultureamp.design/di/update-data-viz-docs-with-stacked-bars/guidelines/data-visualization/

docs: add bar chart visuals and more details

---

draft-packages/title-block-zen/package.json

Bugfix caused my missing dependency

fix: added missing dependency

---

draft-packages/filter-drawer/KaizenDraft/FilterDrawer/FilterDrawer.tsx
draft-packages/filter-drawer/package.json
draft-packages/modal/package.json
draft-packages/tile/KaizenDraft/Tile/components/GenericTile.tsx
draft-packages/tile/package.json
yarn.lock

Does what it says on the box. To be released before https://github.com/cultureamp/kaizen-design-system/pull/772

fix: Added missing dependencies for Modal, FilterDrawer, and Tile

---

draft-packages/filter-drawer/tsconfig.dist.json

ci: Added missing config to fiilter drawer

---

site/docs/components/pagination.mdx

Added guidance to center pagination at the bottom of a page's content.

docs: Center pagination

---

packages/component-library/components/Heading/Heading.module.scss
packages/component-library/components/Heading/Heading.tsx

Ally and Louis are testing stuff.

fix: Added a danger variant to heading (CANARY)

---

draft-packages/stories/Button.stories.tsx
draft-packages/stories/Divider.stories.tsx
draft-packages/stories/Dropdown.stories.tsx
draft-packages/stories/Popover.stories.tsx
draft-packages/stories/TitleBlockZen.stories.tsx
draft-packages/stories/ZenNavigationBar.stories.tsx
legacy-packages/stories/TitleBlock.stories.tsx

Fixes some small visual defects in our stories. This does not affect components, just how they are displayed in Storybook.
Storybook 6 adds 1rem padding to stories now, which has introduced some small visual defects in stories. I took this opportunity to make some smaller fixes to unrelated stories: 
* Added negative margins to stories that span full width w/ absolute position so they don't look broken. I didn't end up setting relative on the container because of this: 
* Components that are absolutely positioned now include a minimum height so the stories are not cut off (see screenshots) 
* Wisteria bg was not applying to all reversed stories
Improved the documentation panel for popovers: 
[ ] I have considered …

docs: Added NoMargin wrapper to titleblocks 

---

draft-packages/button/package.json

- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pag …

fix: Add loading spinner as button dependency

---

site/docs/guidelines/tables-lists.mdx

Added new guidelines around use of tables versus lists.
To clarify usage and associated interaction patterns.
https://dev.cultureamp.design/dlimiter-tables-lists/guidelines/tables-lists/

docs: add tables vs lists

---

site/docs/components/drawer.mdx

Adding additional guidelines about when to use Drawers vs. Modals, based on feedback from Kevin.
**Checklist**
[ ] If this contains visual changes, has it been reviewed by a designer?

docs: update drawer guidelines

---

draft-packages/stories/Button.stories.tsx
draft-packages/stories/Card.stories.tsx
draft-packages/stories/GuidanceBlock.stories.tsx
draft-packages/stories/Tabs.stories.tsx
packages/component-library/stories/Heading.stories.tsx
packages/component-library/stories/Paragraph.stories.tsx

Fix our storybook stories that are using incorrect background settings.

docs: Update story background colour settings

---

site/docs/components/rich-text-editor.mdx

Adds component guidelines for new Rich Text Editor component.
Branch preview: https://dev.cultureamp.design/dlimiter-rich-text-editor/components/rich-text-editor/

docs: New rich text editor component

---

tsconfig.json
yarn.lock

Fix compilation issues with legacy packages. 
The legacy packages were not being compiled.

ci: Include legacy packages when building packages

---

site/docs/components/commentary.mdx

Created draft of commentaries documentation.

docs: create commentary documentation

---

packages/hosted-assets/Kaizen/HostedAssets.elm

(so that we can centralise and potentially change the cdn url)
There is a typescript helper for centralising the asset cdn url base path, but it doesn't exist for Elm. This adds the elm equivalent.
This is required for making the Elm equvialents in https://github.com/cultureamp/kaizen-design-system/blob/master/draft-packages/illustration
```
module Integrations.Common.InfoBox exposing (view)
import Box.Box as Box exposing (box, marginBottom, padding, paddingTop, paddingX, paddingY)
import CssModules exposing (css)
import Heading.Heading as Heading exposing (TypeVariant(..))
import Html exposing (Html, div, img, text)
import Html.Attributes exposing (src)
import Kaizen.HostedAssets as HostedAssets
import KaizenDraft.Well.Well as Well
import Paragraph.Paragraph as Paragraph exposing …
```

feat: add Elm helper function for HostedAssets

---

package.json
yarn.lock

Reverts cultureamp/kaizen-design-system#932

chore(deps): REVERT bump style-loader from 1.3.0 to 2.0.0 (#932)

---

draft-packages/slider/KaizenDraft/Slider/Slider.tsx
draft-packages/slider/KaizenDraft/Slider/styles.module.scss
draft-packages/slider/README.mdx
draft-packages/slider/index.ts
draft-packages/slider/package.json
draft-packages/slider/tsconfig.dist.json
draft-packages/stories/Slider.stories.tsx
site/docs/components/slider.mdx
yarn.lock

Copy over slider from performance, located in `performance-ui/src/entry/OneOnOneSpacePage/CheckIn/RatingScale.tsx`
This component is needed for activities in Skills coach. …

feat: Slider component

---

draft-packages/form/KaizenDraft/Form/CheckboxField/CheckboxField.tsx
draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.tsx

- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pag …

feat: Add value to checkbox

---

.github/pull_request_template.md

Make it clearer in the PR template checklist when you need to ask a designer or an advocate for review.
And also make it a clickable checklist.
Fixes #978 
There's also been some confusion about when we ask for a designer to review if it needs to be a design advocate. (It doesn't). We also had an unwritten suggestion that new components or breaking changes should have an advocate review.

chore: update PR template checklist

---

packages/design-tokens/tokens/shadow.json

Update the color of the shadows from wisteria to black. 
This token was erroneously added as wisteria, when it should have been black. These changes are subtle, as seen in the screenshots. Note that these changes apply to the design tokens and will effect every component and consumer who uses them. The screenshots are for demonstration. 
Small shadow before:
Small shadow after:
Large shadow before: 
Large shadow after: 
- Have you updated any relevant documentation or left useful comments in the …

feat: Updated color of shadow to black with opacity

---

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/NavigationBar.tsx
draft-packages/zen-navigation-bar/KaizenDraft/ZenNavigationBar/components/MenuItem.tsx
draft-packages/zen-navigation-bar/docs/ZenNavigationBar.stories.tsx
legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.tsx
packages/component-library/components/Button/components/GenericButton.tsx
packages/component-library/components/NavigationBar/NavigationBar.tsx
packages/component-library/package.json
packages/design-tokens/tokens/color.ts
packages/generator/generators/app/index.ts
packages/generator/generators/draft/index.ts
packages/react-deprecate-warning/src/WithDeprecatedComponent.tsx
packages/react-deprecate-warning/src/WithDeprecatedProp.tsx
packages/react-deprecate-warning/src/util.ts
yarn.lock

This PR improves the type safety of the codebase by fixing implicit any instances.
Set "noImplicitAny" to true, observe the errors, fix each one by one.
This commit got from 105-ish -> 73 errors.
"noImplicitAny" is set back to false, as this should be a gradual process. Otherwise the PR would be massive.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers …

fix: implicit any amendments

---

draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/styles.scss
draft-packages/form/KaizenDraft/Form/Primitives/Input/styles.scss
draft-packages/popover/KaizenDraft/Popover/styles.scss
draft-packages/search-box/KaizenDraft/SearchBox/styles.module.scss
draft-packages/tag/KaizenDraft/Tag/Tag.scss
legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.scss
packages/component-library/bin/design-uplift/replace-add-alpha.sh
packages/component-library/components/Button/styles.scss
packages/component-library/components/MenuList/Menu.module.scss
packages/component-library/styles/color.scss

This is a canary release to test the yelly-ness in consuming repos.

feat: Deprecate add-tint, add-shade, and add-alpha

---

draft-packages/menu/KaizenDraft/Menu/components/MenuContent.module.scss

Removes an import that was unused and causing issues for sub-dependencies.

fix: remove unused animation import

---

catalog-info.yaml

This pull request adds a **Backstage entity metadata file** to this repository so that the component can be added to the [Backstage Culture Amp software catalog](https://backstage.usw2.dev-us.cultureamp.io).
After this pull request is merged, the component will become available.
For more information, read an [overview of the Backstage software catalog](https://backstage.io/docs/features/software-catalog/software-catalog-overview).

docs: Add catalog-info.yaml config file

---

site/docs/guidelines/header.mdx

Updating header documentation
New IA has introduced flow-of-work admin pages, requiring clarification about when to use the Account admin header.

docs: update header

---

draft-packages/split-button/KaizenDraft/SplitButton/styles.scss
draft-packages/split-button/docs/SplitButton.stories.tsx

This PR uplifts the SplitButton component by ensuring that tokens are switched according to the designs and execution document, for the new Heart theme.
https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit-Heart?node-id=14512%3A404
https://docs.google.com/document/d/1G5iN3zZ0XHc0K5FKIFpa263nGW3l8d-jV2nWf6Gcucs/edit#
https://dev.cultureamp.design/danno/heart-uplift/split-button/storybook/?path=/docs/splitbutton-react--anchor-link#stories
- Have you updated any relevant …

feat: Update SplitButton to support Heart

---

draft-packages/select/KaizenDraft/Select/Select.tsx
draft-packages/select/KaizenDraft/Select/styles.elm.scss
draft-packages/select/KaizenDraft/Select/styles.react.scss
draft-packages/select/docs/Select.stories.tsx
draft-packages/select/package.json
yarn.lock

This PR uplifts the Select component slightly by using the Tag component in the MultiValue react-select component, and gets it ready for Heart through using new design and decision tokens.
- If this …

feat: Update Select component to support Heart

---

draft-packages/well/styles.scss

Add heart theme to Well.
Heart sticker sheet: https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit-Heart?node-id=1929%3A14168
Part of the product rebrand …

feat: Add Heart theme support to Well component

---

draft-packages/select/KaizenDraft/Select/styles.elm.scss
draft-packages/select/KaizenDraft/Select/styles.react.scss

Fix the border color on the Select component which was picked up by chromatic, and occurred when updating to Heart.

fix: Select component style regression on Zen

---

draft-packages/button/KaizenDraft/Button/README.mdx
draft-packages/form/KaizenDraft/Form/RadioField/README.mdx
draft-packages/form/KaizenDraft/Form/RadioGroup/README.mdx
draft-packages/likert-scale-legacy/docs/README.mdx
draft-packages/menu/KaizenDraft/Menu/README.mdx
draft-packages/select/KaizenDraft/Select/README.mdx
draft-packages/table/KaizenDraft/Table/README.mdx
packages/component-library/components/Dropdown/README.mdx
site/docs/components/button-group.mdx
site/docs/components/date-picker.mdx
site/docs/components/rich-text-editor.mdx
site/docs/components/search-field.mdx
site/docs/components/split-button.mdx
site/docs/components/tabs.mdx
site/docs/components/tile.mdx
site/docs/guidelines/tables-lists.mdx

Updated the formatting of the focus indicator

docs: Button group focus indicator

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss

Fix for css rule
https://github.com/cultureamp/kaizen-design-system/pull/1377
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the …

fix: fix the css rule

---

site/docs/language/grammar.mdx

Adds single line for line break 🤦

docs: fixes line break typo

---

.buildkite/dockerfiles/publish.Dockerfile
.buildkite/dockerfiles/release.Dockerfile

Related to this issue: https://github.com/aws/aws-cli/issues/6094#issuecomment-819754459
We need aws-cli so I've added gcc, alpine-sdk, and python-dev. 
- If this contains substantial visual changes, …

ci: Added missing libraries to Docker

---

draft-packages/form/ElmStories/SelectFieldStories.elm
draft-packages/form/KaizenDraft/Form/SelectField/SelectField.elm
draft-packages/form/docs/ElmSelectField.stories.tsx
draft-packages/select/ElmStories/SelectStories.elm
draft-packages/select/KaizenDraft/Select/Select.elm
draft-packages/select/KaizenDraft/Select/styles.elm.scss
draft-packages/select/docs/ElmSelect.stories.tsx

Adds the disabled variant of the Elm Select and SelectField components
Select
SelectField
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step …

feat: add disabled variant of Elm Select and SelectField

---

site/docs/guidelines/moods.mdx

Needing to add two new mood colors to the system: Assertive and Prominent.
Have adjusted content on this page to align with new additions and changes being introduced into the Heart theme.

docs: adding-2-new-moods

---

site/docs/guidelines/data-visualization.mdx

Added new data viz tokens and removed any Zen references
- Have Storybook …

docs: added new Data Viz tokens

---

draft-packages/modal/KaizenDraft/Modal/README.mdx

We are introducing some changes to our Modals. The key objective was to make them all LTR-RTl friendly, and while we were at it, we made some improvement to the types of modals.
- Introduced to types of Confirmation Modals (Default and Prominent) so that teams can choose the level of sentiment they want the user to see/feel when presented..
- Changes the name of Information modal to Context modal, to reduce confusion with that existed with Informative Confirmation Modal vs. Information Modal
- Have …

docs: Updating modal guidance

---

site/docs/guidelines/color.mdx
site/src/docs-components/color/ZenCluny.tsx
site/src/docs-components/color/ZenColorGroup.tsx
site/src/docs-components/color/ZenCoral.tsx
site/src/docs-components/color/ZenNeutrals.tsx
site/src/docs-components/color/ZenPeach.tsx
site/src/docs-components/color/ZenSeedling.tsx
site/src/docs-components/color/ZenWisteria.tsx
site/src/docs-components/color/ZenYuzu.tsx

Updated Color page with references to the Heart theme. Aware that the color swatches are referencing Zen. Ally will swap these over soon.
- If this contains substantial visual changes, especially far …

docs: heart-updates-to-color

---

site/docs/language/grammar.mdx
site/src/styles/markdown.scss

Updates capitalization guidelines. [Source](https://docs.google.com/document/d/17vst6HrIaq2UNsb4fc-uPfbNyfjJ2uxkXxiZBMS2KcA/edit)
Direct link to branch preview https://dev.cultureamp.design/dlimiter-new-capitalization-guidelines/language/grammar/#capitalization

docs: new capitalization guidelines

---

draft-packages/tooltip/KaizenDraft/Tooltip/index.ts

Make it so `TooltipProps` can be imported.
Done as part of work to make it so a tooltip can be added to a button in `GuidanceBlock`
- If this contains substantial visual changes, especially far reaching …

feat: export TooltipProps

---

draft-packages/table/KaizenDraft/Table/Table.tsx
draft-packages/table/KaizenDraft/Table/styles.scss
draft-packages/table/docs/Table.stories.tsx

Add a data variant to the `draft-table`, to reduce row-height. The expected usecase of this is when a large amount of results are to be displayed, with text-based row cells.
These are included in Renee's designs to admin goals reporting.
Figma: https://www.figma.com/file/kz2iLEjs3HIOMfF6k5X4l1/Global-Filter-Menu?node-id=1757%3A75767
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going …

feat: Add data variant for table

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss
draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.spec.tsx
draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
draft-packages/guidance-block/docs/GuidanceBlock.stories.tsx
draft-packages/guidance-block/package.json
packages/component-library/components/Icon/Icon.module.scss
yarn.lock

Make it so tooltip can be added to actions inside of `GuidanceBlock`
Sometimes a tooltip is necessary on buttons within `GuidanceBlock`. This PR adds a tooltip prop to actions. It also makes slight UI adjustments so that the component is more inline with the [design](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=1929%3A39077).
- Have you reviewed Culture Amp's Web …

feat: Add tooltip to guidanceblock action

---

draft-packages/loading-spinner/KaizenDraft/LoadingSpinner/LoadingSpinner.tsx

Cleans up the console. Also probably changes the opacity!?
We want less errors and warnings.
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic …

fix: stroke opacity requires camel case

---

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.spec.tsx

Clean up the warnings and errors in the tests.
- Have Storybook stories …

test: clean up title block tests

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss

HAHAHA I guess it was only appropriate that I stuffed this up. You thought I would stop making guidance block PRs but I can't stop writing bugs. Sorry, but I missed the tablet width reset in the version that got merged, the image gets skewed now that we control the width and height from css. I'm very sorry, please forgive me. Lucky for semantic versioning!
Motivation -> embarrassment
Context -> https://github.com/cultureamp/kaizen-design-system/pull/1595
- Have you updated any relevant documentation …

fix: remove the tablet width auto.

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss
draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.tsx
draft-packages/guidance-block/docs/GuidanceBlock.stories.tsx

Ensure `GuidanceBlock` actions are always aligned to the right of the container.
Buttons should be right aligned:
- If this contains substantial visual changes, especially far reaching ones, have you …

fix: Make GuidanceBlock action buttons right aligned

---

packages/brand-moment/index.ts
packages/brand-moment/package.json
packages/brand-moment/src/BrandMoment.scss
packages/brand-moment/src/BrandMoment.stories.tsx
packages/brand-moment/src/BrandMoment.tsx
packages/brand-moment/src/stories/BrandMoment.stories.tsx
packages/brand-moment/src/stories/ExampleHeaders.scss
packages/brand-moment/src/stories/ExampleHeaders.tsx
packages/brand-moment/tsconfig.dist.json
storybook/main.ts

Creates a new component for 'Brand Moments' (see designs here  https://www.figma.com/file/OgCmQ6H2uygDqhd2c86oNt/Brand-Moments).
This will allow camps to easily implement these new screens.
There's a few things that will be incomplete here:
* Hasn't been RTL tested.
* Doesn't respond well to smaller viewports.
* Stories aren't using the correct illustrations.
These will be addressed in follow up PRs.
https://dev.cultureamp.design/create-brand-moment/storybook/?path=/story/brand-moment-react--capture-intro
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participan …

feat: Create BrandMoment component

---

draft-packages/select/KaizenDraft/Select/styles.elm.scss

fix: update Elm select clear button color for Heart

---

draft-packages/select/KaizenDraft/Select/styles.react.scss

This PR correctly adds space between stacked tags within the multi-select. 
https://cultureamp.atlassian.net/browse/PRX-327
Before:
After:
- If this contains substantial visual changes, especially far …

fix: correct spacing between stacked tags within multi select

---

draft-packages/select/KaizenDraft/Select/Select.tsx
draft-packages/select/KaizenDraft/Select/index.ts
draft-packages/select/docs/Select.stories.tsx
draft-packages/select/package.json
yarn.lock

We should allow refs to be passed through all components, but this is particularly important for elements that we are using in forms. Previously we had not allowed this in the Select component, even though the underlying library `react-select` does allow this.
Because `ref` is handled differently to other props, we need to wrap the components in a ForwardRef function. The forwardRef function provides a mutableRef type and `react-select` expects this to be an immutableRef, so we also have to type the arguments in a way that satisfies `react-select` rather than using generic params in forwardRef.
Because we are wrapping the component with forwardRef, we also need to set the displayName, as React will not be able to infer it. This will help with debugging, ensuring the components do not …

feat: forward refs through select component

---

package.json
yarn.lock

Bump Chromatic from 5.7.1 to 5.9.2
This will add support for TurboSnap.

chore: Bump Chromatic to 5.9.2

---

packages/design-tokens/src/__tests__/sass-tokens.spec.ts

Move the spec files from the generated token directory. We should keep compiled / autogenerated separate from spec files / other code. 
**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.

chore: Update location of test file for tokens

---

draft-packages/button/KaizenDraft/Button/styles.scss

Updates the IconButton hover colour to match the correct Heart UI Kit specification.
closes https://github.com/cultureamp/kaizen-design-system/issues/1785

fix: Update IconButton component hover colour to match Heart UI kit

---

site/docs/components/illustration.mdx

The health of Illustration package has changed due to this issue: https://github.com/cultureamp/kaizen-design-system/issues/1857

docs: Update Illustration component health

---

draft-packages/illustration/package.json
packages/brand-moment/package.json
packages/design-tokens/CHANGELOG.md
packages/design-tokens/package.json
packages/notification/package.json

- Have Storybook stories been updated?
**If you're new to Kaizen, please …

chore: Revert design-tokens 4

---

site/docs/guidelines/typography.mdx

- Our typography docs were out of date. Updated them to our new display font/when we use it.

docs: update display font type

---

.buildkite/pipeline.yaml

Yell at the channel when the release step fails.

build: Add slack notification when build fails

---

.github/issue_template.md

Some customer info ended up in an issue so @ActuallyACat mentioned it'd be good to add this to the issue template.

chore: update issue template to include no sensitive info warning

---

draft-packages/well/Well.tsx
draft-packages/well/docs/Well.stories.tsx
draft-packages/well/styles.scss

- Add examples of all the new variants of `<Well />`
Closes this: https://github.com/cultureamp/kaizen-design-system/issues/1454
Too many screenshots so best to check the storybook

feat: add new variants of well

---

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx
draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
draft-packages/illustration/docs/IllustrationScene.stories.tsx

- Add New Account Onboarding
- Add Upload Employee Data

feat: Add missing Brand Moment Illustrations

---

draft-packages/empty-state/KaizenDraft/EmptyState/README.mdx
draft-packages/likert-scale-legacy/docs/README.mdx
draft-packages/menu/KaizenDraft/Menu/README.mdx
draft-packages/modal/KaizenDraft/Modal/README.mdx
draft-packages/well/README.mdx
site/docs/components/filter-menu.mdx
site/docs/components/illustration.mdx
site/docs/components/slider.mdx

Work:
- Update component health after going through #updates_design_systems, #prod_design_systems and releases in Github.
- Please let me know if any also ring a bell!

chore: update component health

---

.github/workflows/codeql-analysis.yml

docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

ci: Add CodeQL action

---

draft-packages/empty-state/CHANGELOG.md
draft-packages/empty-state/package.json
draft-packages/guidance-block/CHANGELOG.md
draft-packages/guidance-block/package.json
draft-packages/illustration/CHANGELOG.md
draft-packages/illustration/KaizenDraft/Illustration/__snapshots__/illustration.spec.tsx.snap
draft-packages/illustration/package.json
draft-packages/modal/CHANGELOG.md
draft-packages/modal/package.json
packages/brand-moment/CHANGELOG.md
packages/brand-moment/package.json
packages/design-tokens/CHANGELOG.md
packages/design-tokens/elm/Kaizen/Theme.elm
packages/design-tokens/package.json
packages/design-tokens/src/themes/index.ts
packages/notification/CHANGELOG.md
packages/notification/package.json
packages/stylelint-plugin/CHANGELOG.md
packages/stylelint-plugin/package.json
packages/stylelint-plugin/src/rules/prefer-color-tokens.spec.ts
storybook/theme-switcher-addon/themeManager.ts

Reverts cultureamp/kaizen-design-system#1957

ci: "revert feat: Change defaultTheme to Heart"

---

packages/component-library/components/OffCanvas/OffCanvas.tsx

Fixes broken hamburger menu on responsive layout for the deprecated Navigation Bar. Currently still being used within the Gatsby site. 
closes #2191 
https://user-images.githubusercontent.com/48232362/139602454-568be97a-aeed-4824-9a73-451a8a85575f.mov

feat: Update visibleMenus state in nav bar

---

draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/README.mdx
site/docs/components/pagination.mdx

🎉 Fixed every accessibility issue found with the title block
🎉 Pagination component was created

docs: Update component health for the fortnight

---

draft-packages/form/KaizenDraft/Form/Primitives/InputSearch/styles.scss

fix: Add type=search specificity to override perf-ui materialize

---

draft-packages/illustration/KaizenDraft/Illustration/Scene.tsx
draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx

Removing Zen theme from Spot and Scene illustrations

feat: Removing Zen theme from Spot and Scene illustrations

---

site/docs/guidelines/link-vs-button.mdx

Expand a little on the point that the cursor reflects the semantic meaning and behaviour of the element. Clarify which article supports this approach and which one makes the case against it.
This topic came up in Slack again, and when sharing the link to this page I found myself having to clarify the guidance presented here.

docs: Clarify "Cursors" guidance for buttons

---

yarn.lock

Updates to latest version of cultureamp/motion-ui from https://github.com/cultureamp/motion-ui/pull/1.
Our fork had a bunch of dev dependencies that weren't needed. More details in https://github.com/cultureamp/motion-ui/pull/1.
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/4285729 …

fix: upgrade to latest cultureamp/motion-ui

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/README.mdx
draft-packages/modal/KaizenDraft/Modal/README.mdx
site/docs/components/slider.mdx
site/docs/components/tabs.mdx

Updates the component health page for the last 4 weeks of work. 
Slider is based on this PR: https://github.com/cultureamp/kaizen-design-system/pull/1956
Tabs is based on this PR: https://github.com/cultureamp/kaizen-design-system/pull/2203
Modal is based on this PR: https://github.com/cultureamp/kaizen-design-system/pull/2337
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, …

chore(site): Update component health

---

.github/workflows/chromatic.yaml

fix: chromeatic action incorrect value mapping

---

draft-packages/tag/KaizenDraft/Tag/Tag.scss
draft-packages/tag/KaizenDraft/Tag/Tag.spec.tsx
draft-packages/tag/KaizenDraft/Tag/Tag.tsx
draft-packages/tag/docs/Tag.stories.tsx
draft-packages/tag/package.json
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/TitleBlockZen.tsx
legacy-packages/title-block/KaizenDraft/TitleBlock/TitleBlock.tsx

closes #790 
- Have Storybook stories been updated?
**If you're new to …

feat: Add Profile varient to Tag

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.scss

- Have Storybook stories been updated?
**If you're new to Kaizen, please …

fix: Update prominent background from blue to purple on GuidanceBlock

---

site/docs/guidelines/email-template.mdx

Initial draft of Email Template guidance.

docs: email-template.mdx

---

draft-packages/guidance-block/KaizenDraft/GuidanceBlock/README.mdx
draft-packages/likert-scale-legacy/README.mdx
draft-packages/tag/KaizenDraft/Tag/README.mdx
site/docs/components/badge.mdx
site/docs/components/global-notification.mdx
site/docs/components/pagination.mdx

Things referenced:
Badge: https://github.com/cultureamp/kaizen-design-system/pull/2314
GuidanceBlock: https://github.com/cultureamp/kaizen-design-system/pull/2367
GlobalNotification: https://github.com/cultureamp/kaizen-design-system/pull/2349
Tag: https://github.com/cultureamp/kaizen-design-system/pull/2330
Pagination: https://github.com/cultureamp/kaizen-design-system/issues/2313

docs: Update component health (mid Dec 2021)

---

site/docs/components/avatar.mdx
site/docs/components/card.mdx
site/docs/components/illustration.mdx

Update component health stats
Pre-chunk planning
- Avatar 
- Card   
- Illustrations

docs: update component health stats

---

.eslintrc.js
draft-packages/guidance-block/KaizenDraft/GuidanceBlock/GuidanceBlock.spec.tsx
draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.spec.tsx
draft-packages/illustration/KaizenDraft/Illustration/Players/VideoPlayer.tsx
draft-packages/menu/KaizenDraft/Menu/StatelessMenu.tsx
draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx
package.json
packages/brand-moment/src/BrandMoment.spec.tsx
packages/design-tokens/docs/pages/examples/themeProviderExample.docsExample.tsx
packages/design-tokens/src/ThemeManager.ts
packages/design-tokens/src/__tests__/ThemeManager.spec.ts
packages/responsive/src/useMediaQueries.tsx
storybook/header-preset/header.tsx
storybook/header-preset/index.tsx
yarn.lock

This PR is part of the nextjs work that unify team is working on. With nextjs, our front end applications are pre-rendered at build time so components which are using DOM features would break. We identified some of kaizen components with this problem and fixed them. We are using this [eslint plugin](https://github.com/cultureamp/eslint-plugin-ssr-friendly?organization=cultureamp&organization=cultureamp) to help us identify problems which needed some modifications so we forked it and made the changes accordingly (PR has been opened on the original repo so we just installing directly from git at the moment)
There is no open issue that is relevant to this
- Have …

feat: Make kaizen prerendering friendly (nextjs related)

---

site/docs/components/avatar-group.mdx
site/docs/components/avatar.mdx

- Update Avatar documentation and component health chart
- Create new Avatar group documentation page and update health chart
After recent updates to the Avatar and creation of Avatar Group the documentation needed to be updated to reflect the changes - see [ticket ref](https://cultureamp.atlassian.net/browse/KDS-110) 
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, …

docs: update avatar and avatar-group docs and health page

---

packages/generator/package.json
yarn.lock

- CVE-2022-0144 vulnerability was identified in buildkite causing build failures. This addresses this issue.
- Fix buildkite builds due to js vulnerabilities.
- All but `shelljs` CVE-2022-0144 has been addressed by frontend-ops
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/42857299 …

chore: update yeoman-generator to address CVE-2022-0144 vulnerability

---

draft-packages/tooltip/KaizenDraft/Tooltip/README.mdx

Revised usage of the tooltip component due to recent development and UI Kit updates.
Updating docs to reflect recent changes made to the UI Kit and code component.

docs: Revised Tooltip documentation

---

js-audit-allow-list.json
package.json
yarn.lock

Issue with publishing on master, latest config/ci change was upgrading Lerna to v4. Rolling back changes to see if this addresses issue.

ci: Rollback lerna to v3.22.1

---

draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.scss
draft-packages/tooltip/KaizenDraft/Tooltip/Tooltip.tsx
draft-packages/tooltip/docs/Tooltip.stories.tsx

Add highlight variant to component and storybook
To reach UI kit parity

feat: add highlight mood to tooltip

---

draft-packages/form/KaizenDraft/Form/TextAreaField/README.mdx

Update component health stats and story id
Following updates to variants and component uplift the documentation needed to reflect the changes

docs: update stats and demo story id

---

draft-packages/form/docs/TextAreaField.stories.tsx

This is branched off our storyWrapper component and is an example of how we would use it within stories.

feat: Use new storywrapper for textAreaField stories

---

js-audit-allow-list.json

Adding some vulnerabilities found in our Gatsby sub-dependencies to the allow list.

chore: Adding some sub-dependencies of Gatsby to allow list [KDS-229]

---

draft-packages/form/docs/SearchField.stories.tsx
site/docs/components/search-field.mdx

Uses StoryWrapper component to consolidate the stories into one sheet.

docs: update searchfield to use StoryWrapper

---

packages/button/docs/Button.stories.tsx

- Update Default Buttons (kaizen demo) to Buttons
- Update Icon (kaizen demo) to Icon Button
- Remove controls on stickersheets.

docs: update buttons story name and controls

---

packages/design-tokens/less/shadow.less
packages/design-tokens/sass/shadow.scss
packages/design-tokens/src/themes/heart.ts
packages/design-tokens/tokens/shadow.json

Design UI kit update
Adjust small box shadow to new updated value

fix: update small box shadow design token value

---

packages/rich-text-editor/docs/RichTextEditor.stories.tsx
packages/rich-text-editor/package.json
packages/rich-text-editor/src/RichTextEditor/RichTextEditor.scss
packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
packages/rich-text-editor/src/RichTextEditor/index.ts
packages/rich-text-editor/src/RichTextEditor/schema.ts
packages/rich-text-editor/src/RichTextEditor/types.ts
yarn.lock

Creates the `RichTextEditor` component, without any controls for now (just paragraphs and hard breaks).

feat: Create RichTextEditor component (sans controls)

---

catalog-info-design-system.yaml
catalog-info-website.yaml
catalog-info.yaml

Sock keeping day.
Fills out our Backstage catalog info a bit more, including a component for our website, and one for our design system.

chore: Expand catalog info for Backstage

---

packages/rich-text-editor/package.json
packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
packages/rich-text-editor/src/RichTextEditor/inputrules.ts
packages/rich-text-editor/src/RichTextEditor/keymap.ts
packages/rich-text-editor/src/RichTextEditor/schema.ts
yarn.lock

Adds the ability to create bullet and numbered lists (only via inputrules for now without a toolbar).

feat: Add list functionality to RichTextEditor

---

draft-packages/title-block-zen/package.json

fix: Set TitleBlock to 6.0.16 to fix deploy

---

site/docs/components/date-range-picker.mdx

- Marked DateRangePicker as implemented, with UI kit parity and all variants

docs: Updated DateRangerPicker health stats

---

.buildkite/scripts/release.sh

- Lerna blows up in CI complaining about Git not being present, or it not being a Git repo
- Adding /workspace as a directory

chore: Fix for lerna build issue

---

draft-packages/tag/docs/Tag.stories.tsx

Fixes [KDS-392](https://cultureamp.atlassian.net/browse/KDS-392)
Update type of Postive to Positive

fix: update stories typo

---

draft-packages/card/docs/Card.stories.tsx

Update `Card` story description to show correct package name.
Example import statement was incorrectly referencing the wrong package.

docs(card): update Card story description

---

packages/rich-text-editor/docs/RichTextEditor.stories.tsx
packages/rich-text-editor/package.json
packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
packages/rich-text-editor/src/RichTextEditor/controlmap.ts
packages/rich-text-editor/src/RichTextEditor/schema.ts
yarn.lock

WIP PR for toolbar list and indent controls
- adds toolbar list buttons
- adds list indent buttons
- abstracts control logic into controlmap instead of in schema

feat: add list buttons to rte

---

packages/rich-text-editor/docs/RichTextEditor.stories.tsx
packages/rich-text-editor/package.json
packages/rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
packages/rich-text-editor/src/RichTextEditor/controlmap.ts
packages/rich-text-editor/src/RichTextEditor/schema.ts
yarn.lock

Adds link functionality to the Kaizen RTE component with the [Link Manager plugin that was just added to the toolkit](https://github.com/cultureamp/rich-text-toolkit/pull/31).

feat: Add link functionality to RichTextEditor

---

packages/date-picker/src/DatePicker/DatePicker.tsx

Initial click shifted/jumped the page to the top. See Jira card for video examples.
- Fixed by adding strategy: fixed - [popper.js docs](https://popper.js.org/docs/v2/constructors/#:~:text=By%20default%2C%20it%20is%20absolute,since%20no%20repositioning%20is%20needed.)

fix(date-picker): Update popper to be fixed

---

packages/date-picker/docs/DateRangePicker.stories.tsx
packages/date-picker/src/DatePicker/DateRangePicker.spec.tsx
packages/date-picker/src/DatePicker/DateRangePicker.tsx

Ensure DateRangePicker is working after recent upgrade and add more tests.
- Add tests
- mini refactor

feat: refactor DateRangePicker and add tests

---

packages/date-picker/docs/DatePicker.stories.tsx

Fix locale arg type from variant to locale.

docs: update locale argType for storybook

---

packages/date-picker/src/DatePicker/components/Calendar/Calendar.scss

Lexical error on sass variable
Wrap variable with #{}

fix: lexical error on sass variable

---

draft-packages/select/KaizenDraft/Select/Select.tsx
draft-packages/select/docs/Select.stories.tsx

To indicate that the dropdown can be closed by clicking the Select component while open.
Changes the Select dropdown indicator to an upwards chevron when the dropdown is open.

feat: Add chevron up to Select when dropdown is open

---

packages/date-picker/src/DatePicker/components/DateInput/DateInput.scss
packages/date-picker/src/_primitives/Calendar/Calendar.scss

Update styles within the UI kit.
- Update the focus ring on days and arrows.
- Add the hover styling when focused.

feat: update focus and hover styles for Calendar component

---

packages/rich-text-editor/src/RichTextEditor/controlmap.ts

- The RTE was unable to use any of the buttons if the rich text editor content was empty.
- This adds a function for the Mark and Node toggle in the control map to create an initial <p> tag if there is no content in the editor. An initial tag is required by prosemirror before and node is able to be wrapped.
https://user-images.githubusercontent.com/36558508/178204989-56c45675-18bd-4ae3-a1ff-8ef2a112b9ef.mp4
https://user-images.githubusercontent.com/36558508/178205011-ed35d15c-b9f2-48c9-b673-a4e6e1dae820.mp4
- Adds `chainTransaction` helper  to chain multiple commands and dispatch each transitions in sequential order
- chainCommand exist on recieving true value so this needed to be created
- Adds `createInitialParagraph` which adds a `<p>` tag to the initial Selection (which should be 0 if …

refactor: update list behaviours

---

packages/component-library/styles/animation.scss
packages/component-library/styles/animations/_animations.scss
packages/component-library/styles/animations/vendor/effects/_slide.scss
packages/component-library/styles/animations/vendor/util/_string.scss

- Fix sass error caused by missing slide effect.
- https://cultureamp.slack.com/archives/C016N8Y1E10/p1658844811356059
- Add the missing slide effect to the vendor file.

fix: add slide effect to animations

---

packages/date-picker/docs/Calendar.stories.tsx
packages/date-picker/docs/DatePicker.stories.tsx
packages/date-picker/src/DatePicker/DatePicker.tsx
packages/date-picker/src/DatePicker/components/DateInput/DateInput.tsx
packages/date-picker/src/_primitives/Calendar/Calendar.module.scss
packages/date-picker/src/utils/calculateDisabledDays.spec.ts

[KDS-459](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-459)
- Add "today" stories to Calendar sticker sheet (disabled isn't there yet because it still needs to be fixed; new Jira card created)
- Update Calendar sticker sheets to have all dates in the past
- Otherwise when we reach the future month, Chromatic will fail every day as "today" will start highlighting itself
- Improve DatePicker controls and fix up some docs slightly

docs(date-picker): improve DatePicker docs

---

packages/select/docs/FilterMultiSelect.stories.tsx
packages/select/index.ts

The root needs to export all the things from the src folder
- adds index.ts to the root of the select folder

fix: add index.ts to export all from src folder

---

draft-packages/filter-menu-button/KaizenDraft/FilterMenuButton/FilterMenuButton.tsx
draft-packages/filter-menu-button/docs/FilterMenuButton.stories.tsx

Deprecate FilterMenuButton in favour of FilterMultiSelect

docs(filter-menu-button): deprecate filter menu button

---

draft-packages/form/KaizenDraft/Form/CheckboxField/CheckboxField.module.scss
draft-packages/form/KaizenDraft/Form/CheckboxGroup/CheckboxGroup.module.scss
draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.module.scss
draft-packages/form/docs/CheckboxField.stories.tsx
draft-packages/form/docs/CheckboxGroup.stories.tsx

- Remove deprecated styles and mixins
- Remove deprecated styles and mixins from checkboxField, Checkbox and checkboxGroup
- Update stories to use stickersheets

feat: remove deprecated styles from checkbox

---

lerna.json

Tell lerna not to publish a package when we only update stories/test files/README.
Not necessary to bump versions for these changes.

chore(lerna): update to ignore stories/test files/readmes on release

---

packages/select/package.json
yarn.lock

After opening the menu through `{tab}` then `{enter}`. The user cannot `click` on the button to re-trigger the menu.
Fixes https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-774
- Upgrade the react-aria button package to the latest version.
- Upgrade react-aria menu package to latest version.
React spectrum git issue here: https://github.com/adobe/react-spectrum/issues/2867

fix: update react-aria button package to fix keydown click bug

---

draft-packages/form/KaizenDraft/Form/Primitives/ToggleSwitch/ToggleSwitch.module.scss

feat: remove deprecated styles

---

draft-packages/form/KaizenDraft/Form/Primitives/FieldGroup/FieldGroup.module.scss
draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.module.scss
draft-packages/form/KaizenDraft/Form/Primitives/Input/Input.module.scss
draft-packages/form/KaizenDraft/Form/Primitives/InputSearch/InputSearch.module.scss
draft-packages/form/KaizenDraft/Form/Primitives/_mixins.scss

Remove deprecated styles from primitive form components
- Remove and replace ca- or kz- tokens

feat: remove deprecated styles from form primitives

---

tsconfig.dist.json

Reverts cultureamp/kaizen-design-system#2967

chore: Revert "chore(tsconfig): add noUncheckedIndexedAccess as true to config"

---

draft-packages/collapsible/KaizenDraft/Collapsible/Collapsible.module.scss
draft-packages/collapsible/docs/Collapsible.stories.module.scss

Remove deprecated styles $ca and $kz from stylesheets and replace with tokens.
- Replace styles with tokens.

feat(collapsible): remove deprecated styles from stylesheets

---

packages/select/src/FilterMultiSelect/components/SelectionControlButton/SelectAllButton/SelectAllButton.spec.tsx
packages/select/src/FilterMultiSelect/components/SelectionControlButton/SelectAllButton/SelectAllButton.tsx

Fix the selectAll button selecting the disabled keys
- filter the disabled keys from the selectAll function
- Add tests

feat: update selectAllButton to not include disabled keys

---

packages/select/docs/FilterMultiSelect.stories.tsx
packages/select/docs/MockData.ts
packages/select/src/FilterMultiSelect/components/ListBox/ListBox.scss
packages/select/src/FilterMultiSelect/components/MultiSelectOption/MultiSelectOption.scss
packages/select/src/FilterMultiSelect/components/Root/Root.tsx
packages/select/src/FilterMultiSelect/provider/SelectionProvider/SelectionProvider.tsx
packages/select/src/FilterMultiSelect/types.ts

- More intuitive developer experience.
- We do not expect consumer to need to control disabled keys at run time.
- Remove disabledKeys prop
- Built disabled keys based on items and pass to SelectionProvider

fix(filterMultiSelect): Kds 825 refactor disabled keys to be part of the data structure

---

.vscode/settings.json
packages/select/src/FilterMultiSelect/FilterMultiSelect.playwright.spec.tsx

- Better test coverage. Adds interaction testing.
- Adds Playwright tests to FilterMultiSelect

test: KDS-837 Add Playwright tests for FilterMultiSelect

---

yarn.lock

Yarn lock fell out of sync with packages.
updates the versions of installed packages in yarn lock

chore(yarn.lock): updated the yarn.lock to reflect new package versions

---

packages/select/docs/FilterMultiSelect.stories.tsx
packages/select/src/FilterMultiSelect/FilterMultiSelect.tsx
packages/select/src/FilterMultiSelect/provider/MenuTriggerProvider/MenuTriggerProvider.tsx
packages/select/src/FilterMultiSelect/provider/SelectionProvider/SelectionProvider.tsx

https://cultureamp.atlassian.net/browse/KDS-694
Add display names to providers/context and update story code block semantics

fix(filtermultiselect): fix console warnings

---

packages/progress-bar/docs/ProgressBar.stories.tsx
packages/progress-bar/src/ProgressBar.tsx

Text styling was missing
- Add new `isReversed` prop.

feat(progressBar): add reversed text styling

---

draft-packages/collapsible/KaizenDraft/ExpertAdviceCollapsible/ExpertAdviceCollapsible.tsx
draft-packages/collapsible/package.json
yarn.lock

When creating the Expert Advice Collapsible, the Brand was imported incorrectly, making it not usable for consumers.
Correct the way Brand is being imported into the component.

fix(deps): import brand as package

---

packages/select/docs/FilterBarExample/DemographicValueSelect.tsx
packages/select/docs/FilterMultiSelect.stories.tsx
packages/select/src/FilterMultiSelect/components/MenuLayout/MenuLoadingSkeleton/MenuLoadingSkeleton.tsx

Reverts cultureamp/kaizen-design-system#3058

fix: Revert "fix: Change MenuLoadingSkeleton to component (#3058)"

---

packages/date-picker/docs/FilterDateRangePicker.stories.tsx
packages/date-picker/docs/FilterTriggerButton.stories.tsx
packages/date-picker/docs/controls/localeControls.ts
packages/date-picker/package.json
packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.spec.tsx
packages/date-picker/src/FilterDateRangePicker/FilterDateRangePicker.tsx
packages/date-picker/src/FilterDateRangePicker/components/Trigger/FilterTriggerButton/FilterTriggerButton.module.scss
packages/date-picker/src/FilterDateRangePicker/components/Trigger/FilterTriggerButton/FilterTriggerButton.spec.tsx
packages/date-picker/src/FilterDateRangePicker/components/Trigger/FilterTriggerButton/FilterTriggerButton.tsx
packages/date-picker/src/FilterDateRangePicker/components/Trigger/FilterTriggerButton/index.ts
packages/date-picker/src/FilterDateRangePicker/components/Trigger/TriggerButtonBase/TriggerButtonBase.module.scss
packages/date-picker/src/FilterDateRangePicker/components/Trigger/TriggerButtonBase/TriggerButtonBase.spec.tsx
packages/date-picker/src/FilterDateRangePicker/components/Trigger/TriggerButtonBase/TriggerButtonBase.tsx
packages/date-picker/src/FilterDateRangePicker/components/Trigger/TriggerButtonBase/index.ts
packages/date-picker/src/FilterDateRangePicker/components/Trigger/_mixins.scss
packages/date-picker/src/FilterDateRangePicker/components/Trigger/_variables.scss
packages/date-picker/src/FilterDateRangePicker/components/Trigger/index.ts
packages/date-picker/src/FilterDateRangePicker/index.ts
packages/date-picker/src/FilterDateRangePicker/utils/formatDateRange.spec.ts
packages/date-picker/src/FilterDateRangePicker/utils/formatDateRange.ts
packages/date-picker/src/types.ts
packages/date-picker/src/utils/calculateDisabledDays.ts
packages/date-picker/src/utils/formatDateAsText.ts
packages/date-picker/src/utils/isDisabledDate.ts
yarn.lock

Add new component FilterDateRangePicker.
- Removes version lock for `component-library` and updates to latest
- Export `Matcher` from types.ts as it is used often
- Add `FilterTriggerButton` (adapted from FilterMultiSelect)
Iterative release phase 1.

feat(date-picker): add FilterDateRangePicker

---

packages/select/index.ts

fix: Export new Select component from package root

---

packages/select/docs/FilterMultiSelect.stories.tsx
packages/select/docs/MockData.ts
packages/select/docs/Select.stories.tsx
packages/select/src/Select/components/Trigger/SingleTriggerButton/SingleTriggerButton.module.scss
packages/select/src/Select/provider/MenuTriggerProvider/MenuTriggerProvider.spec.tsx
packages/select/src/Select/utils/getSelectedOptionLabel/getSelectedOptionLabel.spec.ts

- fix sass function to rgba
- update name of mock data to be less confusing

fix: Kds 1033 label issues spotted in select

---

.vscode/settings.json

To help provide feedback when using classnames function
adds intellisense to classnames, classNames and csx function to better handle active, hover, pseudo state

refactor: update vscode setting for tw intellisense

---

packages/select/docs/Select.stories.tsx
packages/select/src/Select/Select.tsx
packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss
packages/select/src/Select/components/TriggerButton/TriggerButton.tsx

- Add Validation props to Select
- Add `status` and `validationMessage` props
- Create validation story

feat(Select): add validation status and message

---

packages/select/src/Select/Select.tsx

feat: update order of validation message

---

packages/select/docs/Select/Select.stories.tsx
packages/select/src/Select/Select.tsx
packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss
packages/select/src/Select/components/TriggerButton/TriggerButton.tsx
packages/select/src/Select/components/TriggerButton/_mixins.scss

Add reversed styles to Select
- add `isReversedProp`
- Add reversed styling
- add reversed stickersheet

feat: add reversed styles to Select

---

packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss
packages/select/src/Select/components/TriggerButton/_variables.scss

To allow consumers to call `.focus()` and the focus ring to show
Update to psudeo selector for the focus to be `:focus` rather than `:focus-visible`

feat: update focus selector to :focus

---

renovate.json5

chore(config): fix renovate config

---

packages/tailwind/docs/TailwindTokens.stories.tsx
yarn.lock

Consistency in TW class order means increased readability. (Positioning classes first, color classes last etc.)
Adds Tailwind linting via the `prettier-plugin-tailwindcss` package.
Works out of the box with `className=""` and `classnames(...)`

feat: (tailwind) Add prettier package

---

CONTRIBUTING.md
README.md

To help people find the new Kaizen issue tracker

chore(docs): add new Kaizen discourse to Readme and contribution

---

packages/components/future/package.json

Future needs to point to the correct dist file path

fix: future package.json routes

---

packages/components/esbuild.config.js

fix: try to resolve regression issue

---

draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.module.scss
draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.spec.tsx
draft-packages/form/KaizenDraft/Form/Primitives/FieldMessage/FieldMessage.tsx
draft-packages/form/docs/FieldMessage.stories.tsx

- Update to use new Caution Icon for Caution status
- Add Caution to Field Message
- Show the Caution icon when status = caution
- Update the icon alignment to start

feat: update field message caution icon

---

packages/components/package.json
yarn.lock

So that the build includes the tailwind stylesheet...

fix: make @kaizen/tailwind a dep

---

draft-packages/modal/KaizenDraft/Modal/Presets/ConfirmationModal.tsx
draft-packages/popover/KaizenDraft/Popover/classMappers.ts
draft-packages/tag/KaizenDraft/Tag/Tag.tsx
packages/notification/src/components/GenericNotification.tsx

UI kit has been updated to use a new Caution Icon
- Update the components which have a cautionary variant to use the new Icon
- Update the use of `exclamationIcon` import to `errorIcon` to match UI kit terminology

feat: update components to use Caution Icon

---

packages/a11y/package.json
packages/a11y/tsup.config.ts
packages/component-library/package.json
packages/component-library/tsup.config.ts

I was so cowboy in my last release that I forgot a few edits to make it even work lol, need some kinda package.json linter

fix: a11y and component-library package-locks + build

---

.changeset/fresh-cats-train.md
draft-packages/menu/KaizenDraft/Menu/__snapshots__/Menu.spec.tsx.snap
draft-packages/tile/KaizenDraft/Tile/__snapshots__/Tile.spec.tsx.snap
packages/brand-moment/src/__snapshots__/BrandMoment.spec.tsx.snap
packages/button/src/Button/components/GenericButton.tsx
packages/loading-spinner/src/LoadingSpinner/LoadingSpinner.tsx

https://github.com/cultureamp/kaizen-discourse/issues/71
Add a live region polite to the contents of `GenericButton`

feat: 71-working-button-state-needs-to-be-announced-with-a-live-region

---

.changeset/quick-plums-nail.md
lerna.json
packages/components/src/__future__/ExampleComponent/ExampleComponent.module.scss

This is to test the changeset release command

chore: test change

---

.changeset/fresh-cats-train.md

We don't want to publish button using changeset

chore: remove button changeset

---

.buildkite/scripts/changeset.sh
.changeset/fresh-cats-train.md
.changeset/happy-trains-poke.md
.github/workflows/changeset.yaml
packages/components/src/__future__/ExampleComponent/ExampleComponent.module.scss

Changeset needs to know who it is to publish as.

chore: add npm creds to changeset

---

.buildkite/scripts/changeset.sh

Need to assign the secret to the NPM ticket...

fix: changeset publish npm token

---

.github/workflows/changeset.yaml

NPM install is failing on private github packages

add npm config to use githubtoken in changeset

---

.changeset/rude-birds-talk.md
packages/components/package.json
packages/components/src/BrandMoment/BrandMoment.module.scss
packages/components/src/BrandMoment/BrandMoment.spec.tsx
packages/components/src/BrandMoment/BrandMoment.tsx
packages/components/src/BrandMoment/__snapshots__/BrandMoment.spec.tsx.snap
packages/components/src/BrandMoment/_docs/BrandMoment.stories.tsx
packages/components/src/BrandMoment/_docs/ExampleHeaders.scss
packages/components/src/BrandMoment/_docs/ExampleHeaders.tsx
packages/components/src/BrandMoment/index.ts

Moves Brand package to packages/components/src, as per [this issue](https://github.com/cultureamp/kaizen-discourse/issues/46)

feat(components): Kzn 1111/brand moment migrate

---

.changeset/friendly-eagles-walk.md
package.json
packages/components/package.json
turbo.json

No files were built in the process of publishing
Add build step to turbo for max speed.
Add that build script to occur before changeset publish

Fix-changset-build-release

---

plop-templates/basic-component/docs/{{pascalCase componentName}}.stories.tsx.hbs

Forgot to update the import after renaming the template component.
Fix docs template import in plop template for stories.

chore(plop): fix stories template imports

---

.changeset/config.json

Packages versions and changelogs aren't being updated in github.
Update the changeset config to point changelogs to our repo.

fix changelog config to hopefully update releases

---

.changeset/real-terms-shout.md
draft-packages/illustration/KaizenDraft/Illustration/utils.ts

https://cultureamp.slack.com/archives/C0189KBPM4Y/p1682980045869089

FIX: illustration SSR support

---

.changeset/honest-pigs-laugh.md
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/MobileActions.tsx
packages/stylelint-plugin/src/rules/no-invalid-use-of-var-tokens-in-equations.ts
tsconfig.json

Enable `noImplicitReturns` in tsconfig.
Our consumers have stricter linting than us, and our shipping of source files meant they are getting errors.
We should be writing cleaner code anyway, so it's a good motivation to enable it.

chore(tsconfig): enable noImplicitReturns

---

.buildkite/pipeline.yaml

So we know when packages are available to announce

add slack notify to buildkite on passed release build

---

draft-packages/form/KaizenDraft/Form/Primitives/ToggleSwitch/ToggleSwitch.module.scss

Use flex to center check icon

---

packages/rich-text-editor/package.json
yarn.lock

Circular-ish dependency fun (RTE uses the RT Toolkit, which uses Button)!
Upgraded the RT Toolkit to use the latest Button, so now we pull in the latest Toolkit :)

chore(deps): update rich-text-toolkit to ^2.0.2

---

.changeset/wise-ducks-complain.md
packages/select/src/Select/Select.tsx

The buttonRef arg wasn't added to the function declaration, I have added it in

fix: add buttonRef prop to trigger default function

---

package.json
yarn.lock

Update dependencies:
- "@types/react": "^18.2.6",
- "@types/react-dom": "^18.2.4",

chore(deps): update @types/react and @types/react-dom

---

.changeset/itchy-waves-glow.md
draft-packages/illustration/package.json
yarn.lock

Update dependency `lottie-web` to ^5.11.0

chore(deps): update lottie-web to ^5.11.0

---

packages/component-library/package.json
yarn.lock

chore(deps): update yarn.lock

---

.changeset/dull-ways-deliver.md
.stylelintrc.json
draft-packages/hero-card/KaizenDraft/HeroCard/HeroCard.module.scss
draft-packages/popover/KaizenDraft/Popover/Popover.module.scss
draft-packages/table/KaizenDraft/Table/Table.module.scss
packages/component-library/styles/border.scss
packages/select/src/Select/components/TriggerButton/TriggerButton.module.scss

https://cultureamp.slack.com/archives/C0189KBPM4Y/p1684391312303349
- Change the "color-function-notation" rule value to "modern"
- yarn lint:fix

fix: "color-function-notation": "modern" not working sass

---

packages/select/src/FilterMultiSelect/FilterMultiSelect.playwright.spec.tsx

- CI was failing playwright because accessible names were updated and the .locator could not find them
- updates FMS playwright selector name

Update selectors in filter multi select test to fix playwright

---

yarn.lock

I ran `yarn install` and found an uncommitted change.
Commit the `yarn.lock` change.

chore: fix yarn lock

---

.buildkite/pipeline.yaml

Reverts cultureamp/kaizen-design-system#3691

Revert "update release conditional"

---

packages/components/package.json
packages/components/src/FilterBar/FilterBar.spec.tsx
packages/components/src/FilterBar/_docs/FilterBar.mdx
packages/components/src/FilterBar/_docs/FilterBar.stories.tsx
packages/components/src/FilterBar/context/FilterBarContext.tsx
yarn.lock

Add a story showcasing updating values in the FilterBar via an external event, and also add a test.
Story includes an example of encoding/decoding query params.
Prove that it can be done.
[KDS-1473](https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?selectedIssue=KDS-1473)
[KDS-1473]: https://cultureamp.atlassian.net/browse/KDS-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(filter-bar): add example story for updating values via external event

---

.changeset/ten-hotels-yawn.md
packages/components/src/FilterMultiSelect/subcomponents/SearchInput/SearchInput.tsx

We made the new one, but didn't implement it.
Implement it.

Fix-filtermultiselect-searchinput-import

---

.changeset/stale-camels-tap.md
packages/select/src/Select/Select.spec.tsx
packages/select/src/Select/Select.tsx
packages/select/src/Select/components/ListBox/ListBox.tsx
packages/select/src/Select/components/TriggerButton/TriggerButton.tsx

Recommendation from Intopia to add this role to better convey what this is to screen readers.
Adds `role="combobox"` to the `Select` button, plus `aria-controls`, linking it with the list box

Add role=combobox to Select

---

.github/labeler.yml

remove unused labeller

---

.buildkite/scripts/build-storybook.sh
.buildkite/scripts/release.sh

add test setup_npm to build

---

.buildkite/pipeline.yaml
.github/workflows/changeset.yaml

update changeset gh action to trigger release

---

.github/payload/slack-notify-release.json
.github/workflows/changeset.yaml

To know when our publish fails or succeeds
Add a slack notification action for both success and fail after publish occurs.

add slack notifications

---

.github/workflows/changeset.yaml

Reverts cultureamp/kaizen-design-system#3944
Unnecessary.

Revert "explicitly set changeset createGithubReleases"

---

.github/workflows/test-stories.yaml

Forgot to move it earlier.
Add conditional to the first test-stories job (build-storybook).

ci(test-stories): move conditional from chromatic to build-storybook

---

docker-compose.yml

We need this to deploy our storybook to AWS

add back docker-compose

---

.changeset/fifty-weeks-sell.md
.github/workflows/changeset.yaml

Trying something I saw in another example.

KDS-1717 Fix notify slack on release

---

.changeset/hip-jokes-press.md

Mistakenly thought I didn't need a changeset for dep updates.

Add changeset for dep updates

---

.changeset/late-mice-march.md
packages/components/src/FilterMultiSelect/subcomponents/MultiSelectOption/MultiSelectOption.tsx

Copying over from legacy: https://github.com/cultureamp/kaizen-legacy/pull/21

Add classNameOverride to MultiSelectOption

---

package.json
yarn.lock

https://github.com/sass/node-sass/releases/tag/v9.0.0

Bump node-sass to 9.0.0

---

.changeset/ninety-carrots-double.md
packages/components/package.json
yarn.lock

https://github.com/Swatinem/rollup-plugin-dts/blob/master/CHANGELOG.md#600

Bump rollup-plugin-dts to 6.0.1

---

.changeset/tame-phones-mix.md
packages/components/package.json

No longer required by consumers as we distribute compiled css.
Change `@kaizen/design-tokens` from peerDep to devDep.

chore(deps): change @kaizen/design-tokens from peerDep to devDep

---

.changeset/wet-emus-invite.md
packages/components/src/MultiSelect/MultiSelect.spec.tsx
packages/components/src/MultiSelect/MultiSelect.tsx
packages/components/src/MultiSelect/_docs/MultiSelect.mdx
packages/components/src/MultiSelect/_docs/MultiSelect.stickersheet.stories.tsx
packages/components/src/MultiSelect/_docs/MultiSelect.stories.tsx
packages/components/src/MultiSelect/subcomponents/MultiSelectToggle/MultiSelectToggle.tsx

https://cultureamp.atlassian.net/browse/KDS-1714
Notes:
* Strange that `MultiSelectToggle` takes a bunch of props and then splits them between a containing div and the button itself.

Add description to MultiSelect

---

.buildkite/pipeline.yaml

Aims to fix the current broken syntax for the regex selector
- updates the conditional regex selector in pipeline.yml

Kds 1976/add build condition to bk

---

.buildkite/pipeline.yaml
.buildkite/scripts/check-build-for-publish.sh

updating env vars since build.commit was returning nothing
- update env vars

Update buildkite config env vars

---

.buildkite/pipeline.yaml
.buildkite/scripts/check-build-for-publish.sh
docker-compose.yml

Next attempt
update pipeline skip logic

Update bk shell script skip logic

---

.buildkite/pipeline.yaml
.buildkite/scripts/check-build-for-publish.sh
docker-compose.yml

Actually adding labels to this

BK label test

---

.changeset/smooth-students-compare.md
package.json
packages/tailwind/src/tailwind-presets.ts
yarn.lock

Had to update a type because of this change in tailwind: https://github.com/tailwindlabs/tailwindcss/pull/12272

Update tailwindcss to 3.4.0

---

.changeset/tough-dots-camp.md
package.json
packages/components/locales/en.json
packages/components/package.json
packages/components/src/BrandMoment/_docs/BrandMoment.stories.tsx
packages/components/src/ErrorPage/hooks/useErrorMessages.ts

[KZN-1999](https://cultureamp.atlassian.net/jira/software/c/projects/KZN/boards/634?selectedIssue=KZN-1999)
Whimsical messages are hard for translators.
Simplify error page messages.
[KZN-1999]: https://cultureamp.atlassian.net/browse/KZN-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: simplify error page messages

---

.buildkite/dockerfiles/build.Dockerfile

BuildKite can't find pnpm.
Help BuildKite find pnpm.

ci: enable corepack in BuildKite docker build step for pnpm

---

.changeset/silly-chicken-suffer.md
packages/components/src/Workflow/subcomponents/Header/Header.tsx

As part of the Self Reflections 2.0 Audit, one of the items is to fix is `Images have alt or are hidden from assistive tech`
https://cultureamp.atlassian.net/wiki/spaces/PA/pages/3457024042/Perform+Self-Reflections+V2+accessibility+review#%3Across_mark%3A-Images-have-alt-text-or-are-hidden-from-assistive-tech
- Updated Alt text

fix(workflow): CA logo a11y

---

.changeset/late-dragons-switch.md
packages/package-bundler/src/presets/shared-ui/bin/postBuild.ts

Update `fs.rmdirSync` to `fs.rmSync`

fix(bundler): update fs.rmdirSync to fs.rmSync

---

.changeset/fair-toys-study.md

Missed in https://github.com/cultureamp/kaizen-design-system/pull/4696
Add changeset for KAIO bundling fix

chore: add KAIO bundling fix changeset

---

packages/components/src/__actions__/Menu/v3/_docs/ApiSpecification.mdx

Docs: fix code example for menu

---

package.json
packages/components/package.json
pnpm-lock.yaml

- more bulks updates for rollup branch
- updates turbo, frontend-api, react intl, chromatic and prosemirror-commands deps

dep updates 4871 - 2

---

.changeset/cyan-insects-sing.md
packages/components/src/Heading/Heading.module.scss

https://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file
Fix the css import

fix(dist): fix css import

---

.changeset/proud-plants-mix.md
.stylelintrc-css.mjs
packages/components/src/__layout__/Workflow/v3/_docs/Workflow.stories.tsx
packages/components/src/__layout__/Workflow/v3/subcomponents/Footer/components/Root/FooterRoot.module.css
packages/components/src/__layout__/Workflow/v3/subcomponents/Header/components/Root/Root.module.css

Forgot to do a design review
- Remove box shadow from header
- Add border top to footer and border bottom to header
- Tidy up the story example a bit

fix(Workflow v3): design adjustments

---

packages/components/src/Workflow/subcomponents/Footer/components/ProgressStepper/ProgressStepper.module.css
packages/components/src/Workflow/subcomponents/Footer/components/ProgressStepper/ProgressStepper.tsx

Quick fix to update ProgressStepper to remove Text
- removes use of Text component in favor of token styles

update progress stepperName to use text tokens instead

---

.changeset/khaki-bulldogs-end.md
packages/components/src/Filter/FilterSelect/FilterSelect.spec.tsx
packages/components/src/Filter/FilterSelect/FilterSelect.tsx
packages/components/src/Filter/FilterSelect/_docs/FilterSelect.stories.tsx
packages/components/src/__future__/Select/Select.spec.tsx
packages/components/src/__future__/Select/_docs/Select.mdx
packages/components/src/__future__/Select/_docs/Select.stories.tsx
packages/components/src/__future__/Select/subcomponents/ListBox/ListBox.tsx
packages/components/src/__future__/Select/subcomponents/Overlay/Overlay.tsx

Reverts cultureamp/kaizen-design-system#5077

Revert "Filter select accessible label and focus jump fix"

---

.changeset/four-lemons-whisper.md
packages/components/src/Filter/Filter/Filter.module.css
packages/components/src/Filter/FilterBar/FilterBar.module.css
packages/components/src/Filter/FilterBar/subcomponents/FilterBarMultiSelect/FilterBarMultiSelect.module.css
packages/components/src/Filter/FilterButton/FilterButton/FilterButton.module.css

https://cultureamp.slack.com/archives/CETLTFG9G/p1730864181789669?thread_ts=1730433786.082989&cid=CETLTFG9G
Switch container queries to media queries to avoid stacking context issues

Switch container queries to media queries to avoid stacking context issues

---

.changeset/strong-mails-knock.md

chore: add changeset for release

---

.changeset/popular-seahorses-bake.md
packages/components/src/GuidanceBlock/GuidanceBlock.module.css
packages/components/src/GuidanceBlock/GuidanceBlock.tsx

Cleaned this up before copying over some of it to a repo

Convert GuidanceBlock stylesheet to CSS

---

.changeset/curvy-nails-dream.md
packages/components/src/GuidanceBlock/GuidanceBlock.module.css

Did an oopsie in my last PR
https://github.com/cultureamp/kaizen-design-system/pull/5286/files

Fix incorrect comparison operator in GuidanceBlock CSS

---

.github/workflows/canary-release.yml
.github/workflows/changeset.yaml
.github/workflows/check-files.yml
.github/workflows/chromatic-main.yaml
.github/workflows/chromatic-pr.yaml
.github/workflows/clear-cache.yml
.github/workflows/deployment.yml
.github/workflows/test-stories.yaml

Had some recent jobs get stuck and continued to run over an hour 🕙 💸 
Add a timeout to all GH actions jobs

ci(gha): add timeout to all github actions

---

.buildkite/scripts/helpers/setup-registry.sh

ci(buildkite): fix env variable warning

---

pnpm-lock.yaml

chore(deps): lock file dedupe

---

.changeset/tough-pigs-deliver.md

Change set for Tertiary button updates didn't specify it was for tertiary buttons.
Updated change set to be more specific.

Clarify change set

---

.changeset/cold-gorillas-invite.md
packages/components/locales/en-GB.json
packages/components/locales/en.json
packages/components/src/Filter/FilterBar/_docs/FilterBar.spec.stories.tsx
packages/components/src/Filter/FilterBar/_docs/FilterBar.stories.tsx

Must update in locales for changes to be visible
Manually changed the label in the locales to follow the guidelines.

Update locales for "Add Filters" -> "Add filters"

---

.changeset/blue-baboons-scream.md
packages/components/src/Tile/TileGrid/TileGrid.module.scss

Reference [this reported issue](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1736481871007029)

Override browser stylesheet for ul element used in TileGrid

---

.changeset/spicy-pears-taste.md
packages/components/src/__rc__/Icon/constants.ts

https://cultureamp.atlassian.net/browse/KZN-2953
Exposes the share icon via the default set

Adds share icon to default set

---

.changeset/eleven-scissors-tease.md
packages/components/src/Content/Content.module.scss

https://cultureamp.slack.com/archives/C0189KBPM4Y/p1741750586645189?thread_ts=1736726650.060579&cid=C0189KBPM4Y

Content: add min-width:0 to maintain gutter margins

---

.changeset/shaggy-pears-begin.md
packages/components/__tests__/reactIntlMock.ts
packages/components/locales/en.json
packages/components/src/Badge/Badge.tsx
packages/components/src/Filter/FilterMultiSelect/subcomponents/MultiSelectOption/MultiSelectOption.spec.tsx
packages/components/src/Filter/FilterMultiSelect/subcomponents/MultiSelectOption/MultiSelectOption.tsx
packages/components/src/Filter/FilterMultiSelect/subcomponents/SelectionControlButton/ClearButton/ClearButton.tsx
packages/components/src/Filter/FilterMultiSelect/subcomponents/SelectionControlButton/SelectAllButton/SelectAllButton.tsx
packages/components/src/__next__/Tooltip/_docs/Tooltip.spec.stories.tsx

I want translations for the select all and clear button, and did the MultiSelectOption while I was there

Add translations to FilterMultiSelect subcomponents

---

packages/package-bundler/README.md
packages/package-bundler/src/presets/shared-ui/README.md

I recently went through the process of converting a couple of packages to using the Kaizen bundler and thought I'd contribute back to the READMEs for the package and its presets in order to clarify some things I found confusing or missing.
Update READMEs

chore: update readmes

---

.changeset/clever-hairs-fall.md
packages/components/package.json
packages/design-tokens/package.json
packages/tailwind/package.json
pnpm-lock.yaml

[KNZ-3253] fix: upgrade to latest package-bundler to fix type issues

---

packages/design-tokens/_docs/pages/how-to-use-in-js.mdx

docs: fix incorrect css var example
